### ISSUE TITLE
Clarify behaviour of rawId and id fields for resident key credentials

### ISSUE THREAD

**Issue by herrjemand** [w3c/webauthn#1000]
So for resident key, no credId is being provided, and authenticator just returns a list of credentials for a specific origin. So no credID is being used.

So as I understand, in this case rawId and id fields must be empty.

Need to clarify thing behaviour.

**Comment by emlun** [comment]
>[for resident key] in this case rawId and id fields must be empty

No, the `id` and `rawId` are always returned from the client. It's not passed in by the RP in this case, but it's stored in the credential source and returned on use.

**Comment by herrjemand** [comment]
@emlun So what they must be set to?

**Comment by emlun** [comment]
The credential ID of the credential, as usual.

[authenticatorMakeCredential][amc]:

>13. Return to the user agent:
>    - selectedCredential.id, if either a list of credentials (i.e., allowCredentialDescriptorList) of length 2 or greater was supplied by the client, or no such list was supplied.

[getAssertion][get]:

>18.success.2 Let assertionCreationData be a struct whose items are:
>
>    **credentialIdResult**
>    If _savedCredentialIds[authenticator]_ exists, set the value of _credentialIdResult_ to be the bytes of _savedCredentialIds[authenticator]_. Otherwise, set the value of _credentialIdResult_ to be the bytes of the credential ID returned from the successful authenticatorGetAssertion operation, as defined in §6.3.3 The authenticatorGetAssertion operation.
>[...]
>10.success.3.1. Let _pubKeyCred_ be a new PublicKeyCredential object associated with _global_ whose fields are:
>
>    **[[identifier]]**
>    A new ArrayBuffer, created using _global_’s %ArrayBuffer%, containing the bytes of _assertionCreationData.credentialIdResult_.

[amc]: https://w3c.github.io/webauthn/#authenticatorGetAssertion-return-values
[get]: https://w3c.github.io/webauthn/#discover-from-external-source

**Comment by herrjemand** [comment]
So here is scenario:

I login on a brand new machine. I plugin my authentication and login to the site that is using residentCredential. The site send a challenge, the authenticator then is presented with the challenge, and it generates a list of assertions for the RPID. The list then returned to the client, and user being prompted to select one of the credential. User selects credential and returns it to the server. 

No credId been sent to authr, nor the authenticator have returned credId anywhere in responses.

Where does credId comes from?

**Comment by emlun** [comment]
The credential ID is stored in the authenticator and returned in step 13 as quoted above.

**Comment by equalsJeffH** [comment]
Close this with "stat:won't fix" ?

**Comment by herrjemand** [comment]
@equalsJeffH yes *)
