### ISSUE TITLE
Security threat: Username enumeration

### ISSUE THREAD

**Issue by SecureFrom** [w3c/webauthn#1014]
The draft webauthn specification doesn't appear to recognise username enumeration as a security consideration when in reality it is a significant issue when using webauthn as a first factor (passwordlesss) authentication mechanism.

Username enumeration is often overlooked by developers but actually it can have major ramifications for users and sites. Troy hunt explains it well in his blog:-
 * https://www.troyhunt.com/website-enumeration-insanity-how-our-personal-data-is-leaked

I note sites may be likely to use email addresses as usernames but even if they don't any usernames may still contain real world identities or other confidential identifying information.

I believe it's a important issues for the webauthn specification because:-
 * All implementations based solely on the current webauthn specification would be affected
 * All the demo's I found have this problem  (demonstrating it will likely be a common misstep)
 * Even when the risk is understood, mitigation would be difficult with the current protocol design

Recommendations:-
 1. Add User enumeration to the list of security and/or privacy considerations
 2. Change the registration and validation documentation to make clear sites should avoid this issue by not informing end users when usernames are not found in their database. It will be necessary for them to mock user public keys to prevent more sophisticated attackers from recognising the failed attempt.
 3. Consider amending the protocol to make it simpler for developers to do the right thing and not allow user enumeration. Currently developers would need to mock complex data structures to prevent unknown users being discerned from known users.

**Comment by ve7jtb** [comment]
The user ID is part of the signed assertion.   If it is generated by anyone other than the legitimate user it would be an invalid assertion as they would not have the correct key.

Any response to the Authenticating party happens above the level of WebAuthentication. 
The application typically returns a session cookie or an error. 

The application indicating if the account exists or not as part of an invalid authentication is outside the scope of WebAuthn.

The general W3C privacy guidelines should cover this.  
There is no protocol change required for first-factor authentication.

**Comment by emlun** [comment]
Thanks for bringing this up. I'd say there are three likely deployment scenarios:

1. **Two-factor authentication with password**

    The user first logs in with a traditional password, and then performs a WebAuthn authentication ceremony to prove possession of a second factor. The WebAuthn ceremony is completely behind a traditional password authentication gateway, so username enumeration should not be an issue at this point.

2. **Multi-factor authentication without password and without username**

    The user visits the login page and receives a WebAuthn challenge for any credential. Since the user does not provide a username to initiate this ceremony, username enumeration is not an issue.

3. **Single-factor authentication without password**

    The user initiates a WebAuthn authentication ceremony by submitting their username, and the signed response from the authenticator is the only authentication factor used. **Username enumeration is a risk** in this deployment scenario, if the server returns an error for unknown usernames. I'll admit that Yubico's demo server does exactly that at this time, and analogously returns an error during registration if a username is taken. I don't think there's much you can do about the registration case, unless the username is an e-mail address in which case the server can just claim to have sent a follow-up e-mail regardless of whether the address is already registered.

I don't think (3) will be a rare deployment scenario, so I agree we should address this in the spec. At the very least as an implementation consideration, or possibly even as a new RP operations section outlining recommendations for how to structure data flow for initiating a ceremony.

**Comment by samuelweiler** [comment]
Looks okay to me.  I added a sub-PR https://github.com/w3c/webauthn/pull/1058 to use the word "attacker" instead of "user" for the attack scenario.
