### ISSUE TITLE
Credential counter must initialise as 1 

### ISSUE THREAD

**Issue by herrjemand** [w3c/webauthn#1025]
Currently we say: 
> **a per credential signature counter:**
allocate the counter, associate it with the new credential, and initialize the counter value as zero.

In the same time we say:

>**no signature counter**
let the signature counter value for the new credential be constant at zero.

Per-credential counter must start with 1 to avoid confusion.

**Comment by sangraecho** [comment]
This is ok in registration process since sign counter is not examined. In authentication process, the server can identify no signature counter if sign counter is 0 again and per credential signature counter if sign counter is larger than 0.

So per-credential counter doesn't have to start with 1.
