### ISSUE TITLE
Add Android "N" attestation type.

### ISSUE THREAD

**Issue by rlin1** [w3c/webauthn#103]
SafetyNet attestation type is not a perfect fit for the Basic Attestation model, the newly announced Android "N" HW attestation is a much better fit.
So we should at least add the Android "N" attesation.

**Comment by leshi** [comment]
Just as with SafetyNet, the W3C should not duplicate Android specs.  So at most, this should look something like:
```
interface AndroidAttestation {
    readonly attribute unsigned long version;
    readonly attribute DOMString attestationBlob;
};
```

**Comment by rlin1** [comment]
Agreed: W3C should not duplicate Android specs

**Comment by gmandyam** [comment]
Proprietary attestation formats do not belong in the Webauthn API specification.  They should be defined in an attestation registry (along with a reference to a normative specification that has been reviewed by the group).
