### ISSUE TITLE
FIDO U2F supports Attestation CA (AttCA)?

### ISSUE THREAD

**Issue by Kieun** [w3c/webauthn#1042]
[Section 8.6](https://w3c.github.io/webauthn/#fido-u2f-attestation) describes FIDO U2F attestation statement format. The supported attestation types includes _Basic_ and _AttCA_.
But, there is no description regarding _AttCA_ in case of U2F although TPM format has such description for _AttCA_. Also, there is no case which returns _AttCA_ after verifying U2F attestation.

I know that there were discussions related to this from Google, I'm not sure whether decision is made to support _AttCA_ or not.

So, We have following options.

1. Remove _AttCA_ from the U2F supported attestation types
2. Add descriptions of _AttCA_ cases to [Section 8.6](https://w3c.github.io/webauthn/#fido-u2f-attestation). Also, modify _AttCA_ description in [Section 6.4.3](https://w3c.github.io/webauthn/#sctn-attestation-types) by adding U2F cases

**Comment by emlun** [comment]
The same is true for the "packed" statement format. The RP sees no structural difference between _Basic_ and _AttCA_, they differ only in what's in the attestation certificate. Perhaps this should be called out in the [description of _AttCA_][attca].

[attca]: https://w3c.github.io/webauthn/#attca

**Comment by nadalin** [comment]
@emlun Please open PR on this
