### ISSUE TITLE
About the canonical CBOR encoding form

### ISSUE THREAD

**Issue by peteroupc** [w3c/webauthn#1051]
The definition of the CTAP canonical CBOR encoding form says:

> If the major types are different, the one with the lower value in numerical order sorts earlier.

Shouldn't "value" better read "major type" here?  What if the major types are not both number types (e.g., positive integer and text string)?

**Comment by emlun** [comment]
Yes, it seems like you've understood the intent correctly: "the one whose major type has the lower value in numerical order sorts earlier". We're forwarding this issue to the FIDO specs: fido-alliance/fido-2-specs#579

**Comment by peteroupc** [comment]
Thank you, but apparently the issues page there is inaccessible to me.

**Comment by emlun** [comment]
Yes, unfortunately it's private to the fido-alliance GitHub organization. If you have any additional questions, you're welcome to post them here and I'll forward them.

**Comment by emlun** [comment]
fido-alliance/fido-2-specs#579 has been closed with the message:

>Major types in CBOR are always represented as numbers.
