### ISSUE TITLE
Editorial: WebAuthn or WebAuthN

### ISSUE THREAD

**Issue by apowers313** [w3c/webauthn#1056]
Throughout the W3C WebAuthn spec, the spec / technology is referred to as "WebAuthn". In CTAP, it is sometimes referred to as "WebAuthn" (e.g. [here](https://fidoalliance.org/specs/fido-v2.0-id-20180227/fido-client-to-authenticator-protocol-v2.0-id-20180227.html#u2f-authenticatorMakeCredential-interoperability)) and sometimes "WebAuthN" (e.g. [here](https://fidoalliance.org/specs/fido-v2.0-id-20180227/fido-client-to-authenticator-protocol-v2.0-id-20180227.html#biblio-webauthn)). Third-party usage is becoming mixed as well.

Part of this is because of the historical usage of AuthN to mean "authentication" versus AuthZ to mean "authorization". Should we revert back to the historical usage in the spec (e.g. WebAuthN)?

**Comment by emlun** [comment]
@agl asserts we should go with "WebAuthn". I agree that this looks prettier.

**Comment by selfissued** [comment]
I think the most important thing is for us to be consistent and use the same spelling every time.  I'm fine with either spelling.  I do get that "AuthN" is commonly used in the industry and so understand why some would prefer "WebAuthN".

**Comment by emlun** [comment]
How do we make a decision?

**Comment by equalsJeffH** [comment]
The lower cased "Authn" is also commonly used in the industry, just saying.  I prefer the lower case "WebAuthn", which is what I've been consistently using, but can live with either if it's a big deal.

**Comment by rlin1** [comment]
Decision last week was to standardize on WebAuthn (lower case n)

**Comment by agl** [comment]
From 2018-09-12 call: it's "WebAuthn".

**Comment by nadalin** [comment]
@emlun Please make sure all instances use lowercase "n" and close

**Comment by rlin1** [comment]
Quick search in index.bs today didn't find any WebAuthN in the document.

**Comment by emlun** [comment]
All instances in the WebAuthn spec currently use lowercase "n". Please re-open this if there's anything else we need to do, like include style guidance in the spec preamble or something.
