### ISSUE TITLE
Update Figure 1 to follow up the spec modification

### ISSUE THREAD

**Issue by Kieun** [w3c/webauthn#1059]
Figure [1](https://w3c.github.io/webauthn/#fig-registration) depicts the registration flow and high level architecture.
There is a clientData in Msg 6, which is clientDataJSON in fact. So, we need to modify the Figure 1 to use clientDataJSON instead of clientData for readers no to be confused.

**Comment by emlun** [comment]
Thanks for pointing that out!

**Comment by equalsJeffH** [comment]
yes, I noticed the same thing last night/yesterday, thx @Kieun !
