### ISSUE TITLE
Document wide review

### ISSUE THREAD

**Issue by wseltzer** [w3c/webauthn#106]
The [charter](https://www.w3.org/Webauthn/charter/) requires us to seek horizontal review for accessibility, internationalization, performance, privacy, and security with the relevant Working Groups, and with the TAG, and to seek review from:
- Web Application Security Working Group
- Web Platform Working Group
- Web Payments Working Group
- Privacy Interest Group
- Accessible Platform Architectures (APA) Working Group

External Organizations
- IETF HTTP Authentication Working Group
- IETF Token Binding Working Group

Here's an umbrella issue for tracking those reviews.

**Comment by nadalin** [comment]
@wseltzer We have initiated the system wide review for this draft, so moving this to PR now

**Comment by samuelweiler** [comment]
APA is tracking our request(s) for accessibility at : https://www.w3.org/WAI/APA/wiki/Web_Authentication:_An_API_for_accessing_Scoped_Credentials_Level_1
