### ISSUE TITLE
Adding the way to get trust anchors for CTAP1/U2F authenticators

### ISSUE THREAD

**Issue by Kieun** [w3c/webauthn#1063]
Section 7.1 describes the way for RP to process credential registration.
At step 15, there is a description regarding the way for RP to get trust anchors and refer FIDO metadata service as an example with AAGUID information.
In case of CTAP1/U2F authenticators, the RP needs to obtain the FIDO metadata by with attestation certificate public key identifier. 
How about adding or changing such description for the readers?

**Comment by christiaanbrand** [comment]
We looked at this, but there's already a link to the Fido Metadata specification in there and since we don't think U2F authenticators will grow much now that FIDO2 is out, we don't think it makes sense to add that directly here.
