### ISSUE TITLE
Wrong Registration Ceremony Privacy Reference

### ISSUE THREAD

**Issue by milesstoetzner** [w3c/webauthn#1068]
Step 21 of [createCredential](https://www.w3.org/TR/webauthn/#createCredential) should be "See § 14.5 Registration Ceremony Privacy" instead of "See § 14.6 Authentication Ceremony Privacy".

Correct me, if I am wrong.

Greetings, 
Miles

**Comment by emlun** [comment]
Good catch, thanks!
