### ISSUE TITLE
Section 10: extensions are OPTIONAL

### ISSUE THREAD

**Issue by samuelweiler** [w3c/webauthn#1076]
Section 9 says all extensions are OPTIONAL; section 10 says the ones in this doc are RECOMMENDED.  Per 2119, these are quite different terms.  I propose that the section 9 text is correct (or else we make AppID RECOMMENDED and the others OPTIONAL).  

None of this is about flagging these as informational - as I understand it, we're making the case that all extension text should be normative, enabled by all (or all but one) extensions being optional.

I think the discrepancy should be cleared before PR.

**Comment by YubicoDemo** [comment]
I think Section 10 of the spec should read:
10. Defined Extensions
This section defines the initial set of extensions to be registered in the IANA "WebAuthn Extension Identifier" registry established by [WebAuthn-Registries]. These are OPTIONAL for implementation by user agents targeting broad interoperability.

**Comment by jcjones** [comment]
Agreed with the above, marking section 10 as section 9 is.

**Comment by jcjones** [comment]
PR #1076 open, @selfissued , thanks!
