### ISSUE TITLE
Typo in Figure 1?

### ISSUE THREAD

**Issue by xfq** [w3c/webauthn#1084]
In [Figure 1 Registration Flow](https://www.w3.org/TR/2018/CR-webauthn-20180807/#fig-registration), `PublicKeyCredentialCreateOptions` seems to be a typo.

Maybe it means `PublicKeyCredentialCreationOptions`?

**Comment by nicksteele** [comment]
@xfq is right it should be `PublicKeyCredentialCreationOptions`

**Comment by apowers313** [comment]
That was my mistake and I agree it should be `PublicKeyCredentialCreationOptions`  -- [fixed on MDN](https://developer.mozilla.org/en-US/docs/Web/API/Web_Authentication_API) now, but I'm not sure what @equalsJeffH is using for editing these images here.

**Comment by emlun** [comment]
Thanks! Fixed in #1085.

**Comment by equalsJeffH** [comment]
>  I'm not sure what @equalsJeffH is using for editing these images here.

Inkscape
