### ISSUE TITLE
Typo clientExtensions should be authenticatorExtensions

### ISSUE THREAD

**Issue by milesstoetzner** [w3c/webauthn#1089]
I think in [step 18.4](https://www.w3.org/TR/webauthn/#discover-from-external-source) "clientExtensions" should be "authenticatorExtensions" (two times).

> 4. If options.allowCredentials
> [...]
>is empty
Using local configuration knowledge of the appropriate transport to use with authenticator, invoke the authenticatorGetAssertion operation on authenticator with rpId, clientDataHash, allowCredentialDescriptorList, userPresence, userVerification, and **authenticatorExtensions** as parameters.
>[...]
> is empty
> Using local configuration knowledge of the appropriate transport to use with authenticator, invoke the authenticatorGetAssertion operation on authenticator with rpId, clientDataHash, userPresence, userVerification and **authenticatorExtensions** as parameters.
> 

Greetings,
Miles

**Comment by emlun** [comment]
That indeed seems to be the case. Good catch, thanks!
