### ISSUE TITLE
Clarify language in Section 13 'Security Considerations'

### ISSUE THREAD

**Issue by brentfulgham** [w3c/webauthn#1097]
Section 13 "Security Considerations" is normative. The second paragraph (beginning "At this
time") twice uses unclear language ("which is/are overall applicable").
Is this normative?

The second case ("defines…security characteristics which are overall applicable") is particularly concerning, as the referenced document defines multiple levels of conformance, and it's
unclear which (if any) this is attempting to invoke.

Proposed change:
Strike:
"Also, the [FIDOAuthnrSecReqs] document suite defines authenticator security characteristics which are overall applicable for WebAuthn authenticators." 

... and replace with:

"Also the [FIDOAuthnrSecReqs] document suite provides useful information about authenticator security characteristics."

**Comment by equalsJeffH** [comment]
This suggestion seems fine to me.
