### ISSUE TITLE
Remove uses of MAY from non-normative introductory text

### ISSUE THREAD

**Issue by brentfulgham** [w3c/webauthn#1098]
Section 1 Introduction is non-normative, but contains at least 4 instances of the RFC 2119 term MAY. These should be re-expressed as facts about the rest of the spec; any RFC 2119 language should be in normative sections later on.

**Comment by emlun** [comment]
Would it suffice to just lowercase the MAYs?

**Comment by hober** [comment]
No, that's not sufficient. In W3C and WHATWG specs the casing of RFC 2119 terms does not affect their semantics.

**Comment by emlun** [comment]
Fixed by PR #1103
