### ISSUE TITLE
enrichen registration and authentication ceremonies definitions

### ISSUE THREAD

**Issue by equalsJeffH** [w3c/webauthn#1099]
In various places we are appropriately referring readers to the registration and authentication ceremonies definitions. 

However, those definitions are very high-level and themselves do not link back into the spec such that a reader (e.g. a web developer) might be able to figure out how implementing a ceremony relates to the actual JS they need to write and the API calls they need to make.

e.g., add links to the registration and authentication ceremonies definitions pointing to:
* [[WebAuthnAPIGuide]] (ie: https://developer.mozilla.org/en-US/docs/Web/API/Web_Authentication_API)
* https://w3c.github.io/webauthn/#sctn-use-cases
* https://w3c.github.io/webauthn/#sctn-sample-scenarios
* https://w3c.github.io/webauthn/#sctn-api  (introduction)

**Comment by jcjones** [comment]
For posterity, some confusion on the part of implementing sites was documented in `blink-dev` here:
* https://groups.google.com/a/chromium.org/d/msg/Blink-dev/SdceviqfKJo/WkuBnm9iBgAJ
* https://groups.google.com/a/chromium.org/d/msg/Blink-dev/SdceviqfKJo/6qnqTzEEBwAJ

(There are likely more out there)

**Comment by equalsJeffH** [comment]
moving this to L2-WD-03 milestone to match the open PR #1330....
