### ISSUE TITLE
enhance spec roadmap section

### ISSUE THREAD

**Issue by equalsJeffH** [w3c/webauthn#1100]
the last sentence of the first paragraph in https://w3c.github.io/webauthn/#spec-roadmap ought to be separate and emphasized somehow. 

and then following that, there ought to be a new sentence introducing the bulleted list of audiences, something like:
> Further guidance for specific audiences:

**Comment by emlun** [comment]
Updated URL: https://w3c.github.io/webauthn/#sctn-spec-roadmap
