### ISSUE TITLE
move sample scenarios section up to be after use cases section

### ISSUE THREAD

**Issue by equalsJeffH** [w3c/webauthn#1101]
this would be just a cut'n'paste to move the entire unchanged [#sctn-sample-scenarios](https://w3c.github.io/webauthn/#sctn-sample-scenarios) section to be after [#sctn-use-cases](https://w3c.github.io/webauthn/#sctn-use-cases)

**Comment by emlun** [comment]
Updated URLs:
- https://w3c.github.io/webauthn/#sctn-sample-scenarios
- https://w3c.github.io/webauthn/#sctn-use-cases

**Comment by equalsJeffH** [comment]
thx @emlun! i updated the OP.
