### ISSUE TITLE
Clarify use case described in section 1.2.2

### ISSUE THREAD

**Issue by ngtlin** [w3c/webauthn#1114]
The section 1.2.2 describes a use case of using phone as an authenticator for desktop. It implies that browser needs an API to pull the login status of a user.  Unless the phone can function as a roaming FIDO2 authenticator, basically it is an out-of-band authentication scenario.  Not sure current spec is designed to cover this.

**Comment by emlun** [comment]
> Unless the phone can function as a roaming FIDO2 authenticator

It is exactly the intention of this use case that the phone would expose itself to the desktop computer as a roaming authenticator. Web Authentication doesn't specify the exact protocols for this - nor any other roaming authenticator, for that matter - but the obvious candidate is FIDO CTAP2 which would enable using it over Bluetooth, USB and/or NFC.

Does that answer your questions?

**Comment by ngtlin** [comment]
Yep,  thanks.
