### ISSUE TITLE
Should clients enforce challenge length?

### ISSUE THREAD

**Issue by herrjemand** [w3c/webauthn#1115]
Hey folks. I was reading through the WebAuthn specs and I am quiet confused about this sentence:

> In order to prevent replay attacks, the challenges MUST contain enough entropy to make guessing them infeasible. Challenges SHOULD therefore be at least 16 bytes long.

So challenges **MUST** have enough enough entropy, but **SHOULD** be at least 16 bytes?
We state mandatory requirement concludes to non-mandatory requirement.

Set aside, what if server vendor deems 1 byte enough entropy?

I feel like this is something that needs to be enforced by the client but not explicitly specified in specs.

**Comment by plehegar** [comment]
This might relevant for this issue:
Both Chrome and Firefox currently fulfill the promise if you use an empty ArrayBuffer for options.publicKey.challenge . The subtest at
https://github.com/web-platform-tests/wpt/blob/692ce5ae58a420893bd318e74b7e342a980b05a6/webauthn/createcredential-badargs-challenge.https.html#L20 .
As a side, I believe the test is incorrect to expect a TypeError and instead should expect a SecurityError, if any.

**Comment by herrjemand** [comment]
@emlun yeah, I understand that point. However if we don't set any threshold we wont have any.

**Comment by plehegar** [comment]
Edge does use a TypeError on the empty ArrayBuffer so it seems my assumption TypeError/SecurityError was incorrect, ie the test is actually right.

**Comment by herrjemand** [comment]
Unanimously decided not to enforce challenge length.

**Comment by plehegar** [comment]
[[
yuriy: there is contradiction here, no set length.
... should we change this?
... if not will RP do crazy things like empty buffer
... FIDO

Alliance needs to have an answer

agl: I think we are going to fix this.

yurity: should it be "must" browsers enforce 16bytes

christiaan: why is that a browser things

jc_Jones: I would argue its RP thing

16 bytes is a nice change.

scribe: why is 16 good, why not 8?

agl: 16 is canonical for this. I am fine with this.

Christiaan: it blocks other things on FIDO side.
... may in the next ersion, but not a change at this late stage.

jbradley: challenges does not go over CTAP. Authenticator gets a hash and some other things
... making it a must might not be the solution. I don't know if we get much with a minimum length

elundberg: if there is nothing, RP may have to be more vigilant.

yuriy: so next version and discuss later.

jc_Jones: I don't know if we will have more arguments later. unless we define the challenge
... the danger will persist
... the error possibility is very wide. think solution here is we need to look at nonce construction and take that chunk and drop it in here

jbradley: potentially we break implementations if we tightly control nonce

jc_jones: I would say we say this is out of scope. but is consideration for RP. I don't think we should mandate any number of bytes

jeffH: I agree with jc

agl: I do to, but tests says can't be zero.

plh: we may need to remove the test and see if we have a different conclusion later.
... I would make a pull request to remove that test.
... double check if this is the correct test or something else.
]]
https://www.w3.org/2018/12/19-webauthn-minutes.html
