### ISSUE TITLE
Attestation privacy advice creates large scale security risks

### ISSUE THREAD

**Issue by herrjemand** [w3c/webauthn#1127]
> A WebAuthn authenticator manufacturer may choose to ship all of their authenticators with the same (or a fixed number of) attestation key(s) (called Basic Attestation). This will anonymize the user at the risk of not being able to revoke a particular attestation key if its private key is compromised.

I understand that from privacy perspective, this is a really good advice. However it is really bad security approach. Imagine manufacturer that releases ten million devices. One's device attestation key is compromised, so entire ten million devices must be marked as revoked. This is why it's called "batch" and not "manufacturer", because certificate and keypair are generated per "batch" of keys, so quantifiably limited. Right now our policy is 1 attestation keypair per 100k. That is deemed sufficient to mitigate privacy risks, while enabling effective security scaling of the attestation.

> [UAFProtocol] requires that at least 100,000 authenticator devices share the same attestation certificate in order to produce sufficiently large groups. This may serve as guidance about suitable batch sizes.

This is FIDO's policy regarding of the protocol. U2F/FIDO2/UAF are all have the same mandatory requirements.

**Comment by herrjemand** [comment]
Propose changing to:

> Currently FIDO2 authenticator manufacturer must ship a batch, of a size at least 100,000 devices, with the same attestation batch certificate and keypair, that is chains to the attestation root, which is generally stored in authenticator metadata statement. For the next batch the manufacturer will generate new attestation keypair and certificate, that will chain as well to the same attestation root. This approach ensures that users privacy is preserved, due to the size of batch, while ensuring sufficient risk management in case of compromise of the device.

**Comment by herrjemand** [comment]
@rlin1 Can you comment?

**Comment by ratoui** [comment]
I agree. 

In any case, FIDO Authenticator security requirements starting at L1 already enforce this privacy requirement on FIDO2 authenticators as well. So it's better to adopt your new text for consistency.

**Comment by rlin1** [comment]
From a security perspective, there should also be an upper bound (e.g. some millions) for the number of authenticator instances using the same attestation private key.
See "A large number of authenticators sharing the same Attestation Certificate provides better privacy, but also makes the related private key a more attractive attack target." in https://fidoalliance.org/specs/fido-uaf-v1.2-rd-20171128/fido-uaf-protocol-v1.2-rd-20171128.html#authenticator-attestation 

FIDO ECDAA based attestation provides a better combination of privacy and security - since each authenticator uses a different attestation private key, but the public keys a "blinded" so two attestation signatures from the same authenticator instance cannot be attributed to the same authenticator instance - but only to the same authenticator model.

**Comment by emlun** [comment]
For the record, a compromised _attestation private key_ does not necessarily mean that all devices of the batch become unusable. Any _credential private keys_ previously created by those devices would still be safe. A compromised attestation private key only means that _future_ credentials attested by that attestation key can no longer be trusted to uphold the same security guarantees (in particular, a guarantee that the credential private key was generated on board the device would no longer hold), but all attestation statements produced _before_ the breach remain unaffected.

So, this statement is only half true:

>One's device attestation key is compromised, so entire ten million devices must be marked as revoked.

What would need to be revoked is the trust in attestation statements produced after the breach, so credentials created after the breach would be revoked (assuming the RP's attestation policy cares), but any credentials older than that would _not_ need to be revoked.

**Comment by emlun** [comment]
It is also in the authenticator manufacturer's interest to make the batches as small as possible - to limit financial and brand damage from product recalls, lawsuits, etc. - so I don't think it's particularly likely that a hardware vendor would willingly use the same attestation key for larger batches than necessary.

**Comment by herrjemand** [comment]
@emlun I did not meant that user keys are compromised. I mean attestation keys are. If attestation key is compromised, that means that every authenticator that is on the market with that attestation key must be removed, so can't be used for future registrations.

> It is also in the authenticator manufacturer's interest to make the batches as small as possible - to limit financial and brand damage from product recalls, lawsuits, etc. - so I don't think it's particularly likely that a hardware vendor would willingly use the same attestation key for larger batches than necessary.

I think from our past experience,  we've seen that vendors do mistakes all the time. The big. The small. The experienced. The newbies.

Currently we have a policy of 100k devices per attestation key.

**Comment by emlun** [comment]
>every authenticator that is on the market with that attestation key must be removed

No - users can safely continue to use the credentials they've already created (before the breach is determined to have happened) with such a device. Credential creation is a relatively rare occurrence, so many users might not be affected at all.

>so can't be used for future registrations.

Agreed; this can be enforced via server-side software updates.

What I mean to say is that a compromised attestation key is not a black-and-white security disaster as I read the OP to mean; the practical impact depends a lot on the circumstances about when the breach happened vs. when it was discovered, and each RP's attestation policy. I agree we shouldn't encourage larger batches than necessary, but I don't think normative requirements on batch sizes are in scope for the WebAuthn spec. That seems more suitable for a certification authority like FIDO to decide - the only RPs for which this kind of breach would have any impact at all are the same RPs that are likely to require authenticator certification.

**Comment by herrjemand** [comment]
@emlun Proposing this compromise:

> A WebAuthn authenticator manufacturer, should produce large enough batch of the authenticators, that are shipped with the same attestation key. In the same time the batch size shall be low enough to ensure that in case of attestation key compromise, the least amount of users is affected. This approach ensures that users privacy is preserved, due to the size of batch, while ensuring sufficient risk management in case of compromise of the attestation keys on the device.

> For example: FIDO protocols require that at least 100,000 authenticator devices share the same attestation keys and certificate in order to produce sufficiently large groups. This may serve as guidance about suitable batch sizes.

**Comment by emlun** [comment]
Looks like a good start. I can draft a PR for this.

**Comment by herrjemand** [comment]
@emlun If you could I'd appreciate it *)
