### ISSUE TITLE
add explanatory note to step 3 in authenticatorMakeCredential Operation

### ISSUE THREAD

**Issue by equalsJeffH** [w3c/webauthn#1133]
I just thought I'd found a bug in http://w3c.github.io/webauthn/#op-make-cred because on initial read it seems that even though  there's a match for an excluded cred, the user is asked for verification and the authnr is supposed to go ahead and create a cred. However, upon searching issues, and reading further in that step to discern that errors are returned in any case, this is all being done for privacy-preserving reasons (see issue #806 )

if we have cycles we ought to put a Note: in that step wrt what's going on...

**Comment by emlun** [comment]
Updated URL: https://w3c.github.io/webauthn/#sctn-op-make-cred
