### ISSUE TITLE
Refer android-safetynet verification to SafetyNet documentation?

### ISSUE THREAD

**Issue by emlun** [w3c/webauthn#1135]
@arnar notes in https://github.com/w3c/webauthn/issues/1132#issuecomment-454998300:

> I wonder if it's best to simply refer to [SafetyNet documentation](https://developer.android.com/training/safetynet/attestation#verify-compat-check) on this, rather than chasing any potential changes there.

I believe this has been suggested off-hand before, too. We've had several inaccuracies in the verification steps copied into WebAuthn: #968, #1018, #1132.

Should we delete the [android-safetynet](https://w3c.github.io/webauthn/#android-safetynet-attestation) verification procedure from WebAuthn and just refer to the [SafetyNet documentation](https://developer.android.com/training/safetynet/attestation#verify-compat-check) instead?

**Comment by emlun** [comment]
I personally have no strong opinion either way on this. Reducing duplication is always nice, but I also find it difficult to find precise instructions in the SafetyNet documentation on how to verify the attestation statement offline - it seems like the target audience for the documentation is mainly Android app developers rather than cryptographic protocol implementers, as the primary option for verification seems to be to contact an online verification service. It's possible to piece together most of our [android-safetynet](https://w3c.github.io/webauthn/#android-safetynet-attestation) verification procedure from the [source code samples](https://github.com/googlesamples/android-play-safetynet/tree/master/server), except they don't do our verification of the `ctsProfileMatch` attribute.

**Comment by equalsJeffH** [comment]
this will be closed by PR #1170
