### ISSUE TITLE
Maybe upgrade user handle PII prohibition to a MUST

### ISSUE THREAD

**Issue by agl** [w3c/webauthn#1146]
The user handle is not considered to be PII in CTAP2 and in Webauthn [says](https://www.w3.org/TR/webauthn/#user-handle):

> The user handle SHOULD NOT contain personally identifying information about the user, such as a username or e-mail address; see §14.9 User Handle Contents for details.

And [section 14.9](https://www.w3.org/TR/webauthn/#sctn-user-handle-privacy) says:

> Since the user handle is not considered personally identifying information &hellip; the Relying Party SHOULD NOT include personally identifying information

So is it PII or not? If not, the word MUST (rather than SHOULD) would seem to be indicated. I don't know what real-world effect it'll have, but it would be sad if RPs did the wrong thing and cited that lack of a MUST as justification.

**Comment by emlun** [comment]
In the end there's nothing to enforce such a requirement, but I support making this change as a clear statement of intent.

**Comment by akshayku** [comment]
+1 for changing it to MUST.
