### ISSUE TITLE
Support for apps acting as platform authenticators for authenticating in mobile browsers

### ISSUE THREAD

**Issue by holycleugh** [w3c/webauthn#1150]
I understand that a mobile device can be used to authenticate a desktop browser via bluetooth or NFC. Do Android or iOS have any mechanisms to allow 3rd party mobile apps to act as platform authenticators for the mobile browser?

As far as I can tell, there's no mechanism for discovering platform authenticators other than the built-in ones like fingerprint readers. If the user is authenticating to a browser on a desktop, the browser and the mobile app can communicate via bluetooth, for example, but it isn't possible (to my knowledge) for a phone to connect to itself over bluetooth. I'm not sure if the phone could connect to itself via NFC. Or maybe the app could emulate a USB device?

Krypton uses a browser extension instead of bluetooth for communication, but browser extensions are not commonly supported on default mobile browsers either.

**Comment by equalsJeffH** [comment]
clarifying question: is the use case for enabling "3rd party mobile apps to act as [webauthn/fido] platform authenticators for the mobile browser" primarly driven by situations where the underlying platform does not offer such authenticators (yet) ?

**Comment by holycleugh** [comment]
No, even if the device provides a hardware authenticator, the user may want to use a 3rd party mobile app.
This is part of a general question about support for software authenticators, which could be more flexible than hardware authenticators by e.g., providing multidevice support, backups or additional security configuration. Currently, even for desktop software authenticators, projects like SoftU2F have to emulate USB HID, which is possible but not easily made cross platform.

**Comment by emlun** [comment]
This seems to me like it's out of scope for WebAuthn since this has to do with OS-level inter-process communication, and any solution to this is therefore likely to be platform specific.
