### ISSUE TITLE
Where is the reference implementation for WebAuthn?

### ISSUE THREAD

**Issue by mduffy215** [w3c/webauthn#1152]
Shouldn't a major W3C proposal have a reference implementation showing developers how the code actually works???!!!  Where are the code samples???!!!

This one is totally lame:  https://github.com/MicrosoftEdge/webauthnsample

You really cannot determine the merits of a proposal until you have code that actually works.  This proposal should be shelved by the W3C until the proponents put forth a reference implementation.

**Comment by herrjemand** [comment]
@mduffy215 Here is my introduction https://medium.com/@herrjemand/introduction-to-webauthn-api-5fd1fb46c285

Here is DUO SEC guide https://duo.com/blog/guide-to-web-authentication

Here is Auth0 https://webauthn.me/

Here is a list of useful resources https://github.com/herrjemand/WebauthnAwesome

**Comment by mduffy215** [comment]
Thank you!

**Comment by nadalin** [comment]
Yuriy answered
