### ISSUE TITLE
AuthenticatorAttachment description is incorrect

### ISSUE THREAD

**Issue by emlun** [w3c/webauthn#1153]
The description of the [`AuthenticatorAttachment` enumeration][authatt] reads (emphasis added):

>This enumeration’s values describe authenticators' attachment modalities. Relying Parties use this for **two purposes**:
>- to express a preferred authenticator attachment modality when calling navigator.credentials.create() to create a credential, and
>- to inform the client of the Relying Party's best belief about how to locate the managing authenticators of the credentials listed in **allowCredentials** when calling **navigator.credentials.get()**.

In fact, `AuthenticatorAttachment` is used only in [`AuthenticatorSelectionCriteria`][authsel], which in turn is only used in `create()`. The "best belief about how to locate the managing authenticators" in [`allowCredentials`][allowCredentials] is in fact a sequence of [`AuthenticatorTransport`][authtran] values, not `AuthenticatorAttachment`.

Therefore, the second bullet point in the above quote can be eliminated (and the preceding text modified to align).

[authatt]: https://w3c.github.io/webauthn/#enumdef-authenticatorattachment
[authsel]: https://w3c.github.io/webauthn/#dictdef-authenticatorselectioncriteria
[allowCredentials]: https://w3c.github.io/webauthn/#dom-publickeycredentialrequestoptions-allowcredentials
[authtran]: https://w3c.github.io/webauthn/#enumdef-authenticatortransport

**Comment by emlun** [comment]
Related: #851. If we end up adding an `authenticatorAttachment` property to `PublicKeyCredentialRequestOptions`, this would only require modest changes to re-point the reference from `allowCredentials` to `PublicKeyCredentialRequestOptions`.

**Comment by equalsJeffH** [comment]
Yep, please, let's fix :)
