### ISSUE TITLE
further details for authenticatorCancel operation

### ISSUE THREAD

**Issue by equalsJeffH** [w3c/webauthn#116]
We may wish to add to the authenticatorCancel operation description some considerations for rolling back state (counters, keys, etc.)

**Comment by equalsJeffH** [comment]
see also #125

**Comment by equalsJeffH** [comment]
see also issue #292

**Comment by AngeloKai** [comment]
I am moving the issue back to WD-07 because I am addressing the cancel issues together at once.

**Comment by equalsJeffH** [comment]
@AngeloKai said:
> I am moving the issue back to WD-07 because I am addressing the cancel issues together at once.

Ok, changing assignee to @AngeloKai

**Comment by equalsJeffH** [comment]
@jcjones notes in webauthn f2f tpac 2017-11-09: that we ought to have some hand-wavy general impl-cons for authnrs

**Comment by nadalin** [comment]
@selfissued Mike please add a sentence in the implementation section to say this is job of the transport specs (CTAP)

**Comment by jcjones** [comment]
(and U2F, which leaves it undefined but still isn't webauthn's problem...)

**Comment by equalsJeffH** [comment]
on 6-Dec-2017 webauthn call: move to this to PR milestone, we'll have more data wrt the "authenticator model" spec section's level of abstraction.

**Comment by AngeloKai** [comment]
The CTAP spec described the detailed workings of canceling authenticator operation and the current webauthn spec described the rough model of authenticator cancel works: https://w3c.github.io/webauthn/#authenticatorcancel. I don't see a need to further define authenticator cancel operation. Therefore, closing the issue for now. 

@equalsJeffH can you please inform me what further detail you think we should provide? If so, we can re-open the issue.
