### ISSUE TITLE
Refine User Verification description 

### ISSUE THREAD

**Issue by Kieun** [w3c/webauthn#1162]
The description of [User Verification ](https://w3c.github.io/webauthn/#user-verification)includes following sentence.

> The intent is to be able to distinguish individual users.

In fact, If we enroll multiple fingerprints of family members to the authenticator (device), the authenticator never identify the each users. But, this sentence may mislead to readers that the authenticator can distinguish or identify the users.

It is more like the process that checks the user's authority to register the credential or authenticate with the credential.

**Comment by emlun** [comment]
It is true that authenticators might allow registering several people's fingerprints to the same account, for example, but I'd argue it's still true that the _intent_ of UV is to distinguish individual users. Also, multiple people could very well share the same "user" account at an RP anyway. I don't think we really need to change anything here.

**Comment by emlun** [comment]
On second thought, maybe we should acually define the term "user". Then that definition could point out that a user could be one or more physical persons.

**Comment by leshi** [comment]
I suggest saying "legitimate device owner" or "device owner"
