### ISSUE TITLE
No way to identify authenticator type whether is is platform or roaming if RP does not specify the type during registration

### ISSUE THREAD

**Issue by Kieun** [w3c/webauthn#1163]
If RP does not specify [AuthenticatorAttachment](https://w3c.github.io/webauthn/#enumdef-authenticatorattachment) during registration, depending on the devices or user preferences, user may register the platform authenticator or the roaming authenticator.

From the RP perspective, RP may refer the FIDO metadata with delivered aaguid. But, sometimes aaguid (e.g., non attestation conveyance preference) cannot identify specific authenticator so that RP cannot get the authenticator type.

To provide better UXs for authentication and authentication management, it's nice to deliver such information within the registration process.

**Comment by emlun** [comment]
Fixed by #1050?

**Comment by emlun** [comment]
Duplicate of #889

**Comment by Kieun** [comment]
@emlun It seems that #1050 PR solve this issue by returning more detailed information.
So, I'm closing this issue.
