### ISSUE TITLE
Clarify the name `AuthenticationExtensions...`

### ISSUE THREAD

**Issue by equalsJeffH** [w3c/webauthn#1166]
@selfissued noted in https://github.com/w3c/webauthn/pull/909#pullrequestreview-122522981:
> The word "Authentication" in the "AuthenticationExtensions..." identifiers refers to "Web Authentication" - not a particular method.

We should add a Note: clarifying this in the WebAuthn spec if there is not one there already.

**Comment by nadalin** [comment]
@equalsJeffH Can you create a PR for this ?

**Comment by equalsJeffH** [comment]
see PR #1210
