### ISSUE TITLE
Error: registration failed: packed attestation: self attestation not implemented

### ISSUE THREAD

**Issue by traviswltrs** [w3c/webauthn#1169]
Today I tried to use the Webauthn.org site to register an account using the latest version of chrome from my 2016 macbook pro (first one with the touchbar).  I chose the option to use my fingerprint sensor.  The touchbar gave me a status message to use the fingerprint sensor but when I do, Chrome pops up a messaage asking for permission to share my usb security key make and type with webauthn.  Regardless of whether or not I permit this the registration fails with the message in the subject line of this post.

In case it helps, I'm running Mac OS Mojave 10.14.3

Just wanted to pass along the information.
![screen shot 2019-03-07 at 11 01 27 am](https://user-images.githubusercontent.com/280943/53970716-4e6ed000-40c9-11e9-8b2a-0e9881fc70c6.png)

**Comment by emlun** [comment]
I think this belongs in https://github.com/apowers313/fido2-server-demo/

**Comment by emlun** [comment]
Moved to apowers313/fido2-server-demo#21
