### ISSUE TITLE
challenge in ClientData should be ArrayBuffer or BufferSource ?

### ISSUE THREAD

**Issue by equalsJeffH** [w3c/webauthn#117]
https://w3c.github.io/webauthn/#sec-client-data
```dictionary ClientData {
    required DOMString           challenge;    <<==  should be ArrayBuffer or BufferSource ?
    [...]
};
```
I *think* ArrayBuffer is more appropriate in ClientData than BufferSource, but I'm not sure, and I'm not sure it actually matters since ClientData is used internal-to-the-authnr in order to marshal info before hashing it.

**Comment by vijaybh** [comment]
No, this is left as DOMString on purpose.

ClientData is, as you note, an internal structure that needs to be serialized and hashed. So we need to define what that serialization looks like. We have two choices:

1. Define these types as DOMString, and say they will be produced by encoding the appropriate quantity as base64.
2. Define these types as ArrayBuffer, in which case they will be serialized in the array literal notation, i.e. something like "{ challenge: [31, 41, 59, 26, 53, 58, 97, 93, 238, ...], ... }"

The first seems more readable and is more compact, so I went with that when fixing #61.
