### ISSUE TITLE
Add explicit description on what should be done in incognito/private browsing mode

### ISSUE THREAD

**Issue by leshi** [w3c/webauthn#1174]
Web users should probably have the consistent experiences around using incognito/private browsing mode on all browsers.

This is especially relevant to platform authenticators.  As an example, Chrome on OS X integrates with Touch ID and stores state.  That state will get cleared when the user clears browser data.  This is not the case with platform authenticators provided by Windows.

Another interesting situation comes up around creating platfrom authenticator credentials in incognito.  In some browsers it will persist, in others it wouldn't.

**Comment by leshi** [comment]
Let's have each platform/implementer write what they're doing/planning to do.

**Comment by nadalin** [comment]
@akshayku Please fill in what Microsoft does

**Comment by kreichgauer** [comment]
Chrome on MacOS keeps authenticator state per Chrome profile. In Incognito mode, the Touch ID authenticator currently is available and uses the authenticator state of the parent non-Incognito profile, but informs the user that creating a new credential would persist state beyond the lifetime of the Incognito session. In Guest Mode, Touch ID is not available.

**Comment by akshayku** [comment]
Basic thought I had was, having different behavior in inprivate/incognito mode and regular mode gives away the knowledge of browser's operating mode to the RP. Which all browsers strive not to do that. 

Above comment was for MacOS. How about Windows/Android?

I would prefer a warning to the user saying about the implications of creating a credential in incognito/inprivate mode and allowing the creation of the credential on each browser.

**Comment by agl** [comment]
On the call of 2019-07-17, Akshay asked what Chrome does differently for Incognito on Windows. Based on a quick search it looks like [we disable platform authenticators](https://cs.chromium.org/chromium/src/device/fido/win/webauthn_api.cc?rcl=3aae7bd7cbb38edb3ad144e4173525dce280dc52&l=373) in that case. There we link to [this](https://bugs.chromium.org/p/chromium/issues/detail?id=908622) Chromium bug which basically says &ldquo;we should figure this out&rdquo;.

**Comment by agl** [comment]
> Basic thought I had was, having different behavior in inprivate/incognito mode and regular mode gives away the knowledge of browser's operating mode to the RP. Which all browsers strive not to do that.

We certainly don't want to create an isIncognito() call. Thus easily observable behaviour changes that result in a low-noise analog of isIncognito() are bad.

I think registering / asserting a credential is abrupt enough that it doesn't count as &ldquo;easily observable&rdquo; (so long as there's no silent failures that are distinguishable), so it's isUVPAA that's the major worry. For Android and Windows, [isUVPAA returns false](https://cs.chromium.org/chromium/src/chrome/browser/webauthn/chrome_authenticator_request_delegate.cc?rcl=dc1714fa48e02e61fba27a1c1fc720f95bcd3323&l=333) in Incognito. This is a signal, but it's very noisy and thus hopefully useless for sites trying to figure out whether a Javascript context is in an incognito session.

As Martin notes [above](https://github.com/w3c/webauthn/issues/1174#issuecomment-501833031), we do support platform authenticators on macOS with warnings. I think the reason that we don't do something similar for Windows and Android is a lack of ability to conveniently show such warnings.

**Comment by equalsJeffH** [comment]
attempting to summarize the above such that we might address this issue by including said info in the spec in a Note (pls review the below):

In incognito mode:

| Feature                          |  Android                    |  Windows                 | MacOS | 
| :--- | :--- | :--- | :--- |
| register new credential  | works only with roaming authnrs | works only with roaming authnrs | works with roaming authnrs; with platformTouchID-authnr shows warning |
| get assertion                 | works only with roaming authnrs | works only with roaming authnrs | works with roaming authnrs; with platformTouchID-authnr shows warning |
| isUVPAA() return value | always returns `false`  | always returns `false`  | returns accurate value (?) |

**Comment by agl** [comment]
From the call of 2019-07-31:

We agree the putting some language in the spec about this, and aligning user agents' behaviour, makes sense. I think that language should be non-normative because I'm worried about introducing normative language around something that has hitherto been implementation defined.

We lean towards a system of notice about the persistence of credential creation rather than one of forbidding creating credentials in private modes, or one of making credentials ephemeral.

**Comment by akshayku** [comment]
+1

**Comment by equalsJeffH** [comment]
I think this can be addressed in a milestone later than wd-03

**Comment by equalsJeffH** [comment]
On 2020-09-30 call: 
@agl notes that having normative recommendation here is probably not approp.  haven't recently heard complaints regarding this.  behavior in incognito mode is typically browser-specific. closing it is fine.  
@akshayku does not think this belongs in webauthn spec.
