### ISSUE TITLE
Git merge variants

### ISSUE THREAD

**Issue by emlun** [w3c/webauthn#1183]
Question for everyone merging pull requests: is there any particular reason we're sometimes doing rebase/squash merges instead of plain merges? I find rebase-merges make it unnecessarily difficult to track what branches have been merged and not.

**Comment by agl** [comment]
> rebase/squash merges

Does that mean commits with a single parent rather than two? I've been doing PRs from a fork of the repo and using the GitHub button to merge. If that's crappy, please let me know because it'll be purely out of ignorance if I'm not doing the right thing!

**Comment by emlun** [comment]
Yes, that means replacing the original commits with new ones (or just one, in the case of squash). Merging with the "Create a merge commit" variant of the merge button, you get:

```
* fffffff Merge branch 'feature2' into master (master)
|\
* \ eeeeeee Merge branch 'feature1' into master
|\ \
| | * ddddddd Add feature 2 (feature2)
| | * ccccccc WIP: feature 2
| * | bbbbbbb Add feature 1 (feature1)
|/ /
|/
* aaaaaaa Initial commit
```

where commit `fffffff` has both `bbbbbbb` and `ddddddd` as ancestors. In this case, `git branch --merged master` will tell you that both the `feature1` and `feature2` branches are merged into `master` and can safely be deleted.

Merging with the "Squash and merge" variant, you get:

```
* d0d0d0d Add feature 2 (master)
* b0b0b0b Add feature 1
| * ddddddd Add feature 2 (feature2)
| * ccccccc WIP: feature 2
|/
| * bbbbbbb Add feature 1 (feature1)
|/
* aaaaaaa Initial commit
```

where the original commits `bbbbbbb`, `ccccccc` and `ddddddd` have been replaced with the new commits `b0b0b0b` and `d0d0d0d`. The history on master is a bit tidier, but `git branch --merged master` doesn't know that the branches have been merged, because the commits on master are different commits than those in the branches. "Rebase and merge" is the same except there will be two new commits on master from the `feature2` branch instead of them being squashed into one.

**Comment by jcjones** [comment]
I'm ok with moving back to merge commits as a default. I don't really mind.

**Comment by emlun** [comment]
2019-03-20 WG call: This has been discussed earlier, and it was decided to do rebases to keep things tidy.

I'm fine with that, I can try to modify my workflow to work better with that approach.
