### ISSUE TITLE
finish up on "provide transport info during registration"

### ISSUE THREAD

**Issue by equalsJeffH** [w3c/webauthn#1188]
per my comment https://github.com/w3c/webauthn/pull/1050#pullrequestreview-201829572 on PR #1050 "provide transport info during registration":

We should update step 18 of [Registering a New Credential](https://www.w3.org/TR/2019/PR-webauthn-20190117/#registering-a-new-credential) such that it also directs the RP to call `AuthenticatorAttestationResponse.getTransports()`, and store the result along with the `credentialId` and `credentialPublicKey`.

@emlun expressed support in the original comment on PR #1050.

[ supports caBLE ]

**Comment by Kieun** [comment]
Also, we need to add more descriptions to reflect these changes to section [5.10.4](https://w3c.github.io/webauthn/#transport).
