### ISSUE TITLE
Q: Regarding Security Concerns Surrounding WebAuthn: Don't Implement ECDAA (Yet)

### ISSUE THREAD

**Issue by yanosz** [w3c/webauthn#1196]
Hello folks, 

researching webauthn and reading https://paragonie.com/blog/2018/08/security-concerns-surrounding-webauthn-don-t-implement-ecdaa-yet I've few questions in my mind, I have not found an answer, yet. I hope, that this is an appropriate way to reach out:

* Is there any statement in the Webauthn-Community answering PIE's concerns regarding the cryptographic protocols? I know https://www.noknok.com/blog-post/nok-nok-labs-addresses-potential-webauthn-protocol-security-concerns/, but this doesn't address the cryptographic details
* From my impression, selecting certain algorithms can avoid PKCS1 v1.5 padding. The COSE-registry has a lot of different algorithms. I'm not that into the COSE's terminology, but some algorithms appear to be purely symmetric and cannot be used in conjunction with webauthn.
  * Is that correct?
  * https://webauthndemo.appspot.com/ supports -7, -35, -36,  -37, -38, -39, -257, -258, -259, including variants with PKCS 1 v1.5. Do you know there reasons? 1 - as required by https://fidoalliance.org/specs/fido-v2.0-rd-20180702/fido-server-v2.0-rd-20180702.html#other is not among, them.
  * Is there a best-practice for algorithm-selection, when using webauthn in web apps? 

I'd be cool to find an answer to these questions. I'm still stumbling.

Thanks, in advance,
yanosz

**Comment by dwaite** [comment]
I believe there was some confusion by PIE on the role of ECDAA. It is meant as a way to attest the providence of an authenticator, not to secure the authentication itself. If ECDAA was completely broken, it would mean that a relying party may change their trust of authenticators which use ECDAA attestation (such as initiating a migration process off of those authenticators).

A server cannot 'avoid' ECDAA the way it can avoid requesting a particular signing algorithm, as the attestation format is a detail of the authenticator. A server that cares about the providence of an authenticator could choose to consider any authenticators using ECDAA attestations to have the default self-asserted/unattested level of trust. However, most sites are expected to not care about attestation at all, and the browsers will often strip attestation unless the user gives consent during registration.

When you say "1 - as required by fido-server-v2.0-rd-20180702", I believe you are talking about the P-256 curve, not a signing algorithm? A server must support this as part of other signing algorithms, such as ES256.

For the other points (and in my personal opinion) a lot of PIE's other arguments amount to "implementing crypto correctly is hard". Yes, if you are implementing *any* crypto algorithm (including those leveraging PKCS 1.5 padding), you should protect against timing attacks. Yes, if you accept a curve point you should verify that point is on the curve. Yes, if you use a format like JOSE/COSE that supports multiple algorithms, you should verify that the algorithm you requested was the one used. A good third party JOSE/COSE library should do those for you (and should have third party audits to back that up).

In an ideal world non-research usage would move to using a selected handful of algorithms and a library like libsodium - but there are political, technical and legacy support reasons that will never happen.

**Comment by selfissued** [comment]
The working group made an explicit decision not to define and register algorithm identifiers for ECDAA, given its uncertain security state.  That supports the premise of this issue.

**Comment by jcjones** [comment]
Per discussion on the WG call:

I think this is yet another argument that WebAuthn WG needs to produce, minimally, an explainer document as to (as an incomplete list of examples) 
1) thorny bits of how the JS API works, 
2) challenge hygiene,
3) migration from FIDO U2F JS API,
4) risk-assessment-grounded choices about attestation types (whether to demand Direct, whether to prohibit None)
5) algorithm selection

(See: #1231, #91, https://github.com/w3c/webauthn/search?q=explainer&type=Issues)

The previous efforts on this were closed as not being a deliverable of the WG. However, perhaps we should just start collecting the data in this wiki: https://github.com/w3c/webauthn/wiki/Explainer:-How-to-Implement-WebAuthn-as-a-Relying-Party

So let's take it there and start collecting. Per the above though, I am closing this issue.

**Comment by equalsJeffH** [comment]
The wiki jcjones pointed to above never received any updates, and in the meanwhile, [How to FIDO](https://github.com/fido-alliance/how-to-fido/blob/master/HowToFIDO.md) has appeared, so I have deleted the stillborn wiki page.
