### ISSUE TITLE
Underspecified RP ID length

### ISSUE THREAD

**Issue by emlun** [w3c/webauthn#1198]
Neither the [RP ID][rpid] definition nor [`PublicKeyCredentialRpEntity`][rpent] specifies any length requirements for the RP ID. This isn't a problem for executing the protocol, since the RP ID is hashed, but it does leave unspecified how long RP IDs authenticators are expected to support storing with resident credentials. This might at worst cause confusing display behaviours ~~for resident credential pick lists~~ in (as of yet not standardised) credential management interfaces.

[rpent]: https://w3c.github.io/webauthn/#dictdef-publickeycredentialrpentity
[rpid]: https://w3c.github.io/webauthn/#rp-id

**Comment by equalsJeffH** [comment]
on 17-Apr-2019 call -- we need to collect data wrt the RP ID lengths they support / need to support

**Comment by emlun** [comment]
Current Yubico prototypes truncate to 64 bytes from the right (i.e., the top domain and least specific subdomains may be truncated); our existing production devices don't store the RP ID and are therefore unaffected. We would object to a requirement to store more than 64 bytes of the RP ID.

**Comment by akshayku** [comment]
Authenticators don't have to store RPID if they don't want. They can get away with storing RPIDHash as an index.

**Comment by emlun** [comment]
Ah right, this indeed shouldn't affect credential pick lists since a specific RP ID is always given in that context. It could matter for (as of yet unspecified) credential management interfaces, but perhaps we should leave that to CTAP?

**Comment by akshayku** [comment]
Yup, we should leave that to the CTAP. Currently, RPIDHash as index is being used in credential management design.

**Comment by emlun** [comment]
Alright, I guess we can close this then.
