### ISSUE TITLE
Supported features detection from the browser

### ISSUE THREAD

**Issue by Kieun** [w3c/webauthn#1202]
This issue is related to the #1199 and this is more broader cases.
We, LINE, are trying to leverage WebAuthn for our login flow and suffering some issues handling different browsers/platforms.
RPs supporting WebAuthn already may have some logics to enable or disable supporting WebAuthn by looking at user agent information.
For real word implementation, it is very hard for us to detect such supported or not-supported features from UA.
It is better to have some APIs to provide supported features for RP to easily leverage the features.

**Comment by emlun** [comment]
Which specific features do you need to detect?

**Comment by Kieun** [comment]
Core features that we want to detect are followings: 
-> resident key support
-> supported client extensions
-> attestation conveyance
-> require user verification
As we @akshayku mentioned, for RP perspective, we need to get such information for making concrete use cases.

**Comment by jasonf1990** [comment]
@akshayku and I have been discussing this on our side as well.  We've been thinking of something along the lines of the following, accounting for the items mentioned above as well as some additional ones:

interface supportedCapabilities {
  readonly attribute boolean areU2FDevicesSupported; 
  readonly attribute boolean areCTAPDevicesSupported;
  readonly attribute boolean areResidentKeysSupported;
  readonly attribute boolean isUserVerificationSupported;
  readonly attribute boolean isTokenBindingSupported;
  readonly attribute sequence<AuthenticatorTransport> transportsSupported;
  readonly attribute sequence<DOMString> extensionsSupported;
};

partial interface PublicKeyCredential {
  static Promise<platformInfo> getSupportedCapabilities();
}

Will open a PR as well.

**Comment by emlun** [comment]
Removed pr-open label since #1219 was closed.

**Comment by equalsJeffH** [comment]
closing this since we closed the PR
