### ISSUE TITLE
better explain the relation between attestation models and attestation types

### ISSUE THREAD

**Issue by equalsJeffH** [w3c/webauthn#121]
better explain the relation between attestation models and attestation types at end of https://w3c.github.io/webauthn/#attestation

**Comment by rlin1** [comment]
I propose:
a) renaming Attestation Type to Attestation Format as this is what it really means.
b) rename attestation model to attestation type to align terminology with FIDO Metadata Statement.

**Comment by rlin1** [comment]
see branch rolf-attestation-types-121

**Comment by rlin1** [comment]
Will close as it has been merged into master.
