### ISSUE TITLE
Provide API for indicating whether the platform has attached(bound) authenticator or not

### ISSUE THREAD

**Issue by Kieun** [w3c/webauthn#1218]
WebAuthn API has [isUVPAA()](https://www.w3.org/TR/webauthn/#isUserVerifyingPlatformAuthenticatorAvailable) for RP to check whether the current user device has available platform authenticator.
This API may return true if the following conditions are met:

1. The platform provides or has attached (bound) WebAuthn authenticators
2. The authenticator is enabled (feature turned on) and user verification method (like PIN or biometrics) is enrolled on the authenticator if it supports uv.

Sometime RP wants to promote WebAuthn even in case where the user has platform authenticator but it is not enabled.
If there is such API, RPs are willing to check and show some guides for users to enable the authenticator depending on the policy.

I'm not sure how much of the users' devices do have the platform authenticator but not enabled for Android/Win10.

**Comment by equalsJeffH** [comment]
> (a) The authenticator is enabled (feature turned on) and (b) user verification method (like PIN or biometrics) is enrolled on the authenticator (c) if it supports uv.

Well, given the description of [the isUserVerifyingPlatformAuthenticatorAvailable() Method (isUVPAA())](https://www.w3.org/TR/webauthn/#isUserVerifyingPlatformAuthenticatorAvailable) it is [client platform](https://www.w3.org/TR/webauthn/#client-platform)-specific as to (a) and (b).  The intent of that method is to answer the (c) question.  

Perhaps isUVPAA() ought to be more rigorously specified wrt (a) and (b)?  I'm not sure whether that would be viewed as reasonable by client platform implementors.

**Comment by Kieun** [comment]
@equalsJeffH Just returning true/false to RP is not sufficient to handle UVPAA. As @jafisher-microsoft suggested, we would get more information. This is also good for platform vendors since they are able to get more chances to enable such new features.
Currently, Win10 and Android does not return true even it has supported authenticator on the platform if it is not enabled.

**Comment by emlun** [comment]
PR #1219 no longer covers this.

**Comment by equalsJeffH** [comment]
UA implementors are uncomfortable with adding a feature such as this as noted above https://github.com/w3c/webauthn/issues/1218#issuecomment-493221913, closing this
