### ISSUE TITLE
Poor documentation of how authnr aspects (platform, UV, RK) interact

### ISSUE THREAD

**Issue by emlun** [w3c/webauthn#1231]
An RP implementer remarks:

>And some extra things that would be nice:
>[...]
>- An explainer on how the different physical access concepts interact: user presence vs. user verification vs. platform authentication vs. prevent silent access. [This](https://www.w3.org/TR/webauthn/#sctn-authenticator-taxonomy) is a little confusing.

**Comment by bdewater** [comment]
Related to this issue: guidance on a passwordless login experience. [Common advice](https://developers.yubico.com/FIDO2/FIDO2_WebAuthn_Developer_Guide/Resident_Keys.html) seems to be to set `requireResidentKey: true` but the taxonomy table indicates that for first-factor authenticator, either single or multi-factor, client-side storage is just as acceptable.
