### ISSUE TITLE
Privacy risk from revealing allowed credentials

### ISSUE THREAD

**Issue by manger** [w3c/webauthn#1246]
A relying party wanting to use WebAuthn Authenticators (including those with non-resident keys) as a 1st factor needs to prompt for a username (eg email address) then reveal that user's credential ids by listing them in the allowedCredentials argument to the navigator.credentials.get() call. Hence, a user's credential ids are revealed to anyone who enters their username.

This is not a security problem (revealing a credential id does not allow anyone to authenticate with that credential). But it might be a slight privacy issue: it reveals how many authenticators a user has registered with this RP; and the length of each credential id gives a hint about its type. While the credential ids for the same user at another RP will have different values, it is likely that there will be the same number and they will have the same length.

[§13.10 Username Enumeration](https://w3c.github.io/webauthn/#sctn-username-enumeration) already suggests an RP return a fake credential id when it has no account for a given username (see [issue 1014](https://github.com/w3c/webauthn/issues/1014)). But RPs may not do that as many don't bother preventing username enumeration.

An RP could include fake credential ids alongside the real credential ids in the allowedCredentials argument (eg so everyone appears to have, say, 10 authenticators). That should be able to address most of the privacy risk (if the fakes are carefully chosen).

Is this worth mentioning in the Privacy Considerations section?
Could extra fake credentials harm the WebAuthn experience (either affecting the user interface, slowing performance, or causing errors)?

**Comment by emlun** [comment]
Thanks for pointing this out, we're aware of the issue but it hasn't been a high priority since we're not aware of much interest in using non-resident keys for 1st factor authentication.

I guess we could note in the suggestion of fake credential IDs that the same idea could be used to obfuscate a list containing real credential IDs as well. We could also propose using password authentication as a first step before the WebAuthn ceremony, but that would be a different use case than the one you're considering.

**Comment by manger** [comment]
Given that Chrome requires credential ids (even for resident keys) this affects _every_ 1st-factor WebAuthn use-case. And even if (or when) Chrome supports omitting the allowed credentials list, the issue still occurs unless websites are willing to block all non-resident authenticators, fracturing the ecosystem.

**Comment by emlun** [comment]
RPs don't need to block non-resident authenticators, they just need to not support authentication with a non-resident credential as the only authentication factor. Second-factor use cases prevent the information leak.

**Comment by equalsJeffH** [comment]
suggest editing the original post:
s/ WebAuthn Authenticators (including those with non-resident keys) as / WebAuthn Authenticators with non-resident credentials as /
