### ISSUE TITLE
Certain issues in client extension pass-through specification

### ISSUE THREAD

**Issue by peteroupc** [w3c/webauthn#1273]
There are two issues with Section 9, which discusses how clients pass through unrecognized extensions.

1.  In the algorithm for converting client extension inputs to CBOR, section 9 currently says: "When the JavaScript value _is a non-integer number_, it is converted to a 64-bit CBOR floating point number."  But until recently, JavaScript has only one number type, namely a 64-bit floating-point number of the class `Number`, and no integer types such as 32- or 64-bit integers.  And currently, of the defined WebAuthn extensions, only biometricPerfBounds includes number types, namely `float`, in client extension inputs. This suggests to me that—

    - section 9 can simply say "When the JavaScript value is a `float` [or `float` or `double`]..." rather than "When the JavaScript value is a non-integer number", and
    - WebAuthn should discourage new extension definitions that use any number type other than float (or `double`) in their client extension inputs (due to the [lack of a threshold](https://github.com/w3c/webauthn/issues/1044) above which integers are converted to floating-point numbers rather than CBOR integers).

2.  When a client passes through an unrecognized extension, the special cases for ArrayBuffers, non-integer numbers, and CBOR byte strings are probably intended to apply when those values appear as keys and values of arrays and maps, rather than just when they stand alone (one possible interpretation due to how this section incorporates RFC7049 by reference).  This can be addressed, for example, by adding text as follows: "However, if the JavaScript value contains ArrayBuffers and/or non-integer numbers [contains ArrayBuffers, `float`s, and/or `double`s], they are converted as described above rather than as given in that section."

**Comment by dwaite** [comment]
This seems related to #1263

**Comment by dwaite** [comment]
As you have stated, the javascript type will almost always be `Number`.

My interpretation of this statement has been, if the client does not understand an extension (such as `authenticatorBiometricPerfBounds`, it must detect whether a value is an integer. If so, it sends it as a CBOR integer. If not, it sends it as a 64-bit floating point value.

So in this example, `FAR` and `FRR` represent values from zero to one, inclusive. If the client did not understand this extension and the javascript request had either a value of 0.0 or 1.0 for either of these parameters, that parameter would be sent to the authenticator not as a 64 bit floating point value - but as a positive integer.

**Comment by peteroupc** [comment]
In that case, this issue is also related to #1044, in that there is no unambiguous way to "detect whether a [JavaScript `Number`] value is an integer"  And this matters for canonicalization purposes (neither WebAuthn nor RFC7049 clarify this matter sufficiently for such purposes).  For example, CBOR integers can store only integers in [-(2^64), 2^64 - 1], not all integers representable in a JavaScript `Number`.  Likewise, 32- and 64-bit signed and unsigned integers cannot represent all integers representable in a JavaScript `Number`.  On the other hand, JavaScript `Number`s can represent all integers in [-(2^53), 2^53], but not all integers in, say, [-(2^64), 2^64].  This results in several plausible choices for the threshold below which integer `Number`s are converted to CBOR integers (e.g., 2^53, 2^64, and 2^32).  My suggested solution avoids this problem by referring to _types_, not _numbers_.

**Comment by selfissued** [comment]
As discussed on the 14-Aug-19 working group call, the pass-through transformation is already unambiguously specified.  We understand that one consequence of the way that it is specified is that floating point parameters with whole integer values will be passed as CBOR integers, rather than CBOR floats.  This was an intentional choice, since JavaScript historically has had only one (floating point) representation for numeric values and we certainly wanted interfaces using only integers to be represented using CBOR integers.

Yes, if an authenticator implements an extension using floating point values and it wants it to work in pass-through mode, it must be prepared to accept these values when represented either as CBOR floats or CBOR integers.  While not ideal, this is workable in practice, and well understood.

I believe that this issue should be closed with no action on this basis.

**Comment by peteroupc** [comment]
In that case, the only thing I would suggest is to change "When the JavaScript value is a non-integer number, _a number less than -2^64, or a number 2^64 or greater,_ it is converted to a 64-bit CBOR floating point number."  This change preserves the behavior of representing 0 and 1 (and other integers representable in CBOR major types 0 and 1) as CBOR integers, as is the intention.

As I mentioned in an earlier comment, CBOR integers (with major type 0 or 1) can't represent all integers representable in a JavaScript `Number`.  For example, an integer as high as 2^86 or as low as -2^86 is representable as a JavaScript `Number` but is not representable as a CBOR integer (major type 0) (but it can be represented in a bignum with CBOR tag 2, but I don't believe the intention is to serialize any integers as bignums in CBOR).

**Comment by selfissued** [comment]
I am OK with us adding a clarification of the intent along the lines that you suggest.  I'll plan to create a pull request to do this.  Thanks.

**Comment by peteroupc** [comment]
To add to my previous comment:

Likewise, there are integers representable as CBOR integers (major type 0 and 1) but not representable in a JavaScript `Number`.  This includes all odd integers in the interval (2^53, 2^64).

As a result, the suggested text "... a non-integer number, a number less than -2^53, or a number 2^53 or greater ..." is plausible, just as "... a non-integer number, a number less than -2^64, or a number 2^64 or greater ..." is.

**Comment by nadalin** [comment]
@akshayku Create PR

**Comment by nadalin** [comment]
@selfissued Create PR

**Comment by selfissued** [comment]
Note that the range issues (2^53, 2^64, etc.) are already discussed in Section 4.2 (Converting from JSON to CBOR) of RFC 7049 (CBOR), so I don't believe the PR also needs to discuss them.
