### ISSUE TITLE
Misleading key order in attestation object diagram

### ISSUE THREAD

**Issue by emlun** [w3c/webauthn#1274]
The [attestation object][attobj] diagram lists the CBOR map keys in the order: `authData`, `fmt`, `attStmt`, but WebAuthn [requires CBOR to be canonically encoded][canon]. This means that clients MUST encode the attestation object with the key order: `fmt`, `attStmt`, `authData`.

We should perhaps update the diagram to reflect the actual key order, or at least mention this in a note along with the diagram.

See also: https://github.com/brave/brave-ios/issues/1365

[attobj]: https://w3c.github.io/webauthn/#attestation-object
[canon]: https://w3c.github.io/webauthn/#sctn-conforming-all-classes

**Comment by emlun** [comment]
I also just noticed a typo in the figure: "attestsion statement format" to the right of the "ATTESTATION STATMENT" title in the bottom-right.

**Comment by equalsJeffH** [comment]
Thanks @emlun and to @agl whoi submitted the bug on Brave.  

It seems to me that we also need to modify the CDDL in [Section 6.4.4. Generating an Attestation Object](https://www.w3.org/TR/webauthn/#generating-an-attestation-object):

Old:
```cddl
    attObj = {
                authData: bytes,
                $$attStmtType
             }

    attStmtTemplate = (
                          fmt: text,
                          attStmt: { * tstr => any } ; Map is filled in by each concrete attStmtType
                      )
```
New:
```cddl
    attObj = {
                $$attStmtType           // this yields ordering of: "fmt", "attStmt", "authData"
                authData: bytes,
             }

    attStmtTemplate = (
                          fmt: text,
                          attStmt: { * tstr => any } ; Map is filled in by each concrete attStmtType
                      )
```

**Comment by equalsJeffH** [comment]
fyi/fwiw, since we're using `.svg` illustration files, the file is the source and I simply edited it in Inkscape.
