### ISSUE TITLE
Section 8.6 step 6 clarification (Correct Hash algorithm)

### ISSUE THREAD

**Issue by tomciopp** [w3c/webauthn#1279]
I'm implementing a relying party and I have a question about the FIDO U2F verification procedure. It looks like the hash function is hard coded to sha256 in most other implementations and I believe that is correct, but wanted to make sure. 

The associated link listed along with the step does not provide any clear indication of what should be done as it just links to a 144 page document that reviews standards for ECC, and not a subsection of that document that will be of use to the implementer in this case. 

Other implementers have grabbed the hash algorithm from the auth_data => attested_credential_data => credential_public_key map and then done a lookup  based on COSE. This seems to me like an unnecessary step, but I am not 100% sure.

**Comment by emlun** [comment]
Which hash in which step specifically are you talking about?

**Comment by tomciopp** [comment]
https://w3c.github.io/webauthn/?source=post_page---------------------------#sctn-fido-u2f-attestation

Verification => Step 6

**Comment by bdewater** [comment]
The U2F attestation formats section should be read within the context of other sections on attestation 🙂. But the back and forth can be confusing. Section 6.4.5 on signature formats for the different attestation formats mentions:
> For COSEAlgorithmIdentifier -7 (ES256), and other ECDSA-based algorithms, a signature value is encoded as an ASN.1 DER Ecdsa-Sig-Value [...] CTAP1/U2F authenticators are already producing signatures values in this format

If you want to follow the rabbit-hole with the sources given in section 8.6, step 3 refers to ALG_KEY_ECC_X962_RAW key format which according to the [FIDO registry document](https://fidoalliance.org/specs/fido-v2.0-id-20180227/fido-registry-v2.0-id-20180227.html#h3_tags-used-for-crypto-algorithms-and-types) can be used with ECDSA/SHA-256 and SM2/SM3. 

[SEC1: Elliptic Curve Cryptography](http://www.secg.org/sec1-v2.pdf) referred to in step 6 mentions:
> The ANS X9.62 standard specifies ECDSA for use by the financial services industry. It requires
ECDSA to be used with an ANSI-approved hash function, and with elliptic curve domain parameters with n > 2 <sup>160</sup> to meet the stringent security requirements of the banking industry. Subject to these constraints and other procedural constraints such as the use of an ANSI-approved random number generator, the specification of ECDSA in this document should comply with ANS X9.62-2005.

Per the excerpt of ANSI X9.62-2005 (a non-free document) from https://standards.globalspec.com/std/1955141/ANSI%20X9.62 :
> The ECDSA shall be used in conjunction with an Approved hash function, as specified in X9 Registry Item 00003, Secure Hash Standard (SHS). The hash functions Approved at the time of publication of this document are SHA1 (see NOTE), SHA-224, SHA-256, SHA-384 and SHA-512. 

The Secure Hash Standard latest version is https://csrc.nist.gov/publications/detail/fips/180/4/final but the only common hash function through this all is... you guessed it 😄 SHA-256.

**Comment by tomciopp** [comment]
@bdewater Thank you for the clarification. I think we should put a note in the documentation that sha256 is the expected hash function because I went a little bananas trying to track this info down.

**Comment by agl** [comment]
> Other implementers have grabbed the hash algorithm from the auth_data => attested_credential_data => credential_public_key map and then done a lookup based on COSE. This seems to me like an unnecessary step, but I am not 100% sure.

You're talking about verifying the attestation signature? If so, then looking at the [credential public key](https://w3c.github.io/webauthn/#credentialpublickey) is wrong because that's the public key that has just been _generated_ by the authenticator. It's not the key that's embedded into the authenticator and used to sign the (transformed) [attested credential data](https://w3c.github.io/webauthn/#sctn-attested-credential-data).

The attestation certificate is an X.509 certificate and thus contains a [Subject Public Key Info](https://tools.ietf.org/html/rfc5280#section-4.1) which describes the public key but not the signature hash function. The hash function is just SHA-256 by convention and we should nail that down in the spec.
