### ISSUE TITLE
Specify if clients are expected to follow redirects for icon URLs

### ISSUE THREAD

**Issue by lgarron** [w3c/webauthn#1285]
At GitHub, we have "nice" profile icon URLs like https://github.com/lgarron.png

That URL redirects to https://avatars2.githubusercontent.com/u/248078?v=4 , which is moderately stable but could change some day. Could I ask for the spec to specify whether RPs are expected to follow the redirect from the more permanent URL?

I can't find information on this; #1139 is the closest I've found

**Comment by emlun** [comment]
Both `user.icon` and `rp.icon` are specified by the RP*, so RPs aren't expected to process them at all after passing them into a WebAuthn function call. #1139 has some discussion on what authenticators and/or clients are expected to do with them.

\* Or by the user under the RP's supervision, unless the user modifies the client-side script. In either case, the RP controls the values for the purposes of this discussion.

**Comment by lgarron** [comment]
Ah, I'm sorry, I meant to ask about clients!

**Comment by dwaite** [comment]
My understanding of the correlation issue is that a client may cache the icon at the conclusion of authentication and registration, but a client will not resolve the icon before authentication using the network due to correlation concerns.

I agree with @lgarron that very few relying parties will manage to fit a usable icon within the 85 bytes you can hypothetically squeeze out of a 128 character data URL. It is more likely they will use a regular URL and let clients deal with the UX of not having an icon.

**Comment by emlun** [comment]
> A recommended target of 4K or 8K is somewhat doable.

Sorry, this is not going to happen for hardware authenticators at least. Resident credentials already require a significant amount of storage space.

**Comment by dwaite** [comment]
> On a practical note do we have the size etc of the icons sufficiently defined so that a platform could display them? This may be a bit like the authenticator icon in meta-data, something that seems like a good idea, but is never used in practice

Thats my concern. We also have two icons:

1. The RP entity icon, which likely is the same for all RP registrations. It isn't useful for choosing a credential to use, but may be useful if you are managing the credentials on an authenticator.

2. The user entity icon, which is likely different for each registration. It might be useful for choosing a credential to use, but will likely only contain a usable value if the RP maintains profile information including a photo or avatar. It also must be user-differentiated, so fundamentally must leak information on loading.

If desired, the RP icon would have a good shot of being changed to be widely usable. For example, we could reference an image source set via .well-known of the RP domain, and have clients fetch that without session state. Of course, a well-known lookup also technically no longer needs the URL field.

We don't have infrastructure to use the user icon ad-hoc (such as an intermediate, anonymizing cache). So the user icon is only really displayable if previously cached by a registration or authentication action, loaded by user action, etc.  We still would have the problem that not all RPs have a usable picture for this, or guidance on how it will be displayed.

**Comment by nadalin** [comment]
@jcjones Create PR

**Comment by jcjones** [comment]
I will make a PR to deprecate the image fields and any others that are unlikely to be utilized by platforms or authenticators.

**Comment by jcjones** [comment]
Still working on this!
