### ISSUE TITLE
Browsers adding extensions.

### ISSUE THREAD

**Issue by ve7jtb** [w3c/webauthn#1287]
We currently have one browser adding the CredProtect extension set to level 2 if the RP doesn't specify a level.

While that may be reasonable at some level, RP are required by WebAuthn to reject registrations with extensions that the RP didn't ask for in step 12.

https://www.w3.org/TR/webauthn/#registering-a-new-credential

The workaround is having all RP specify Credprotect explicitly.  That is probably not ideal.
We could beck off the requirement to reject.  As long as the RP knows the extension it is perhaps OK for it to accept it.

I suspect that clients adding extensions on the users behalf will not be that unusual going forward.

John B.

**Comment by sbweeden** [comment]
I think we need to separate out the discussion of what a reasonable default might be from the current point, which is that WebAuthn processing rules currently require the rejection of messages that include unsolicited extensions.

**Comment by sbweeden** [comment]
Per call on 2019-08-28 I will write a PR to relax the MUST requirement.

**Comment by sbweeden** [comment]
See PR: #1289
