### ISSUE TITLE
webauthn should have the ability to cross platform

### ISSUE THREAD

**Issue by netroby** [w3c/webauthn#1290]
I read many implement of webauth, for windows, user may use windows hello, for linux, user may use usb key, for android device, user may use finger print.

but we need a universal auth solution ( like a android app [ google authenticator])
or what ever. 

If it was a phone app, we can login any app/website ,by using the one authenticator

**Comment by sbweeden** [comment]
That is unrealistic. What if you don’t have a mobile or are not permitted to have one in possession in your operating environment?

For the most part cross-platform authenticators are available via USB and NFC transports and caBLE is on the way for using a mobile authenticator via a form of BLE against a laptop browser. For other edge cases, register more than one authenticator against the same account.

**Comment by emlun** [comment]
Closing since this should be covered by roaming authenticators (CTAP) in general and (upcoming) [CaBLE](https://github.com/w3c/webauthn/pull/909) in particular. You're welcome to re-open the issue if these solutions do not cover your use case.
