### ISSUE TITLE
Consider whether browsers should truncate `name` and `displayName`.

### ISSUE THREAD

**Issue by agl** [w3c/webauthn#1296]
We say of [PublicKeyCredentialEntity](https://www.w3.org/TR/webauthn/#dictionary-pkcredentialentity)'s `name` and [PublicKeyCredentialUserEntity](https://www.w3.org/TR/webauthn/#sctn-user-credential-params)'s `displayName`, that:

> Authenticators MAY truncate [&hellip;] to a length equal to or greater than 64 bytes.

**Some authenticators do, indeed, truncate these strings at 64 bytes**. This may cut a UTF-8 sequence and thus produce invalid strings in responses. Because of this, WebAuthn now has [a section](https://w3c.github.io/webauthn/#sctn-strings) on handling these truncated strings.

However, some authenticators will also _**reject any operations where the strings are longer than 64 bytes**_. Whatever the fidelity of that behaviour to the spec, it's now reality. _Therefore we should consider whether it's the browser's job to do the truncation in order to ensure that requests work_. If we do not, then RPs will probably do it themselves because things will fail otherwise and once RPs do it, we'll not be able to add support for future authenticators which have more storage.

(Since there exist truncating authenticators out there, [the rules](https://w3c.github.io/webauthn/#sctn-strings) around string handling still apply because those authenticators aren't going away either.)

(I don't know, off-hand, what the behaviour for `icon` is in practice.)

(This relates to fido-alliance/fido-2-specs#673.)

**Comment by lgarron** [comment]
I don't know if this is the best place to comment, but: if RPs *do* have to truncate in the future, it would help to have some guidance on whether it matters that the RPs do a strict truncation.

Something like an ellipsis would help distinguish between names that are ≈64 bytes and those that are longer: `thisismyexteemelylongusernamethatistotallyreasonabletouseonth…`  
But that wouldn't be strict truncation.

**Comment by nadalin** [comment]
@agl to create PR
