### ISSUE TITLE
Consider rewording restrictions around origin

### ISSUE THREAD

**Issue by sbweeden** [w3c/webauthn#1297]
At present section https://w3c.github.io/webauthn/#relying-party-identifier states a restriction in the green Note box about origin scheme must be https. 

Whilst this is true when the RP is only used by browsers using WebAuthn, the platform authenticator of Android when used in a native app doesn't do this - it uses a different URI for origin and a hosted assetlinks.json file to bind this to the RPID.

Should the WebAuthn spec be inclusive of this type of use case, or at least mention that RPs MAY accept other origins for non-browser clients provided there is a trust mechanism in place to ensure the client validates that the origin is permitted by the RPs domain?

**Comment by agl** [comment]
WebAuthn is a W3C spec and thus it should probably only deal with the web. You might be interested in https://github.com/fido-alliance/fido-2-specs/issues/682 however.

**Comment by sbweeden** [comment]
I noticed in that issue:

_Credentials for these contexts will want to be separated such that they can never be used unexpectedly by the web._

In the Android case it is explicitly a goal that the credentials can be shared between the browser and native mobile contexts. That’s in part why I think it does relate to WebAuthn.

**Comment by herrjemand** [comment]
@agl I am a little bit lost. I thought that WebAuthn is the document that defines server processing. And now we gonna have FIDO2 specs contains "exception" to the WebAuthn specs?

**Comment by sbweeden** [comment]
@herrjemand there are other gaps in that space. For example FIDO2 conformance requires a server to be able to support use cases for UP=false whereas WebAuthn explicitly requires UP=true always. How would you propose to resolve that irregularity?

**Comment by herrjemand** [comment]
@sbweeden That comes from authenticators supporting silent authentication, and we test it because this feature is explicitly in development.

**Comment by sbweeden** [comment]
It is not mentioned in any normative server specification.

**Comment by equalsJeffH** [comment]
As discussed in the webauthn f2f 20-Sep-2019 -- we probably ought to put a Note: in the RP assertion validation rules that points the RP dev's to whichever platform rules for assertion validation is appropriate, eg, Android, Windows, etc...

**Comment by nadalin** [comment]
@sbweeden Please create PR per @equalsJeffH  note

**Comment by sbweeden** [comment]
> As discussed in the webauthn f2f 20-Sep-2019 -- we probably ought to put a Note: in the RP assertion validation rules that points the RP dev's to whichever platform rules for assertion validation is appropriate, eg, Android, Windows, etc...

The current PR adds to the Note in the RP definition, which in turn is referenced by the validation steps for both credential creation and assertion. I don't see any value in enumerating specific platform vendors at the moment since this is likely to change over time.
