### ISSUE TITLE
Clarify Relying Party Server or Server

### ISSUE THREAD

**Issue by kasecato** [w3c/webauthn#1309]
I was confused by the label `Relying Party Server` in [Figure 1](https://www.w3.org/TR/webauthn-1/#fig-registration) and [2](https://www.w3.org/TR/webauthn-1/#fig-authentication). This is because I thought the server was "Relying" something like "FIDO2 Server" or "WebAuthn Server" but it seemed to be validating on it. MDN simply describes it as "[Server](https://developer.mozilla.org/en-US/docs/Web/API/Web_Authentication_API#Registration)."

**Comment by agl** [comment]
Although Relying Party Server is not explicitly defined, [Relying Party](https://www.w3.org/TR/webauthn-1/#webauthn-relying-party) is defined and we couldn't think of any helpful changes to the diagram. We may tweak the Relying Party definition to mention the server/Javascript split, however.
