### ISSUE TITLE
Privacy leak via credential IDs also applies to resident credentials

### ISSUE THREAD

**Issue by maxhata** [w3c/webauthn#1311]
> This privacy consideration applies to Relying Parties supporting single-factor authentication with non-resident credentials.

This should apply not only to non-resident credentials but also resident credentials if credentialIds are sent. Sending credentialIds in an allowCredentials is a legitimate flow for authentication. Thus, I suggest to change "with non-resident credentials" to something like "when sending an allowCredentials with credentialIds."

**Comment by emlun** [comment]
Thanks, this is being worked on in #1250.
