### ISSUE TITLE
Underspecified client output in `exts` extension

### ISSUE THREAD

**Issue by emlun** [w3c/webauthn#1314]
[10.6. Supported Extensions Extension (exts)](https://w3c.github.io/webauthn/#sctn-supported-extensions-extension) reads:

>**Client extension output**
>Returns the list of supported extensions as an array of extension identifier strings.
>
>**Authenticator extension output**
>The SupportedExtensions extension is a list (CBOR array) of extension identifier (UTF-8 encoded) strings.

It is not clear if the client extension output is supposed to be the list of extensions the client supports, or the list from the authenticator decoded as a JavaScript array.

**Comment by emlun** [comment]
Ah - on second read, the extension summary does seem to clarify it:

>This extension enables the WebAuthn Relying Party to determine which extensions the authenticator supports.

So I suppose the client extension output section should rather be something like:

>**Client extension output**
>Returns the authenticator extension output as an array with each extension identifier UTF-8 decoded into a USVString.

**Comment by equalsJeffH** [comment]
>This extension enables the WebAuthn Relying Party to determine which extensions the authenticator supports.

hm. We do have extensions that are known only to the webauthn client eg [10.1. FIDO AppID Extension (appid)](https://w3c.github.io/webauthn/#sctn-appid-extension).

It does seem given how ["Supported Extensions" extension](https://w3c.github.io/webauthn/#sctn-supported-extensions-extension) is written that it may have been originally intended to report only on supported authnr extensions.  But is that what we really want/need?

I'm thinking that the ["Supported Extensions" extension](https://w3c.github.io/webauthn/#sctn-supported-extensions-extension) ought to report on _all_ extensions supported by the client platform + authnr.

**Comment by equalsJeffH** [comment]
on 2020-01-15 call:  so the extn as written is about authnr extensions, @emlun's clarifications in the PR #1361 look fine to folks, so we're going to merge the PR as-is and maybe someday get back to the meta-level questions of whether the extn itself is of use and whether it ought to report on client-platform extensions additionally.
