### ISSUE TITLE
update extensions framework to include interfacing with user agent permissions framework

### ISSUE THREAD

**Issue by equalsJeffH** [w3c/webauthn#133]
update extensions framework to include interfacing with user agent permissions framework

**Comment by equalsJeffH** [comment]
see also #208

**Comment by selfissued** [comment]
@equalsJeffH is there anything left to do for this issue?  If so, are the concrete proposed changes?  If not, we should close this one.

**Comment by nadalin** [comment]
@equalsJeffH , @selfissued  Can we close this one since Mike has redone the extension section ?

**Comment by equalsJeffH** [comment]
@AngeloKai has asserted that interfacing with the permissions framework is not applicable for webauthn in this context, and AFAIK we've just accepted that, so closing this. tho, if someone disagrees please cite appropriate specs etc.

**Comment by riking** [comment]
I feel like this should be addressed - it seems like a mistake to allow websites to get geolocation information without the user being notified.

> Client extension processing  
>
> Check the [[permissions state]] for geolocation. If the permission state is `"denied"`, the client MUST remove the extension and not pass it to the authenticator. If the permission state is `"prompt"`, the user agent MAY prompt the user and restart this processing, or MAY remove the extension without prompting. If the permission state is `"granted"`, the client creates the authenticator extension input with the Boolean value `true`.

**Comment by equalsJeffH** [comment]
reopening due to https://github.com/w3c/webauthn/issues/133#issuecomment-349458824

**Comment by equalsJeffH** [comment]
It seems that having the geoloc extension check the permissions framework is a resonable thing since geoloc is a defined permision in: https://w3c.github.io/permissions/#permission-registry

**Comment by gmandyam** [comment]
@equalsJeffH 

Wouldn't the client (UA) check the permissions framework, rather than the extension implementation itself?  Since the client can choose to drop extensions, it can use the permissions framework as part of the criteria in determining whether to drop or not.

**Comment by equalsJeffH** [comment]
@gmandyam 
Yeah, that might be the case, perhaps the extension only needs to say that the client platform ought to check permissions as appropriate and if available, e.g., geoloc, and reference  https://w3c.github.io/permissions/ ?

**Comment by selfissued** [comment]
I agree that the client platform should do this check - not the extension

**Comment by nadalin** [comment]
@gmandyam will create PR

**Comment by selfissued** [comment]
@gmandyam can you please create the PR today or tomorrow morning so we can review it during the FIDO 2.0 meeting tomorrow?  Thanks.

**Comment by gmandyam** [comment]
Addressed through https://github.com/w3c/webauthn/pull/771

**Comment by selfissued** [comment]
Can this be closed now that #771 has been merged?
