### ISSUE TITLE
RP guidance for `invalidStateError` returned from `[[Create]]()`

### ISSUE THREAD

**Issue by equalsJeffH** [w3c/webauthn#1331]
the Note that PR #1326 inserts into the spec explains the purpose of the UV gesture solicited in the `authenticatorMakeCredential()` operation when there are match(es) in the `|excludeCredentialDescriptorList|`. Essentially, we're explaining in the (new) Note that: "if the RP gets an `invalidStateError` back from a nav.creds.Create() call, they can do something user-helpful with that info".

However, this guidance for the RP is buried in "Note:"s in spec sections that _we are not suggesting_ RP devs read (i.e., in the [spec roadmap](https://w3c.github.io/webauthn/#sctn-spec-roadmap)).  

Additionally, our "[RP Ops - registering a new cred](https://w3c.github.io/webauthn/#sctn-registering-a-new-credential)" section only says "abort the ceremony with a user-visible error" if an error is returned from Create().

 Seems like we ought to provide more guidance to the RP reader. Perhaps add this to the "[rp operations - registering a new cred](https://w3c.github.io/webauthn/#sctn-registering-a-new-credential)" section ?

Are there also similar RP considerations for "[RP Ops - verifying an authentication assertion](https://w3c.github.io/webauthn/#sctn-verifying-assertion)" we ought to add to the latter section?

**Comment by equalsJeffH** [comment]
this is a nice-to-have issue, can be addressed in a milestone later than wd-03 or not at all.

**Comment by equalsJeffH** [comment]
@sbweeden -- what's your take on this issue?  Is it worth addressing?  If so, might you have wording suggestions?

**Comment by sbweeden** [comment]
Closing - addressed with #1502
