### ISSUE TITLE
exclude/allowCredentials state different defaults in definition vs description

### ISSUE THREAD

**Issue by emlun** [w3c/webauthn#1346]
[The definitions state](https://w3c.github.io/webauthn/#dictionary-makecredentialoptions):

```
    sequence<PublicKeyCredentialDescriptor>      excludeCredentials = [];
    sequence<PublicKeyCredentialDescriptor>      allowCredentials = [];
```

But [the descriptions state](https://w3c.github.io/webauthn/#dom-publickeycredentialcreationoptions-excludecredentials):

>***excludeCredentials*, of type sequence\<PublicKeyCredentialDescriptor\>, defaulting to `None`**
>***allowCredentials*, of type sequence\<PublicKeyCredentialDescriptor\>, defaulting to `None`**

Which is correct?

**Comment by equalsJeffH** [comment]
I think the definitions are correct, IIRC. bikeshed perhaps is misunderstanding what to state in the descriptions. this may have been caused by a webidl-driven auto-spec edit, have to look into that....

**Comment by emlun** [comment]
Looks like this goes back to the very beginnings of the spec, it's not a recent change: https://www.w3.org/TR/2017/WD-webauthn-20170505/#dom-publickeycredentialrequestoptions-allowlist

The earliest spec version with the `[]` default is https://www.w3.org/TR/2017/WD-webauthn-20170216/#dom-assertionoptions-allowlist, but that doesn't use the same definition header.

**Comment by emlun** [comment]
Digging deeper, this seems like a bug in Bikeshed: https://github.com/tabatkins/bikeshed/issues/1592

**Comment by emlun** [comment]
This is now fixed upstream, so any builds with a fresh Bikeshed installation should be good. I'll keep an eye on the editor's draft and close this once the fix shows up there.

**Comment by equalsJeffH** [comment]
thx @emlun, do we need to manually update the travis machinery to use the latest bikeshed?

**Comment by emlun** [comment]
I don't think so, the Travis build should be using the latest Bikeshed version as far as I can tell. Unless the `install` step is cached, but it looks like it's not.

https://github.com/w3c/webauthn/blob/6349d2422ac13318a6a54e1432ca84b79a98a1fc/.travis.yml#L19

**Comment by emlun** [comment]
This is now fixed in the working draft.
