### ISSUE TITLE
BLE Resolvable Private Address resolution using IRK

### ISSUE THREAD

**Issue by rjhallock6** [w3c/webauthn#1371]
Hi, I’ve created a biometric BLE Authenticator App that operates correctly in all regard except one. 

Some background: the BLE stacks of both Android and iOS implement Resolvable Private Address for security reasons. RPA is a process where when pairing the client and authenticator device agree on IRK use. Thereafter, when authenticator initiates advertising the BLE stack on that device assigns a new device address for the advertising session. The paired client will see the new address, not the address used during pairing, and resolve it to the original pairing device address using the IRK. This occurs during the client scanning process.

The problem: the authenticators FIDO or U2F BLE session begins advertising with a new device address added by the stack after demonstration of intent from the user (button tap, bio capture/verify, or whatever). Meanwhile, the browser client app, webauthn.js for example, has executed either create() or get() doing so using the paring device address of the BLE device with FIDO GATT. If a scan had not been done before either, the access will fail and a timeout results and the FIDO or U2F attempt aborts.

Problems isolation: I believe the problem is within the webauthn.js module. Within it there is no code to force IRK address resolution that I could find. Either navigator.bluetooth.requestDevice() or navigator.bluetooth.requestLEScan() would have to be called prior to either create() or get() to resolve the issue.

As a temporary workaround I’ve created a web app I run in a separate tab along side the FIDO or U2F client. In this I’ve tried both requestBLEScan () and requestDevice() and either works to solve the problem. 

Workaround app attached.
[requestLEScan.txt](https://github.com/w3c/webauthn/files/4167490/requestLEScan.txt)

**Comment by agl** [comment]
This is the W3C group that defines WebAuthn, the Web Platform API. WebAuthn only suggests that BLE might be used as a transport and doesn't define anything about how it's implemented. (That's handled by FIDO.) Also, the WebAuthn API doesn't have any BLE addresses in it.

It seems that perhaps this is a bug report for a specific platform implementation of BLE support?

**Comment by rjhallock6** [comment]
Thanks, your's prompted digging deeper to learn fido_device_discovery was added to the navigator sdk last year. I now need to learn if an sdk build with that has been release and if any browser is yet using it.

**Comment by jensatch** [comment]
I'm also seeing the issue on Windows 10 versions 1903, 1909. We're developing FIDO authenticator apps for Android and iOS and both exhibit the same problem where after the authenticator's Bluetooth address changes, the platform cannot find the device during calls to getAssertion and makeCredential. Running an advertisement scanner on the platform prior to calling webauthn works around the problem. The problem returns when the address changes again. The address changes every 15 minutes.

It feels like a bug in the Windows CTAP implementation. If so, it will likely affect any BLE authenticator that uses the BLE privacy feature. Android and iOS both use the feature (we have no choice), and the FIDO spec recommends that BLE authenticators use the privacy feature.

**Comment by rjhallock6** [comment]
I now have Windows 10 FIDO and U2F operational for testing. I’m using Windows 1909 with Chrome 80.0.3987.106. Its still necessary to set the Chrome://flags experimental web platform features and web authentication api ble support.

**Comment by MMucka** [comment]
Hi, I'm facing the same issue. I want to create Android Fido authenticator and there is still problem with connecting from Windows side. When I keep running scanner in chrome://bluetooth-internals/#devices, there is no problem (workaround). But it would be great to have it working without this. Does anybody found solution, or can you please point me on different repo, where I could find more information? Thank you
