### ISSUE TITLE
Return authentication method used for platform types

### ISSUE THREAD

**Issue by gcbenjamin** [w3c/webauthn#1373]
Is there currently any way of distinguishing in the response from the API what platform authentication method was used? For example, was fingerprint used on the android device or was fingerprint bypassed to use the devices PIN instead? Did fingerprint fail and PIN was used? Currently I can fail with my fingerprint 5 times and use PIN instead and I am still returned a success. (I'm guessing its the same for FaceId but I'm yet to test FaceId).

Use case: I'm a parent and my kids know my pin. Why? Just ask 99% of parents with small kids...... :P 
My website is implementing WebAuthN and contains sensitive data (like credit card). By allowing WebAuthN my site is now far LESS secure than a traditional password. You could argue that you should keep your device PIN as secret as a password but in reality that is not the case. Even a dirty phone screen leaves the unlock pattern smudge for the whole world to see!

**Comment by sbweeden** [comment]
There are extensions defined in WebAuthn for this however the browser vendors have so far chosen not to implement support for them quoting various privacy concerns.

**Comment by gcbenjamin** [comment]
Can you point me to the extensions? I can at least keep an eye on and keep bugging the browsers for a change :)

**Comment by dwaite** [comment]
https://www.w3.org/TR/webauthn/#sctn-uvm-extension

**Comment by gcbenjamin** [comment]
So chrome (or is it android?) doesn't return the UVM used to verify with the device, but returns all the UVMs supported by the device. So on my device for instance, I get back the flags for fingerprint, pin and draw pattern every time no matter what verification I use. Have chrome (or android) interpreted the spec incorrectly or is that the expected behaviour?

**Comment by gcbenjamin** [comment]
I think I see the confusion, well, I got confused and had to read it a few times. The WebAuthn spec says 

> The authenticator sets the authenticator extension output to be one or more user verification methods indicating the method(s) used by the user to authorize the operation, as defined below. This extension can be added to attestation objects and assertions

Theres also a link through to the FIDO registry for UVMs [https://fidoalliance.org/specs/fido-v2.0-id-20180227/fido-registry-v2.0-id-20180227.html#user-verification-methods]. Reading this could maybe be interpreted as if the authenticator has the capability, set the flag. 

> The USER_VERIFY constants are flags in a bitfield represented as a 32 bit long integer. They describe the methods and capabilities of an UAF authenticator for locally verifying a user. The operational details of these methods are opaque to the server. These constants are used in the authoritative metadata for an authenticator, reported and queried through the UAF Discovery APIs, and used to form authenticator policies in UAF protocol messages.

**Comment by Kieun** [comment]
@gcbenjamin You can refer the related chromium issue.
https://bugs.chromium.org/p/chromium/issues/detail?id=1046700

**Comment by gcbenjamin** [comment]
@Kieun When they say it's not exposed by the framework, are they referring to Android?

**Comment by Kieun** [comment]
Yes, it's Android. Cheers!

**Comment by equalsJeffH** [comment]
we decided on 2020-021-19 call that this issue has been asnwered.
