### ISSUE TITLE
Inputs to WebAuthn methods should not include strict Enum types

### ISSUE THREAD

**Issue by jcjones** [w3c/webauthn#1376]
We need to audit all enums passed into WebAuthn to ensure that WebAuthn can be extended without causing WebIDL failures for lagging implementations.

What we did for Transport was to define that the input values be DOMString and coerced when possible into the acceptable enum values. At the 26-02-2020 face-to-face we agreed that in general, enums input into WebAuthn, if unknown, be treated as if the value was not set (e.g., the default value).

This affects #1366.

**Comment by equalsJeffH** [comment]
on 2020-03-11 call:  we just noted the verbal agreement we had that @agl to address the [`AttestationConveyancePreference`](https://www.w3.org/TR/webauthn-2/#enum-attestation-convey) enum as a part of completing PR #1366, and then @jcjones was intending to address the remaining enums in the spec.

**Comment by equalsJeffH** [comment]
Note: PR #1366 now addresses changing `PublicKeyCredentialCreationOptions.attestation` to a `DOMString`.
