### ISSUE TITLE
refine `publickey-credential` feature policy to have separate policies for Create and Get

### ISSUE THREAD

**Issue by equalsJeffH** [w3c/webauthn#1377]
see issue #1336

**Comment by yanz-androidify** [comment]
#1372

**Comment by nadalin** [comment]
@equalsJeffH Please create PR

**Comment by equalsJeffH** [comment]
on 2020-03-25 call:  look at @jcjones' PR #1394 to see if that is "pr-open" for this issue.

**Comment by equalsJeffH** [comment]
@equalsJeffH to change the publickey-credential feature policy identifier to be publickey-credentials-get, per pr #1394.

**Comment by equalsJeffH** [comment]
pr #1394 merged.  closing this issue.

**Comment by equalsJeffH** [comment]
followup: https://github.com/w3c/webappsec-feature-policy/pull/370 just landed.  See also: https://github.com/w3c/webappsec-feature-policy/blob/master/features.md
