### ISSUE TITLE
More explicitly document use cases

### ISSUE THREAD

**Issue by equalsJeffH** [w3c/webauthn#1389]
We need to provide more specific guidance for RPs about how to configure the several options for `navigator.credentials.{create,get}` and, secondly, to provide a reserve mapping of options back to intents.

See PR #1300

**Comment by equalsJeffH** [comment]
i think we should do something along these lines, but it can be addressed in a milestone later than wd-03

**Comment by equalsJeffH** [comment]
see also the closed PR #1300
this is a nice-to-have and puntable to a later spec version -- doing this properly is not "hard", but will take effort. I envison something like revamping along the lines of pr#1300, but also citing https://github.com/fido-alliance/how-to-fido/blob/master/HowToFIDO.md for "the full details"
see also issue #334

**Comment by timcappalli** [comment]
This is a bit dated now after the How to FIDO work that then morphed into passkeys.dev
