### ISSUE TITLE
Add direction to somewhere to ask for help to the contributing guidelines

### ISSUE THREAD

**Issue by CrowdHailer** [w3c/webauthn#1391]
I have been looking around this repo and finding answers to most of the questions I have in various issues and PR's.

Does such a community exist which will accept questions for people trying to use webauthn?
It would be great if there was some line in the contributing.md which said
"If you are unsure if your issue belongs here please ask in X"

If there is no suitable community to put in as X, it would still be helpful to point to an FAQ page or even tag on stackoverflow

**Comment by arshadnoor** [comment]
https://groups.google.com/a/fidoalliance.org/forum/#!forum/fido-dev

**Comment by CrowdHailer** [comment]
Thank you. I had wondered if there was something more specific to webauthn, however if not then that will do.

**Comment by equalsJeffH** [comment]
addressed by @arshadnoor
