### ISSUE TITLE
WebAPI: add userID as input parameter in authenticatorGetAssertion 

### ISSUE THREAD

**Issue by equalsJeffH** [w3c/webauthn#14]
<a href="https://github.com/smachani1"><img src="https://avatars.githubusercontent.com/u/7386729?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Originally submitted by: [smachani1](https://github.com/smachani1)**, on: _Monday Oct 05, 2015 at 01:11 GMT_

----

Section 3.2 The authenticatorGetAssertion operation
It will be useful to include the userID as an input parameter, specifically if the authenticator is used as a second factor.  The user doesn’t have to select an identity if more than one FIDO credentials  are associated with the same origin

**Comment by equalsJeffH** [comment]
<a href="https://github.com/equalsJeffH"><img src="https://avatars.githubusercontent.com/u/226571?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Original poster: [equalsJeffH](https://github.com/equalsJeffH)**, on: _Monday Dec 07, 2015 at 19:24 GMT_

----

this remains an open issue the w3c web authn wg will need to address once it begins work. thus setting milestone to ms-fido-v2.0-w3c

**Comment by vijaybh** [comment]
The RP can achieve the same effect simply by only asking for an assertion from that user's credential IDs.
