### ISSUE TITLE
credential id privacy

### ISSUE THREAD

**Issue by AxelNennker** [w3c/webauthn#140]
the current editor's draft does not limit credential id in any way while it promises that the privacy of the user is protected cross RP - unlinkability.
https://w3c.github.io/webauthn/#credential-id

The Privacy subsection https://w3c.github.io/webauthn/#sec-attestation-privacy mentions Attestation Keys but not credential id. A credential id could leak PII if the platform or the authenticator is not careful about this.

If https://github.com/w3c/webauthn/issues/6 introduces structure to credential id then information leakage should be considered too.

**Comment by equalsJeffH** [comment]
@jcjones notes in webauthn f2f tpac 2017-11-09 :   we will want to address this, but do not need to do for CR milestone -- punt to PR

**Comment by rlin1** [comment]
TODO: address in privacy considerations section

**Comment by nadalin** [comment]
@selfissued can you add a sentence about reuse of credential ids in the privacy sense, see @jcjones for deltails

**Comment by rlin1** [comment]
This is NOT only related to the credential ID.  Authenticators can (and are intended) to be used to authenticate the user.  This might lead to unexpected consequences when using "anonymous" browsing mode.

**Comment by rlin1** [comment]
Need to address whether/why not it could be possible to detect whether a CredentialID belongs to the current user *without* active user interaction(e.g. UP, UV).

**Comment by emlun** [comment]
It is currently possible to detect without user consent in at least some circumstances, although at least the following method cannot be done silently. You make a `getAssertion()` call naming the credential ID you want to probe for; if it times out you gain no knowledge (courtesy of hotplugging), but if it fails before timeout you know the credential is available and that the user has declined the operation.

**Comment by equalsJeffH** [comment]
Punting to PR milestone per discussion at webauthn f2f tpac 2017-11-09, see: https://github.com/w3c/webauthn/issues/140#issuecomment-343223907

**Comment by equalsJeffH** [comment]
I believe this issue is addressed by the recent PR #899, cf. https://w3c.github.io/webauthn/#sctn-privacy-attacks and https://w3c.github.io/webauthn/#sec-non-correlatable-credentials

**Comment by emlun** [comment]
Even with #899 I don't think there's any normative requirement to the effect of making sure credential IDs are not correlatable/identifying, but I agree that what we have is probably good enough.

**Comment by equalsJeffH** [comment]
I dunno if it'd be possible to have such a normative requirement. 

Shall we close this as fixed?

**Comment by AxelNennker** [comment]
Thank you
