### ISSUE TITLE
Example 4 in 1.3.3 uses txAuthSimple

### ISSUE THREAD

**Issue by ve7jtb** [w3c/webauthn#1401]
We could leave the example as txAuthSimple is a registered extension, however that may not be as helpful to developers as one might hope.

We could rework the example to use another extension, or remove the extension entirely.

It just seems thrown in there and not really relevant to the example.

**Comment by selfissued** [comment]
I think we should rework the example to use an extension in the spec - perhaps AppID.

**Comment by equalsJeffH** [comment]
on 2020-04-01 call:  we need to re-work the example to use one of the remaining extensions. @sbweeden suggests using credProps.  others suggest appID.  @ve7jtb will do something and we can complain about it....
