### ISSUE TITLE
Outdated link for operation timeout: DOMException: The operation either timed out or was not allowed. See: https://w3c.github.io/webauthn/#sec-assertion-privacy.

### ISSUE THREAD

**Issue by WGTW** [w3c/webauthn#1404]
If [cancelling](https://i.imgur.com/tOjojN6.png) authentication in the WebAuthn API authentication dialog, the console will be warned with an uncaught promise, calling out the timeout for the operation. This error gives a link to check out, but this link hasn't worked for months. It seems like the paragraph has since been refactored or removed:

> Uncaught (in promise) DOMException: The operation either timed out or was not allowed. See: https://w3c.github.io/webauthn/#sec-assertion-privacy.

![CredentialUIBroker_2020-04-08_11-11-31](https://user-images.githubusercontent.com/37328509/78766906-33385900-798a-11ea-9f5b-b81ff38e8d64.png)

Can said link/reference be fixed to link to a working section/paragraph on the W3C/Webauthn  documentation?

Steps to reproduce said error:
1. Open developer tools console on a locally hosted WebAuthn supported page
2. Launch the authentication WebAuthn API Authenticaton dialog
3. Activate cancel on a WebAuthn API Authenticaton dialog
4. Check browser developer tools console for the error

**Comment by nsatragno** [comment]
This seems like a chrome bug, not a spec bug. Please file a bug in crbug.com with the component "Blink>WebAuthentication", thanks!
