### ISSUE TITLE
Is android safety net nonce the same as web authnn challenge?

### ISSUE THREAD

**Issue by vieiralc** [w3c/webauthn#1413]
How similar is android SafetyNet to Web Authnn? Is the challenge passed to the authenticator to generate an attestation object equivalent to the nonce that is passed to Android SafetyNet? Could I use a nonce with WebAuthnn?

**Comment by agl** [comment]
A nonce, in cryptography, is generally used to prove freshness: by incorporating a random value chosen by the verifier, it's possible to convince the verifier that a response was generated after that random number was generated. SafetyNet works this way and the challenge in WebAuthn can certainly be used in this way too.
