### ISSUE TITLE
"privacy ca" term in images/fido-attestation-structures.svg

### ISSUE THREAD

**Issue by equalsJeffH** [w3c/webauthn#1421]
ought to change "privacy ca" term in images/fido-attestation-structures.svg (lower left corner) to "anonymization CA" or "attestation CA".

**Comment by equalsJeffH** [comment]
this is a very minor nice-to-have issue, can be addressed in a milestone later than wd-03 or not at all.

**Comment by emlun** [comment]
Obsoleted by PR #1607.
