### ISSUE TITLE
What is the difference between origin verification at client and RP end?

### ISSUE THREAD

**Issue by tarun14110** [w3c/webauthn#1434]
This is a question.
According to the webauthn specification, the client verifies the origin of the RP. As the client, has already verified the origin of RP and sends to the authenticator, the authenticator would use the correct credential binding. A phishing website would not be able to get credentials on someone's else behalf. So, why RP need to verify the relying party ID? I'm sure I'm missing something here.

**Comment by emlun** [comment]
It's a defense in depth and good security hygiene. It would help a bit in case a faulty authenticator reuses the same private key and credential ID across RPs, but I think you're right that it's not strictly necessary if both client and authenticator are compliant - if the client is malicious, a phishing site can forge the RP ID anyway, and if the client is benevolent, any valid signature from a phishing site will have been made with the wrong private key.

**Comment by tarun14110** [comment]
Thanks, @emlun this makes much more sense.
