### ISSUE TITLE
clientDataJSON sent to authenticator?

### ISSUE THREAD

**Issue by Nesuma** [w3c/webauthn#1442]
I'm a little confused why under 5.2. Authenticator Responses it says 
`This attribute contains a JSON serialization of the client data passed to the authenticator by the client in its call to either create() or get().`
and why (for registration) `pubKeyCred.response.clientDataJSON` gets its value from `credentialCreationData.clientDataJSONResult` instead of `clientDataJSON` directly when the value is just `clientDataJSON` copied a few steps earlier and there is no real `clientDataJSON**Result**`.

In the algorithms of 5.1.3 and 5.1.4 only the `clientDataHash` is passed to the authenticator. The CTAP specification also expects only the hash. Researching didn't solve my problem:
 
https://developer.mozilla.org/en-US/docs/Web/API/Web_Authentication_API
`only a hash is sent because the link to the authenticator may be a low-bandwidth`

https://webauthn.guide/
`clientDataJSON: This represents data passed from the browser to the authenticator`

https://developers.yubico.com/WebAuthn/WebAuthn_Developer_Guide/WebAuthn_Client_Authentication.html
`The clientDataJSON contains the JSON-serialized data passed to the authenticator by the client in order to generate the credential`

What am I missing or are these problems just artifacts of an earlier version of webauthn?

**Comment by nicksteele** [comment]
> confused why under 5.2. Authenticator Responses it says
`This attribute contains a JSON serialization of the client data passed to the authenticator by the client in its call to either create() or get().`

This could definitely be made clearer.

> why (for registration) `pubKeyCred.response.clientDataJSON` gets its value from `credentialCreationData.clientDataJSONResult` instead of `clientDataJSON`
Because, for brevity's sake, it should be kept in bytes until needing to be unpacked by the RP

The references that you list (one of which I am an author of and will update) are somewhat simplifying what occurs I think: the authenticator does indeed only request the `clientDataHash` rather than a byte-serialized version of the `ClientDataJSON`.

**Comment by dwaite** [comment]
The relying party sends a challenge, which the client augments with additional collected information (the requesting origin being the big one). This collected client data is never directly shared with the authenticator, instead it is treated as a binary stream and a hash of it is sent. This hash is included in the response.

The relying party needs the collected data in a binary/buffer representation, as JSON tooling may interpret the document and corrupt the ability to calculate the same hash as in the response. The relying party would also parse the buffer as JSON to make sure the data matches what was expected.

**Comment by Nesuma** [comment]
Okay thanks, that solves the question for me
