### ISSUE TITLE
Bio-Metric Authentication done by Another finger print

### ISSUE THREAD

**Issue by securewebsite** [w3c/webauthn#1444]
Hello,

I have used webauthn with Bio-metric. If someone has device and my password and he can just use his finger print and he can login. Finger print scanning is not working with webauthn. I am using this with PHP based system and I have checked the same with Google's webauthn demo. I found that Bio-metric is kind of no use if finger print scanned is not stored. I have tested this with many browser and platforms like 

https://webauthn.io/dashboard
https://webauthn.me/

I can register with my finger print and someone else can use his finger print and able to login. Am I missing something here? 

Please guide me how to resolve this issue.

**Comment by agl** [comment]
If I'm understanding your question correctly, you are registering a credential using a fingerprint but finding that someone else, whose fingerprint is not enrolled, can also pass the fingerprint check?

If so, can you say what authenticator you're using? I.e. is it a physical token plugged into a USB,  Touch ID on macOS, or something else?

Secondly, are you requesting [user verification](https://w3c.github.io/webauthn/#user-verification) when registering and asserting the credential? (I.e. with [this](https://w3c.github.io/webauthn/#dom-authenticatorselectioncriteria-userverification) parameter during registration and [this](https://w3c.github.io/webauthn/#dom-publickeycredentialrequestoptions-userverification) one during assertion.)

If you're doing everything right, it's still possible that the fingerprint sensor on the authenticator is just bad and is producing a false positive result for the wrong fingerprint.

**Comment by securewebsite** [comment]
Yes, that is true someone else who is no Authenticator is able to use the device and login. I am using bio metric USB.

**Comment by emlun** [comment]
@securewebsite 

1. What is the authenticator brand and model name?
2. Does your `navigator.credentials.create()` or `.get()` call set [`userVerification: "required"`](https://www.w3.org/TR/webauthn-2/#dom-publickeycredentialrequestoptions-userverification), or some other value for this parameter?
3. When you get the response back, is the [UV flag](https://www.w3.org/TR/webauthn-2/#flags) set?

**Comment by agl** [comment]
(Will close next week if no response.)

**Comment by agl** [comment]
(Actually, we feel that [fido-dev](https://groups.google.com/a/fidoalliance.org/forum/#!forum/fido-dev) is the correct place for this.)

**Comment by securewebsite** [comment]
Please close this I found the problem. I found that I have to first use local App to register finger print using software before I register it on web portal.
