### ISSUE TITLE
§9.2 requires client extension output but appidExclude sets none

### ISSUE THREAD

**Issue by emlun** [w3c/webauthn#1445]
[§9.2. Defining Extensions](https://w3c.github.io/webauthn/#sctn-extension-specification) reads:

>Any client extension that is processed by the client MUST return a client extension output value so that the WebAuthn Relying Party knows that the extension was honored by the client.

[§10.2. FIDO AppID Exclusion Extension (appidExclude)](https://w3c.github.io/webauthn/#sctn-appid-exclude-extension) reads:

>*Client extension output*
>None.

At least one of these should change, as the spec is internally inconsistent as is.

**Comment by selfissued** [comment]
We should always return `true` when this extension is used, as described in https://w3c.github.io/webauthn/#sctn-extension-specification.

**Comment by selfissued** [comment]
I will create a PR to make the extension conformant.
