### ISSUE TITLE
add additional attestation format(s) from Apple

### ISSUE THREAD

**Issue by equalsJeffH** [w3c/webauthn#1453]
Apple has indicated they have their own [attestation statement format(s)](https://www.iana.org/assignments/webauthn/webauthn.xhtml) that they'd like to have included in the spec. this is just a placeholder to keep it in mind.

**Comment by equalsJeffH** [comment]
on 2020-08-26 call:  jiewan is still awaiting for internal reply, it'll be only one attestation.

**Comment by mackie1001** [comment]
As of iOS 14 Beta 6 it appears the new attestation format is now in play. Based on conversations you've had is this subject to change or are we just waiting on official documentation? 
I see that some have started looking into is using the DeviceCheck/AppAttest docs as a starting point but do you know of any working reference implementations?

**Comment by equalsJeffH** [comment]
we are waiting apple to provide a specification of their [attestation statement format(s)](https://www.iana.org/assignments/webauthn/webauthn.xhtml)

**Comment by mpeng-okta** [comment]
Quick question @equalsJeffH: I see that this has been added to the [WebAuthn Level 2 editor draft](https://w3c.github.io/webauthn/#sctn-apple-anonymous-attestation). Are there any plans on adding the attestation format  the existing WebAuthn Level 1 spec as well, and if not, does this mean an implementation of the Level 1 spec should ignore the `apple` attestation format?

I also see that it hasn't been registered yet [on IANA's page for attestation format identifiers](https://www.iana.org/assignments/webauthn/webauthn.xhtml). Would this have any implications for RP developers, or would it be fine to begin building support for this attestation format -- i.e. we could consider the IANA registration just a procedural step/formality?
