### ISSUE TITLE
Create an implementation issue tag, route implementation questions to community group

### ISSUE THREAD

**Issue by nicksteele** [w3c/webauthn#1454]
The W3C has created a WebAuthn adoption community group to address developer adoption and implementation resources in order to promote the standard. If the working group could flag issues in this group that are implementation or adoption concerns and send them to us for answers and for us to figure out general areas of problems that developers are facing that'd be great. 

[Our repository](https://github.com/webauthn-adoption/practical-webauthn/) and our [W3 org page.](https://www.w3.org/community/webauthn-adoption/)

**Comment by equalsJeffH** [comment]
created the https://github.com/w3c/webauthn/labels/type%3Aadoption-or-impl label for tagging such issues/PRs in this repo.
