### ISSUE TITLE
Secure context should be MUST not SHOULD

### ISSUE THREAD

**Issue by vijaybh** [w3c/webauthn#146]
WebAuthn depends on origin isolation to provide privacy protection for the user. Also, if origins can be spoofed, then MITM attacks become possible. Currently the spec says secure contexts SHOULD be required. We SHOULD really upgrade this to a MUST...

**Comment by equalsJeffH** [comment]
yep, agreed.

**Comment by mikewest** [comment]
I'd also suggest using the `[SecureContext]` IDL attribute on entry points to the API like `navigator.authentication`, as well as visible interfaces like `ScopedCredentialInfo`, `WebAuthentication`, etc.

**Comment by mikewest** [comment]
(https://heycam.github.io/webidl/#SecureContext)

**Comment by equalsJeffH** [comment]
Reopening given @mikewest 's comments above.

**Comment by equalsJeffH** [comment]
from https://heycam.github.io/webidl/#SecureContext I /think/ doing this adequately addresses this issue..
```
    partial interface Navigator {
        [SecureContext]
        readonly attribute WebAuthentication authentication;
    };
```

**Comment by yaronf** [comment]
Seems to me the semantics of marking a partial interface with this tag is not what we want. Quoting: ``The partial interface or partial namespace is available only in secure contexts if and only if the original interface or namespace definition is.``

**Comment by equalsJeffH** [comment]
doh. thanks. fixing...

**Comment by equalsJeffH** [comment]
further detailed remediation discussion is in PR #203
