### ISSUE TITLE
Platform authenticator support is inconsistent in private/incognito modes

### ISSUE THREAD

**Issue by herrjemand** [w3c/webauthn#1465]
So during the recent testing, I've discovered that support for platform authenticator vary between Chromium based browsers and Firefox.

In Chromium browsers platform authenticator is not available in Privacy/Incognito mode, and isUserVerifyingPlatformAuthenticatorAvailable() returns false:

Microsoft Edge
![Screenshot 2020-08-06 at 21 30 34](https://user-images.githubusercontent.com/1636116/89569241-17a46880-d82d-11ea-89db-aabbf1ef17b3.png)

Google Chrome
![Screenshot 2020-08-06 at 21 29 28](https://user-images.githubusercontent.com/1636116/89569262-1ecb7680-d82d-11ea-9a69-08b83b7beaa4.png)

Where Firefox allows usage of the platform authenticator in the Privacy/Incognito mode.

![Screenshot 2020-08-06 at 21 31 36](https://user-images.githubusercontent.com/1636116/89569318-3acf1800-d82d-11ea-86d4-3f8d21532ff3.png)

I can not see any mention that browsers shall or must restrict platform authenticators in the Privacy/Modes.

**Comment by alanwaketan** [comment]
Another aspect to this issue is whether we should keep the same policy for external authenticators as well.

**Comment by herrjemand** [comment]
Additional check:

Google Chrome on MacOS allows platform authenticator for incognito

<img width="1792" alt="Screenshot 2020-08-06 at 21 50 28" src="https://user-images.githubusercontent.com/1636116/89570809-5f2bf400-d82f-11ea-86f4-2a48aad5d388.png">

This is fun! XD

**Comment by nicksteele** [comment]
This is being discussed by the WebAuthn adoption community group and will be on the agenda for our meeting on Monday.

**Comment by nicksteele** [comment]
For further clarification, this was mentioned as a topic that was out of scope given [W3C's observations ](https://w3ctag.github.io/private-browsing-modes/) on the topic of private browsing.
