### ISSUE TITLE
update "feature policy" reference to new name: "permissions policy"

### ISSUE THREAD

**Issue by equalsJeffH** [w3c/webauthn#1473]
see: https://www.w3.org/TR/permissions-policy/

**Comment by jcayzac** [comment]
Hi,

I can take a look at this!
It seems a lot of URL fragments have also changed in the permissions policy document, and some other documents haven't updated to the new terminology (webusb…) so it will take a little while…

**Comment by jcayzac** [comment]
Dependency: https://github.com/WICG/webusb/issues/190
