### ISSUE TITLE
 The risk of attacker may can identify whether if the account support FIDO or not

### ISSUE THREAD

**Issue by keikoit** [w3c/webauthn#1475]
Hi this is Keiko Itakura from Rakuten which is member of both W3C and FIDO Alliance Japan.

We(FIDO Japan WG) wonder there is a security risk in the following in WebAuthn.  I would like to know what W3C thinks of this, and also if there is a plan to reflect changes in the WebAuthn specs about this possible risk.

- Isn't there a risk that the attacker can identify whether or not the account supports FIDO?

There is a possibility the CredentialID/Username pair is exposed in the case of NRK(Non resident key) .  
For example,
- Let's say an attacker sends Usernames that can guess e-mail addresses etc. to the RP. 
- Then he can see the repllies from the RP servers for each.
- If a CredentialID-like thing is returned, and if it shows whether or not the account supports FIDO(The reply is different from the case where FIDO is not supported. )
- then the attacker can select the accounts that do not support FIDO as target.
If they use this, they can see that unsupported ones have weak security and are easy to attack. Do you not think this is a security issue?  And if it is a problem, how can this problem be addressed?

**Comment by Kieun** [comment]
It might depend on how RP handles such NRK authentication request. 

- Ideally, RP might simply return randomly generated credential id which makes the attacker harder to distinguish
- RP might introduce reCAPTCHA or something to block automated try (brute force)
- To slow down the attacker's attempts, RP might introduce rate limiting (exponentially increasing timeout)
- RP might leverage NRK just for step-up authentication

**Comment by maxhata** [comment]
WebAuthn Level 2 spec has articulated the issue relating to exposing credenantialIds from a privacy perspective. It is an important aspect. But equally serious is that exposing credentialIds will help attackers identify  which usernames/accounts are not protected by FIDO and still using passwords for a service that uses mixed legacy passwords and FIDO. Knowing this, attackers will improve their success rate of their list based attacks.

For a consumer service provided by an RP, transitioning from legacy password based authentication to FIDO cannot happen over a night. Many services will depend on user's opt-in to transition from passwords to FIDO. Therefore, mixed use of passwords and FIDO will continue for a certain period. 

As such, RPs need to implement some counter measures, such as those described above, to prevent this kind of opportunities for attackers (How effective they can be, how much complex work RP will have to do, and how it will affect usability for consumers will still need to be investigated). 

This is not a privacy issue but a security issue. I think WebAuthn spec should articulate this from a security perspective and suggest RPs to implement certain mechanisms to prevent this from happening depending on their policies.

**Comment by Kieun** [comment]
This risk is also true for RK use case. If RPs support passwordless-flow (delivering credential ids during authentication), it still exposes such information to attackers. So, in this case, we might need similar counter measures.

**Comment by emlun** [comment]
This is similar to what's described in [14.6.3. Privacy leak via credential IDs](https://w3c.github.io/webauthn/#sctn-credential-id-privacy-leak), and the same countermeasures should apply here. Perhaps we should make a mention of this in the security considerations section, too, but it doesn't look like anything substantive needs to be added.

I don't agree that this also applies to the discoverable keys (username-less) use case, as the server then returns only a challenge to initiate the ceremony. If the server only supports username-less authentication, I don't see how this issue can occur. It remains if the server supports both discoverable and non-discoverable keys, though.

**Comment by maxhata** [comment]
14.6.3. Privacy leak via credential IDs does discuss on the issue of exposing credentiaIds. But I do not think it is enough.

One of the most significant security consequences of exposing credentialIds is that it let attacker know which accounts are not FIDO/WebAuthn enabled yet and still using passwords only. This information will give better chance for attackers to succeed in their list based attacks for the legacy passwords only accounts as they can focus on the weaker accounts.

As I mentioned above, for consumer use cases, RPs cannot transition all accounts to FIDO/WebAuthn enabled ones right away and this vulnerability remains for a long time.

This is one of the serious design consideration for RPs to deploy FIDO/WebAuthn.

We should call upon this 'security' risk to RPs explicitly in the specification.

**Comment by maxhata** [comment]
> I don't agree that this also applies to the discoverable keys (username-less) use case, as the server then returns only a challenge to initiate the ceremony. If the server only supports username-less authentication, I don't see how this issue can occur. It remains if the server supports both discoverable and non-discoverable keys, though.

For discoverable keys, there are two deployment scenarios:

Case A: allowCredentials=empty
Case B: allowCredentials=credentialIds

I agree, there is no credentialId exposure issue with Case A.
But there is credentialId exposure issue with Case B.

So why RPs deploy Case B?

When you are deploying on multiple platforms, certain platforms do not support discoverable keys and others do. If RPs use common denominator approach (same flow and same UX for their consumers), they tend to use allowCredentials=credentialIds for all platforms, and this choice brings about the credentialId exposure issue even for platforms that do support discoverable keys. So the spec should remind RPs about this risk if they use common denominator approach.

**Comment by emlun** [comment]
Agreed - that's what I was trying to say, but thanks for clarifying. And it does seem appropriate to point this out in security considerations.

**Comment by keikoit** [comment]
Thank you for clarify and follow-up Hata-san!
And I appreciate your speedy reply and action, Kieun-san Emlun-san and Nadalin-san.
Let us please continue to communicate closely
