### ISSUE TITLE
"version 4 GUID" should be "version 4 UUID"

### ISSUE THREAD

**Issue by equalsJeffH** [w3c/webauthn#148]
we have this text..
```
The claimedAAGUID element contains the claimed Authenticator Attestation GUID (a version 4 GUID, see [RFC4122]). 
```
..however, RFC4122 uses the term UUID, though it does draw equivalence to GUID in two places.  anyway, if one searches RFC4122 for "version 4 guid" you get no hits, but you do for "version 4 uuid", so I think we should change the above to be..
```
The claimedAAGUID element contains the claimed Authenticator Attestation GUID (a version 4 UUID, see [RFC4122]). 
```

**Comment by vijaybh** [comment]
How would people feel about removing all references to GUIDs/UUIDs and RFC 4122 here? Couldn't AAGUID just be an opaque identifier, chosen to be universally unique with high probability? Maybe we could restrict it to 128 bits as well, but it's not clear to me what benefit we get from requiring the top nibble to be in a specific format.

**Comment by equalsJeffH** [comment]
I've been party to specs that have specified identifiers as such, eg saml-core-2.0-os.pdf, and that has apparently worked out in practice as far as I know. so I suppose I'm ok with doing that. In the latter SAMLv2 core spec, we say..
> The mechanism by which a SAML system entity ensures that the identifier is unique is left to the implementation. In the case that a random or pseudorandom technique is employed, the probability of two randomly chosen identifiers being identical MUST be less than or equal to 2^-128 and SHOULD be less than or equal to 2^-160. This requirement MAY be met by encoding a randomly chosen value between 128 and 160 bits in length.

**Comment by equalsJeffH** [comment]
note that I added..
> ... A pseudorandom generator MUST be seeded with unique material in order to ensure the desired uniqueness properties between different systems.

..to the above-quoted text after I'd initially clicked [comment].
