### ISSUE TITLE
changing to "permissions policy" messed up MDN links

### ISSUE THREAD

**Issue by equalsJeffH** [w3c/webauthn#1486]
changing to the new "permissions policy" name from "feature policy" apparently messed up MDN links in some fashion.  Compiling the spec now yields this message:
>WARNING: No 'sctn-feature-policy' ID found, skipping MDN features that would target it.

Fixing this may require adjustments over on the MDN side of things -- I wonder if MDN is up-to-date with the feature-policy spec splitting into two specs?

**Comment by jcayzac** [comment]
The warning comes from a reference to the old `sctn-feature-policy` anchor (renamed to `sctn-permissions-policy` now) in the [`mdn/webauthn`](https://github.com/tabatkins/bikeshed-data/blob/e142c0bd/data/mdn/webauthn.json#L2065) cache of the `bikeshed-data` repo. It should go away once the cache is updated.

**Comment by equalsJeffH** [comment]
@jcayzac wrote: 
> There no action or fix to be had in this repo.

Ok, thx @jcayzac!  We'll stand by and see if this warning goes away.

**Comment by equalsJeffH** [comment]
It does in fact seem that the warning has gone away. Am closing this issue.
