### ISSUE TITLE
Update Contributors for CR 

### ISSUE THREAD

**Issue by ve7jtb** [w3c/webauthn#1494]
I didn't add myself in my pull requests, and there may be other people who should be added. 
Jiewen adding himself in the apple pull request reminded me.

**Comment by jcayzac** [comment]
@ve7jtb I think I may have forgotten to add myself in #1476 (no idea if that qualifies, tho ^^)

**Comment by selfissued** [comment]
There's also an Acknowledgements section, which should be used as appropriate.

**Comment by ve7jtb** [comment]
> @ve7jtb I think I may have forgotten to add myself in #1476 (no idea if that qualifies, tho ^^)

add to acknowledgements from Dec 2 call.

**Comment by nicksteele** [comment]
Movin' on up. Please update with [Nick Steele](mailto:nick.steele@gemini.com)(Gemini)

**Comment by Kieun** [comment]
Maybe I might have a [qualification](https://github.com/w3c/webauthn/issues?q=is%3Aissue+author%3A%40me) with Ki-Eun Shin.

**Comment by futureimperfect** [comment]
Please consider adding me too.

[James Barclay](mailto:james.barclay@getcruise.com) (Cruise)

https://github.com/w3c/webauthn/pulls?q=is%3Apr+author%3Afutureimperfect+is%3Aclosed

https://github.com/w3c/webauthn/issues?q=is%3Aissue+author%3Afutureimperfect+is%3Aclosed

**Comment by ve7jtb** [comment]
I moved up Nick
James is already an acknowledgement 

I added Kieun and Julien Cayzac to acknowledgements

I can move them around if people have an opinion.
