### ISSUE TITLE
Update IANA Considerations section

### ISSUE THREAD

**Issue by nicksteele** [w3c/webauthn#1495]
The [IANA Registry](https://www.iana.org/assignments/webauthn/webauthn.xhtml) should be updated to include Apple's new attestation format identifier.  --- done 28-Oct-2020

update 30-Oct:
However, there is further cleanup needed beyond adding the Apple attestation format, see https://github.com/w3c/webauthn/issues/1495#issuecomment-719616541 below

**Comment by equalsJeffH** [comment]
pr #1491 should also update the https://w3c.github.io/webauthn/#sctn-att-fmt-reg section appropriately.

**Comment by equalsJeffH** [comment]
once the webauthn L2 spec goes to REC status then we (e.g. webauthn wg chairs) can reach out to IANA and have them register the new items (as compared to what's presently registered) in section 12: https://w3c.github.io/webauthn/#sctn-IANA

**Comment by equalsJeffH** [comment]
update: I've contacted IANA and realized there's a bit more L2 IANA considerations clean up we need to do (beyond adding the "apple" attestation format, eg, due to also removing extensions and adding new ones), so am renaming this issue to reflect that.
