### ISSUE TITLE
Difference Level-1 and Level-2

### ISSUE THREAD

**Issue by petermorlion** [w3c/webauthn#1501]
Is there an easy way to see the difference between the current recommendation (https://www.w3.org/TR/webauthn) and the new draft (https://www.w3.org/TR/webauthn-2)? I've been implementing the current recommendation, and would like to know if I need to make any (breaking) changes because of the Level 2 draft.

**Comment by nadalin** [comment]
You may want to take a look at https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fwww.w3.org%2FTR%2F2019%2FWD-webauthn-2-20191126%2F <https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fwww.w3.org%2FTR%2F2019%2FWD-webauthn-2-20191126%2F&doc2=https%3A%2F%2Fwww.w3.org%2FTR%2F2020%2FWD-webauthn-2-20200730%2F> &doc2=https%3A%2F%2Fwww.w3.org%2FTR%2F2020%2FWD-webauthn-2-20200730%2F

**Comment by petermorlion** [comment]
Thank you. Great tip.
