### ISSUE TITLE
Location extension returns the authenticator coordinates to RP without user consent

### ISSUE THREAD

**Issue by jumde** [w3c/webauthn#1517]
A user consent/permission prompt should be presented to the user before returning the coordinates to the relying party. Web-pages trying to retrieve information about user's current location when the user does not wish to reveal it for example: using vpn or tor - can use this to leak the current user-coordinates.

**Comment by ve7jtb** [comment]
No platform currently implements this extension.  Getting rid of it would be the other way to go.
In principal there are other ways for a RP page to ask for location.

**Comment by jumde** [comment]
@ve7tjb - Getting rid of the extension makes sense if no platform implements it.  What are the other ways RP asks for user location? In general, notification, consent or permission from user would be helpful, if the location is being requested by the RP.

**Comment by agl** [comment]
The location extension doesn't exist in level two (and was never implemented at level one).
