### ISSUE TITLE
KeyUsage requirement (Certificate Signing or empty) for attestation roots

### ISSUE THREAD

**Issue by xbillyj** [w3c/webauthn#1519]
RP chain build validation of attestation statements can fail if the Key Usage extension is present and does not include "Certificate Signing".

See https://github.com/fido-alliance/mds-ops/issues/4 for related issue. Goal is to avoid vendors errantly publishing roots with non-empty KeyUsage that does not include Certificate Signing.

**Comment by agl** [comment]
From the call of 2020-11-18:

This issue is valid, but it's a comment about X.509 validity. We feel that it would be too weird to remark upon a detail of X.509 in WebAuthn when rest of the verification process isn't specified here, and we don't want to start doing so.
