### ISSUE TITLE
Problem with authn selection extension

### ISSUE THREAD

**Issue by vijaybh** [w3c/webauthn#152]
The current text says:
>If an authenticator was selected from AuthenticatorSelectionList, its AAGUID MUST be added by the client to the ClientData as the client data value for this extension.

However this creates a chicken-and-egg problem. The client may send out a request to a number of authenticators. It needs to include the AAGUID of the authenticator that finally responds in its clientData. But by the time the client knows the AAGUID, the clientData has already been sent to the authenticator and signed over.

One way (the simplest way?) to address this is to simply remove this requirement for adding anything to the clientData, since the AAGUID of the selected authenticator will be in the attestation anyways.

**Comment by equalsJeffH** [comment]
It seems to me that removing the above-quoted requirement to add AAGUID to to ClientData is ok, given that claimedAAGUID is returned in the attestation Though I suggest we have Rolf sign off on it also -- he may have had a specific reason for stipulating AAGUID's inclusion in ClientData.
