### ISSUE TITLE
user-agent signal for enterprise attestation should be understandable for general users

### ISSUE THREAD

**Issue by jumde** [w3c/webauthn#1521]
From the spec: 

> enterprise
This value indicates that the Relying Party wants to receive an attestation statement that may include uniquely identifying information. This is intended for controlled deployments within an enterprise where the organization wishes to tie registrations to specific authenticators. User agents MUST NOT provide such an attestation unless the user agent or authenticator configuration permits it for the requested RP ID.
If permitted, the user agent SHOULD signal to the authenticator (at invocation time) that enterprise attestation is requested, and convey the resulting AAGUID and attestation statement, unaltered, to the Relying Party.

Most users in an enterprise setting will not understand what `enterprise attestation` means. It would be helpful for users if the user-agent/authenticator signals that `user identifying information` is being requested.

**Comment by agl** [comment]
From the call of 2020-11-18:

The term &ldquo;enterprise attestation&rdquo; in the quoted text is not suggesting wording for any UX, it's talking about a signal that is sent to the authenticator.

Most (all?) browsers alert the user to the use of attestation in general thus it seems very like that they will also do so for enterprise attestation. But we don't feel that it's the place of the WebAuthn spec to be mandating UX accommodations.

**Comment by swickr** [comment]
@samuelweiler: It appears you added privacy-needs-resolution after the issue was marked closed; for what reason was the label added?

**Comment by nadalin** [comment]
@swickr This is a feature of CTAP not webauthn. This is documented over in FIDO land.

**Comment by samuelweiler** [comment]
@swickr, to give @jumde a chance to make sure he was satisfied with the WG's answer.  Looking at this again, I'm satisfied.  @jumde, are you?

**Comment by jumde** [comment]
lgtm, thanks @nadalin @samuelweiler
