### ISSUE TITLE
Consider adding/using personal name examples that are more culturally neutral/diverse [editorial]

### ISSUE THREAD

**Issue by aphillips** [w3c/webauthn#1525]
1.2.2. Authentication
https://w3c.github.io/webauthn/#sctn-usecase-authentication

> User is shown a list of their example.com identities, e.g., "Sign in as Alice / Sign in as Bob."

Giving examples such as "Alice" and "Bob" is Western (if not U.S.) centric. Consider using more diverse names as examples, including those that are popular globally. (The I18N WG notes that "Alice" and "Bob" are common examples in the security/privacy space.) Elsewhere in the specification we found examples, such as:

> A human-palatable name for the user account, intended only for display. For example, "Alex P. Müller" or "田中 倫". The Relying Party SHOULD let the user choose this, and SHOULD NOT restrict the choice more than necessary.

The "Alex P. Müller" example contains a non-ASCII character, but it is not consistent with German usage (we surmise that German was the intention of the example). The name "田中 倫" contains a space between the family (first, Tanaka) and given (second, Lin/Lynn) name. It's a good example, but is not repeated.

This is a minor editorial comment.

**Comment by agl** [comment]
> The "Alex P. Müller" example contains a non-ASCII character, but it is not consistent with German usage (we surmise that German was the intention of the example).

Could you expand on what's incorrect about “Alex P. Müller”? I think the surname [is real](https://www.nobelprize.org/prizes/physics/1987/muller/biographical/) and [Alexander appears to be a reasonably common given name in German](https://www.beliebte-vornamen.de/jahrgang/j2015).

I'll upload a change to address the other points in just a second.

**Comment by aphillips** [comment]
@agl Thanks for the response. We'd suggest dropping the middle initial. For more info, see: https://www.w3.org/International/questions/qa-personal-names.en#middleinitial

You may find other parts of this article useful in other ways as a reference.

**Comment by emlun** [comment]
By the way, the intent when [the "Alex (P.) Müller" example was added](8cdeac8e52a0b21688fdd429fafb43a8dc2b445d) was for it to also be androgynous. I realize from @agl's link that it might not be seen that way in a German context (and although the intent was not specifically for it to be German, just non-ASCII, it certainly looks that way), but maybe it works well enough internationally?

**Comment by r12a** [comment]
The i18n WG regards this issue as closed. Thank you.
