### ISSUE TITLE
Support for language/direction metadata in PKCE 'name'?

### ISSUE THREAD

**Issue by aphillips** [w3c/webauthn#1526]
5.4.1. Public Key Entity Description (dictionary PublicKeyCredentialEntity)
https://w3c.github.io/webauthn/#dictionary-pkcredentialentity

> name, of type DOMString
>    A human-palatable name for the entity. Its function depends on what the PublicKeyCredentialEntity represents:

The `name` attribute of the entity description is subjected to RFC8266 content requirements (aka PRECIS), but there is no provision for base direction metadata or language metadata (see our document [String-Meta](https://www.org/TR/string-meta)). It is therefore possible that the name will not be displayed correctly to end users due to spillover or font-selection (or other language-specific operations).

See also 5.4.3:

> A human-palatable name for the user account, intended only for display. For example, "Alex P. Müller" or "田中 倫". The Relying Party SHOULD let the user choose this, and SHOULD NOT restrict the choice more than necessary.

**Comment by agl** [comment]
This field ends up transmitted to the security key hardware, which is fixed-function, practically un-updatable, and which only accepts a single field. So, while changes in future devices could be imagined, any solution that adds fields will not function with any of the millions of devices already in existance.

Thus, while they are discouraged in the document, the systems for embedding this information in the string ([1](https://www.w3.org/TR/string-meta/#rlm) [2](https://www.w3.org/TR/string-meta/#unicodeTags)) seem the most promising. Their downside here is the encoding size: 24 bytes for many languages.

**Comment by ve7jtb** [comment]
Encoding in the string is the only viable option. 
On the other hand that will probably break authenticators with built-in displays.  
I don't know that that can be avoided however if direction and script are needed.

**Comment by r12a** [comment]
The i18n WG regards this issue as closed. Thank you.
