### ISSUE TITLE
Broken link to SVG in Figure 3 at w3.org

### ISSUE THREAD

**Issue by riastradh** [w3c/webauthn#1534]
In webauthn-2-20201116 [Figure 3](https://www.w3.org/TR/2020/WD-webauthn-2-20201116/#fig-authData), there is a broken img link to `images/fido-signature-formats-figure1.svg`, which yields 404 now, at both the [undated w3.org URL](https://www.w3.org/TR/webauthn-2/images/fido-signature-formats-figure1.svg) and the [dated w3.org URL](https://www.w3.org/TR/2020/WD-webauthn-2-20201116/images/fido-signature-formats-figure1.svg), but used to have an image [according to the Internet Archive](https://web.archive.org/web/20190620050625/https://www.w3.org/TR/webauthn-2/images/fido-signature-formats-figure1.svg).  The [gh-pages URL at w3c.github.io](https://w3c.github.io/webauthn/images/fido-signature-formats-figure1.svg) works fine.

**Comment by wseltzer** [comment]
Thanks for the heads-up. Now fixed.

**Comment by wseltzer** [comment]
manifest generated to include the images with autopub https://github.com/w3c/webauthn/pull/1535
