### ISSUE TITLE
Question about platform authenticator 

### ISSUE THREAD

**Issue by jason-webcomm** [w3c/webauthn#1540]
As we known Apple using attestation "Apple Anonymous Attestation Statement Format" to prevent identity information leak. 
But is there any way to block specify device using webauthn ? For example, I trust apple's all device except iPad. Current I only can get platform from userAgent(maybe spoofed).

please advice, thanks.

**Comment by sbweeden** [comment]
I think the answer is simply: No, there is no way to _block specify_ [sic] _device using webauthn_

I don't believe it was ever intended for WebAuthn to permit such a thing to be possible, nor (in my opinion) do I believe the WebAuthn specification community would condone such an intent.

**Comment by dwaite** [comment]
A relying party UX can inform the user of what is acceptable, and can refuse things which are not acceptable with a user-displayed error - but the API itself does not provide filtering capabilities for makes and models.

The expectation is that for relying parties which do not have specific security needs (such as a bank, employer, or government agency) that _any_ authenticator the user brings which meets technical requirements is acceptable.

**Comment by jason-webcomm** [comment]
Let me explain the requirement. Due to [samsung-galaxy-s10 ](https://www.theverge.com/2019/10/17/20919026/samsung-galaxy-s10-ultrasonic-fingerprint-sensor-security-flaw-screen-cover-protector) with screen-cover-protector cause the fingerprint sensor working error. How can we prevent this situation using webauthn?

P.S. This will use on internet bank.

**Comment by Kieun** [comment]
At this moment, the best approach is leveraging direct attestation to get some details about the authenticator and relying on user agent information. In the WebAuthn, there is no way for RPs to get such information like native application.

**Comment by sbweeden** [comment]
This issue is being closed per WebAuthn call on 6 Jan 2021. The current options for accepting/rejecting registration from an authenticator are covered by direct attestation.
