### ISSUE TITLE
Broken reference link for [EduPersonObjectClassSpec].

### ISSUE THREAD

**Issue by wseltzer** [w3c/webauthn#1544]
https://internet2.edu/media/medialibrary/2013/09/04/internet2-mace-dir-eduperson-200604.html 404s 

This appears to be an updated version of the reference: 
https://software.internet2.edu/eduperson/internet2-mace-dir-eduperson-201602.html

Thanks @jennyliang220 for pointing out the issue.

**Comment by gokmenll** [comment]
thanks :)
