### ISSUE TITLE
Support for authenticators providing more than one key

### ISSUE THREAD

**Issue by agl** [w3c/webauthn#1546]
(Filed ahead of L3 charter renewal to highlight things that we are thinking about for L3 so that the charter does not preclude it.)

We may wish authenticators to be able to provide a second public key / signature, likely in an extension, where the keys have different security properties.

**Comment by sbweeden** [comment]
So many things come to mind with a pattern like this, such as:

- Would the user be aware they are registering two keypairs - and would they be so informed in the user agent UI?
- Would this extension also apply to an assertion ceremony such that keypair replacement / rollover is possible, e.g. including to a newer algorithm? If so, would auto-revocation of the old key be part of the semantics that an RP should implement?

I realise early days, but a suggestion for this kind of extension has boundless possibilities.

**Comment by emlun** [comment]
Sounds very similar to parts of our recovery extension proposal in #1425, this could definitely be useful for a variety of things.

**Comment by nicksteele** [comment]
This sounds very similar to a couple ideas that have been floating around FIDO and W3C space, the recovery extension as emil mentioned and I could also see this being used for enterprise attestation purposes.

**Comment by Firstyear** [comment]
I think that it's worth having a concrete design around the intended user experience and authentication flows here so that a discussion can be had. At the moment it's not clear what this solves.

**Comment by equalsJeffH** [comment]
See also @akshayku's strongly related issue #1640.

**Comment by agl** [comment]
(Replaced by https://github.com/w3c/webauthn/issues/1658.)
