### ISSUE TITLE
editorial cleanups noted by Mr Pinkas

### ISSUE THREAD

**Issue by equalsJeffH** [w3c/webauthn#1549]
from: https://lists.w3.org/Archives/Public/public-webauthn/2021Jan/0018.html

*6)* There are some empty sections where text should be added:

  * 13.4. Security considerations for clients
  * 14.5. Privacy considerations for clients

*7)* There is a typo in Section 1.1: "expecially".

**Comment by equalsJeffH** [comment]
> There are some empty sections where text should be added:
> 13.4. Security considerations for clients

The content of section 13.4, up through WD-webauthn-2-20191126 had been section 13.3.1. Browser Permissions Framework and Extensions. This latter subsection was removed in the next spec rev, [WD-webauthn-2-20200730](https://www.w3.org/TR/2020/WD-webauthn-2-20200730/#sctn-security-considerations-client), because we had removed the only example of an extension (location) that could conceivably make use of the Browser Permissions Framework. However, we neglected to also remove the parent section header, 13.4. 

Removing the parent section header, 13.4, will address this.

> 14.5. Privacy considerations for clients

This section's content is present and accounted for, so I do not understand what might be missing.

**Comment by emlun** [comment]
> [§14.5. Privacy considerations for clients]'s content is present and accounted for, so I do not understand what might be missing.

I'm guessing some text between the section heading and the next subsection heading (of which §14.4 and §14.6 are also examples), which I think is "required" for formally correct typesetting. But I don't think there's really anything useful we could put there, so I think it should be fine to break that convention.
