### ISSUE TITLE
Issue with user_verification=preferred

### ISSUE THREAD

**Issue by p0w1** [w3c/webauthn#1571]
If `user_verification=preferred` (default) is set, the current specification says "... will not fail the operation if the response does not have the UV flag set."
This is a security issue under certain conditions and it is not the behavior a user would expect. If you want to use "preferred" in order to accept tokens/browsers which do not support user_verification it is Ok. However if a user registers with the UV flag set, he should be forced to use UV for every future authentication attempt. Otherwise the "preferred" option does not make any sense because an attacker could always authenticate without UV.

The specification should be updated so that the UV-flag verification depends if the user used it during the registration or not.

**Comment by equalsJeffH** [comment]
please see prior/existing discussion in https://github.com/w3c/webauthn/issues/1510

**Comment by equalsJeffH** [comment]
closing, please see Issue #1510

**Comment by Firstyear** [comment]
See also https://github.com/w3c/webauthn/issues/1556 which discusses this too.
