### ISSUE TITLE
FIDO + 3DS is a strange combination

### ISSUE THREAD

**Issue by cyberphone** [w3c/webauthn#1579]
The current "gold standard" for payments in the physical world is EMV.   EMV offers a superior user experience, security and privacy compared to 3DS.  Adapting EMV for the Web is what the rest of the payment industry already have done although these solutions are entirely proprietary and usually only have a national scope.  In fact, even Google Pay uses an EMV-like scheme.

However, based on private communication with several involved parties, Google, the FIDO Alliance, and the WebAuthn WG have come to the conclusion that 3DS rather is FIDO's path for payments.  Before taking a final decision, it might be worth looking into some relevant background information.

Why is FIDO + 3DS a strange combination? Well,

- 3DS is a "workaround" scheme created back in the 90'ties because client platforms offered essentially nothing to secure on-line payments.

- With FIDO + Browser-intrinsic payment SW this is no longer true.  If fact, such a platform could security- privacy- and usage-wise without doubt rival discrete EMV cards + payment terminals.

3DS requires users to handover their account number to merchants.  This seems to clash with the privacy ideas that were the foundation for FIDO.  3DS does not support account-to-account (A2A) based payments which is the current focus among banks in most countries.  The recently launched multi-billion Euro project known as the European Payment Initiative is entirely based on A2A.
@christiaanbrand @equalsJeffH

**Comment by Firstyear** [comment]
Would it be possible to supply references to 3ds and more details to help facilitate this discussion and review? I think there is a sparse amount of information here making it hard to have an effectively review and comment.

**Comment by cyberphone** [comment]
@Firstyear Well, "deciphering" the current WebAuthn/3DS specification is not for the fainthearted:  
https://github.com/rsolomakhin/secure-payment-confirmation/blob/master/sequence-diagrams/SecurePaymentConfirmation-Pilot-Checkout.png

It is hardly surprising that the payment industry (in general) rather have taken on EMV-like approaches.

**Comment by equalsJeffH** [comment]
> However, based on private communication with several involved parties, Google, the FIDO Alliance, and the WebAuthn WG have come to the conclusion that 3DS rather is FIDO's path for payments.

AFAIK the above assertion is incorrect and the WebAuthn WG has no "official" position on this topic at this time AFAIK.  ISTM this topic is more appropriate for the https://github.com/w3c/webpayments/ repo.

@danyao @srsheth

**Comment by cyberphone** [comment]
Dear @equalsJeffH, SPC is **Google**'s project which recently has been adopted by the W3C Payment WG (https://www.w3.org/blog/wpwg/2021/02/18/an-emv-3-d-secure-view-of-emvco-fido-and-w3c-activities/), _in practice_ replacing earlier deliverables including the **PaymentHandler** which (as I also predicted) probably wont go very far: https://github.com/cyberphone/doc/blob/gh-pages/payments/paymenthandler.md.

Being "excommunicated" by the Payment WG after airing diverging views of the merits of PaymentHandler, 3DS, and step-up authentication, I have to leave this topic here with a hope that it will be researched by people with interests making the FIDO ecosystem more attractive for banks.

FWIW, by rather taking the route I have proposed, _secure and convenient account-to-account (A2A) Web payments would finally be possible using pure Web technology_.  A2A is currently outside of what even Google and Apple Pay can do 😎  This would also be beneficial to **Open Banking** which is entirely focused on A2A operations.
@nadalin

**Comment by equalsJeffH** [comment]
see also issue #1570

**Comment by equalsJeffH** [comment]
On 2021-03-17 call:
The WG consensus is that these payments-oriented discussions are not relevant to the webauthn WG and belong elsewhere, e.g., https://github.com/w3c/payment-request/issues and/or https://github.com/rsolomakhin/secure-payment-confirmation/issues
