### ISSUE TITLE
Assertion signatures with JWS?

### ISSUE THREAD

**Issue by cyberphone** [w3c/webauthn#1581]
Pardon my somewhat limited experience with WebAuthn and CTAP2...
Anyway, for payment assertions like https://github.com/rsolomakhin/secure-payment-confirmation/issues/40 you would probably like to use JWS.  However, FIDO2 signatures do not seem to conform to JOSE standards if I interpret this figure correctly:
https://w3c.github.io/webauthn/images/fido-signature-formats-figure2.svg

The existing JOSE stack apparently needs one or more extensions to cope with this.

Any suggestions or preferences?
@selfissued

**Comment by cyberphone** [comment]
Could the following additions to JOSE headers be usable?
```json
"alg": "EC-CTAP2"
"AD-CTAP2": "base64url-encoded Authenticator Data"
```

**Comment by emlun** [comment]
I'm not sure I understand your question, but it looks to me like rsolomakhin/secure-payment-confirmation#40 is planning to use the WebAuthn API unchanged, and only modify how the [`challenge`](https://w3c.github.io/webauthn/#dom-publickeycredentialrequestoptions-challenge) is constructed. I'm not sure where JWS comes into this.

Is your worry in rsolomakhin/secure-payment-confirmation#40 that the `challenge` may be derived from nondeterministically serialized JSON, so it would be difficult to reconstruct the exact signed data? If so, that should largely be solved by the fact that the [`clientDataJSON`](https://w3c.github.io/webauthn/#dom-authenticatorresponse-clientdatajson) field of the signed response contains the exact bytes that were signed. So a Relying Party can first verify that the signature is valid over the signed data `authenticatorData || clientDataJSON`, and then parse `clientDataJSON` and verify that the contents are correct.

**Comment by selfissued** [comment]
You're correct that FIDO signatures are not compatible with JWS.  This is by design.
