### ISSUE TITLE
Inconsistent RP directions for handling credential transports

### ISSUE THREAD

**Issue by emlun** [w3c/webauthn#1587]
The definition of [`AuthenticatorAttestationResponse.getTransports()`](https://www.w3.org/TR/2021/PR-webauthn-2-20210225/#dom-authenticatorattestationresponse-transports-slot) reads:

>[...] The values SHOULD be members of AuthenticatorTransport but Relying Parties MUST ignore unknown values.

However [§7.1. Registering a New Credential, step 23](https://www.w3.org/TR/2021/PR-webauthn-2-20210225/#ref-for-dom-authenticatorattestationresponse-gettransports%E2%91%A3) reads (emphasis added):

>[...]
>It is RECOMMENDED to also:
>- Associate the credentialId with the transport hints returned by calling credential.response.getTransports(). **This value SHOULD NOT be modified** before or after storing it. [...]

These directions seem to be in conflict, and I think the latter is more correct. The transports value is primarily for the client to consume while the RP just needs to echo it back later, so the RP shouldn't need to care about what it contains. So I think we should edit the former to read:

>The values SHOULD be members of AuthenticatorTransport but Relying Parties MUST accept unknown values.

or perhaps:

>The values SHOULD be members of AuthenticatorTransport but Relying Parties SHOULD accept unknown values.

**Comment by Firstyear** [comment]
I think it becomes a question of the first line actually - stating that RP must ignore unknown values, means that acceptance of an unknown value would be RP specific? So the correct word in this case is "may" I think?

It could be better to have clearer wording about the impact of unknown values here, since as you accurately note, the conflict in these statements and what should be done to handle it, should really be clarified.

**Comment by Kieun** [comment]
Storing transports is up to RPs. So, it is better for the sentence to be something like this.

> If the RP decides to store transports, the value ..

AFAIK, some RP may refer transports during get call to provide better UX flows so that RP would like to reject unknown value.

**Comment by maxhata** [comment]
>AFAIK, some RP may refer transports during get call to provide better UX flows so that RP would like to reject unknown value.

Using information on transport for get call is very effective for RPs to guide the
users, not having to take the them to  confusing UX, especially for mobile. RPs are using it for their deployments.

**Comment by dwaite** [comment]
I suspect we should tighten up language by speaking instead terms of credential descriptors, which contain a credential ID  (which is authoritative from the authenticator as part of the attested data on create) and transports (which is advisory and shared unprotected from the client). 

A client SHOULD persist a credential descriptor, with both id and transports, to provide hints to the client for authenticator management and for any future authentication attempts of non-discoverable credentials. Changing or removing values from the transports may impact user experience or even prevent use of the credential.
