### ISSUE TITLE
Web Standard to Access Device Authenticators

### ISSUE THREAD

**Issue by sirinath** [w3c/webauthn#1597]
Bio metric authentication is more secure than passwords as there is a less of chance to forget them. Much of the web used passwords. I believe this should change and there should be easy cross browser support for other modes of authentication which is easy and seamless.

**Comment by dwaite** [comment]
Web Authentication supports biometric authentication via platform-integrated authenticators (such as Windows Hello or Apple's FaceID) as well as via biometric-enabled roaming authenticators (such as a USB key fob with a fingerprint reader).

**Comment by emlun** [comment]
@sirinath Does that address your concerns and/or answer your questions? Can we close this?

**Comment by sirinath** [comment]
Yes. It addresses it.
