### ISSUE TITLE
Multiple Authenticator Options and Policies

### ISSUE THREAD

**Issue by cyberphone** [w3c/webauthn#1601]
When using Windows Hello with WebAuthn I get multiple options to authorize the login.  FingerPrint, PIN, and Password.

This appears to be platform specific and also having no relation to possible RP policies.

Although biometric authentication is great, there are legitimate use-cases where a password/PIN would be required like for people that are hospitalized and a relative or other proxy carries out their on-line banking activities.

For this to work satisfactory there should be an RP option forcing the user to create a password/PIN that also must conform to an RP policy ("1234" may not be satisfactory).

**Comment by emlun** [comment]
Yes, RPs typically do not dictate what kinds of UV the user may use, rather the user may choose through their choice of authenticator. The RP may limit the user's options by enforcing an attestation policy of acceptable authenticators. Apart from that, might your UV method concerns be covered by the [`uvm` extension](https://www.w3.org/TR/2021/REC-webauthn-2-20210408/#sctn-uvm-extension)?

PIN policy seems to me like it's also best handled via attestation policy, as attestation would be required anyway for the RP to trust that the authenticator honestly enforces the PIN policy. For example, I think FIDO certification requires some level of PIN complexity enforcement.

**Comment by Firstyear** [comment]
Additionally, it's worth pointing out that perhaps this is also RP specific to allow account impersonation rather than finding a way to provide the credentials to an external party.

**Comment by emlun** [comment]
Yes, in the specific case of allowing access to another person I would say it's probably a better solution to have person 2 register their own authenticator instead of both persons sharing one authenticator.

**Comment by cyberphone** [comment]
Creating another authenticator is a better system if RPs make authenticator management by existing users a simple process.   This has a lot of cool applications.  Another solution would be to register an existing credential as proxy but that doesn't work well with FIDO since credentials are scoped to a specific domain.

**Comment by akshayku** [comment]
Notes from webauthn wg meeting on 5/5

Exposing PIN policies to every RP creates an issue with every RP will have different policies and user only have one authenticator.  Hence it doesn't work for the user. In enterprise cases, you can work with the authenticator to have your own polices. 

As such, nothing more to be done here. Closing this issue.
