### ISSUE TITLE
Is there a way to store metadata in the authenticator with/without an extension?

### ISSUE THREAD

**Issue by certainlyNotHeisenberg** [w3c/webauthn#1613]
(I have in mind just a small amount of data, nothing very large.) This really amounts to three very similar questions:

1. Is there a way to do this _without_ an extension (so that it's supported by all WebAuthn implementations)?
2. Is there a way to do this with an extension currently implemented in most browsers?
3. Is there a way to do this with an extension on the road to wide implementation?

On (1), my hope was that perhaps [`attestedCredentialData`](https://w3c.github.io/webauthn/#attested-credential-data) would work, but my sense is this doesn't supported RP defined metadata, even of small size. Am I correct in saying this? Is there another option that isn't an extension?

On (2) and (3), my best guess is that only suitable extension is [`largeBlob`](https://w3c.github.io/webauthn/#sctn-large-blob-extension), which I believe hasn't been implemented by all the major browsers and platform authenticators. (What I'm looking for is in some sense "`smallBlob`", if only that existed!) Is there any extension that would work? Does anyone know if for example Safari has any plans to implement support for `largeBlob` for iOS authenticators?

**Comment by agl** [comment]
You can put data in the user.id, which will be persisted by CTAP2 authenticators. (Although you shouldn't put anything sensitive in there.)

The "small blob" extension is credBlob: https://fidoalliance.org/specs/fido-v2.1-rd-20210309/fido-client-to-authenticator-protocol-v2.1-rd-20210309.html#sctn-credBlob-extension

It's supported in Chrome (although probably hasn't reached stable yet), but needs CTAP 2.1 authenticators.

largeBlob is also supported in Chrome behind a flag, but authenticators are likewise rare.
