### ISSUE TITLE
Firefox generates credentials using TPM with Windows Hello - but does not send TPM attestation

### ISSUE THREAD

**Issue by arshadnoor** [w3c/webauthn#1620]
In some recent testing, using the following:

- Laptop with fingerprint reader
- Windows Hello configured with a fingerprint
- Windows 10 Pro - Version 1909, Build 1863.1440
- Firefox (64-bit) 89.0
- Chrome (64-bit) 91.0.4472.77
- Edge (64-bit) 91.0.864.37
- Opera (64-bit) 76.0.4017.177
- Brave 1.25.70 (64-bit) Chrome 91.0.4472.77
- Test site: https://demo4.strongkey.com/basicserver

All listed browsers use the TPM to generate platform keys when registering at this site; however, only Firefox does not provide a TPM attestation - it returns "none" - while the remaining three return TPM attestations. We can confirm that the TPM was used by Firefox because **certutil -csp NGC -key** shows a new key in the list after successful registration with Firefox; when the key is deleted with _certutil_, the credential cannot be found for authentication and Firefox prompts for a Security Key. At other times (when the TPM key is not deleted), Firefox continues to work with TPM generated keys - even when not created by Firefox - to authenticate users to the site.

The FIDO2 server on the back-end is StrongKey's FIDO Certified implementation, and sends registration challenges with the declaration that it will accept any attestation format in this web-application.

Is there an explanation for this? Couldn't find anything in Bugzilla. TIA.

**Comment by dveditz** [comment]
Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1716859 on this issue

**Comment by akshayku** [comment]
It is not a spec bug. I will also try to follow up offline on this with Mozilla. But it seems like they are not passing tpm attestation back to the RP.
