### ISSUE TITLE
Dependencies on CTAP2 canonical CBOR encoding form?

### ISSUE THREAD

**Issue by cyberphone** [w3c/webauthn#1624]
That the CBOR world now has (at least) 3 different canonical formats to deal with is not particularly cool.

Question: Is anybody aware of a single FIDO implementation that is **not** compatible with both CTAP2 canonical and https://datatracker.ietf.org/doc/html/rfc8949#section-4.2.3 ?  Or to put it differently: does anybody actually use integer keys that require more than a byte?  Because that is the potential interoperability issue, right? 

If there is no such implementation, I would consider revising this part of the specification.  As far as I can tell, canonicalization should (with respect to FIDO), only _potentially_ be an issue for attestation signatures.

**Comment by dwaite** [comment]
The CTAP specification does not follow the base deterministic encoding rules; specifically, there is not an attempt to minimize the size of floating point numbers (a MUST in RFC 8949 4.2.1). I believe the other rules match - taking into account the CTAP spec and known extensions do not use tags or map/array values as map keys.

It is possible that the existing encoding rules could be translated to be based on §4.2.1 with caveats, but it would still be another encoding - implemented in shipping hardware and cryptographically signed to prevent cleanup for consistency.

**Comment by cyberphone** [comment]
If existing FIDO products are compatible with RFC 8949 4.2.1, this would be the right moment to remove the dependency on a proprietary solution since it is redundant. 

Floating point data seems unlikely to be a part of shipping FIDO hardware.

**Comment by dwaite** [comment]
I'll add that the location and biometric authenticator performance bounds extensions in level 1 both use floating-point values.

**Comment by cyberphone** [comment]
Thanx, I didn't know that.

**Comment by equalsJeffH** [comment]
I think @dwaite has effectively answered this and that we can close this issue.

**Comment by cyberphone** [comment]
we can close the issue but if I was in the FIDO alliance I would perform a questionnaire among vendors to see their interest in getting back on standards track.

**Comment by cyberphone** [comment]
Another way of dealing with this issue, would be to update clients to adjust FP data according to RFC 8949.  It is not beautiful but would provide a path to better compliance with IETF standards.  AFAICT, such a change wouldn't break anything.

**Comment by cyberphone** [comment]
@dwaite 
https://github.com/w3c/webauthn/issues/1386
seems to say that the proposal doesn't have any practical downsides, or are there other implemented extensions that depends on pre-8949 canonicalization?
