### ISSUE TITLE
reference CTAP2.1 PS spec and fix broken link

### ISSUE THREAD

**Issue by equalsJeffH** [w3c/webauthn#1635]
webauthn L2 Rec references the old CTAP v2.0-ps-20190130 spec, and thus the link to "large, per-credential blobs" does not work (the latter is a webauthn L2 Rec errata item (I dunno if it is worth fixing)).

we need to update the webauthn L3 working draft should link to `https://fidoalliance.org/specs/fido-v2.1-ps-20210615/fido-client-to-authenticator-protocol-v2.1-ps-20210615.html`

the link to `[=§6.2. Responses=]` in the CTAP2.1 spec no longer works because we removed that entire section from the CTAP spec (doh).  the two other links to the CTAP spec continue to work.

**Comment by selfissued** [comment]
PR #1961 fixed the first reference issue.  I'll create a PR to fix the second one.
