### ISSUE TITLE
BigNumber serialization is not mentioned

### ISSUE THREAD

**Issue by cyberphone** [w3c/webauthn#1647]
From RFC8949:

_If a protocol includes a field that can express integers with an absolute value of 2^(64) or larger using tag numbers 2 or 3 (Section 3.4.3), the protocol's deterministic encoding needs to specify whether smaller integers are also expressed using these tags or using major types 0 and 1.  Preferred serialization uses the latter choice, which is therefore recommended._

Maybe the CTAP canonicalization spec. {c|sh}ould mention that it is using the former (not recommended) choice?

**Comment by agl** [comment]
(This is a CTAP issue because the rules live there. Will move into the CTAP tracker and thus closing here.)
