### ISSUE TITLE
DOMString[] should be FrozenArray<DOMString>

### ISSUE THREAD

**Issue by domenic** [w3c/webauthn#165]
```
readonly    attribute DOMString[]   x5c;
```

The `[]` syntax has been removed from Web IDL.

**Comment by equalsJeffH** [comment]
hm.  this illustrates the brittleness of depending upon an editors' draft -- is WebIDL 2nd Ed going to be stable at some point? Or is it a de-facto "living standard" ?   how quickly are changes to the editors' draft implemented in the various browser-vendor toolchains?

in any case a cursory comparison of..
https://www.w3.org/TR/WebIDL/#idl-array            (1st Edition)
http://heycam.github.io/webidl/#idl-frozen-array  (2nd Edition)
..seems to indicate that for our purposes in webauthn the T[] and FrozenArray<T> are functionally equivalent and so it is a simple change to the webauthn spec. 

Anyone think different?

**Comment by selfissued** [comment]
This seems editorial to me, since it's about syntax in the spec, not about the semantics of any identifiers or changes to APIs or protocol elements.

**Comment by domenic** [comment]
No, this changes the semantics of the API.

**Comment by selfissued** [comment]
Thanks @domenic .  Since it's an API change, we should decide this before the Implementer's Draft.

**Comment by equalsJeffH** [comment]
@selfissued 
>  Since it's an API change, we should decide this before the Implementer's Draft.

agreed, plus this does not seem to be a complex change.

**Comment by AngeloKai** [comment]
@equalsJeffH @selfissued @domenic From an implementer's perspective, I believe the Edge codebase doesn't really distinguish them. To us this doesn't impact implementation. Of course I can't speak for Firefox or Chrome, though based on J.C.'s code I assume they have it figured out.

**Comment by selfissued** [comment]
Sounds like we can do this.

**Comment by domenic** [comment]
I don't understand how the Edge codebase could not distinguish them. They have observably different behavior to authors, e.g. `Array.isArray`, as I cited above. (I can list many more if you need them, e.g. the presence of the `x5c.map` function, or the value of `x5c[Symbol.isConcatSpreadable]` and its impact on code like `[].concat(x5c)`.)

If Edge does not distinguish, that is a bug in Edge.

**Comment by equalsJeffH** [comment]
hey guess what? good news, the webauthn spec's use of..
```
readonly    attribute DOMString[]   x5c;
```
..which was the source of this issue, went away a while back -- note that this issue is from Aug 16, 2016.

Also note, in case one wonders, that the webIDL two token value `[]` continues to exist (in webIDL) and represent an empty sequence value, which we _do_ make use of in webauthn (for allowList and excludeList). 

So I am closing this issue.
