### ISSUE TITLE
Choosing An Attestation Statement Format?

### ISSUE THREAD

**Issue by DanielSanchezDiaz** [w3c/webauthn#1659]
Hello! This is a really well written specification, super helpful! I do have one question however. Is there a way to convey a preference for an attestation statement format to the authenticator? From the spec: "It is expected that most authenticators will support a small number of attestation types and attestation statement formats, while Relying Parties will decide what attestation types are acceptable to them by policy." This part made it seem like relying parties only had control over the attestation type but not the attestation statement format fmt. Since authenticators might be able to support different types of attestation statement formats, I'd like to know if there is a way to convey that you would prefer say "packed" over "fido-u2f"
Thanks so much!

**Comment by sbweeden** [comment]
To answer your question, there is not. 

In practical use, the RP doesn't get to decide and every authenticator I've seen supports just one type for mainstream WebAuthn use (e.g. packed-basic). Regarding the example you used, I've only ever seen fido-u2f attestations when using authenticators or clients that don't support CTAP2. 

Do you have a specific use case where you think an individual authenticator *should* support more than one attestation statement format?

**Comment by arshadnoor** [comment]
You could continue to be "lazy" if you used an open-source, FIDO 
Certified server that supports most, if not all, attestation formats. 
You could even get "lazier" by not having to write any FIDO code and 
just focus on the business application. :-D

https://sourceforge.net/projects/strongkeyfido
https://github.com/strongkey/fido2

Arshad Noor
StrongKey

**Comment by equalsJeffH** [comment]
this is addressed by PR #1660, closing.
