### ISSUE TITLE
Consider using USVString instead of DOMString sometimes

### ISSUE THREAD

**Issue by domenic** [w3c/webauthn#166]
The difference here is a bit subtle, but generally for anything that is going to be serialized as bytes and sent down a wire, USVString is more correct. The one case that stood out is imageURL. There might be others, but I am not familiar enough with the domain.

**Comment by equalsJeffH** [comment]
see also #175

**Comment by selfissued** [comment]
This seems to me like it affects the API, and if so, we should decide it before the Implementer's Draft.  Am I right, @domenic ?

**Comment by domenic** [comment]
Yep.

**Comment by selfissued** [comment]
From the discussion on the call, it sounds like we can do this.

**Comment by nadalin** [comment]
@selfissued please make sure we have already done this and close as if so

**Comment by nadalin** [comment]
@selfissued please close this

**Comment by selfissued** [comment]
USVString is used for icon and rpId
