### ISSUE TITLE
Which extensions (if any) are supported by platform authenticators?

### ISSUE THREAD

**Issue by ghost** [w3c/webauthn#1673]
(My apologies if this is the wrong place to ask such a question. I know it's out of scope of the spec itself, though of course it's very relevant to anyone using WebAuthn.)

I've struggled to find good information on which WebAuthn [extensions](https://www.w3.org/TR/webauthn-2/#sctn-extensions) (if any) are supported by platform authenticators. Does anyone know where this information might be?

I'd imagine it depends on how each browser implements the spec. My sense has been the extensions only really apply to roaming authenticators, but I can't find anything concrete either way. I'd really appreciate any help!

**Comment by certainlyNotHeisenberg** [comment]
@timcappalli Thanks for the suggestion. Sent it to that list (see [here](https://groups.google.com/a/fidoalliance.org/g/fido-dev/c/nlsM77wo4s0/m/mitu3c0tAgAJ)).

**Comment by utliluom33** [comment]
@certainlyNotHeisenberg
