### ISSUE TITLE
Does signing the credential public key with the attestation private key prove to the RP that the user owns the credential private key?

### ISSUE THREAD

**Issue by boogerlad** [w3c/webauthn#1679]
https://www.w3.org/TR/webauthn/#attestation-certificate says

> At registration time, the authenticator uses the attestation private key to sign the Relying Party-specific credential public key (and additional data) that it generates and returns via the authenticatorMakeCredential operation. Relying Parties use the attestation public key conveyed in the attestation certificate to verify the attestation signature

but in self attestation

> the Authenticator does not have any specific attestation key pair. Instead it uses the credential private key to create the attestation signature

To me, self attestation directly proves to the RP that the user has the credential private key since the credential public key is used to verify the attestation signature.

If webauthn was used as a usernameless registration / login, with self attestation, I would feel confident that after registering, they can also be signed in immediately without any further action. With other kinds of attestation (basic, none, etc), I feel that after registering, I would need to go through the login flow to get proof that the user has the private key. Am I misunderstanding?

**Comment by equalsJeffH** [comment]
on 2021-11-03 call:
@agl notes  a possible attack which would be due to RPs overwriting existing cred metadata and causing a victim user to login to an attacker's account.  he will write a note for the spec on this./

**Comment by equalsJeffH** [comment]
re-opening because @agl will write above-mentioned note.
