### ISSUE TITLE
also cite the other extant TLS channel binding mechanisms?

### ISSUE THREAD

**Issue by equalsJeffH** [w3c/webauthn#168]
the webauthn spec presently cites only the work-in-progress IETF Token Binding specs for purposes of cryptographically binding to the underlying TLS channel. platform support for that spec will be forthcoming but not overnight (plus the spec is not finalized). there are other extant TLS channel binding mechanisms -- the Channel ID mech (impl'd in chrome) and the RFC5929 mechs. though RFC5929 tls-unique is proven insecure and is deprecated, tls-server-end-point remains at least conceptually viable and if there is support for it in the wild it should perhaps be cited (as an option) since token binding is only emergent.

**Comment by equalsJeffH** [comment]
this issue is relevant to all places in the spec where we mention "token binding".

**Comment by vijaybh** [comment]
I would like to propose closing this. It seems the IETF TB is close enough to implementation that the added complexity in a new spec like WebAuthn would not be worth it.

**Comment by equalsJeffH** [comment]
OK - Token Binding is in WG Last Call, so I'm fine with this.
