### ISSUE TITLE
caBLE for Payments

### ISSUE THREAD

**Issue by cyberphone** [w3c/webauthn#1681]
This is just a F.Y.I.
https://www.emvco.com/emv_insights_post/what-are-the-emv-specifications

<table><tr><td><i>Consumers today expect their payment device to work anywhere in the world, whether they are paying face-to-face or online. This process must be familiar, convenient, secure and reliable for consumers and for businesses</i></td></tr></table>

Converted into practical terms it means that the device (a phone) provides an integrated payment experience regardless of payment scenario (mobile browser, desktop browser/phone, PoS/phone).  caBLE does not seem to be aligned with this goal.  Existing wallet providers will therefore most likely stick to QR code which covers the two latter use cases and do not depend on cloud service support. QR works great for FIDO based payments as well.

The security issues related to QR like vulnerability to phishing do not apply to payments because the merchant is usually cryptographically tied to the authorized data and must also pass through a payment intermediary vouching for the authenticity of the _registered_ merchant, making this kind of attack much less interesting.

 Note that the above does not relate to SPC since it is neither targeting PoS payments, nor integrated payment experiences.

**Comment by ianbjacobs** [comment]
I do think this relates to SPC:

* PSP calls SPC on a desktop.
* User authenticates with authenticator discoverable through caBLE

Ian

**Comment by nicksteele** [comment]
This is not an issue directly impacting the WebAuthn standard.
