### ISSUE TITLE
Fix the "aborted flag" reference

### ISSUE THREAD

**Issue by nsatragno** [w3c/webauthn#1682]
https://github.com/whatwg/dom/pull/1027 removed the "abort flag" definition on the [dom spec](https://dom.spec.whatwg.org/), which broke our spec (and others).

~~We should either have it reference the ["aborted" attribute](https://dom.spec.whatwg.org/#dom-abortsignal-aborted) or the ["aborted" concept](https://dom.spec.whatwg.org/#abortsignal-aborted), and update the language accordingly.~~

**Comment by nsatragno** [comment]
Guidance for this is here https://dom.spec.whatwg.org/#abortcontroller-api-integration

**Comment by annevk** [comment]
@nidhijaju are you willing to write a patch here? It seems that there's also some places here where we might want to forward the abort reason.

**Comment by annevk** [comment]
Note that this is not purely an editorial change as aborting might now result in a different exception.
