### ISSUE TITLE
Incorrect "to create" phrase used in get() section's introduction?

### ISSUE THREAD

**Issue by equalsJeffH** [w3c/webauthn#1687]
There these two paragraphs in section [5.1.4. Use an Existing Credential to **Make an Assertion** - PublicKeyCredential’s \[\[Get\]\]\(options) Method](https://www.w3.org/TR/2021/REC-webauthn-2-20210408/#sctn-getAssertion);
> The get() implementation [CREDENTIAL-MANAGEMENT-1] calls PublicKeyCredential.\[\[CollectFromCredentialStore]]() to collect any credentials that should be available without user mediation (roughly, this specification’s authorization gesture), and if it does not find exactly one of those, it then calls PublicKeyCredential.\[\[DiscoverFromExternalSource]]() to have the user select a credential source.

> Since this specification requires an authorization gesture **to create** any credentials, the PublicKeyCredential.[[CollectFromCredentialStore]](origin, options, sameOriginWithAncestors) internal method inherits the default behavior of Credential.\[\[CollectFromCredentialStore]](), of returning an empty set.  [emphasis added]

When I recently re-read that section of the spec and encountered that "to create" phrase, I immediately had these questions: 

Why is the phrase "to create" used here?  Ought it be "to use" or "to exercise" ?  

I.e., I do not understand how a gesture at cred creation time would factor in here?

**Comment by emlun** [comment]
I think the "credential" in that phrase is what CredMan calls a "single-use [credential](https://w3c.github.io/webappsec-credential-management/#concept-credential)", right? Which is distinct from a "credential source" which is what we usually mean by "credential" in WebAuthn.

**Comment by equalsJeffH** [comment]
Well, to perhaps better explain why I'm thinking the "to create" phrase is (possibly) incorrect in the quoted paragraph...

[Those quoted paragraphs above](https://github.com/w3c/webauthn/issues/1687#issue-1077103548) are in the section about using an existing credential to make an assertion -- they are not discussing credential creation. And the first quoted paragraph says:
> The **get()** implementation ... calls PublicKeyCredential.[[CollectFromCredentialStore]]() to **_collect_ any credentials that should be available _without user mediation_**

..and then the second paragraph is explaining why the webauthn spec simply "...inherits the default behavior of Credential.[[CollectFromCredentialStore]](), of returning an empty set.", and it would seem that the reason ought to be that it is because webauthn requires a gesture (ie user mediation) _to use_ any credentials (rather than "to create").

**Comment by emlun** [comment]
Ok, let me try to better explain why I'm thinking it might still be technically correct... :smile: 

> they are not discussing credential creation

Indeed, but what you mean here is "credential _source_ creation". An assertion is also a "credential" as defined by CredMan, so creating an assertion is indeed creating a "credential" (but not a "credential _source_").

All that said, even if it is _technically_ correct it may well be worth changing the wording to avoid confusions like this one. :smile: The paragraph in question might be the only one that breaks the within-WebAuthn convention that "credential creation" actually means "credential _source_ creation".

**Comment by equalsJeffH** [comment]
> what you mean here is "credential source creation". An assertion is also a "credential" as defined by CredMan, so creating an assertion is indeed creating a "credential" (but not a "credential source").

doh!  thanks for bearing with me :zany_face: 

> ... even if it is _technically_ correct it may well be worth changing the wording to avoid confusions like this one ...

agreed, so how about this:
> Since this specification requires an authorization gesture to create any [=assertions=]

...?

**Comment by emlun** [comment]
Looks good to me! :+1:
