### ISSUE TITLE
FIDO credential decommissioning

### ISSUE THREAD

**Issue by jdenghifive** [w3c/webauthn#1696]
FIDO credential decommissioning (with 3 cases) is specified in clause 1.3.5. However no API is defined yet for that end. Would like to raise the issue and request discussions here. The specified three uses cases ought to covered, and accomodate both credential types (client-side and server-side).

**Comment by nadalin** [comment]
We have discussed this several times now and have chosen not to proceed down this path.

**Comment by equalsJeffH** [comment]
on 9-Feb-2022 call:
@agl noes that the "Report signaling" section of https://github.com/w3c/webauthn/wiki/Explainer:-broadening-the-user-base-of-WebAuthn#report-signaling  speaks to the needs being expressed here.

**Comment by equalsJeffH** [comment]
on 9-Mar-2022 call: 
Not having heard back from @jdenghifive, we've triaged this to the "futures" milestone for future consideration.  
@agl noted that the "report signaling" section of the explainer (linked in the comment above) continues to be, in general, an interesting idea that the working group should consider when it has the cycles.

**Comment by timcappalli** [comment]
closing to consolidate discussions on this topic. please continue discussions here: https://github.com/w3c/webauthn/issues/1967
