### ISSUE TITLE
Clarification needed regarding meaning of "user verification is required"

### ISSUE THREAD

**Issue by infinisil** [w3c/webauthn#1699]
Step 15 of [Registering a new Credential](https://www.w3.org/TR/webauthn-2/#sctn-registering-a-new-credential) mentions

> 15. If [user verification](https://www.w3.org/TR/webauthn-2/#user-verification) is required for this registration, verify that the [User Verified](https://www.w3.org/TR/webauthn-2/#concept-user-verified) bit of the [flags](https://www.w3.org/TR/webauthn-2/#flags) in authData is set.

this should maybe be changed to this instead

> 15. If options.[authenticatorSelection](https://www.w3.org/TR/webauthn-2/#dom-publickeycredentialcreationoptions-authenticatorselection).[userVerification](https://www.w3.org/TR/webauthn-2/#dom-authenticatorselectioncriteria-userverification) is set to [required](https://www.w3.org/TR/webauthn-2/#dom-userverificationrequirement-required), verify that the [User Verified](https://www.w3.org/TR/webauthn-2/#concept-user-verified) bit of the [flags](https://www.w3.org/TR/webauthn-2/#flags) in authData is set.

---

Similarly with step 17 of [Verifying an Authentication Assertion](https://www.w3.org/TR/webauthn-2/#sctn-verifying-assertion):

> 17. If [user verification](https://www.w3.org/TR/webauthn-2/#user-verification) is required for this assertion, verify that the [User Verified](https://www.w3.org/TR/webauthn-2/#concept-user-verified) bit of the [flags](https://www.w3.org/TR/webauthn-2/#flags) in authData is set.

should maybe be this instead:

> 17. If options.[userVerification](https://www.w3.org/TR/webauthn-2/#dom-publickeycredentialrequestoptions-userverification) is set to [required](https://www.w3.org/TR/webauthn-2/#dom-userverificationrequirement-required), verify that the [User Verified](https://www.w3.org/TR/webauthn-2/#concept-user-verified) bit of the [flags](https://www.w3.org/TR/webauthn-2/#flags) in authData is set.

--- 

And if that shouldn't be done, how is "user verification is required" different from the respective `userVerification` being set to `required`?

**Comment by emlun** [comment]
Most of the time they would mean the same thing, yes. There could be some esoteric cases where they're not, but this seems like a fair change to me. There is precedent in the spec for verifying against the `options` object, for example in [step 5 of §7.2. Verifying an Authentication Assertion](https://www.w3.org/TR/2021/REC-webauthn-2-20210408/#ref-for-dom-publickeycredentialrequestoptions-allowcredentials%E2%91%A0%E2%91%A3): 

>5. If _`options`_.[`allowCredentials`](https://www.w3.org/TR/webauthn-2/#dom-publickeycredentialrequestoptions-allowcredentials) [is not empty](https://infra.spec.whatwg.org/#list-is-empty), verify that _`credential`_.[`id`](https://w3c.github.io/webappsec-credential-management/#dom-credential-id) identifies one of the [public key credentials](https://www.w3.org/TR/webauthn-2/#public-key-credential) listed in _`options`_.[`allowCredentials`](https://www.w3.org/TR/webauthn-2/#dom-publickeycredentialrequestoptions-allowcredentials).

**Comment by equalsJeffH** [comment]
on 2022-02-23 call:  @emlun to update this to use language along the lines of "if RP policy requires user verification...."

**Comment by emlun** [comment]
@Infinisil Does #1704 clarify this well enough? You can see a preview of the spec with the change here: https://pr-preview.s3.amazonaws.com/w3c/webauthn/pull/1704.html

**Comment by infinisil** [comment]
In #1704 I argued that it still doesn't make much sense like that
