### ISSUE TITLE
WebAPI: Authentication failure due to inactivity

### ISSUE THREAD

**Issue by equalsJeffH** [w3c/webauthn#17]
<a href="https://github.com/smachani1"><img src="https://avatars.githubusercontent.com/u/7386729?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Originally submitted by: [smachani1](https://github.com/smachani1)**, on: _Monday Oct 05, 2015 at 01:24 GMT_

----

Section 5.2 Authentication
•	re: step 9.b if de-registration of the public key on the server due to inactivity  resulted on the credential being removed from the authenticator these type of authentication failures - which can frustrate users-  can be avoided.

**Comment by equalsJeffH** [comment]
<a href="https://github.com/equalsJeffH"><img src="https://avatars.githubusercontent.com/u/226571?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Original poster: [equalsJeffH](https://github.com/equalsJeffH)**, on: _Monday Dec 07, 2015 at 19:15 GMT_

----

this remains an open issue the w3c web authn wg will need to address once it begins work. thus setting milestone to ms-fido-v2.0-w3c

**Comment by vijaybh** [comment]
It's not clear how the authenticator would find out that the server has deleted the key. Also, not deleting the credential does not seem to have any bad effects from a security perspective.
