### ISSUE TITLE
makeCredential() should use a dictionary

### ISSUE THREAD

**Issue by annevk** [w3c/webauthn#170]
Taking six parameters is too much. It would be much clearer if this took a dictionary with members that have brief names ("account", not "accountInformation").

**Comment by equalsJeffH** [comment]
which rev of the spec did you refer to?  We did some collapsing of optional args into dictionaries in the current editors' draft..
https://w3c.github.io/webauthn/

Regarding the variable names themselves, that is personal taste.

**Comment by annevk** [comment]
I looked at the editors' draft, but it seems it changed very recently to collapse the last three arguments into a dictionary. That's probably good enough if the first three arguments will always remain required.

**Comment by equalsJeffH** [comment]
> That's probably good enough if the first three arguments will always remain required.

that's our intention at this time. closing this issue.
