### ISSUE TITLE
callerOrigin

### ISSUE THREAD

**Issue by annevk** [w3c/webauthn#171]
What do you mean by origin of the caller?

**Comment by equalsJeffH** [comment]
you're apparently referring to..
>Set callerOrigin to the origin of the caller.

..in both..
https://w3c.github.io/webauthn/#makeCredential
https://w3c.github.io/webauthn/#getAssertion

"origin of the caller" refers to the origin of the document whose javascript is invoking either makeCredential() or getAssertion(). 

perhaps you could suggest more appropriate terminology?

**Comment by annevk** [comment]
So these APIs are not available in workers?

Note that "document whose JavaScript" is woefully imprecise since the JavaScript can come from anywhere.

What you likely mean is something like "current settings object's origin" (see WHATWG HTML Standard).

**Comment by equalsJeffH** [comment]
@annevk asked:
> So these APIs are not available in workers?

it is not entirely clear at this time (seems to me) -- see also: #199
