### ISSUE TITLE
Process to report non-compliant credentials

### ISSUE THREAD

**Issue by Firstyear** [w3c/webauthn#1713]
Hi all,

So far having implemented webauthn-rs, and developed a compatibility testing site, we have uncovered a number of non-compliant credentials (windows 11 + TPM in some cases sends a truncated aaguid, pixel 3a/4 do not send valid authenticator attestation response). 

There seems to be no good way to handle this situation, and no clear way to direct feedback to the various manufactures to report non-compliant credentials/devices. Is this a process that we can improve as part of this wg?

**Comment by ve7jtb** [comment]
Those are in principle all Fido-certified authenticators.   Officially reporting it to Fido might be a path. 

However, filing bug reports with the respective platforms and linking to them from an issue may be the most pragmatic approach.

@akshayku can probably comment on the Win 11 issue.

**Comment by akshayku** [comment]
@Firstyear , Can you share one such truncated AAGUID response? I have not seen such responses.

**Comment by Firstyear** [comment]
@akshayku I'll CC you on the issue in the webauthn-rs project where we found it. 

Is there anyone from Google who can assist with https://bugs.chromium.org/p/chromium/issues/detail?id=1300354 ?

**Comment by Firstyear** [comment]
Is there anyone in this WG from google? I'm having issues with chromium again, and had two issues closed wontfix without investigation. 

https://bugs.chromium.org/p/chromium/issues/detail?id=1312841

https://bugs.chromium.org/p/chromium/issues/detail?id=1312843

**Comment by nicksteele** [comment]
These are not issues that relate to the WebAuthn standard. I would recommend bringing issues like this up with the WebAuthn Community Adoption group as we can help route requests.
