### ISSUE TITLE
getClientExtensionResults returns nil in Safari 15.4

### ISSUE THREAD

**Issue by andreydanil** [w3c/webauthn#1715]
After upgrading to macOS Monterey (which comes with Safari 15.4), the getClientExtensionResults are null. Using Chrome Version 99.0.4844.x, the getClientExtensionResults contain the appId extension, which is the expected happy path.

When no extensions are used, the `getClientExtensionResults` method returns an empty object. 

According to the [mdn docs](https://developer.mozilla.org/en-US/docs/Web/API/PublicKeyCredential/getClientExtensionResults)
> Warning: As of March 2019, only appId (used during creation with [PublicKeyCredentialRequestOptions.extensions](https://developer.mozilla.org/en-US/docs/Web/API/CredentialsContainer/get)) is supported by [Chrome](https://bugs.chromium.org/p/chromium/issues/detail?id=818303) and [Edge](https://docs.microsoft.com/microsoft-edge/dev-guide/windows-integration/web-authentication#api-surface). Firefox does not seem to [support any extension](https://bugzilla.mozilla.org/show_bug.cgi?id=1370728).

From my testing, Firefox (91.7.1esr) does support the appId extension. 
Is this a recent change in Safari 15.4 which the appId extension is no longer supported supported? Can the documentation be updated?

**Comment by timcappalli** [comment]
Please use fido-dev@fidoalliance.org to discussion authenticator implementation concerns. This repo is for the WebAuthn specification.

**Comment by andreydanil** [comment]
Will do. Thanks!
