### ISSUE TITLE
"web origin of the script"

### ISSUE THREAD

**Issue by annevk** [w3c/webauthn#173]
What do you mean by this?

**Comment by equalsJeffH** [comment]
"web origin of the script" is no longer in the current editors' draft.  also, what was meant was essentially `callerOrigin` which is being discussed in #171, so I'm closing this issue. thanks for your feedback.

**Comment by equalsJeffH** [comment]
so conceivably this issue applied to all the instances of `web origin` in the spec, which ought to be simply `origin`. reopening.
