### ISSUE TITLE
facet should be defined in terms of the HTML Standard

### ISSUE THREAD

**Issue by annevk** [w3c/webauthn#174]
RFC6454 is more or less obsolete for web browsers.

**Comment by annevk** [comment]
Note that you need to be very clear which algorithm you actually want to be used here (Unicode vs ASCII).

**Comment by equalsJeffH** [comment]
This is addressed by PR #202 -- closing manually.

**Comment by annevk** [comment]
Was it? When searching for "facet" in https://w3c.github.io/webauthn/ I don't see anything.

**Comment by equalsJeffH** [comment]
yeah, sorry, it was "addressed" in that the term "facet" is no longer usesd.
