### ISSUE TITLE
Attestation on Get Assertion

### ISSUE THREAD

**Issue by timcappalli** [w3c/webauthn#1741]
Topic from June F2F meeting

With the changing security properties of WebAuthn credentials, we need to re-evaluate the need for an RP to request attestation during a Get Assertion.

<placeholder for discussion>

**Comment by timcappalli** [comment]
2022-06-09 - during F2F, general consensus that allowing this at the spec level is a good idea.

**Comment by sbweeden** [comment]
@agl suggested this would be covered in the DPK PR

**Comment by nicksteele** [comment]
Is this being covered specifically in regards to DPK or for other credentials as well? I'd prefer the latter.

**Comment by agl** [comment]
Done in the DPK changes.

**Comment by nicksteele** [comment]
Done

**Comment by emlun** [comment]
Fixed in #1663.
