### ISSUE TITLE
clarify normality of authenticator model - is it actually authenticator API ?

### ISSUE THREAD

**Issue by equalsJeffH** [w3c/webauthn#176]
Presently, we characterize the webauthn authenticator (authnr) model as a "specific abstract functional model".

However, we are refining this authnr model (e.g. PR #154) such that it is becoming more concrete. Perhaps we need to update the language in the spec such that instead of an "authenticator model", it is an "authenticator API". 

Note that if one looks at the extant example of the FIDO U2F USB-HID, Bluetooth, and NFC "authenticator transport protocols"..

https://fidoalliance.org/specs/u2f-specs-1.0-bt-nfc-id-amendment/fido-u2f-hid-protocol.html
https://fidoalliance.org/specs/u2f-specs-1.0-bt-nfc-id-amendment/fido-u2f-bt-protocol.html
https://fidoalliance.org/specs/u2f-specs-1.0-bt-nfc-id-amendment/fido-u2f-nfc-protocol.html

..one can imagine that a similar protocol(s) and subsequent low-level "authenticator API(s)" could be defined for WebAuthn, i.e., as is tacitly imagined in the webauthn "Authentication" use case where one's smartphone is acting as the authenticator for a browser running on a laptop (a protocol between the laptop and the phone is needed to fulfill this use case).

**Comment by equalsJeffH** [comment]
see also #153

**Comment by selfissued** [comment]
Is there anything left to do for this issue, or should it be closed?

**Comment by equalsJeffH** [comment]
This issue intersects with factoring the existence of, and interface to, [CTAP](https://fidoalliance.org/specs/fido-v2.0-rd-20161004/fido-client-to-authenticator-protocol-v2.0-rd-20161004.html) into WebAuthn, so should remain open for now.

**Comment by selfissued** [comment]
My problem with this issue (and a number of others) is that it doesn't propose a specific textual change, and is therefore not actionable.  If you want to keep it open @equalsJeffH , I believe you should update it to say exactly what it is that you're asking us to do.  Statements like "think about X" are not actionable.

**Comment by equalsJeffH** [comment]
see also issue #410 "replace authenticator model with CTAP"

**Comment by equalsJeffH** [comment]
@selfissued 
> My problem with this issue (and a number of others) is that it doesn't propose a specific textual change, and is therefore not actionable.

Well, shucks, I disagree. We need to be able to note "we need to think about this..." items (this is one such example) in an organized fashion, and deal with them in our workflow. To me, your complaint is more about not really having an agreed upon workflow for such things.  

A proposed workflow for [stat:Discuss]-labeled issues:

1. label the issue with [stat:Discuss]
2. set milestone for "when we think we ought to figure this out and have an actionable plan"
3. think about it (as we go along and/or as prodded to by chair(s) and colleagues) and if someone has a proposed resolution, add it to the issue comments, or to an appropriate related issue (this assumes setting and keeping issue cross-references, such as to #410 for this issue)
4. if solution approach gets agreed on, impl in a PR referencing the original issue and any associated issues. Close original issue & associated issues upon PR merge.
5. If original issue not resolved and deemed "not necessary to solve now" upon reaching the milestone, but deemed "we do need to do something about this at some point", punt to a future milestone along with associated issues, if any, as apropos. 
6. If original issue deemed "nah, we don't need to do this", or "no longer applicable/apropos", close original issue and any associated issues as apropos.

**Comment by equalsJeffH** [comment]
WRT the particulars in this issue, see https://github.com/w3c/webauthn/issues/410#issuecomment-303892288 and https://github.com/w3c/webauthn/issues/410#issuecomment-303893322

**Comment by nadalin** [comment]
@equalsJeffH can we close this now that #464 is merged ?

**Comment by equalsJeffH** [comment]
we are at this time keeping the "authenticator model" as an "abstract model", of which CTAP is one concrete example. so closing this.
