### ISSUE TITLE
Unofficial draft 

### ISSUE THREAD

**Issue by ghost** [w3c/webauthn#1767]
Hello I wanted to authenticate my two Public Keys and had to find out that both were converted into an Interface ! I was able to authenticate only one of two . I found an unofficial draft , that  might fix your Problems . I have messed Up and moved my value and I am affraid i'll do more damage If I try to undo them. Best regards Querulant 
https://mikewest.github.io/credentialmanagement/usecases/

**Comment by emlun** [comment]
Sorry, it's hard to understand what your question or suggestion is. For help with implementation questions, please turn to the [public-webauthn@w3c.org](https://lists.w3.org/Archives/Public/public-webauthn/) mail list or the [WebAuthn Adoption Community Group](https://www.w3.org/community/webauthn-adoption/) instead.

**Comment by nicksteele** [comment]
It's unclear how this issue affects the specification, @emlun has included links to better outlets for the issues you experienced.
