### ISSUE TITLE
lowercase form of this RP ID

### ISSUE THREAD

**Issue by annevk** [w3c/webauthn#178]
You need to actually define what this means.

However, given that origins are already normalized, perhaps the algorithm you use (which you also don't seem to define) to derive the RP ID is already fine and "lowercase form" is just adding confusion.

**Comment by annevk** [comment]
Yeah, I meant normalized with respect to the dictionary meaning, not as a standards term.

**Comment by equalsJeffH** [comment]
OK, thx, thought so.   Though, is the answer to my question (2nd parag) "yes", i.e., origin.host and origin.domain are asciiDomains, by default, if non-null ?

**Comment by annevk** [comment]
They are. Note that the domain field is only there for legacy `document.domain` purposes. You don't want to touch it here.

**Comment by equalsJeffH** [comment]
this issue is closely related to #171 and will be addressed as part of addressing the latter.

**Comment by equalsJeffH** [comment]
this is addressed by PR #202 -- closing manually.

**Comment by annevk** [comment]
You still haven't defined lowercase as far as I can tell...

**Comment by annevk** [comment]
You closed a bunch of my issues, but I'm not really convinced the fixes are it.

**Comment by equalsJeffH** [comment]
sorry, this is going to be fixed by PR #198, which I thought was going to get merged right after we merged PR #202, but that didn't occur, reopening...
