### ISSUE TITLE
Incorrect heading level on `prf` extension

### ISSUE THREAD

**Issue by MasterKale** [w3c/webauthn#1781]
## Proposed Change

The `prf` extension on the Editor's Draft appears as at the same level as the new "Client Extension" and "Authenticator Extension" headers:

![Screen Shot 2022-07-21 at 9 58 31 PM](https://user-images.githubusercontent.com/5166470/180366306-65b9c1de-5a0d-49f3-9d66-f1cf9e48eb24.png)

It just needs an extra `#` added to it. I'm self-assigning as I'll take care of this with a PR tomorrow.

**Comment by emlun** [comment]
Oh sorry, I didn't see this before I noticed the same thing and opened #1784.
