### ISSUE TITLE
`uvm` extension is missing authenticator extension input and output WebIDL definitions

### ISSUE THREAD

**Issue by MasterKale** [w3c/webauthn#1782]
## Proposed Change

It looks like the definitions for the `uvm` extension's authenticator extension input and output are in some kind of pre-formatted state, compared to its client extension input and output definitions:

## Client input and output

![Screen Shot 2022-07-22 at 6 12 03 AM](https://user-images.githubusercontent.com/5166470/180446526-524fb0f0-03a7-4c96-aaa9-0a859c6279f8.png)

## Authenticator input and output

![Screen Shot 2022-07-22 at 6 12 13 AM](https://user-images.githubusercontent.com/5166470/180446535-5b35a4a7-08ca-4a0b-a409-0a2c1eb1d4cf.png)

I came to this section of the spec looking for clarification on whether this extension's authenticator output is indeed intended to be defined as a property in `AuthenticationExtensionsAuthenticatorOutputs`, but you currently have to infer that from `$$extensionOutput`.

**Comment by MasterKale** [comment]
...Immediately after posting this I come to understand that these are CDDL definitions; I notice other such CDDL definitions lack formatting, or references to related WebIDL definitions. So maybe the actual issues here are:

1. CDDL definitions don't get any formatting
2. There's nothing connecting these to any related types. Someone unfamiliar with CDDL definitions has to infer that `$$extensionOutput` actually refers to the CDDL definition for `AuthenticationExtensionsAuthenticatorOutputs`

**Comment by Firstyear** [comment]
@MasterKale What device did you find that supports UVM? I've been needing samples for ages.

**Comment by MasterKale** [comment]
> @MasterKale What device did you find that supports UVM? I've been needing samples for ages.

I don't have any good news on that front for you at this moment, I was merely attempting to reference CDDL definitions for some new types in my WebAuthn lib 😅

**Comment by Firstyear** [comment]
Ahhh. For now we don't support it, because nothing in the wild supports it.

**Comment by MasterKale** [comment]
> 1. CDDL definitions don't get any visual formatting

During the WG meeting today it was suggested this be taken up with the Bikeshed project. Closing out as it's not really an issue we can address here.
