### ISSUE TITLE
Add SM2 Digital Signature Algorithm Support

### ISSUE THREAD

**Issue by thedreamwork** [w3c/webauthn#1783]
## SM2DSA is an alternative to the ECDSA algorithm specified in [[RFC6637]](https://tools.ietf.org/id/draft-openpgp-oscca-00.html#RFC6637).

In [the IETF RFC draft named "SM2 Digital Signature Algorithm"](https://datatracker.ietf.org/doc/html/draft-shen-sm2-ecdsa-02) a signature algorithm is specified. The SM2 signature scheme has a small advantage over ECDSA (US) and ECGDSA (Germany) for verifiers: the verifier need not compute any inverses modulo 𝑛. Otherwise the signer's costs are similar to the others. Security analysis of ECDSA is extraordinarily complicated and unsatisfying, in contrast to Schnorr; For better promotion in China,  I suggest adding support for SM2 Digital Signature Algorithm to the specification.

**Comment by Firstyear** [comment]
This would need to be part of https://datatracker.ietf.org/doc/html/rfc8152#section-8 

Additionally, this algorithm is still only a draft, and would probably need more examination before being widely deployed or recommended. 

I'm not sure this request belongs in this repo?

**Comment by thedreamwork** [comment]
Thanks, I agree first need to consider CBOR Object Signing protocol. Meanwhile, need to keep an eye on the webauthn protocol. We noticed that SM2/SM3/SM4 has been added in openssl.[1][2][3]
If it is to be widely used in regions such as China, then it is necessary to add SM algorithm to the protocol. 

[1] https://github.com/openssl/openssl/pull/4793
[2] https://github.com/openssl/openssl/pull/4616
[3] https://github.com/openssl/openssl/pull/4552

**Comment by emlun** [comment]
The WebAuthn spec references an external registry of signature algorithms, see [§5.8.5. Cryptographic Algorithm Identifier (typedef COSEAlgorithmIdentifier)](https://www.w3.org/TR/2021/REC-webauthn-2-20210408/#sctn-alg-identifier):

>A [COSEAlgorithmIdentifier](https://www.w3.org/TR/2021/REC-webauthn-2-20210408/#typedefdef-cosealgorithmidentifier)'s value is a number identifying a cryptographic algorithm. The algorithm identifiers SHOULD be values registered in the IANA COSE Algorithms registry [[IANA-COSE-ALGS-REG]](https://www.w3.org/TR/2021/REC-webauthn-2-20210408/#biblio-iana-cose-algs-reg), for instance, -7 for "ES256" and -257 for "RS256".

So they just need to be added to the IANA registry. No change to WebAuthn is needed, unless the new algorithms need additional restrictions like those we have in [§5.8.5](https://www.w3.org/TR/2021/REC-webauthn-2-20210408/#sctn-alg-identifier) for some algorithms.

**Comment by zzl360** [comment]
The SM2 signature algorithm  has beed add to[ ISO/IEC 14888-3:2018](https://www.iso.org/obp/ui/#iso:std:iso-iec:14888:-3:ed-4:v1:en).If we want to use SM2 in webauthn,we just have to register SM2 in the IANA COSE Algorithms registry. Am I right?

**Comment by emlun** [comment]
Yes, as far as the WebAuthn specification is concerned. You may however also need to encourage RPs and authenticator vendors to implement support for this new algorithm, as the WebAuthn spec does not mandate support for any particular set of algorithms (nor could it enforce such a requirement if there was one).
