### ISSUE TITLE
Is it possible to integrate SQRL with webauthn?

### ISSUE THREAD

**Issue by ghost** [w3c/webauthn#1786]
## Description
Is it possible to integrate SQRL with webauthn? (question or feature)

## Related Links
- https://github.com/Jaaap/SQRL/issues/20
- https://community.bitwarden.com/t/steve-gibson-from-grc-and-sqrl/26638
- https://community.bitwarden.com/t/sqrl-identity/273
- https://community.bitwarden.com/t/sign-in-using-qr-code-without-master-password/15727
- https://community.bitwarden.com/t/temporary-master-password/9725
- https://fidoalliance.org/how-fido-works/
- https://doubleoctopus.com/security-wiki/protocol/fast-identity-online/
- https://fidoalliance.org/
- https://www.grc.com/sqrl/sqrl_explained.pdf
- https://www.grc.com/sqrl/sqrl_cryptography.pdf
- https://www.grc.com/sqrl/sqrl_on_the_wire.pdf
- https://www.grc.com/sqrl/sqrl_operating_details.pdf
- https://www.grc.com/sqrl/SQRL_Explained.pdf

**Comment by ramriot** [comment]
If I may, I have quite a familiarity with SQRL & a little less so with Webauthn & Fido2-UAF.

As far a a complete integration where by a SQRL V1.0 client can talk to a WebAuthn back end, it would need some significant additions to the spec to accommodate this protocol as an authenticator & there are some deficits with SQRL V1.0 in the realm of asserting TLS E2E authenticity that may not be advantageous. Thus a few backward compatible upgrades so the SQRL spec would be required.

That said, there are some aspects of SQRL in the Realm of Site Specific Key generation & lifetime identity management (as described in your citations) that are vastly superior to the current non-scaling way that FIDO2 manages keys that I think would be advantageous to add as an option.

In that space then, possibly having a WebAuth compostable authenticator app or token that uses the core SQRL mode of forward-only deterministic key generation & management would be something worth working on as an alternative to trying to shift WebAuthn at this stage.

**Comment by raphael-louis-andress** [comment]
@ramriot Hi! how are you? so... thank you for feedback ;D

**Comment by timcappalli** [comment]
Please use the FIDO-DEV list for implementation discussions. This repo is for the WebAuthn specification itself. 

https://groups.google.com/a/fidoalliance.org/g/fido-dev
