### ISSUE TITLE
Enterprise attestaion is a bool in WebAuthn and an Int in CTAP2.1

### ISSUE THREAD

**Issue by ve7jtb** [w3c/webauthn#1795]
## Proposed Change

Describe your proposed change. If you have suggested text, please file a corresponding Pull Request.
The current WebAuthn text uses options enterprise to set enterpriseAttestationPossible state to true if present.

In CTAP enterpriseAttestation can have two values 1 for Vendor-facilitated enterprise attestation and 2 for Platform-managed enterprise attestation.  

This might cause confusion if the CTAP2.1 spec is not read closely
Sec 5.1.3 point 20.5 should probably be something like:

Let enterpriseAttestationPossible be an Intiger value, as follows. If options.[attestation](https://w3c.github.io/webauthn/#dom-publickeycredentialcreationoptions-attestation)

is set to [enterprise](https://w3c.github.io/webauthn/#dom-attestationconveyancepreference-enterprise)
Let enterpriseAttestationPossible be 2 if the user agent wishes to support enterprise attestation for options.[rp](https://w3c.github.io/webauthn/#dom-publickeycredentialcreationoptions-rp).[id](https://w3c.github.io/webauthn/#dom-publickeycredentialrpentity-id) (see [Step 8](https://w3c.github.io/webauthn/#CreateCred-DetermineRpId), above). Otherwise 1.

otherwise
Let enterpriseAttestationPossible be absent.

**Comment by Firstyear** [comment]
Given that webauthn sits atop ctap, could we actually use an enumeration of this value to make it clearer?

**Comment by nadalin** [comment]
@ve7jtb Do we just want to close this ?

**Comment by ve7jtb** [comment]
No action
