### ISSUE TITLE
Dependencies section is out of date and duplicates terms index

### ISSUE THREAD

**Issue by emlun** [w3c/webauthn#1797]
[§3. Dependencies](https://w3c.github.io/webauthn/#sctn-dependencies) states that

>This specification relies on several other underlying specifications, listed below and in [Terms defined by reference](https://w3c.github.io/webauthn/#index-defined-elsewhere).

It also states, for example:

>**HTML**
>The concepts of [browsing context](https://html.spec.whatwg.org/multipage/browsers.html#browsing-context), [origin](https://html.spec.whatwg.org/multipage/origin.html#concept-origin), [opaque origin](https://html.spec.whatwg.org/multipage/origin.html#concept-origin-opaque), [tuple origin](https://html.spec.whatwg.org/multipage/origin.html#concept-origin-tuple), [relevant settings object](https://html.spec.whatwg.org/multipage/webappapis.html#relevant-settings-object), and [is a registrable domain suffix of or is equal to](https://html.spec.whatwg.org/multipage/origin.html#is-a-registrable-domain-suffix-of-or-is-equal-to) are defined in [[HTML]](https://w3c.github.io/webauthn/#biblio-html).

...but the [Terms defined by reference][terms-index] section lists many more terms for most of these dependencies.

Should we attempt to keep these sections in sync, or should we move most details out of §3. Dependencies? The [Terms defined by reference][terms-index] section is generated automatically and should always cover all references to other Bikeshed-covered specs, but the Dependencies section needs to be maintained manually. Specs outside of Bikeshed coverage (CBOR, CDDL, etc.) would still need to be listed manually in §3 Dependencies, though.

[terms-index]: https://w3c.github.io/webauthn/#index-defined-elsewhere

**Comment by nadalin** [comment]
@ve7jtb please see if this is still relevant
