### ISSUE TITLE
do not totally lose the term "WebAuthn Relying Party"

### ISSUE THREAD

**Issue by equalsJeffH** [w3c/webauthn#180]
this issue is derived from, and focuses only on the "WebAuthn Relying Party" portion of..

> Re: [webauthn] Text aesthetic updates
> https://lists.w3.org/Archives/Public/public-webauthn/2016Jul/0021.html

Regarding this set of commits..

> [webauthn] new commits pushed by jcjones
> https://lists.w3.org/Archives/Public/public-webauthn/2016Jul/0016.html

...

> - Change "WebAuthn Relying Party" to just "Relying Party"  

..although this change reduces wordiness, I do have some concerns..

I can live with using the unqualified term "Relying Party" in
many places in the text, however, we have been hearing literally for
years, especially from the Fed'd Identity Mgmt community, how confusing
they find the use of the unqualified "Relying Party" term.  Over the years
I've observed many instances of unnecessary misunderstanding and
getting-bolloxed-up due to use of imprecise/ambiguous terminology.

Thus, if others object to using the fully-qualified WebAuthn Relying Party" term 
everywhere, then I suggest editing the new RP definition to be like so..

```
WebAuthn Relying Party
Relying Party

  The entity whose web application utilizes the Web
  Authentication API to register and authenticate users.
  See Registration and Authentication, respectively.

  Note: While the unqualified term Relying Party is also used in other
  contexts (e.g., OAuth, SAML, X.509, etc.), an entity acting as a
  Relying Party in one context is not necessarily a Relying Party
  in others. For example, in an identity management deployment,
  WebAuthn may be used as a user authentication mechanism at the
  Identity Provider, who thus is also acting in the WebAuthn
  Relying Party role.
```

Additionally, within each major section I'd use the "WebAuthn Relying
Party" term on first use and "Relying Party" otherwise.

I think it's really important we make this extra effort to disambiguate
the terms. 

Also, we /could/ use the acronym "WRP", say, rather than the spelled-out
unqualified "Relying Party" term.

**Comment by equalsJeffH** [comment]
see also: #79, #80

**Comment by selfissued** [comment]
I agree that we should keep the term "WebAuthn Relying Party", at least when the term is first introduced.  It would be fine at that point to also say that, in this specification, this is sometimes shortened to just "Relying Party" or "RP".

**Comment by equalsJeffH** [comment]
to expand on @selfissued's thoughts, note that we ought to go through and make all `[RP]` and `[RPS]` occurrences to be `[=[RP]=]` etc. and we can add "webauthn relying party" appropriately in the terminology section and make equivalent to Relying Party, and also say that, in this specification, this is sometimes shortened to just "Relying Party" or "RP".

**Comment by selfissued** [comment]
BTW, I don't like introducing the term "WRP".  If we abbreviate, let's stay with the standard "RP" abbreviation.

**Comment by AngeloKai** [comment]
By the way, all the [RP] and [RPS] are changed to [=[RP]=] when we were publishing WD-05.

**Comment by equalsJeffH** [comment]
@selfissued, @AngeloKai, understood.

**Comment by nadalin** [comment]
@selfissued can you make sure that when RP is used refers to WebAuthn Relying Party
