### ISSUE TITLE
Variable reference issue in DPK processing rules

### ISSUE THREAD

**Issue by sbweeden** [w3c/webauthn#1817]
## Proposed Change

See: https://github.com/w3c/webauthn/blob/main/index.bs#L7107

This is related to DPK processing rules for the create and get operations.

It says:
```
Let attObjForDevicePublicKey be the value of the [devicePubKey](https://w3c.github.io/webauthn/#dom-authenticationextensionsclientoutputs-devicepubkey) member of clientExtensionResults.
```

I am fairly sure that this is not correct, insofar as attObjForDevicePublicKey is not a member of clientExtensionResults - instead it is authenticator extension data (i.e. part of the `extensions` of the `authData` variable).

The same issue is relevant to section 10.2.2.3.2 (Authentication processing rules) step 1.

I think these should say something like:
```
Let attObjForDevicePublicKey be the value of the [devicePubKey](https://w3c.github.io/webauthn/#dom-authenticationextensionsclientoutputs-devicepubkey) member of the extensions in authData.
```

**Comment by sbweeden** [comment]
@agl - FYI - can you please confirm this issue is valid?

**Comment by agl** [comment]
> Let attObjForDevicePublicKey be the value of the [devicePubKey](https://w3c.github.io/webauthn/#dom-authenticationextensionsclientoutputs-devicepubkey) member of clientExtensionResults.

Well, the DPK output is in clientExtensionResults too, although it's in the `authenticatorOutput` member now that the signature has been moved out of it. So I should have updated that. But one could take it from the authenticator data too. That version is signed over by the primary credential, although whether that matters to RPs who care about DPK, I'm not sure.

I'll craft a PR to mention the move to `authenticatorOutput`, but do you, as an RP, want to read it from the authData?

**Comment by sbweeden** [comment]
As an RP, I would prefer to read it from the authenticator-attested field rather than the unsigned client extensions output. If it's an exact copy in the `authenticatorOutput` unsigned client extension, then shouldn't part of the verification be making sure these are the same value?

**Comment by sbweeden** [comment]
For that matter - is there any particular reason a redundant copy of the authenticator extension information also appears in the client extension output?

**Comment by agl** [comment]
>  If it's an exact copy in the authenticatorOutput unsigned client extension, then shouldn't part of the verification be making sure these are the same value?
> is there any particular reason a redundant copy of the authenticator extension information also appears in the client extension output?

As a pattern, authenticator outputs are duplicated into the client outputs. Mike Jones has always insisted on it.

I don't believe that we have instructions for verifying the concordance of extension outputs elsewhere, thus we don't here either. I don't mind either way.

**Comment by sbweeden** [comment]
Let's discuss in next regular WebAuthn call. Personally I can't understand why an RP would ever use the client extension output as authoritative for this data given its not signed, whereas the copy within the authData is signed.

**Comment by emlun** [comment]
Related discussion: https://github.com/w3c/webauthn/pull/1663#discussion_r987425504

**Comment by sbweeden** [comment]
POV from @selfissued requested.

**Comment by nadalin** [comment]
@selfissued Please review

**Comment by selfissued** [comment]
As discussed in the 14-Dec-22 working group call, it doesn't make security sense to fields from the signed authenticator extension output to the client extension output in an unsigned form.  I suggest that when the extension is supported and used, that the client extension output simply be `true` - indicating that the extension was used and the values in the authenticator extension output should be used.

**Comment by emlun** [comment]
Thanks @selfissued!

In that case, I think we have the option to also change the authenticator extension output format slightly:

```diff
 $$extensionOutput //= (
-    devicePubKey: bstr,
+    devicePubKey: attObjForDevicePublicKey,
 )
```

That is remove the extra layer of byte string wrapping, since we no longer need it to make sure the representation is byte-identical between authenticator and client outputs. Thoughts on that @agl?

**Comment by agl** [comment]
> Thoughts on that @agl?

The client output was the only motivation for the wrapping so it shouldn't stick around if the client output changes.

**Comment by sbweeden** [comment]
In preparing a PR to address this issue, I noticed that the DPK signature will still need to be transmitted in client extension output since there is no vehicle for unsigned extension output in authData. As a result the boolean flag to indicate the extension was processed is unnecessary in client extension output since the signature must be present there already and can serve as the vehicle to indicate to the RP that the extension should be available for processing in authData.

**Comment by sbweeden** [comment]
Fixed - closing.
