### ISSUE TITLE
Spec draft points to wrong GitHub issues page

### ISSUE THREAD

**Issue by hillbrad** [w3c/webauthn#183]
The "please use GitHub issues" language in the "Status of this Document" section points to the GitHub issues page for the reporting spec, not this one.

https://www.w3.org/TR/2016/WD-webauthn-20160531/

**Comment by equalsJeffH** [comment]
good catch, thanks.

**Comment by equalsJeffH** [comment]
the "Status of this Document" section is generated by bikeshed AFAIK.  @jcjones -- is the href attribute, of the link Brad is pointing to, configurable within our bikeshed instance (i.e., the one that generates the gh-pages branch's content, i.e., the editors' draft)?

**Comment by equalsJeffH** [comment]
hm, I tried adding the "issue tracking" metadata param within index.bs like so..
`Issue Tracking: Github https://github.com/w3c/webauthn/issues`, but the resultant bikeshed output still has the problem as-described by Brad.  However, this did add an "issue tracking" item to the spec's front matter under the spec title, which is something we oughta retain in any case.

**Comment by equalsJeffH** [comment]
see tabatkins/bikeshed#799

**Comment by vijaybh** [comment]
Note that this exposes another problem: we had locked our Bikeshed version some time ago to a "known good" version to avoid other issues. So even though Tab has fixed this issue in the upstream sources we do not benefit from it.

A long time ago I'd suggested that we keep our Bikeshed config in our own repo and copy it over the Bikeshed version (i.e. keep our own version of bikeshed/include/webauthn just like we do for bikeshed/spec-data right now). I just never got around to it. This seems like another reason to do that.
