### ISSUE TITLE
WebAuthn Level 2 specification page error: ERR_TOO_MANY_REDIRECTS 

### ISSUE THREAD

**Issue by mirkop** [w3c/webauthn#1832]
## Description
Hello,

There is an ERR_TOO_MANY_REDIRECTS error that occurs when attempting to access the WebAuthn Level 2 specifications. I tried accessing that page using several different browsers, and they all generated the same "too many redirects" error.
(Chrome, Edge, FireFox, & Safari)

https://www.w3.org/TR/webauthn-2/

www.w3.org redirected you too many times.
ERR_TOO_MANY_REDIRECTS

I hope this is the correct place to report this issue. If not, let me know where I can report this.

Thank you,
Mirko J. Ploch
SurePassID Corporation

**Comment by MasterKale** [comment]
Hmm, maybe you caught the side mid-deployment or some such. For what it's worth it's loading fine for me this morning in all variations of Chrome, Firefox, and Safari:

![Screenshot 2022-12-09 at 9 13 53 AM](https://user-images.githubusercontent.com/5166470/206756768-6822898b-1fb3-488c-820e-bf5f9b463770.png)

**Comment by mirkop** [comment]
It's working for me now too. I tried it for a while before and after reporting it. Who knows what happened. Thank you.
