### ISSUE TITLE
Add "smart-card" to AuthenticatorTransport enum (WebKit)

### ISSUE THREAD

**Issue by micolous** [w3c/webauthn#1835]
## Proposed Change

WebKit has added a new transport, `smart-card`, in https://github.com/WebKit/WebKit/pull/2207

https://github.com/WebKit/WebKit/blob/f5eb326e26ffc147b9421cbb3db9ce1d21750d8e/Source/WebCore/Modules/webauthn/WebAuthenticationConstants.h#L95

This transport does *not* appear in the list of transports in the spec: https://w3c.github.io/webauthn/#enum-transport

This should be added to the list.

It looks like this transport uses the [CryptoTokenKit TKSmartCard API](https://developer.apple.com/documentation/cryptotokenkit/tksmartcard), from which a vague reading may suggest this eventually hooks into platform CCID APIs... which makes me think this is basically the same as the (standard) `nfc` transport, but is intended to work with NFC transceivers on macOS.

~~However, when I tried to use this on Safari 16.2 on macOS 13.1 with a PC/SC compatible CCID NFC transceiver (which works fine with other applications), Safari doesn't try to use it at all. Perhaps Apple folks (or those with Radar access) could comment further, as [the public bug](https://bugs.webkit.org/show_bug.cgi?id=242365) is light on details.~~

*Edited (2022-12-19):* it seems to be in the Safari Technology Preview v160, but doesn't work on devices with a PIN.

**Comment by ve7jtb** [comment]
Apple added CCID to support PKI smartcards in the last major releases. 
At the same time Safari enabled Fido over CCID.   That works just fine. plig in your favorite CCID reader into MacOS or an iPad and tap at the first menu.  Pin is supported.  

On the authenticator side, In Fido Security requirements, CTAP is not allowed to be exposed over CCID.  It is exposed over NFC (Yubikeys have USB CCID interfaces and explicitly disable fido over them, Older Pre YK5 had U2F exposed over CCID)
Given that CCID is not a supported transport for the aUthenticator and NFC already exists, I don't think webauthn needs a new enum. 

If someone from apple has a different opinion, I would be interested.
Yes on iOS there are potentially 2 NFC readers one built in and one over CCID but that is an internal implementation deatal to my understanding.

**Comment by pascoej** [comment]
We send a GetUID and if present, we treat the AuthenticatorTransport as nfc. It's only if we don't get a UID back we report "smart-card," which is meant to indicate a smart card with contacts. Again, contactless smart cards are treated as nfc. 

I have a few sample cards of this type and they are a bit strange, none support a user presence gesture other than inserting the card..

I introduced "smart-card" to handle this situation as theoretically your smart card reader with contacts may be built in or connected via pci, so USB didn't seem appropriate.

**Comment by serianox** [comment]
Worked a lot on authenticators on smartcards, so I'll try to give a little bit of context. 😊

"nfc" is a shortcut for authenticators on an ISO 14443-3/7816-4 contactless interface - which NFC reader can communicate with.

> We send a GetUID and if present, we treat the AuthenticatorTransport as nfc. It's only if we don't get a UID back we report "smart-card," which is meant to indicate a smart card with contacts. Again, contactless smart cards are treated as nfc.

That's the expected behavior, contactless authenticators are "nfc".

> As for smart-cards with contacts: I have a few sample cards of this type and they are a bit strange, none support a user presence gesture other than inserting the card...

Yes, there is no user presence gesture on smartcard in contactless. If you plug it through its contact interface, you should have more or less the same behavior than in contactless, the user presence is managed by the client.

But this is not a standardized transport... maybe in the next CTAP 2.2.

> RPs can use this transport hint to decide to include language about inserting a smart-card vs inserting a usb security key. I imagine the only significant users of smart-cards with contacts being used as a FIDO authenticator will be enterprises.

👍

> Microsoft is the only other platform supporting CCID readers as far as I know.

Windows has also been supporting contact smart card since day one. That's a result of how WinSCard is designed, and Microsoft decided not to go to the length of guessing if the card on the reader is read through contact or contactless interface.

**Comment by micolous** [comment]
Thanks for the tips!

> "nfc" is a shortcut for authenticators on an ISO 14443-3/7816-4 contactless interface - which NFC reader can communicate with.
>
> [...] But this is not a standardized transport... maybe in the next CTAP 2.2.

Both the CTAP and U2F specifications only specify command / response APDUs on an ISO 7816-4 level.  Even the CTAP 2.1 spec calls it ["ISO7816, ISO14443 **and** Near Field Communication"][0] (emphasis added), so you could squint at that and argue "ISO7816-3 contact cards are valid in the current spec".  After all, EMV also runs over both contact and contactless interfaces with not much distinction between them.

[0]: https://fidoalliance.org/specs/fido-v2.1-ps-20210615/fido-client-to-authenticator-protocol-v2.1-ps-errata-20220621.html#nfc

However, I've only found a couple of vendors which claim to support that as a transport, and an [open source U2F JCOP applet](https://github.com/tsenger/CCU2F). Even composite authenticator devices which have a USB CCID interface (eg: Yubikey) don't support CTAP over that interface, even when they _also_ support NFC.

> We send a GetUID and if present, we treat the AuthenticatorTransport as nfc. It's only if we don't get a UID back we report "smart-card," which is meant to indicate a smart card with contacts. Again, contactless smart cards are treated as nfc.

That seems reasonable to me.

My request is that if this distinction is to be exposed over the WebAuthn API in some way, then it should be documented. 😄 

> ...there is no user presence gesture on smartcard in contactless. If you plug it through its contact interface, you should have more or less the same behavior than in contactless, the user presence is managed by the client.

This is similar to USB U2F devices which have no button (eg: PlugUp). You could also falsify the user presence check on both by power-cycling the interface (from software), and the PC/SC API offers a standard way for card readers mechanically ejecting or accepting cards.

I've also noticed the way that presence checks work on NFC devices differs by vendor (and even the ones that check could probably be falsified in the same way), but that's a whole _other_ can of worms.

> Microsoft is the only other platform supporting CCID readers as far as I know.

[webauthn-rs](https://github.com/kanidm/webauthn-rs) (which I wrote most of [its authenticator code](https://github.com/kanidm/webauthn-rs/tree/master/webauthn-authenticator-rs)) supports FIDO 2.0/2.1 authenticators via the PC/SC API, but calls it `nfc` for consistency with the WebAuthn spec, and it doesn't bother to do a `GetUID`.

If the `smart-card` transport identifier _was_ standardised, then I'd adopt it too. 😄 

> Windows has also been supporting contact smart card since day one. That's a result of how WinSCard is designed, and Microsoft decided not to go to the length of guessing if the card on the reader is read through contact or contactless interface.

It's more about how PC/SC is designed: on an application level, it's just a way to exchange APDUs with a card, and they're all a bunch of bytes... it doesn't really matter whether that's a contact or contactless interface. You could design an optical smartcard interface, and as long as you have IFD handlers for it, and it talked ISO 7816-4, that'd all just work for existing applications 😜 

The Windows WebAuthn API [only declares a constant for "NFC"][1], and its PC/SC code is all in the `MicrosoftCtapNfcProvider`. So my guess is that they either opted to not make the distinction because the CTAP spec doesn't.

[1]: https://github.com/microsoft/webauthn/blob/9fb38aa2775e286f504fc087efc62e5557bee881/webauthn.h#L250

**Comment by serianox** [comment]
> Going off the [publicly published security requirements](https://fidoalliance.org/specs/fido-security-requirements/fido-authenticator-security-requirements-v1.5-fd-20211102.html) there is no reference to CCID at all.

Still also looking for it. I'm sure we wrote it somewhere, but I can't find where...

> Both the CTAP and U2F specifications only specify command / response APDUs on an ISO 7816-4 level. Even the CTAP 2.1 spec calls it ["ISO7816, ISO14443 and Near Field Communication"](https://fidoalliance.org/specs/fido-v2.1-ps-20210615/fido-client-to-authenticator-protocol-v2.1-ps-errata-20220621.html#nfc) (emphasis added), so you could squint at that and argue "ISO7816-3 contact cards are valid in the current spec". After all, EMV also runs over both contact and contactless interfaces with not much distinction between them.

Yes, that was my clumsy attempt to clarify the spec... Basically, FIDO define what is a FIDO authenticator "that can be used with a NFC reader", and in the spec we define it at ISO 7816-4 level (and if you connect the dot, it should implement an ISO 14443 interface).

> However, I've only found a couple of vendors which claim to support that as a transport, and an [open source U2F JCOP applet](https://github.com/tsenger/CCU2F). Even composite authenticator devices which have a USB CCID interface (eg: Yubikey) don't support CTAP over that interface, even when they also support NFC.

Any dual interface smartcard with a FIDO applet should do the same, if the vendor didn't add specific code to prevent selection outside of contactless.

> You could also falsify the user presence check on both by power-cycling the interface (from software), and the PC/SC API offers a standard way for card readers mechanically ejecting or accepting cards.

Yes, you can falsify it from the p.o.v. of the token, who can't see the difference between a cold reset and a power cycle. But the actual check of user presence is done by the client software.

> It's more about how PC/SC is designed: on an application level, it's just a way to exchange APDUs with a card, and they're all a bunch of bytes... it doesn't really matter whether that's a contact or contactless interface. You could design an optical smartcard interface, and as long as you have IFD handlers for it, and it talked ISO 7816-4, that'd all just work for existing applications 😜

If you start playing with contact interfaces, you'll soon discover T=0, and you wish you hadn't. 🙃

> [webauthn-rs](https://github.com/kanidm/webauthn-rs) (which I wrote most of [its authenticator code](https://github.com/kanidm/webauthn-rs/tree/master/webauthn-authenticator-rs)) supports FIDO 2.0/2.1 authenticators via the PC/SC API, but calls it nfc for consistency with the WebAuthn spec
> The Windows WebAuthn API [only declares a constant for "NFC"](https://github.com/microsoft/webauthn/blob/9fb38aa2775e286f504fc087efc62e5557bee881/webauthn.h#L250), and its PC/SC code is all in the MicrosoftCtapNfcProvider. So my guess is that they opted to not make the distinction to keep things simple, and because the CTAP spec doesn't.

You made the same design decision as Microsoft. [libfido2](https://developers.yubico.com/libfido2/) did the same, they also have a PC/SC interface.
