### ISSUE TITLE
Spelling mistake expecially in 1.1 https://www.w3.org/TR/2019/REC-webauthn-1-20190304/#spec-roadmap

### ISSUE THREAD

**Issue by vanroth1** [w3c/webauthn#1841]
![spelling-11-especially](https://user-images.githubusercontent.com/41262516/214052522-3ef625cc-44b0-4b89-a8a0-56efe1d63477.png)
In chapter 1.1 

Relying Party web application developers, **_expecially_** those responsible for Relying Party web application login flows, account recovery flows, user account database content, etc.

Relying Party web application developers, **_especially_** those responsible for Relying Party web application login flows, account recovery flows, user account database content, etc.

**Comment by emlun** [comment]
Thanks! This was fixed in commit e6791c053bcb7f205713d05a53041539c5542ae7 and is [no longer present in L2](https://www.w3.org/TR/2021/REC-webauthn-2-20210408/) and forward.
