### ISSUE TITLE
Add topOrigin to clientData for cross-origin GET in iframe

### ISSUE THREAD

**Issue by timcappalli** [w3c/webauthn#1842]
This issue is to track the change discussed in the last WebAuthn call about adding the following for cross-origin GET in an frame:
- ~~add top origin (`topOrigin`), aka what's shown to the user in the browser bar, to clientData~~ (done in #1801)
- Add text around how RP should process and evaluate this information

This will match the changes being added in #1801 for create. PR coming in the next few weeks.

**Comment by timcappalli** [comment]
> Add text saying clients should show both the RP ID and top origin to the user during getAssertion

@agl @akshayku any suggestions on where this should go? 

Under section 13, there's "Visibility Considerations for Embedded Usage", but the current text is targeted at RPs.
Section 14.5 is about privacy considerations for clients, so maybe this is the best spot?

**Comment by Kieun** [comment]
In the latest editor's draft, `topOrigin` is missing in the [`get` method's processing step 10](https://w3c.github.io/webauthn/#sctn-discover-from-external-source).

> Let collectedClientData be a new [CollectedClientData](https://w3c.github.io/webauthn/#dictdef-collectedclientdata) instance whose fields are:
[type](https://w3c.github.io/webauthn/#dom-collectedclientdata-type)
The string "webauthn.get".
[challenge](https://w3c.github.io/webauthn/#dom-collectedclientdata-challenge)
The [base64url encoding](https://w3c.github.io/webauthn/#base64url-encoding) of pkOptions.[challenge](https://w3c.github.io/webauthn/#dom-publickeycredentialrequestoptions-challenge)
[origin](https://w3c.github.io/webauthn/#dom-collectedclientdata-origin)
The [serialization of](https://html.spec.whatwg.org/multipage/browsers.html#ascii-serialisation-of-an-origin) callerOrigin.
[crossOrigin](https://w3c.github.io/webauthn/#dom-collectedclientdata-crossorigin)
The inverse of the value of the [sameOriginWithAncestors](https://w3c.github.io/webauthn/#dom-publickeycredential-discoverfromexternalsource-origin-options-sameoriginwithancestors-sameoriginwithancestors) argument passed to this [internal method](https://tc39.github.io/ecma262/#sec-object-internal-methods-and-internal-slots).

**Comment by timcappalli** [comment]
Good catch @Kieun! TYVM. Addressed in #1891
