### ISSUE TITLE
Differentiate when devicePubKey unsupported vs. failed?

### ISSUE THREAD

**Issue by emlun** [w3c/webauthn#1846]
[§10.2.2. Device-bound public key extension (devicePubKey)](https://w3c.github.io/webauthn/#sctn-device-publickey-extension) currently reads (emphasis added):

> If the [authenticator](https://w3c.github.io/webauthn/#authenticator) is incapable of generating a [hardware-bound device key pair](https://w3c.github.io/webauthn/#hardware-bound-device-key-pair), **or the registration or authentication operation fails** for any reason, this extension is ignored and no [hardware-bound device key pair](https://w3c.github.io/webauthn/#hardware-bound-device-key-pair) is created. In this case, there is **no [devicePubKey](https://w3c.github.io/webauthn/#devicepubkey) extension output** generated.

However, [§9.2. Defining Extensions](https://w3c.github.io/webauthn/#sctn-extension-specification) reads (emphasis added):

> Similarly, **any extension that requires authenticator processing MUST return an [authenticator extension output](https://w3c.github.io/webauthn/#authenticator-extension-output)** to let the [Relying Party](https://w3c.github.io/webauthn/#relying-party) know that the extension was honored by the authenticator. If an extension does not otherwise require any result values, it SHOULD be defined as returning a JSON Boolean [client extension output](https://w3c.github.io/webauthn/#client-extension-output) result, set to true to signify that the extension was understood and processed. **Likewise, any [authenticator extension](https://w3c.github.io/webauthn/#authenticator-extension) that does not otherwise require any result values MUST return a value** and SHOULD return a CBOR Boolean [authenticator extension output](https://w3c.github.io/webauthn/#authenticator-extension-output) result, set to true to signify that the extension was understood and processed.

I think it is appropriate that the extension returns no output when not supported or when the authenticator is incapable. But in the spirit of the above requirements and guidelines, there should probably be some way to differentiate between that and the case when the extension is supported but processing fails for some reason.

## Proposed Change

(The following assumes that PR #1845 will be merged)

- Change the authenticator extension output type from

  ```
  $$extensionOutput //= (
      devicePubKey: attObjForDevicePublicKey,
  )
  ```
  to
  ```
  $$extensionOutput //= (
      devicePubKey: attObjForDevicePublicKey / false,
  )
  ```
  and when authenticator extension processing fails for any reason (other than the authenticator being incapable), return `false` as the authenticator extension output and include no unsigned output in the unsigned extensions map.

  Essentially, a `false` output would indicate that the extension might succeed on that device if the RP retries the request at a later time, while an absent output would indicate the extension is unlikely to succeed if retried.

- When the authenticator extension output is `false`, return an empty object as the client extension output (i.e., let `signature` be `undefined`). [Any dictionary member that is not required is optional](https://webidl.spec.whatwg.org/#dictionary-member-optional), so this requires no change to the WebIDL.

**Comment by emlun** [comment]
...and as I wrote this out I realized I'm going to immediately argue against myself (hey, that's what discussions are for!):

> Essentially, a `false` output would indicate that the extension might succeed on that device if the RP retries the request at a later time, while an absent output would indicate the extension is unlikely to succeed if retried.

On further thought this doesn't quite hold up: an absent output could also just mean the client is not recent enough, while the authenticator is perfectly capable of the required operations. So the `false` proposed above might actually not add any information?

So perhaps the meaning of `false` should be the other way around, at least on the client output level - if the client understands the extension, and knows that the authenticator will never support it, then return some variant of "~false" to indicate the RP can stop retrying on this machine. If that is in combination with an authenticator output of `false`, then it means the extension is supported but failed; if the client output is "~false" and the authenticator output is absent, that means the authenticator will never support it.

As noted above, I suppose empty object (`{}`) would be the natural way to express a "~false" client output without complicating the WebIDL types. But then: this adds a bit of complexity in processing the output values. Is the information gained worth that added complexity?

**Comment by agl** [comment]
Picking at the language in the spec:

> Similarly, any extension that requires authenticator processing MUST return an [authenticator extension output](https://w3c.github.io/webauthn/#authenticator-extension-output) to let the [Relying Party](https://w3c.github.io/webauthn/#relying-party) know that the extension was honored by the authenticator.

If the authenticator refused / failed to create a DPK then the extension wasn't honored by the authenticator.

> If an extension does not otherwise require any result values, it SHOULD be defined as returning a JSON Boolean [client extension output](https://w3c.github.io/webauthn/#client-extension-output) result, set to true to signify that the extension was understood and processed.

DPK does require result values. (And in the case in question, the extension was not processed.)

> Likewise, any [authenticator extension](https://w3c.github.io/webauthn/#authenticator-extension) that does not otherwise require any result values MUST return a value and SHOULD return a CBOR Boolean [authenticator extension output](https://w3c.github.io/webauthn/#authenticator-extension-output) result, set to true to signify that the extension was understood and processed.

DPK does require result values. (And in the case in question, the extension was not processed.)

So I don't think any of those apply here?

In practice, I don't believe that the authenticator failing to create a DPK is a useful signal for sites. It "shouldn't" happen. Of course, weird corruption does happen on a tiny handful of devices that can cause all sorts of weirdness, but that argues too much: if _any_ sort of weird behaviour is in scope then we would have no end of error conditions to explicitly handle.

**Comment by emlun** [comment]
Agreed, I don't think the difference (if any) is actually useful to the RP. An RP that wants to use `devicePubKey` should always request the extension anyway. The case where a supporting authenticator randomly fails, but would succeed if the request is immediately retried, should be rare enough that it's not worth these complications. Thanks for your thoughts!
