### ISSUE TITLE
How long the relying party should maintain the challenge and related information?

### ISSUE THREAD

**Issue by Kieun** [w3c/webauthn#1848]
In section [13.4.3. Cryptographic Challenges](https://w3c.github.io/webauthn/#sctn-cryptographic-challenges), there are some information about such requirements.
> As a cryptographic protocol, Web Authentication is dependent upon randomized challenges to avoid replay attacks. Therefore, the values of both [PublicKeyCredentialCreationOptions](https://w3c.github.io/webauthn/#dictdef-publickeycredentialcreationoptions).[challenge](https://w3c.github.io/webauthn/#dom-publickeycredentialcreationoptions-challenge) and [PublicKeyCredentialRequestOptions](https://w3c.github.io/webauthn/#dictdef-publickeycredentialrequestoptions).[challenge](https://w3c.github.io/webauthn/#dom-publickeycredentialrequestoptions-challenge) MUST be randomly generated by [Relying Parties](https://w3c.github.io/webauthn/#relying-party) in an environment they trust (e.g., on the server-side), and the returned [challenge](https://w3c.github.io/webauthn/#dom-collectedclientdata-challenge) value in the client’s response MUST match what was generated. This SHOULD be done in a fashion that does not rely upon a client’s behavior, e.g., the [Relying Party](https://w3c.github.io/webauthn/#relying-party) SHOULD store the challenge temporarily until the operation is complete. Tolerating a mismatch will compromise the security of the protocol.

Following sentence is quite unclear to me.
> This SHOULD be done in a fashion that does not rely upon a client’s behavior, e.g., the [Relying Party](https://w3c.github.io/webauthn/#relying-party) SHOULD store the challenge temporarily until the operation is complete.

It seems that the RP server should have a kind of timeout to invalidate the challenge in order not to rely on the client's behavior.
RP might set some timeout values by considering the expected user action timeout and indicate such expectations in the options. Our current implementation follows such behavior.

One of issues if the RP have similar logics as follows if the conditional UI (autofill) is used.
1. User loads the login page (w/ conditional UI) and fetches the webauthn.get options.
2. User does not perform webauthn login process.  e.g., moves to other tabs and stays there until the server's challenge is timeout
3. User moves to the original tab and performs webauthn login with Auto-Fill UI
4. _User sees an error since the challenge on the RP server side is already timeout(or invalidated)_

**In above case, if the RP server does not have any timeout for the issued challenge, it would create some security risks.**

What's the recommendation of this? Or, is it better to respect preferred timeout value from the option in the browser' auto-fill implementation?

**Comment by timcappalli** [comment]
We could potentially align the challenge validity with the RP requested timeout value, but since that is only a hint to the client, it may not be perfect. But at a minimum, it would at least provide a max window.

**Comment by Kieun** [comment]
If the browser aligns the RP requested timeout value, then anyway RP could invalidate expired challenge without worrying so much. 
But in other aspects, after the request is timed out from RP and browser, then how the RP triggers Auto-Fill UI again?

**Comment by Kieun** [comment]
@sbweeden If it is the case, then the RP client should handle such timeout to cancel the pending request and this needs to be explained in somewhere in the spec.

**Comment by sbweeden** [comment]
I think this example, already in the spec, covers how to abort an in-progress request: https://w3c.github.io/webauthn/#sctn-sample-aborting

**Comment by Kieun** [comment]
@sbweeden I know the abort example was already there and we've been implementing it on our demo, but it would be good to indicate or explain to recommend aborting pending operation for auto-fill UI.

**Comment by MasterKale** [comment]
I think in general we could suggest RP's allow challenges to be used _once_ within N minutes, because a user may walk away mid-ceremony and come back, and should be able to immediately re-attempt without needing to request new options. This has been our practical experience working with WebAuthn, mind you, and I suspect other RP's have done something similar without introducing any security issues into the auth flow.

**Comment by dolda2000** [comment]
I too recently grappled with this situation and eventually decided to us one global challenge per web session, unbounded by time, that is "consumed" when one (of potentially several) conditional sessions actually complete. I consider this a very imperfect solution, but I found it to be the least bad of the options I considered.

Unless it's too late, I would suggest changing/amending conditional mediation to a two-stage process, where a call is made back into the website script when a user *actually* decides to interact with the conditional mediation session, at which time a challenge can be fetched from the server. Just my two cents.
