### ISSUE TITLE
Emphasize use of `user.name` for RP's to help users distinguish credentials

### ISSUE THREAD

**Issue by MasterKale** [w3c/webauthn#1852]
## Context

RP's, like us at Cisco, use WebAuthn with a broad RP ID scoped in a way to allow for credential reuse across multiple "applications" on unique subdomains. Unfortunately, we've discovered that current, nascent passkeys management UIs emphasize displaying a credential's RP ID and username, which are often 

**Chrome:**
![Screenshot 2023-02-13 at 6 14 57 PM](https://user-images.githubusercontent.com/5166470/218621848-26d77b83-3737-4130-8361-39affbb70a04.png)

**1Password:**
![Screenshot 2023-02-13 at 6 23 15 PM](https://user-images.githubusercontent.com/5166470/218622594-f03118b1-3e40-4816-aebb-b015e5e85ec6.png)

**Safari (macOS):**
![Screenshot 2023-02-13 at 6 16 38 PM](https://user-images.githubusercontent.com/5166470/218621842-16eee8a2-a1c0-4d35-aa5c-c122dd9ae904.png)

## Proposed Change

What if we added a "`note`" property somewhere in [PublicKeyCredentialCreationOptions](https://www.w3.org/TR/webauthn-2/#dictdef-publickeycredentialcreationoptions) to allow RP's to annotate a credential for the management interfaces to then expose to users for the user's ease of management?

Here are examples of places that "`note`" could go:

**1Password ("notes"):**
![Screenshot 2023-02-13 at 6 15 44 PM](https://user-images.githubusercontent.com/5166470/218623136-c25e018c-6662-4d88-b90d-6fd66d42cfad.png)

**Safari ("Notes"):**
![Screenshot 2023-02-13 at 6 29 01 PM](https://user-images.githubusercontent.com/5166470/218623469-e9fc11e3-ea68-43d4-b190-c9f9e14570e4.png)

![Screenshot 2023-02-13 at 6 29 22 PM](https://user-images.githubusercontent.com/5166470/218623480-1290fdf3-1026-41a0-86c5-b97f286bad52.png)

This feels beneficial to both RP's and end users.

**Comment by Firstyear** [comment]
Would the note be embedded in the resident key itself though? How will this work for yubikeys? 

Feels a lot more like this is a specific notes field for passkeys that are managed by platforms.

**Comment by MasterKale** [comment]
> Would the note be embedded in the resident key itself though?
Perhaps it's more of a "client note", and leave it up to clients to handle maintaining a note for a given credential ID? The spec could add the value and suggest how clients might benefit from it, then leave the synchronization up to the clients like how we do with passkeys backup.

> How will this work for yubikeys?
A "client note" model would potentially work for Yubikeys too.

**Comment by ve7jtb** [comment]
We have two fields now, and from the looks of it only one is being displayed.

We should try to get some consistency with what RP are sending and User agents are displaying before adding another field that won't be displayed.

If what is currently displayed is displayname then having the name be "mmiler@beta_environment" would be what was originally intended.   The name field is the name of the account to display to the user in whatever format the RP wants.

I suspect this is an education problem along with the platforms not showing the info.

**Comment by james-d-elliott** [comment]
Yeah by my reading of the following section this is the intent of the `displayName`: https://www.w3.org/TR/webauthn-2/#dom-publickeycredentialuserentity-displayname

> A [human-palatable](https://www.w3.org/TR/webauthn-2/#human-palatability) name for the user account, intended only for display. For example, "Alex Müller" or "田中倫". The [Relying Party](https://www.w3.org/TR/webauthn-2/#relying-party) SHOULD let the user choose this, and SHOULD NOT restrict the choice more than necessary.

**Comment by MasterKale** [comment]
> If what is currently displayed is displayname then having the name be "mmiler@beta_environment" would be what was originally intended.

[`displayName`](https://www.w3.org/TR/webauthn-2/#dom-publickeycredentialuserentity-displayname) doesn't read like the kind of value that'd look like "mmiller@beta_environment". The name examples in the spec constrains thoughts of what are appropriate values for this field to "full name" representations of the user. Perhaps there's a chance here to expand the examples to denote this could be used for my "Beta Environment" example.

> A [human-palatable](https://www.w3.org/TR/webauthn-2/#human-palatability) name for the user account, intended only for display. For example, "Alex Müller" or "田中倫". The [Relying Party](https://www.w3.org/TR/webauthn-2/#relying-party) SHOULD let the user choose this, and SHOULD NOT restrict the choice more than necessary.

[PublicKeyCredentialUserEntity](https://www.w3.org/TR/webauthn-2/#dictdef-publickeycredentialuserentity)'s [`name`](https://www.w3.org/TR/webauthn-2/#dom-publickeycredentialentity-name) property seems similar, too - this field seems like it'd be where the user's email address might go:

> The name field is the name of the account to display to the user in whatever format the RP wants.

So if we wanted to encourage full use of `PublicKeyCredentialUserEntity`, perhaps we can clarify these two further with example use cases to satisfy my proposal.

**Comment by MasterKale** [comment]
It turns out both Chrome and Safari use `user.name` when displaying passkeys:

**Chrome:**
![Screenshot 2023-02-13 at 7 31 56 PM](https://user-images.githubusercontent.com/5166470/218632554-62774e4b-ccf4-48f4-a0f0-793169315dd3.png)
![Screenshot 2023-02-13 at 7 32 42 PM](https://user-images.githubusercontent.com/5166470/218632561-2a507992-9c40-4126-8d5c-20c7a66eee03.png)



**Safari:**
![Screenshot 2023-02-13 at 7 33 07 PM](https://user-images.githubusercontent.com/5166470/218632534-55f99c26-a81c-4bb9-846d-b32897821075.png)
![Screenshot 2023-02-13 at 7 33 26 PM](https://user-images.githubusercontent.com/5166470/218632542-8acc6c74-8ef5-4e68-aea8-1f2cfde63f84.png)

**Comment by emlun** [comment]
I would be in favour of adding a few examples showing these use cases for `user.displayName` and/or `user.name`. There's no reason `user.name` would have to be the account's primary email address (if any), it could easily accommodate something like `mmiller (FooBank via AcmeIAM)` if the RP has several distinct namespaces (like some IAM services do). I guess we just hadn't considered that use case much, so the examples are a bit lacking.

Maybe we should also add a symmetric mention of "determining the difference" to `displayName` - the `name` description currently reads:

>[...] It is intended only for display, i.e., aiding the user in determining the difference between user accounts with similar [displayName](https://w3c.github.io/webauthn/#dom-publickeycredentialuserentity-displayname)s. [...]

but `displayName` does not have a similar mention of disambiguating similar `name`s. There's really not much reason either should be more or less likely to be similar between credentials.

**Comment by james-d-elliott** [comment]
I think clarifying several of these parameters and their use cases may be helpful. For example another similar attribute that may be used is the PublicKeyCredentialEntity's `name` value: https://w3c.github.io/webauthn/#dom-publickeycredentialentity-name

It also is meant to be human-palatable and may be chosen by the end user. In the context of this issue maybe this one mentioned is more applicable as it's more closely related to the actual credential itself?

**Comment by MasterKale** [comment]
> I think clarifying several of these parameters and their use cases may be helpful. For example another similar attribute that may be used is the PublicKeyCredentialEntity's `name` value: https://w3c.github.io/webauthn/#dom-publickeycredentialentity-name

In the screenshots above this is what I meant by "`user.name`", it's this property that is currently used to help convey information about who a credential belongs to.

**Comment by james-d-elliott** [comment]
Yeah I've completely misunderstood the spec in this area, both `user.name` and `user.displayName` are specific to the WebAuthn User Account, not the individual credential itself. It actually makes quite a lot of sense that a specific WebAuthn User Account may have multiple credentials and that something exists to clearly differentiate them in those circumstances.

**Comment by MasterKale** [comment]
There's been clarification that `user.name` can be arbitrary strings, not necessarily only email or user name. `user.displayName` _may_ be supported in certain clients and OS's, but by and large RP's should only count on `user.name` being regularly shown to users.
