### ISSUE TITLE
Redundant step 6 in DPK verification for authentication

### ISSUE THREAD

**Issue by ndpar** [w3c/webauthn#1853]
Step 6 in [10.2.2.3.2. Authentication (get())](https://w3c.github.io/webauthn/#sctn-device-publickey-extension-verification-get) says "Otherwise, the Relying Party does not have..."

It is not clear what "otherwise" in this case means. Step 5 seems to exhaust all the cases of `matchedDpkRecords` defined in Step 4, therefore Step 6 either is redundant or requires clarification in relation to `matchedDpkRecords`.

**Comment by emlun** [comment]
Good catch, thanks! I think you're right that step 6 is redundant. It used to be the "else" part of an "if-else" conditional, and the cases now listed in step 5 used to apply only within the "if" branch of that, so step 6 was needed for the "else" branch. But the "if-else" branching was eliminated in commit [`b92973ce`](https://github.com/w3c/webauthn/commit/b92973ce420c763fc8a4f489a393d4067e5f88b5#diff-5e793325cd2bfc452e268a4aa2f02b4024dd9584bd1db3c2595f61f1ecf7b985L7131), so step 6 should not be needed anymore.

**Comment by emlun** [comment]
@agl Can you confirm that step 6 is redundant now and can be deleted?

**Comment by agl** [comment]
> @agl Can you confirm that step 6 is redundant now and can be deleted?

It's step 7 that should be deleted, no? But yes, sorry, I got lost there and it's clearly redundant. I'll do a PR.

**Comment by ndpar** [comment]
While we are in this place of the spec, a couple of things about this paragraph

> Otherwise there is some form of error: we recieved a known dpk value, but one or more of the accompanying aaguid, scope, or fmt values did not match what the Relying Party has stored along with that dpk value. Terminate these verification steps.

1. "or fmt" seems to be wrong here, because _matchedDpkRecords_ was built using only _aaguid_, _dpk_, and _scope_ for equality. The difference in _fmt_ is covered in the preceding  paragraph.
2. It is implied here that during the lifetime of the DPK neither _aaguid_ or _scope_ can change. It is beneficial, I think, to state it explicitly somewhere (my apology if it is and I missed it). Otherwise it is reasonable for an RP to assume that after some platform authenticator update (and maybe certification) the _aaguid_ can change for the existing DPK.

**Comment by emlun** [comment]
> * "or fmt" seems to be wrong here, because _matchedDpkRecords_ was built using only _aaguid_, _dpk_, and _scope_ for equality. The difference in _fmt_ is covered in the preceding  paragraph.

You're right, the matching and the "Otherwise" description went out of sync in commit 5af393d40ff4275a343cb7b7cec19ac6876045be. I'll add this fix to PR #1858.


> 2\. It is implied here that during the lifetime of the DPK neither _aaguid_ or _scope_ can change. It is beneficial, I think, to state it explicitly somewhere (my apology if it is and I missed it). Otherwise it is reasonable for an RP to assume that after some platform authenticator update (and maybe certification) the _aaguid_ can change for the existing DPK.

I think most would expect that `aaguid` won't change since that is the case for top-level credentials, so I don't think that needs to be called out more explicitly than the verification steps make it. I would expect `scope` to be an immutable credential property as well, but I could see a case for adding some mention of this in the CDDL comments defining `attObjForDevicePublicKey`. But I also think it is unambiguous enough as is. @agl thoughts on this?
