### ISSUE TITLE
Should timeout recommendations for clients be updated to cater for conditional mediation?

### ISSUE THREAD

**Issue by sbweeden** [w3c/webauthn#1908]
## Proposed Change

I was searching through the webauthn L3 draft for "timeout" and noticed the recommendations for clients in https://www.w3.org/TR/webauthn-3/#sctn-getAssertion

They mention 2 minutes recommended for uv=discouraged, and 5 minutes for uv=preferred_or_required

Should these be updated in consideration of the use of conditional mediation?

**Comment by agl** [comment]
(Timeouts don’t apply to conditional requests.)

**Comment by sbweeden** [comment]
Fair enough - I guess it can be closed, and is more a reflection on how the server-side validity of the challenge should be treated.

**Comment by Kieun** [comment]
@sbweeden recently, the recommend timeouts are adjusted to 5 mins regardless of user verification. See #1886.

Regarding timeout for conditional mediation is still under discussion, #1848.
