### ISSUE TITLE
Revisit description of userHandle

### ISSUE THREAD

**Issue by sbweeden** [w3c/webauthn#1909]
## Proposed Change

I may be way off base here, but I feel there is something incorrect about the way we currently describe userHandle.

The [current description of userHandle](https://w3c.github.io/webauthn/#user-handle) suggests:

```
The main use of the user handle is to identify the user account in such authentication ceremonies, but the credential ID could be used instead.
```

I don't think this is true. I think the main use of the user handle is to _allow authenticators to decide when to replace a discoverable credential they already have with a new one during navigator.credentials.create_.

An RP cannot trust userHandle during assertion flows as it is not signed. Only the credentialID is signed. ~Therefore the RP SHOULD use the credentialID to lookup a public key for signature validation and associated user account.~ (Edited: I no longer agree with using the RPID+credentialID as the best way to lookup an account - see discussion below). The user handle can then be verified to be correct as described in step 6 of section 7.2 ([Verifying an Authentication Assertion](https://w3c.github.io/webauthn/#sctn-verifying-assertion)).

**Comment by sbweeden** [comment]
I realise after writing this that I was originally still looking at an [old definition of step 6 of section 7.2](https://www.w3.org/TR/webauthn-3/#sctn-verifying-assertion) and that under the new definition of that step the userHandle can be used to lookup an account then it is required that the credentialID also be matched to that account, which is ok.

I do have some lingering concerns over allowing the user/client to initiate account lookups based on an injected userHandle, but don't have a concrete reason as to why that's a terrible thing to do just yet.

**Comment by Kieun** [comment]
Is this related to #1892?

@sbweeden Your proposal seems that `userhandle` doesn't need to be passed to the RP to identify the user and associated credential during `get` call.

**Comment by sbweeden** [comment]
I wasn't setting out to make that connection, but it is potentially related. Perhaps the best way to look at my concern is to ask this question:

Why *should* the userHandle be passed back to the RP during assertion flows? What practical/valuable purpose does that serve?

The purpose I've heard that makes sense is from @emlun, who suggested it could be preferred by the RP as an index into user accounts since the RP generates it rather than the authenticator. 

The alternative is to use RPID+CredentialID as the lookup index, however in thinking about this more, what would happen if two different authenticators generated the same CredentialID for the RP - unlikely, but isn't that still possible? This would make such lookup non-deterministic, and may even result in a registration failure if the RP is enforcing such uniqueness.

The more I think about it, the more I like what we already have in the L3 draft, with the possible addition of the description that the userHandle also allows the authenticator to recognize when to replace a discoverable credential during creation.

**Comment by Kieun** [comment]
> The alternative is to use RPID+CredentialID as the lookup index, however in thinking about this more, what would happen if two different authenticators generated the same CredentialID for the RP (for different users) - unlikely, but isn't that still possible?

When registering a new credential in the storage, RP needs to check whether the credential id is duplicated or not, if it is duplicated, the RP SHOULD reject registration with the credential Ids.

See step 25 in [Registering a New Credential section](https://w3c.github.io/webauthn/#sctn-registering-a-new-credential).

> Verify that the [credentialId](https://w3c.github.io/webauthn/#authdata-attestedcredentialdata-credentialid) is not yet registered for any user. If the [credentialId](https://w3c.github.io/webauthn/#authdata-attestedcredentialdata-credentialid) is already known then the [Relying Party](https://w3c.github.io/webauthn/#relying-party) SHOULD fail this [registration ceremony](https://w3c.github.io/webauthn/#registration-ceremony).

The spec does not mandate for RPs to reject such duplicated credential Ids, so, if the RP policy does accept the duplicated credential id among different user accounts and without `userHandle`, the RP cannot identify the credential owners if any other user has a credential with same credential id.

**Comment by emlun** [comment]
> Why _should_ the userHandle be passed back to the RP during assertion flows? What practical/valuable purpose does that serve?

I asked the same question back when this was introduced: https://github.com/w3c/webauthn/pull/558#issuecomment-329753114 and that is also where I first heard the argument I now relayed to @sbweeden: https://github.com/w3c/webauthn/pull/558#issuecomment-330317134

**Comment by emlun** [comment]
> The more I think about it, the more I like what we already have in the L3 draft, with the possible addition of the description that the userHandle also allows the authenticator to recognize when to replace a discoverable credential during creation.

This is also mentioned in the [User Handle definition](https://w3c.github.io/webauthn/#user-handle):

>[...]
>[Authenticators](https://w3c.github.io/webauthn/#authenticator) [map](https://w3c.github.io/webauthn/#authenticator-credentials-map) pairs of [RP ID](https://w3c.github.io/webauthn/#rp-id) and [user handle](https://w3c.github.io/webauthn/#user-handle) to [public key credential sources](https://w3c.github.io/webauthn/#public-key-credential-source). As a consequence, an authenticator will store at most one [discoverable credential](https://w3c.github.io/webauthn/#discoverable-credential) per [user handle](https://w3c.github.io/webauthn/#user-handle) per [Relying Party](https://w3c.github.io/webauthn/#relying-party).
>[...]

Should we make that clearer or more prominent?

**Comment by MasterKale** [comment]
A continuing "issue" with `userHandle` is that it remains non-required even in the draft of L3:

https://w3c.github.io/webauthn/#dictdef-authenticatorassertionresponsejson

From an RP's perspective this means that even if we want to leverage `userHandle` during auth we have to build our auth system to fall back to internally identifying the user solely by credential ID. And at that point it seems architecturally cleaner to just forego using `userHandle` at all.

> Should we make that clearer or more prominent?

I think maybe we emphasize this as the primary benefit of `userHandle`. Its use by RP's for supporting "duplicate credential ID's for multiple user accounts because of cosmic bad luck" is probably not as compelling a use case in 2023.

**Comment by arianvp** [comment]
The spec also says:

> [Discoverable credentials](https://w3c.github.io/webauthn/#discoverable-credential) store this identifier and return it as [response](https://w3c.github.io/webauthn/#dom-publickeycredential-response).[userHandle](https://w3c.github.io/webauthn/#dom-authenticatorassertionresponse-userhandle) in [authentication ceremonies](https://w3c.github.io/webauthn/#authentication-ceremony) started with an [empty](https://infra.spec.whatwg.org/#list-empty) [allowCredentials](https://w3c.github.io/webauthn/#dom-publickeycredentialrequestoptions-allowcredentials) argument.

Which kind of implies that a Discoverable credential should return `userHandle`

It makes sense that it is non-required in the `authenticatorAssertionResponse` as non-discoverable credentials can not return a `userHandle`

**Comment by emlun** [comment]
> A continuing "issue" with `userHandle` is that it remains non-required even in the draft of L3:

> We can make the spec more clear maybe. But I think "Discoverable Credentials return `userHandle` when `allowedCredentials` is empty" is something that the spec currently (kind of in a round-about way) mandates

See also issue #1892. Thanks @arianvp, looks like we might need to bring the formal authenticatorGetAssertion algorithm more in line with the User Handle description in your quote.
