### ISSUE TITLE
Misaligned steps in Section 7.2

### ISSUE THREAD

**Issue by ndpar** [w3c/webauthn#1913]
Steps 7.2.7 and 7.2.8 disappeared from the [latest version](https://w3c.github.io/webauthn/#sctn-verifying-assertion). The remained steps shifted by 2.

**Comment by emlun** [comment]
Huh. Looks like Bikeshed is counting the [switch cases](https://github.com/w3c/webauthn/blob/6dfbdbaad8425140030afacb7de27eb13e7872ce/index.bs#L5452-L5465) as if they were in the parent numbered list - I confirmed this locally by adding a third switch case, and indeed the number of the next step increased to 9. This seems like a bug in Bikeshed?

**Comment by agl** [comment]
@agl to file this as a crbug and ask Tab.
