### ISSUE TITLE
Signaling when user credentials are shared between users to the `relying party`

### ISSUE THREAD

**Issue by Kieun** [w3c/webauthn#1922]
## Description

Some of passkey providers have been providing credential sharing between multiple users. RPs (or enterprise) might have some controls to allow or disallow credential sharing.
Such controls are varying across passkey providers and sometimes RPs might not be aware that user's credential has been shared to others.

Some RPs would like to know such things in order to score the security risk.

I'm thinking that this could be offered as following options.

- Option 1: mark the credential is shared when returning attestation or assertion within the `authData` (might be `flag`)
- Option 2: leverage `well-known URL` at relying party side and send a signal at the time when the user credential is actually shared

**Comment by Firstyear** [comment]
Worth pointing out the FIDO MDS still has some data corruption issues, so it would be good to get those looked at. I have a full set of patch notes if you need @dwaite
