### ISSUE TITLE
Extension's data security on assertion

### ISSUE THREAD

**Issue by BeetLab** [w3c/webauthn#1940]
## Proposed Change

Hi everyone!

I've read different specs on Passkeys topic and found lack of security considerations about the following.

Assume there's a web-browser asking user to authenticate with existing credentials using QR code. The user scans QR with their's mobile phone and it transfers signature as well as extensions responses to browser.
According to [FIDO Bluetooth spec](https://fidoalliance.org/specs/fido-u2f-v1.2-ps-20170411/fido-u2f-bt-protocol-v1.2-ps-20170411.html#bluetooth-pairing-client-considerations)  section " Bluetooth pairing: Client considerations":
"Bluetooth pairing is "system-wide", then any application on that device might be able to interact with an Authenticator."

Does that mean, that PRF, largeBlob (or credBlob) extensions responses can be intercepted by malware on the users laptop that running web-browser?

Thanks.

**Comment by timcappalli** [comment]
> According to [FIDO Bluetooth spec](https://fidoalliance.org/specs/fido-u2f-v1.2-ps-20170411/fido-u2f-bt-protocol-v1.2-ps-20170411.html#bluetooth-pairing-client-considerations) section " Bluetooth pairing: Client considerations":
> "Bluetooth pairing is "system-wide", then any application on that device might be able to interact with an Authenticator."

Cross-Device Authentication (hybrid) does not use BLE pairing (and does not use any part of that referenced specification). In general, if a web browser is compromised, all bets are off.

Please use [FIDO-DEV](https://groups.google.com/a/fidoalliance.org/g/fido-dev) or [Passkeys Discussion](https://github.com/passkeydeveloper/discussions/discussions) for questions. This repo is for specification work.
