### ISSUE TITLE
PublicKeyCredentialJSON is an invalid WebIDL construct

### ISSUE THREAD

**Issue by petervanderbeken** [w3c/webauthn#1958]
```
typedef (RegistrationResponseJSON or AuthenticationResponseJSON) PublicKeyCredentialJSON;
```
is invalid WebIDL. [`RegistrationResponseJSON`](https://w3c.github.io/webauthn/#dictdef-registrationresponsejson) and [`AuthenticationResponseJSON`](https://w3c.github.io/webauthn/#dictdef-authenticationresponsejson) are both dictionaries and thus not [distinguishable](https://webidl.spec.whatwg.org/#dfn-distinguishable), and WebIDL [unions](https://webidl.spec.whatwg.org/#dfn-union-type) require each pair of flattened members in a union to be distinguishable.

Replacing `PublicKeyCredentialJSON` with `object` would work (with prose describing it's either `RegistrationResponseJSON` and `AuthenticationResponseJSON`), or there might be a solution with merging `RegistrationResponseJSON` and `AuthenticationResponseJSON` into one dictionary type somehow (would probably require some creativity with required/optional members in various dictionaries).

**Comment by MasterKale** [comment]
Thanks for pointing this out. WebIDL is so tricky to get right 😅 

> Replacing `PublicKeyCredentialJSON` with `object` would work (with prose describing it's either `RegistrationResponseJSON` and `AuthenticationResponseJSON`)

I can submit a PR that aims to take things this direction. I'd hate to have to mash up everything into a single dictionary as I think it'd be quite messy for RP's to work with.

**Comment by arianvp** [comment]
I actually found the union awkward when translating this to go. These are the types my RP uses in Go. Perhaps we can use it as inspiration for the IDL

```go
type PublicKeyCredential struct {
	ID                      Base64URLString                       `json:"id"`
	AuthenticatorAttachment string                                `json:"authenticatorAttachment"`
	ClientExtensionResults  AuthenticationExtensionsClientOutputs `json:"clientExtensionResults"`
	Type                    string                                `json:"type"`
	Response                Response                              `json:"response"`
}

type Response struct {
	AuthenticatorAttestationResponse
	AuthenticatorAssertionResponse

	ClientData        Base64URLString `json:"clientDataJSON"`
	AuthenticatorData Base64URLString `json:"authenticatorData"`
}
```

```go
type AuthenticatorAttestationResponse struct {
	AttestationObject  Base64URLString `json:"attestationObject"`
	Transports         []string        `json:"transports"`
	PublicKey          Base64URLString `json:"publicKey"`
	PublicKeyAlgorithm string          `json:"publicKeyAlgorithm"`
}

type AuthenticatorAssertionResponse struct {
	Signature  Base64URLString  `json:"signature"`
	UserHandle *Base64URLString `json:"userHandle"`
}
```
