### ISSUE TITLE
Remove the [SameObject] attribute from PublicKeyCredential::authenticatorAttachment

### ISSUE THREAD

**Issue by jschanck** [w3c/webauthn#1977]
The WebIDL standard says
> The [[SameObject](https://webidl.spec.whatwg.org/#SameObject)] extended attribute must not be used on anything other than a [read only](https://webidl.spec.whatwg.org/#dfn-read-only) [attribute](https://webidl.spec.whatwg.org/#dfn-attribute) whose type is an [interface type](https://webidl.spec.whatwg.org/#idl-interface) or [object](https://webidl.spec.whatwg.org/#idl-object).

The `authenticatorAttachment` field of `PublicKeyCredential` is a nullable [DOMString](https://webidl.spec.whatwg.org/#idl-DOMString) which is neither an interface type nor an object.

## Proposed Change

Remove `[SameObject]` from
https://github.com/w3c/webauthn/blob/baf774ade7f70efe4fb2a361e50d618e1f956ff1/index.bs#L1524

**Comment by emlun** [comment]
Good catch, thanks!
