### ISSUE TITLE
Deprecation warning for fido-u2f, apple, and android-safetynet?

### ISSUE THREAD

**Issue by vanbukin** [w3c/webauthn#1989]
`fido-u2f`: [Google Chrome, Edge, Firefox no longer supports U2F](https://developer.chrome.com/blog/deps-rems-95/#deprecate-u2f-api-cryptotoken)

`apple`: [Apple has moved to Passkeys starting from iOS 16 and no longer provides an Attestation Statement (to be precise - returns 'none')](https://developer.apple.com/videos/play/wwdc2022/10092/?time=1211)

`android-safetynet`: [Google has announced the deprecation of SafetyNet Attestation.](https://developer.android.com/privacy-and-security/safetynet/deprecation-timeline)

----
Perhaps it would be worthwhile to add notes to the specification about certain Attestation Statement Formats either not being supported from specific browser versions, or discontinuing support in the future (as is the case with SafetyNet).

This would be a good support when implementing libraries for WebAuthn. So that those who develop them would not spend effort supporting something that is either used by a very small percentage of the audience, or not used at all.

**Comment by emlun** [comment]
`fido-u2f` attestation is not deprecated, it will always continue to be used by U2F security keys from before the release of FIDO2. The deprecation of the U2F JavaScript API has no effect on this; these security keys still remain compatible with the WebAuthn API (though not all features, like User Verification and discoverable keys).

I don't know about the other formats, though.

**Comment by vanbukin** [comment]
@emlun Yes, you are correct about `fido-u2f`. I apologize if it was misleading. However, as far as I understand, for `fido-u2f` there will be no `userHandle`, which is mandatory for the usernameless sign-in scenario (If the user was not identified before the authentication ceremony was initiated). Perhaps this point is worth mentioning.

**Comment by emlun** [comment]
This is mentioned in [§2.2.1. Backwards Compatibility with FIDO U2F](https://w3c.github.io/webauthn/#sctn-conforming-authenticators-u2f), and implied by the description of [`PublicKeyCredential.response.userHandle`](https://w3c.github.io/webauthn/#dom-authenticatorassertionresponse-userhandle):

>[...] The authenticator MUST always return a [user handle](https://w3c.github.io/webauthn/#user-handle) if the [allowCredentials](https://w3c.github.io/webauthn/#dom-publickeycredentialrequestoptions-allowcredentials) option used in the [authentication ceremony](https://w3c.github.io/webauthn/#authentication-ceremony) is [empty](https://infra.spec.whatwg.org/#list-is-empty), and MAY return one otherwise.

Since U2F authenticators must always be used with non-empty `allowCredentials`, this implies that they always MAY (and in fact always do) return `userHandle: null`.

**Comment by vanbukin** [comment]
Apologies, for `fido-u2f` there indeed are instructions about the nuances of its operation. Thank you for the clarification. And what about `apple` and `android-safetynet`? Is it suitable to mention deprecation for them?

**Comment by emlun** [comment]
2023-10-25 WG call: Apple reports they are not comfortable with calling `apple` attestation deprecated at this time. Google confirms that SafetyNet attestation is deprecated, but judging by the deprecation timeline, SafetyNet attestation will still be supported in some form until January 2025. The WG feels we should not make any change to the spec so long as the attestation format is being produced by authenticators. We hope to release L3 of the spec well before January 2025 (the [WG charter ends in April 2024](https://www.w3.org/2022/04/webauthn-wg-charter.html)), so we will not make any change for this in L3.
