### ISSUE TITLE
How is an RP to know if a packed attestation root certificate is used for multiple authenticator models?

### ISSUE THREAD

**Issue by sbweeden** [w3c/webauthn#1998]
Consider the current text at: https://www.w3.org/TR/webauthn-3/#sctn-packed-attestation-cert-requirements

This suggests that the packed attestation certificate cert OID extension 1.3.6.1.4.1.45724.1.1.4 is compulsory, but only if the root CA is used for multiple authenticator models. How is an RP supposed to know if it is or it isn't used for multiple authenticator models such that it can *conditionally* enforce this requirement?

Is there anything in MDS to indicate this condition?
Is an RP supposed to lookup the MDS (by aaguid), then find the matching root CA entry from attestationRootCertificates, then scan all other known MDS to see if any others contain the same root CA (seems like extraordinary overkill, and subject to errors).

If this cert OID extension is really always required for packed attestation certificates, then we should say that, otherwise it should be marked optional, and there seems little value in requiring validation of its contents against the AAGUID in authenticatorData.

**Comment by emlun** [comment]
I've interpreted this requirement to be a (mostly unenforceable, as you point out) requirement on authenticator vendors. I agree that it's not enforceable by anything other than a certification procedure, with the authenticator vendor honestly documenting its production processes to the certification body.

I think it's worthwhile to have this as a normative expectation stated in the spec, but I agree it's a bit misleading that the `packed` verification procedure includes the step "Verify that _attestnCert_ meets the requirements in [§ 8.2.1 Packed Attestation Statement Certificate Requirements](https://www.w3.org/TR/webauthn-3/#sctn-packed-attestation-cert-requirements)", and this being one of the requirements in that section.

Although on the other hand, the next step of the verification procedure is:

>- If _attestnCert_ contains an extension with OID 1.3.6.1.4.1.45724.1.1.4 (id-fido-gen-ce-aaguid) verify that the value of this extension matches the [aaguid](https://www.w3.org/TR/webauthn-3/#authdata-attestedcredentialdata-aaguid) in _authenticatorData_.

So I guess one could also argue that that implies the RP doesn't need to verify the "If the related attestation root certificate is used for multiple authenticator models" part?
