### ISSUE TITLE
Wrong type of encrypted content specified for credentialId under "Credential Storage Modality" section

### ISSUE THREAD

**Issue by sylph01** [w3c/webauthn#2002]
## Problem Description

In "6.2.2. Credential Storage Modality", the current version says

> By encrypting (i.e., wrapping) the [credential private key](https://www.w3.org/TR/webauthn-2/#credential-private-key) such that only this [authenticator](https://www.w3.org/TR/webauthn-2/#authenticator) can decrypt (i.e., unwrap) it

but as per 7.5 of "6.3.2. The authenticatorMakeCredential Operation", 

> Otherwise:
> Let credentialId be the result of serializing and encrypting credentialSource so that only this authenticator can decrypt it.

so, it is not (just) the credential private key that is being encrypted, but it is rather the serialized public key credential source. 

## Proposed Change

before: 

> By encrypting (i.e., wrapping) the [credential private key](https://www.w3.org/TR/webauthn-2/#credential-private-key) such that only this [authenticator](https://www.w3.org/TR/webauthn-2/#authenticator) can decrypt (i.e., unwrap) it

after: 

> By encrypting (i.e., wrapping) the [public key credential source](https://www.w3.org/TR/webauthn-2/#public-key-credential-source) such that only this [authenticator](https://www.w3.org/TR/webauthn-2/#authenticator) can decrypt (i.e., unwrap) it

**Comment by emlun** [comment]
Thanks for the report!
