### ISSUE TITLE
Consider replacing "Github" with "GitHub"

### ISSUE THREAD

**Issue by TylerJMorg** [w3c/webauthn#2007]
## Proposed Change

For context, the following excerpt in the _Status of this Document_ section currently reads as follows:
> Please use [Github issues](https://github.com/w3c/webauthn/issues).

I'd recommend to capitalize the _h_ in _Github_ to read as follows:
> Please use [GitHub issues](https://github.com/w3c/webauthn/issues).

This is quite a small change but may be useful for the sake of consistency. This lowercase _h_ in GitHub is only found in this section, no where else. Both in the current [working draft](https://www.w3.org/TR/2023/WD-webauthn-3-20230927/) (2023-09-27) and in the current [editor's draft](https://w3c.github.io/webauthn/) (2023-12-13).

Let me know if you have any questions.

Many thanks!

**Comment by arianvp** [comment]
It's a single letter change. Sounds less effort to send a PR for this than to have written this entire issue 😅

**Comment by TylerJMorg** [comment]
I probably should lol. I knew this issue would be laughably minute change. 🥲
