### ISSUE TITLE
Section 13.1 makes confusing statement saying `CredentialID` is unsigned, where it's actually signed in some cases.

### ISSUE THREAD

**Issue by dannyniu** [w3c/webauthn#2028]
`CredentialID` is signed during `authenticatorMakeCredential` (sect 6.3.2), as part of `attestedCredentialData` in `authenticatorData`.

## Proposed Change

Change the title of section 13.1. to: "Credential ID Unsigned During The authenticatorGetAssertion Operation".

**Comment by emlun** [comment]
Thanks! Would PR #2029 suffice to make this clearer?

**Comment by dannyniu** [comment]
@emlun Yes it does.
