### ISSUE TITLE
The standard is very web-centric, can be a bit confusing for app-only users

### ISSUE THREAD

**Issue by JetForMe** [w3c/webauthn#2048]
I'm not sure if this is actually a limitation of the spec, or a keychain implementation like Apple’s.

I recently implemented WebAuthn registration and authentication for my iOS app. The app is the only UI (there is no webapp), but it does have a server component. Stored passkeys are listed like this, but I'd rather instead of showing “latencyzero.com” (the effective domain) or “chargeminder.latencyzero.com” (the RP url), it showed the domain name as “Latency: Zero, LLC” and the app name as “ChargeMinder.” I don’t think the spec allows for a “display name ” for the effective domain or RP ID, does it? Or is Apple displaying the wrong thing(s) here?

In any case, this is confusing for the user, because my company name isn't strongly branded in the app. I’ve raised this issue with Apple, too.

![iOSPasskeyDisplay](https://github.com/w3c/webauthn/assets/401600/3d06ed18-af90-4d6a-99e4-8382ee946832)

**Comment by timcappalli** [comment]
This implementation is correct.

All WebAuthn credentials are scoped to a web origin. The Web Authentication specification only defines a Web Platform API. Native apps use OS-level abstractions of WebAuthn, defined by each app platform (e.g. OS). Those app platforms also handle mapping app identifies to web origins, typically using a well-known URL type construct.

How WebAuthn clients and authenticators display app-platform specific metadata (such as an app name or publisher) are out of scope for the Web Authentication specification.

**Comment by JetForMe** [comment]
I agree that the spec shouldn't dictate how the client displays the information. And forgive me, I’m not 100% sure I understand the nuances of the spec, especially since I'm using a third-party library to handle the lower-level details, like signing and verifying, parsing the attestations, etc.

But as far as I can tell, the spec doesn't formalize the notion of a Relying Party Display Name. I think if it did, it could encourage implementations to use that when displaying information about credentials to the user.

**Comment by timcappalli** [comment]
The spec does have an RP name option: https://www.w3.org/TR/webauthn-2/#dom-publickeycredentialentity-name

Many clients and authenticators do not use it, likely because it is a freeform value. Using just the RP ID has been the status quo for many years. 

I'd recommend giving feedback to client and authenticator vendors directly.

**Comment by JetForMe** [comment]
Oh, excellent, thank you! And I did share feedback with Apple (FB13697058). I'll add that information to it.

**Comment by boogerlad** [comment]
> Many clients and authenticators do not use [RP name]

out of curiousity, what clients and authenticators use RP name?
