### ISSUE TITLE
Credential ID not signed

### ISSUE THREAD

**Issue by yaronf** [w3c/webauthn#206]
5.1.2: "The identifier of the credential used to generate the signature" is returned to the client, but AFAICT it is not actually signed. I'm not sure there's a direct vulnerability because of that, but I think including the ID in the signed material is a best practice.

@vijaybh: Good point. I do not see an attack either, or at least no attack that does not also require the signature scheme to be broken in the first place. Interesting discussion point though.

**Comment by AngeloKai** [comment]
I cannot foresee an attack surface based solely on knowing the credential ID either. Credential IDs were designed to be anonymous so that an attacker cannot attack without cracking down the signature scheme first. Should we consider this issue closed?

**Comment by equalsJeffH** [comment]
the spec has evolved such that the Credential ID is part of the attestation data (regardless of attestation format) within the authenticator data, which is signed over.  see 'figure 2' and [figure 3](https://w3c.github.io/webauthn/#fig-attStructs).  closing this issue.
