### ISSUE TITLE
Authenticator data flags reserved bits must be 0 or the figures would ideally be changed

### ISSUE THREAD

**Issue by zacknewman** [w3c/webauthn#2063]
According to [`flags`](https://www.w3.org/TR/webauthn-3/#authdata-flags), bits 1 and 5 are "reserved for future use" without any requirement they are 0; however [Figure 3](https://www.w3.org/TR/webauthn-3/#fig-authData) and [Figure 6](https://www.w3.org/TR/webauthn-3/#attestation-object) display those bits as 0. Are implementations expected to simply ignore those bits the way `flags` says; or are implementations supposed to ensure the bits are 0 as illustrated by the figures? Regardless of the answer, it would be nice if the spec were changed to make the figures and `flags` documentation align better. Specifically, if the bits must be 0, then `flags` should state that; otherwise the figures would ideally be updated to not explicitly show 0 (e.g., `X` or `0|1`).

**Comment by emlun** [comment]
It is defined under "[**Authenticators perform the following steps to generate an authenticator data structure**](https://www.w3.org/TR/webauthn-3/#authenticator-data-perform-the-following-steps-to-generate-an-authenticator-data-structure)" that:

>- The [UP](https://www.w3.org/TR/webauthn-3/#authdata-flags-up) [flag](https://www.w3.org/TR/webauthn-3/#authdata-flags) SHALL be set if and only if [...]. The RFU bits SHALL be set to zero.

However, the [RP Operations](https://www.w3.org/TR/webauthn-3/#sctn-rp-operations) procedures do not instruct to enforce that the flags be zero. Doing so would make any compliant RP implementations incompatible with future changes that allocate these flags to be used, like we have done in L3 with the BE and BS flags.

**Comment by james-d-elliott** [comment]
It may be worth adding a small `It's RECOMMENDED that RP's do not verify the unused flags as future implementations MAY use them.`.
