### ISSUE TITLE
Resident key removal

### ISSUE THREAD

**Issue by erionpc** [w3c/webauthn#2070]
## Description

It would be great if key removal was part of the WebAuthN spec. In the same way that you can currently create and assert you should also be able to remove a key. This would complete a missing piece of the API which would help with better management of device keys. 

## Related Links
https://www.w3.org/TR/webauthn-2/#sctn-sample-decommissioning

_PS: Apologies if another feature request has already been raised for this. I couldn't find another one._

**Comment by emlun** [comment]
Hi! The plan is for the [WebAuthn Report API](https://github.com/w3c/webauthn/wiki/Explainer:-WebAuthn-Report-API-explainer) to cover this. This is tracked in issue #1967. See also: #2038, #2067
