### ISSUE TITLE
Does WebAuthn supports User-Verifying Roaming Authenticators

### ISSUE THREAD

**Issue by chunsfire** [w3c/webauthn#2076]
## Description

As roaming authenticator specially smartphone is used for user-verification, so how would WebAuthn comes into the picture, & what should be the mechanism to register the smatphone with RP as well as interaction b/w client & smartphone.

## Related Links

**Comment by timcappalli** [comment]
This sounds like more of a general question / implementation question, not a spec issue. Please use passkeys.dev/discuss or FIDO-DEV for those types of questions.

**Comment by chunsfire** [comment]
@timcappalli Just for clarification, Does "User-Verifying Roaming Authenticators" implemented using WebAuthn?

**Comment by arianvp** [comment]
Yes it is supported. See the following table:
https://w3c.github.io/webauthn/#authenticator-type

They're called "First-factor roaming authenticator" in the spec

**Comment by chunsfire** [comment]
thanks @arianvp
