### ISSUE TITLE
How does First-factor roaming authenticator registration happens with RP (involving client)

### ISSUE THREAD

**Issue by chunsfire** [w3c/webauthn#2077]
## Description

If First-factor roaming authenticator is involved for user-presence & user-verification when a user accesses protected web-app through laptop/desktop. It first needs to register itself with the RP.

What are the steps involved in registration process b/w First-factor roaming authenticator & RP? 
Couldn't find the appropriate section for this.

## Related Links

**Comment by timcappalli** [comment]
@chunsfire as mentioned on your previous issue, please use passkeys.dev/discuss or FIDO-DEV for deployment / architectural questions. This issue tracker is for the spec itself.

**Comment by emlun** [comment]
The steps are the same as for any other kind of credential, and are described in [§7.1. Registering a New Credential](https://www.w3.org/TR/2023/WD-webauthn-3-20230927/#sctn-registering-a-new-credential).
