### ISSUE TITLE
CredentialCreationOptions/mediation not yet defined in CredMan

### ISSUE THREAD

**Issue by emlun** [w3c/webauthn#2079]
`{{CredentialCreationOptions/mediation}}` is not yet defined upstream in CredMan, so the following passage in [§5.1.3. Create a New Credential](https://w3c.github.io/webauthn/#sctn-createCredential) is currently invalid:

>By setting `options.mediation` to [conditional](https://w3c.github.io/webappsec-credential-management/#dom-credentialmediationrequirement-conditional), [Relying Parties](https://w3c.github.io/webauthn/#relying-party) can indicate that they would like to register a credential without prominent modal UI if user has already consented to create a credential. [...]

```
LINK ERROR: No 'idl' refs found for 'mediation' with for='['CredentialCreationOptions']'.
{{CredentialCreationOptions/mediation}}
```

This is blocked on https://github.com/w3c/webappsec-credential-management/issues/225 which must be resolved before we can release L3 (otherwise we'll have to revert PR #1951).

**Comment by pascoej** [comment]
https://github.com/w3c/webappsec-credential-management/issues/225 has been resolved.

**Comment by emlun** [comment]
Indeed the warning no longer occurs in my Bikeshed build (one might need to `bikeshed update` if the issue still occurs). Thanks!
