### ISSUE TITLE
Align the order of fields in PublicKeyCredentialDescriptorJSON with PublicKeyCredentialDescriptor

### ISSUE THREAD

**Issue by zacknewman** [w3c/webauthn#2082]
[`PublicKeyCredentialDescriptorJSON::id`](https://www.w3.org/TR/webauthn-3/#dom-publickeycredentialdescriptorjson-id) comes before [`PublicKeyCredentialDescriptorJSON::type`](https://www.w3.org/TR/webauthn-3/#dom-publickeycredentialdescriptorjson-type) despite [`PublicKeyCredentialDescriptor::id`](https://www.w3.org/TR/webauthn-3/#dom-publickeycredentialdescriptor-id) coming after [`PublicKeyCredentialDescriptor::type`](https://www.w3.org/TR/webauthn-3/#dom-publickeycredentialdescriptor-type).

I realize that JSON deserialization should not assume the order of fields, but it would nonetheless be nice if the order of the fields were the same. While JSON is likely almost always used during client-server communication, it is not mandatory so it's possible other data exchange formats are used that do require the order of fields to match. When implementing multiple (de)serialization formats via the help of serialization frameworks like [Serde](https://serde.rs/), it's very beneficial to agree on field order. With both the JSON and "normal" types agreeing on field order, there is no "conflict" as to which to follow.

**Comment by emlun** [comment]
Good observation, thanks!

(I first re-tagged this as editorial but then reverted that, because [WebIDL dictionaries](https://webidl.spec.whatwg.org/#idl-dictionaries) are in fact defined to be ordered)

**Comment by emlun** [comment]
(As pointed out in #2083, the order of WebIDL dictionary members is lexicographical order, not source definition order, so this actually is an editorial change since the WebIDL definitions are equivalent)

**Comment by MasterKale** [comment]
From WG Meeting (7/31): I'm aiming to get a PR to address this ready for review by next week's meeting.
