### ISSUE TITLE
Dictionary members should be ordered lexicographically per Web IDL Standard

### ISSUE THREAD

**Issue by zacknewman** [w3c/webauthn#2083]
[Per Web IDL Standard](https://webidl.spec.whatwg.org/#idl-dictionaries):

> The order of the [dictionary members](https://webidl.spec.whatwg.org/#dfn-dictionary-member) on a given dictionary is such that inherited dictionary members are ordered before non-inherited members, and the dictionary members on the one dictionary definition (including any partial dictionary definitions) are ordered lexicographically by the Unicode codepoints that comprise their identifiers.
>
> For example, with the following definitions:
> ```js
> dictionary B : A {
>   long b;
>   long a;
> };
>
> dictionary A {
>   long c;
>   long g;
> };
>
> dictionary C : B {
>   long e;
>   long f;
> };
>
> partial dictionary A {
>   long h;
>   long d;
> };
> ```
> the order of the [dictionary members](https://webidl.spec.whatwg.org/#dfn-dictionary-member) of a dictionary value of type `C` is `c`, `d`, `g`, `h`, `a`, `b`, `e`, `f`.

This means that while dictionary definitions in the spec are fine since the order of members only applies to _values_ of the dictionary, most of the payloads I have seen in the "wild" simply follow the order of the definitions. Here is an [example](https://www.w3.org/TR/webauthn-3/#example-838c9f88) in the spec itself that violates Web IDL (e.g., among other ordering issues, `authenticatorSelection` should be the first member of `publicKey`). If the dictionary definitions were ordered the way values must be ordered though, then I believe implementations will be less likely to violate the Web IDL Standard since clearly most RP library maintainers are not reading Web IDL Standard but instead follow the order of the definitions they see in the WebAuthn spec.

**Comment by emlun** [comment]
I think this order only applies to the internal dictionary representation that determines things like iteration order. I don't think it's meant to be enforced for parsing values in language bindings. I'll have to review the WebIDL spec some more before I'm sure, but I don't think there's any issue with the spec examples.

**Comment by emlun** [comment]
I'll keep #2082 open because layout consistency is good for readability even when not formally required.

> Is there any recommendation at all on the order of fields?

For how RPs should order fields in JavaScript representations of the options objects: no, order should not matter at all.

The low-level [CTAP protocol does care about serialization order](https://fidoalliance.org/specs/fido-v2.1-ps-20210615/fido-client-to-authenticator-protocol-v2.1-ps-20210615.html#ctap2-canonical-cbor-encoding-form), but that's a different protocol which is not exposed to web applications and is not defined in WebIDL.
