### ISSUE TITLE
Clarify uses of ClientData

### ISSUE THREAD

**Issue by gmandyam** [w3c/webauthn#209]
As per https://w3c.github.io/webauthn/#sec-client-data,

"The client data represents the contextual bindings of both the Relying Party and the client platform."  This implies that authenticator contextual bindings are not included in the ClientData.  Moreover, all dictionary entries listed in this section (challenge, rpId, etc.) do not represent values that are set by the authenticator.

Yet https://w3c.github.io/webauthn/#sec-android-attestation-signature defines platform-specific extensions to ClientData that are authenticator specific, which implies a contextual binding of the authenticator.

My suggestion is to prohibit such platform-specific extensions to ClientData.

**Comment by AngeloKai** [comment]
I am confused about which extension you are concerned about. The section about [Android attestation signature](https://w3c.github.io/webauthn/#sec-android-attestation-signature) is not a extension. Can you illustrate more?

**Comment by gmandyam** [comment]
Was referring to https://www.w3.org/TR/2016/WD-webauthn-20160531/#sec-android-attestation-signature.  The issue was filed before the latest WD.  It looks like the refactored attestation section eliminates platform-specific extensions to Client Data, so this issue may not be relevant anymore.

**Comment by vijaybh** [comment]
For extensions this is fixed in the current version at http://www.w3.org/TR/2016/WD-webauthn-20160928/#extension-client-processing and the attestation part is cleaned up under #244. Let's close this unless someone sees a reason why it's still relevant.

**Comment by equalsJeffH** [comment]
#244 is an issue -- so you mean it "will be" cleaned up as a part of addressing #244 ?

**Comment by gmandyam** [comment]
@vijaybh 

Sec. 4.10.1 currently (11/22/16) states "he client data represents the contextual bindings of both the Relying Party and the client platform. "  My concern is the word "platform", because it seems to open the door to platform-specific extensions to clientData, which I think we want to avoid.  Can we simplify to just "client"?
