### ISSUE TITLE
Passkey - Disable authentication with another device

### ISSUE THREAD

**Issue by BartekMilew** [w3c/webauthn#2090]
I would ask about opportunity to disable and avoid opportunity for user to authenticate with another device.
I encounter information "Sign in with another device" during authentication process and I want to prevent it from appearing. Is it possible ? If not it will be propose to implement. I see that there is option during registration only with attachment-platform

**Comment by timcappalli** [comment]
@BartekMilew this sounds like a deployment question, not a spec issue. Please use passkeys.dev/discuss or the FIDO-DEV list.

**Comment by emlun** [comment]
Related: 

- https://github.com/w3c/webauthn/issues/1688
- https://github.com/w3c/webauthn/issues/1750
- https://github.com/w3c/webauthn/issues/1714

**Comment by timcappalli** [comment]
Deployment question. Nothing actionable for the WebAuthn specification.
