### ISSUE TITLE
Add `topOrigin` to the limited verification algorithm

### ISSUE THREAD

**Issue by zacknewman** [w3c/webauthn#2102]
I rely on the [limited verification algorithm](https://www.w3.org/TR/webauthn-3/#clientdatajson-verification) for my WebAuthn RP library, but I had to amend it to validate [`topOrigin`](https://www.w3.org/TR/webauthn-3/#dom-collectedclientdata-toporigin).

Is there no way this can be added to the spec? I realize backward compatibility is likely the reason it was not added, but could there be a step mentioning optional steps? Or perhaps a section for an alternative "limited verification algorithm" that _doesn't_ guarantee backward compatibility?

In my implementation, I added sub-step 6 to step 1 and sub-step 2 (and two sub-steps of it) to step 11:

> 1\. The inputs to the algorithm are:
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;1\. A bytestring, _clientDataJSON_, that contains `clientDataJSON`— the serialized `CollectedClientData` that is to be verified.
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;⋮
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;6\. A string, _topOrigin_, that contains the expected `topOrigin` that issued the request to the user agent if _crossOrigin_ is true and if available.
> ⋮
> 11\. If _crossOrigin_ is true:
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;1. Append 0x74727565 (`true`) to _expected_.
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;2. If _topOrigin_ exists:
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;1. Append 0x2c22746f704f726967696e223a (`,"topOrigin":`) to _expected_.
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;2. Append CCDToString(`topOrigin`) to _expected_.
>12\. Otherwise, i.e. _crossOrigin_ is false:

**Comment by agl** [comment]
Obviously there's a tension around how "limited" the limited algorithm is. If it keeps gaining things it'll be no better than writing a small JSON parser!

The original motivation for it was that OpenSSH would not accept a JSON parser in their code, and I had sufficient sympathy for that to propose that we constrain the format of the client data accordingly. If this were proposed as a PR, I wouldn't have strong feelings either way, but I do worry in general that the limited form wasn't really intended for normal Web usage, and I'm not sure that we want to adopt a norm that we keep extending the algorithm to cover everything.

Could you expand on why your case both seems to be web-based, yet wants to use the limited algorithm? Is it that you look at results [like this](https://seriot.ch/projects/parsing_json.html#41) and feel that JSON is insufficiently rigorously defined for such usages? If so, I think the saving grace here is that the signature tells you, before parsing, that the JSON is as originally generated and, if the generator (i.e. browser) is trying to mess with you, you've already lost.
