### ISSUE TITLE
Rename PublicKeyCredentialHints to PublicKeyCredentialHint?

### ISSUE THREAD

**Issue by emlun** [w3c/webauthn#2112]
All the other `enum`s defined in the spec have enum names in singular:

- `AuthenticatorAttachment`
- `ResidentKeyRequirement`
- `AttestationConveyancePreference`
- `PublicKeyCredentialType`
- `AuthenticatorTransport`
- `UserVerificationRequirement`
- `ClientCapability`

`PublicKeyCredentialHints` is the only odd one out whose name is in plural. I think singular is also the better convention since values of the enum are a single value at a time, not a collection of several of the enum values.

## Proposed Change

Rename the enum `PublicKeyCredentialHints` to `PublicKeyCredentialHint`.

**Comment by timcappalli** [comment]
Makes sense to me
