### ISSUE TITLE
Make `Credential.id` a `DOMString`

### ISSUE THREAD

**Issue by zacknewman** [w3c/webauthn#2118]
[`Credential.id`](https://w3c.github.io/webappsec-credential-management/#dom-credential-id) is currently a `USVString`. I'm still a little bit confused when `DOMString` or `USVString` should be used, but several PRs have occurred converting `USVString`s to `DOMString`s. Should the same happen here?

**Comment by pascoej** [comment]
This issue would be best handled in https://github.com/w3c/webappsec-credential-management.

**Comment by emlun** [comment]
Yes, `Credential.id` is inherited from the `Credential` interface defined in the Credential Management spec.
