### ISSUE TITLE
Expand algorithm to include attestation format

### ISSUE THREAD

**Issue by leshi** [w3c/webauthn#212]
Expand algorithm to include attestation format.

RPs won't know all attestation formats and should be able to specify what type they support.  Proposed format (or something similar):

```
dictionary Algorithm {
  required sequence < AlgorithmIdentifier > publicKey
  required sequence < AttestationFormat > attestation
}

**Comment by rlin1** [comment]
We could argue that each authenticator model only supports one attestation format and hence by giving a whitelist of preferred authenticators, the RP can also achieve this goal (of transferring the preferred attestation formats).

**Comment by leshi** [comment]
But one attestation format is supported by more than one authenticator, right?  So why should I have to, as an RP, keep up to date with all of the authenticators in the market that support a certain format.   That seems really hard.  It's a lot easier to just say that I support all XXX formats and be done with it.

If I really care about whitelisting only certain authenticators, I can still do that of course.

**Comment by jcjones** [comment]
To reduce the number of incompatible combinations, what if, instead of having (`algorithm`, `attestationFormat`) such as (`ED256`, `U2F`), we instead enumerate it as `algorithm-attestationFormat`, trying them together like `ED256-U2F`?

**Comment by leshi** [comment]
After speaking with some more people, deciding that we don't need to have the server specify this for now.  There aren't that many implemented formats around... If this becomes a problem, we can always extend

```
dictionary ScopedCredentialParameters {
    required ScopedCredentialType  type;
    required AlgorithmIdentifier   algorithm;
};
```

to have an `AttestationFormat`
