### ISSUE TITLE
`options.mediation` should be called something else in step 14 of Registering a New Credential

### ISSUE THREAD

**Issue by zacknewman** [w3c/webauthn#2122]
[Registering a New Credential](https://w3c.github.io/webauthn/#sctn-registering-a-new-credential) explicitly defines _options_ in step 1 as a `PublicKeyCredentialCreationOptions`; however step 14 links _`options`_`.mediation` to [`CredentialCreationOptions.mediation`](https://w3c.github.io/webappsec-credential-management/#dom-credentialcreationoptions-mediation). While `CredentialCreationOptions` is extended with the field [`publicKey`](https://w3c.github.io/webauthn/#dom-credentialcreationoptions-publickey), that doesn't make a `PublicKeyCredentialCreationOptions` an instance of `CredentialCreationOptions` (i.e., the keys of `CredentialCreationOptions` are _not_ keys of `PublicKeyCredentialCreationOptions`).

Perhaps word it something like

> 14. Verify that the [UP](https://w3c.github.io/webauthn/#authdata-flags-up) bit of the [`flags`](https://w3c.github.io/webauthn/#authdata-flags) in _authData_ is set, unless the [`mediation`](https://w3c.github.io/webappsec-credential-management/#dom-credentialcreationoptions-mediation) related to _`options`_ is set to [`conditional`](https://w3c.github.io/webappsec-credential-management/#dom-credentialmediationrequirement-conditional).

You could of course be more verbose and define another variable, _creationOptions_, that is an instance of `CredentialCreationOptions` with `publicKey` set to _`options`_ and reference _`creationOptions`_`.mediation`.

Related to this, does step 14 mean that when `mediation` is `conditional`, the UP bit is ignored (i.e., both 0 and 1 are allowed) or that the UP bit MUST be 0? If the latter, I believe it should be better worded as I was planning to implement it such that the UP bit is simply ignored.

**Comment by emlun** [comment]
Thanks, this is directly analogous to https://github.com/w3c/webauthn/issues/1947 but for the RP operations. Fixed by #2125.

> Related to this, does step 14 mean that when `mediation` is `conditional`, the UP bit is ignored (i.e., both 0 and 1 are allowed) or that the UP bit MUST be 0? If the latter, I believe it should be better worded as I was planning to implement it such that the UP bit is simply ignored.

Does #2126 sufficiently clarify this?
