### ISSUE TITLE
Add `mediation` to `PublicKeyCredentialJSON`

### ISSUE THREAD

**Issue by zacknewman** [w3c/webauthn#2124]
[WebAuthn Relying Party Operations](https://w3c.github.io/webauthn/#sctn-rp-operations) states (emphasis added):

> Upon successful execution of [`create()`](https://w3c.github.io/webappsec-credential-management/#dom-credentialscontainer-create) or [`get()`](https://w3c.github.io/webappsec-credential-management/#dom-credentialscontainer-get), the [Relying Party](https://w3c.github.io/webauthn/#relying-party)'s script receives a [`PublicKeyCredential`](https://w3c.github.io/webauthn/#publickeycredential) containing an [`AuthenticatorAttestationResponse`](https://w3c.github.io/webauthn/#authenticatorattestationresponse) or [`AuthenticatorAssertionResponse`](https://w3c.github.io/webauthn/#authenticatorassertionresponse) structure, respectively, from the client. It must then deliver the contents of this structure to the [Relying Party](https://w3c.github.io/webauthn/#relying-party) _server_, using methods outside the scope of this specification. This section describes the operations that the [Relying Party](https://w3c.github.io/webauthn/#relying-party) must perform upon receipt of these structures.

Based on this description, I interpret that the expectation is for the server to perform all of the necessary validation. Step 14 of [Registering a New Credential](https://w3c.github.io/webauthn/#sctn-registering-a-new-credential) cannot be performed without [`CredentialCreationOptions.mediation`](https://w3c.github.io/webappsec-credential-management/#dom-credentialcreationoptions-mediation):

> 14. Verify that the [UP](https://w3c.github.io/webauthn/#authdata-flags-up) bit of the [flags](https://w3c.github.io/webauthn/#authdata-flags) in _authData_ is set, unless _`options`_`.`[`mediation`](https://w3c.github.io/webappsec-credential-management/#dom-credentialcreationoptions-mediation) is set to [`conditional`](https://w3c.github.io/webappsec-credential-management/#dom-credentialmediationrequirement-conditional).

Either `mediation` should be added to [`RegistrationResponseJSON`](https://w3c.github.io/webauthn/#dictdef-registrationresponsejson) and [`AuthenticatorAssertionResponseJSON`](https://w3c.github.io/webauthn/#dictdef-authenticationresponsejson) so that the ceremony has a defined way of receiving this value, or it should be part of [`PublicKeyCredentialCreationOptions`](https://w3c.github.io/webauthn/#dictdef-publickeycredentialcreationoptions) and [`PublicKeyCredentialRequestOptions`](https://w3c.github.io/webauthn/#dictdef-publickeycredentialrequestoptions) so the server has the value already upon receiving [`PublicKeyCredentialJSON`](https://w3c.github.io/webauthn/#typedefdef-publickeycredentialjson). I realize adding to the `PublicKeyCredentialCreationOptions` and `PublicKeyCredentialRequestOptions` is somewhat silly since `mediation` is already part of [`CredentialCreationOptions`](https://w3c.github.io/webappsec-credential-management/#dictdef-credentialcreationoptions) which `PublicKeyCredentialCreationOptions` is also part via [`publicKey`](https://w3c.github.io/webauthn/#dom-credentialcreationoptions-publickey).

The point of the JSON types is having a defined way for the server to send and receive all necessary information to perform the registration and authentication ceremony criteria, correct? Without this, there is still necessary information missing which sort of defeats the purpose for the JSON types since clients and servers will be forced to come up with their own mechanism and not rely on a standardized way.

Does it make sense to create `CredentialCreationOptionsJSON` and `CredentialRequestOptionsJSON` types?

_* Note step 14 is technically incorrect since `mediation` is not a key of `PublicKeyCredentialCreationOptions` (see #2122)_.

**Comment by BlingBling43** [comment]
> [WebAuthn Relying Party Operations](https://w3c.github.io/webauthn/#sctn-rp-operations) states (emphasis added):
> 
> > Upon successful execution of [`create()`](https://w3c.github.io/webappsec-credential-management/#dom-credentialscontainer-create) or [`get()`](https://w3c.github.io/webappsec-credential-management/#dom-credentialscontainer-get), the [Relying Party](https://w3c.github.io/webauthn/#relying-party)'s script receives a [`PublicKeyCredential`](https://w3c.github.io/webauthn/#publickeycredential) containing an [`AuthenticatorAttestationResponse`](https://w3c.github.io/webauthn/#authenticatorattestationresponse) or [`AuthenticatorAssertionResponse`](https://w3c.github.io/webauthn/#authenticatorassertionresponse) structure, respectively, from the client. It must then deliver the contents of this structure to the [Relying Party](https://w3c.github.io/webauthn/#relying-party) _server_, using methods outside the scope of this specification. This section describes the operations that the [Relying Party](https://w3c.github.io/webauthn/#relying-party) must perform upon receipt of these structures.
> 
> Based on this description, I interpret that the expectation is for the server to perform all of the necessary validation. Step 14 of [Registering a New Credential](https://w3c.github.io/webauthn/#sctn-registering-a-new-credential) cannot be performed without [`CredentialCreationOptions.mediation`](https://w3c.github.io/webappsec-credential-management/#dom-credentialcreationoptions-mediation):
> 
> > 14. Verify that the [UP](https://w3c.github.io/webauthn/#authdata-flags-up) bit of the [flags](https://w3c.github.io/webauthn/#authdata-flags) in _authData_ is set, unless _`options`_`.`[`mediation`](https://w3c.github.io/webappsec-credential-management/#dom-credentialcreationoptions-mediation) is set to [`conditional`](https://w3c.github.io/webappsec-credential-management/#dom-credentialmediationrequirement-conditional).
> 
> Either `mediation` should be added to [`RegistrationResponseJSON`](https://w3c.github.io/webauthn/#dictdef-registrationresponsejson) and [`AuthenticatorAssertionResponseJSON`](https://w3c.github.io/webauthn/#dictdef-authenticationresponsejson) so that the ceremony has a defined way of receiving this value, or it should be part of [`PublicKeyCredentialCreationOptions`](https://w3c.github.io/webauthn/#dictdef-publickeycredentialcreationoptions) and [`PublicKeyCredentialRequestOptions`](https://w3c.github.io/webauthn/#dictdef-publickeycredentialrequestoptions) so the server has the value already upon receiving [`PublicKeyCredentialJSON`](https://w3c.github.io/webauthn/#typedefdef-publickeycredentialjson). I realize adding to the `PublicKeyCredentialCreationOptions` and `PublicKeyCredentialRequestOptions` is somewhat silly since `mediation` is already part of [`CredentialCreationOptions`](https://w3c.github.io/webappsec-credential-management/#dictdef-credentialcreationoptions) which `PublicKeyCredentialCreationOptions` is also part via [`publicKey`](https://w3c.github.io/webauthn/#dom-credentialcreationoptions-publickey).
> 
> The point of the JSON types is having a defined way for the server to send and receive all necessary information to perform the registration and authentication ceremony criteria, correct? Without this, there is still necessary information missing which sort of defeats the purpose for the JSON types since clients and servers will be forced to come up with their own mechanism and not rely on a standardized way.
> 
> _* Note step 14 is technically incorrect since `mediation` is not a - [ ] - key of `PublicKeyCredentialCreationOptions` (see #2122)_.- - [^ #  The Elf  Is  Null !  #  3  D  is  C++ ,  #  small  Cap ,  is  Null,0💞

**Comment by emlun** [comment]
Step 1 of [Registering a New Credential](https://w3c.github.io/webauthn/#sctn-registering-a-new-credential) reads:

>1. Let _options_ be a new [PublicKeyCredentialCreationOptions](https://w3c.github.io/webauthn/#dictdef-publickeycredentialcreationoptions) structure configured to the [Relying Party](https://w3c.github.io/webauthn/#relying-party)'s needs for the ceremony.

Indeed this is currently a bit obscured due to the inconsistency you note in the footnote (#2122), but PR #2125 would correct this to:

>1. Let _options_ be a new [CredentialCreationOptions](https://w3c.github.io/webappsec-credential-management/#dictdef-credentialcreationoptions) structure configured to the [Relying Party](https://pr-preview.s3.amazonaws.com/w3c/webauthn/pull/2125.html#relying-party)'s needs for the ceremony. Let pkOptions be options.[publicKey](https://pr-preview.s3.amazonaws.com/w3c/webauthn/pull/2125.html#dom-credentialcreationoptions-publickey).

So the RP should already know the value of _options_.`mediation`, because it was one of the input arguments the RP set at the beginning of the procedure. There is no need to feed it back to the RP in the output types.
