### ISSUE TITLE
Add links where non-members can make patent licensing committments to `CONTRIBUTING.md`

### ISSUE THREAD

**Issue by zacknewman** [w3c/webauthn#2128]
Currently [`CONTRIBUTING.md`](https://github.com/w3c/webauthn/blob/main/CONTRIBUTING.md) states:

> To contribute, you must either participate in the relevant W3C Working Group or make a non-member patent licensing commitment

however nowhere in that document are there links where one can do so. This makes it difficult for non-members to make contributions (e.g., PRs) because they may not know where to go so that they can make such non-member patent licensing commitments.

**Comment by simoneonofri** [comment]
Updated here https://github.com/w3c/webauthn/pull/2131
