### ISSUE TITLE
Define a U2F attestation format

### ISSUE THREAD

**Issue by leshi** [w3c/webauthn#214]
The current attestation format will not work for U2F authenticators.

We should add a U2F attestation format.

**Comment by rlin1** [comment]
Note: we have recently switched to a 3-level attestation structure, i.e. attestation, authenticatorData, clientData.
The U2F attestation contains two levels: attestation and clientData.

Need to figure out a way to handle this without creating too much confusion.

**Comment by gmandyam** [comment]
@rlin1 Can the UA create the authenticator data on behalf of the U2F authenticator?  I am not finding any data in authenticatorData that cannot be derived from U2F raw messaging (assuming U2F SHA-256 hash of app ID is in fact equivalent to SHA-256 hash of RP ID).

**Comment by equalsJeffH** [comment]
per https://www.w3.org/2017/01/04-webauthn-minutes.html @vijaybh associates this with #244
