### ISSUE TITLE
authenticatorDisplayName should use a localizable language map

### ISSUE THREAD

**Issue by timcappalli** [w3c/webauthn#2151]
Related to #1644

## Proposed Change

authenticatorDisplayName is currently a DOMString and does not support localization, specifically language codes and direction.

Change to a map following the String Meta spec: https://www.w3.org/TR/string-meta/#language-maps

```json
"authenticatorDisplayName": {
    "en":    {"value": "This is English"},
    "en-GB": {"value": "This is UK English", "dir": "ltr"},
    "fr":    {"value": "C'est français", "lang": "fr-CA", "dir": "ltr"},
    "ar":    {"value": "هذه عربية", "dir": "rtl"}
}
```

**Comment by emlun** [comment]
Are you sure a language map is appropriate for this? My first impression was rather that `authenticatorDisplayName` is a [single-language localizable text field](https://www.w3.org/TR/string-meta/#single-linguistic-field) - it's a user-configurable value that should only ever be presented back to the same user.

**Comment by emlun** [comment]
After the discussion at TPAC I've come around to agreeing that a language map may be a good choice. The ability to specify multiple languages may be most useful if a value is pre-populated by the authenticator vendor without necessarily knowing the user's preferred locale; if the user overwrites with their own configuration the map can simply be collapsed to containing a single key.

The language map type is a superset of what can be expressed by the single-language localizable text field, so the language map is the safer choice for forward compatibility.

**Comment by emlun** [comment]
@aphillips As @zacknewman points out above, it looks like [String-Meta §2.1.4 Language Maps](https://www.w3.org/TR/string-meta/#language-maps) doesn't formally define (in WebIDL) the structure of a language map, only by example and later abstractly in [language indexing](https://www.w3.org/TR/string-meta/#dfn-language-indexing) (which is not referenced in §2.1.4). Would it be appropriate for String-Meta to provide a WebIDL definition like:

```webidl
typedef record<DOMString, Localizable> LocalizableMap;
```

or should we define this locally in the WebAuthn spec?

**Comment by aphillips** [comment]
@emlun That's a great callout. I filed a tracking issue and will work on getting that published in String-Meta ASAP

**Comment by emlun** [comment]
Ironically, this issue is now obsolete with PR #2194 merged.
