### ISSUE TITLE
Bit set by the SPC extension should backed up as part of the Public Key Credential Source

### ISSUE THREAD

**Issue by timcappalli** [w3c/webauthn#2153]
PLACEHOLDER

## Proposed Change

Bit set by the SPC extension should backed up as part of the Public Key Credential Source.

**Comment by selfissued** [comment]
This makes sense to me.

**Comment by dwaite** [comment]
Suggest altering the definition of credential source to say that extensions supplied during creation can define their own additional data, e.g.

> A credential source ([CREDENTIAL-MANAGEMENT-1]) used by an authenticator to generate authentication assertions. A public key credential source ~~consists of a struct with~~ *will contain* the following items:

and at the end

> Extensions supplied during the `authenticatorMakeCredential` operation MAY define additional data as part of the credential source.

**Comment by timcappalli** [comment]
@timcappalli to talk to SPC folks about including this in their spec.

**Comment by timcappalli** [comment]
Issue created in SPC: https://github.com/w3c/secure-payment-confirmation/issues/278

Closing.
