### ISSUE TITLE
Add `authenticatorDisplayName` to Step 27 and Step 23 of the registration and authentication ceremonies respectively

### ISSUE THREAD

**Issue by zacknewman** [w3c/webauthn#2156]
#1880 added the optional item `authenticatorDisplayName` to [_Credential Record_](https://w3c.github.io/webauthn/#abstract-opdef-credential-record-authenticatordisplayname); however it was not added to Step 27 of the registration ceremony nor Step 23 of the authentication ceremony. Seeing how `attestationObject` and `attestationClientDataJSON` exist in Step 27, it would be nice to also add `authenticatorDisplayName`. Honestly, I was under the impression `authenticatorDisplayName` was only a `credProps` thing; had it existed in the ceremony criteria section for data to store, I don't think I would have made that mistake.

Something like below would be nice:

> The new [credential record](https://w3c.github.io/webauthn/#credential-record) MAY also include the following OPTIONAL contents:
>
> [`attestationObject`](https://w3c.github.io/webauthn/#abstract-opdef-credential-record-attestationobject)
>
>  _`response.`_[`attestationObject`](https://w3c.github.io/webauthn/#dom-authenticatorattestationresponse-attestationobject).
>
> [`attestationClientDataJSON`](https://w3c.github.io/webauthn/#abstract-opdef-credential-record-attestationclientdatajson)
>
>  _`response.`_[`clientDataJSON`](https://w3c.github.io/webauthn/#dom-authenticatorresponse-clientdatajson).
>
> [`authenticatorDisplayName`](https://w3c.github.io/webauthn/#abstract-opdef-credential-record-authenticatordisplayname)
>
>  _`clientExtensionResults.credProps.`_[`authenticatorDisplayName`](https://w3c.github.io/webauthn/#dom-credentialpropertiesoutput-authenticatordisplayname) or RP-provided value.

**Comment by timcappalli** [comment]
authenticatorDisplayName is likely going to be removed from the spec. But if it stays, this is valid.

**Comment by emlun** [comment]
Even though `credentialRecord/authenticatorDisplayName` was added in #1880 along with `credProps.authenticatorDisplayName`, we should still recommend RPs to provide some way for users to set a "nickname" for their credentials, even if `credProps.authenticatorDisplayName` is deleted. So I think this is valid regardless of the outcome of that discussion.

> Really? #2151 was just opened yesterday.

Yes, the sentiment in favour of dropping `credProps.authenticatorDisplayName` came up in discussions at TPAC shortly after #2151 was opened.
