### ISSUE TITLE
Reconciling with FedCM errors

### ISSUE THREAD

**Issue by npm1** [w3c/webauthn#2158]
At TPAC we had a breakout where we tried to dig into this but we didn't. @timcappalli mentioned that FedCM may want to reconcile with WebAuthn errors. I'm not familiar with the WebAuthn errors being exposed right now but I can explains what we are proposing in https://github.com/w3c-fedid/FedCM/pull/498 to see what kind of coordination we would like to have. Filing this issue to perhaps get the interested folks in a call at some point to flesh this out? Note: surfacing new errors / discussions on the privacy implications of doing so is out of scope for this issue, I'm more interested in looking at the current status quo of each spec so that we can confidently merge the relevant FedCM PR.

**Comment by timcappalli** [comment]
Let's use the existing issue (#2096)
