### ISSUE TITLE
Drop UAF references in favor of better explanation

### ISSUE THREAD

**Issue by bifurcation** [w3c/webauthn#217]
Section 5.3.2. "Attestation Types" is about explaining different ways to do attestation while still being privacy-preserving.  The section should be clearer about its purpose ("Attestation Models"?) and explain directly how these models work and protect privacy, instead of by reference to UAF.

**Comment by equalsJeffH** [comment]
@bifurcation wrote:
> {#sctn-attestation-types} is about explaining different ways to do attestation while still being privacy-preserving.  The section should be clearer about its purpose ("Attestation Models"?) and explain directly how these models work and protect privacy, instead of by reference to UAF.

I think this issue is largely addressed, e.g. the term "attestation models" is gone. Tho I feel that the cites of [UAFProtocol] ought to remain.

**Comment by selfissued** [comment]
Unless our attestation types require reading the UAF Protocol spec to implement correctly, I would remove the references to [UAFProtocol] in the definitions of "Basic Attestation" and "Self Attestation".

**Comment by nadalin** [comment]
@equalsJeffH to verify and maybe close

**Comment by equalsJeffH** [comment]
These references are informative and provide hints to additional context and so ought to remain.
