### ISSUE TITLE
Replace `USVString` with `DOMString`

### ISSUE THREAD

**Issue by zacknewman** [w3c/webauthn#2203]
It would appear that the same justification that was used for #2115 applies to the remaining areas where `USVString` is used:

> As recommended by the [Web IDL spec](https://webidl.spec.whatwg.org/#idl-USVString):
>
>> Specifications should only use `USVString` for APIs that perform text processing and need a string of scalar values to operate on. Most APIs that use strings should instead be using `DOMString`, which does not make any interpretations of the code units in the string. When in doubt, use `DOMString`.

Currently the only places where `USVString` is used are the following extensions:
* [`appid`](https://w3c.github.io/webauthn/#dom-authenticationextensionsclientinputs-appid)
* [`appidExclude`](https://w3c.github.io/webauthn/#dom-authenticationextensionsclientinputs-appidexclude)
* [`prf`](https://w3c.github.io/webauthn/#dictdef-authenticationextensionsprfinputs)

Should these all be changed to `DOMString`?

**Comment by agl** [comment]
These extensions do, however, process their inputs.

The `prf` extension needs to perform base64url decoding of the values, so we need a valid input string. The AppId extensions need to convert the input to UTF-8 and hash it. In both cases, the input needs to be valid strings and invalid UTF-16 would cause an error.

So perhaps these are correctly USVString?

**Comment by emlun** [comment]
2024-11-27 WG call: Those are fair arguments. @zacknewman would you like to open a PR for this?
