### ISSUE TITLE
Should steps 28 and 29 occur before Step 27 in the registration ceremony

### ISSUE THREAD

**Issue by zacknewman** [w3c/webauthn#2204]
Currently [step 27](https://w3c.github.io/webauthn/#reg-ceremony-store-credential-record) occurs before steps [28](https://w3c.github.io/webauthn/#reg-ceremony-verify-extension-outputs) and 29; however it seems weird to "create and store a new [credential record](https://w3c.github.io/webauthn/#credential-record) in the [user account](https://w3c.github.io/webauthn/#user-account)" _before_ successfully completing steps 28 and 29, right? This means one could save a credential even though the ceremony fails later.

A similar issue exists for the authentication ceremony where [step 23](https://w3c.github.io/webauthn/#authn-ceremony-update-credential-record) occurs before steps [24](https://w3c.github.io/webauthn/#authn-ceremony-verify-extension-outputs) and 25.

I think moving those steps last makes the most sense since this way any credential creation or update occurs iff the ceremony succeeds.

**Comment by sbweeden** [comment]
agree this should be switchd. @emlun to create PR per WG call on 20 Nov
