### ISSUE TITLE
Move `allowList` from optional to default on `getAssertion`

### ISSUE THREAD

**Issue by bifurcation** [w3c/webauthn#221]
The relying party cannot use an assertion from a credential for which it does not have the public key.  So the API should only allow an RP to `getAssertion` from a credential whose ID it provides.  This just requires moving `allowList` from the `options` argument to `getAssertion` to the main method signature.

**Comment by vijaybh** [comment]
Requiring allowList is equivalent to saying that getAssertion can only provide supplementary authentication, i.e. give you more assurance about a user whose identity you already sort-of-know. However I believe we do want to support scenarios where the user can authenticate with their WebAuthn authenticator and nothing else.

**Comment by equalsJeffH** [comment]
I agree with @vijaybh -- see also his comment here -- https://github.com/w3c/webauthn/issues/219#issuecomment-250095629 -- for a more full description of a roaming (aka external/portable), first-factor authenticator.

**Comment by equalsJeffH** [comment]
@bifurcation (Richard Barnes) writes in https://lists.w3.org/Archives/Public/public-webauthn/2016Sep/0566.html --

I don't see how you arrive at the equivalence -- it's only enforcing that
makeCredential happened before getAssertion.  Says nothing at all about
whether there's any other authentication.

**Comment by equalsJeffH** [comment]
@vijaybh writes in https://lists.w3.org/Archives/Public/public-webauthn/2016Sep/0567.html --

Requiring the allowList means that the RP must know which credential IDs are relevant in this particular interaction (you would not expect Google to send all registered credential IDs in its database for example). To narrow that scope, you need some hint saying which user’s credential IDs you are looking for. At the same time, you don’t want an unauthenticated client to probe for specific account IDs or users either. So you must have some basic idea of who the user is (or some other way to narrow the list of credential IDs, but similar arguments would apply to any other filter).

**Comment by jcjones** [comment]
I agree with @equalsJeffH and @vijaybh here; it's helpful for this data to exist for passwordless-auth, but it shouldn't be required.

**Comment by AngeloKai** [comment]
Should we consider this issue closed?

**Comment by vijaybh** [comment]
Zombie issue that has been discussed on calls earlier as well
