### ISSUE TITLE
Example Use Cases only has phone-as-authenticator example -- we should add another

### ISSUE THREAD

**Issue by leshi** [w3c/webauthn#223]
The current "Use Cases" section stats:
> The below use case scenarios illustrate use of two very different types of authenticators, as well as outline further scenarios. Additional scenarios, including sample code, are given later in §10 Sample scenarios.

However, I think only one type of authenticator is described (a phone).  I suggest we also and a description of a non-phone authenticator.

**Comment by equalsJeffH** [comment]
see also #11 -- this seems to be essentially a duplicate.
