### ISSUE TITLE
TPM attestation format spec is incomplete

### ISSUE THREAD

**Issue by vijaybh** [w3c/webauthn#226]
As was gently pointed out to me by our local TPM expert, the TPM returns a couple more structures from Tpm_Certify that need to be conveyed back to the RP in order to be able to validate the attestation. Currently going through the TPM specs to get more details on this.

**Comment by rlin1** [comment]
daaKey in section 6.3 is not explained: TODO: explain what it is.

**Comment by equalsJeffH** [comment]
see also #233
