### ISSUE TITLE
authenticatorGetAssertion showing selection UI for external authenticators

### ISSUE THREAD

**Issue by mpolanco** [w3c/webauthn#231]
Section 5.1.2 states: 

> Prompt the user to select a credential from among the above list. Obtain user consent for using this credential. The prompt for obtaining this consent may be shown by the authenticator if it has its own output capability, or by the user agent otherwise.

In the case where no allowList is provided, if multiple credentials are available for the specific domain on an external authenticator with no output capability, who is doing the selection prompting here? Wouldn't the user agent not have access to the contents of the external device or its specific model? My guess would be that the platform has to show the selection UI here, not the user agent.

**Comment by AngeloKai** [comment]
This is no longer valid. It's not the job for the authenticatorGetAssertion to display UI but rather the getAssertion itself.
