### ISSUE TITLE
High Level Architecture Diagram

### ISSUE THREAD

**Issue by CallumBrankin** [w3c/webauthn#237]
Is it possible to add a high level architecture diagram? If not is the high level architecture diagram found [on the FIDO UAF 1.0](https://fidoalliance.org/specs/fido-uaf-v1.0-ps-20141208/fido-uaf-overview-v1.0-ps-20141208.html#fido-uaf-high-level-architecture) similar enough to be used?

**Comment by nadalin** [comment]
This is just about the WEB Api and not how the API will be used and all the interactions, so this diagram does not make sense
