### ISSUE TITLE
need description & illustrations of overall flow: authnr <--> platform API <--> RP 

### ISSUE THREAD

**Issue by equalsJeffH** [w3c/webauthn#24]
<a href="https://github.com/equalsJeffH"><img src="https://avatars.githubusercontent.com/u/226571?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Originally submitted by: [equalsJeffH](https://github.com/equalsJeffH)**, on: _Tuesday Oct 06, 2015 at 18:42 GMT_

---

The fido-2 specs so far lack a cohesive exposition of the  overall flow: authnr <--> platform API <--> RP 

the fido-u2f-raw-message-formats spec covers this in its section 1 Introducion, and has figure 1 illustrating it.  Similar discussion and illustrations are in fido-uaf-protocol ---  I suggest we have a similar exposition and figure(s) in the fido-2 specs that are slated for W3C submission. 

I also note that I was asked about this by a smart person who was looking at the fido-2 specs and couldn't figure out "where the protocol is"

**Comment by equalsJeffH** [comment]
<a href="https://github.com/levangongPayPal"><img src="https://avatars.githubusercontent.com/u/10441380?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Original poster: [levangongPayPal](https://github.com/levangongPayPal)**, on: _Tuesday Oct 06, 2015 at 18:51 GMT_

----

Does the attached diagram fill that need?
I've updated it to reflect latest spec but people should validate it.

[Fido 2.0 API - flow - latest.pdf](https://github.com/fido-alliance/fido-2-specs/files/8761/Fido.2.0.API.-.flow.-.latest.pdf)

**Comment by equalsJeffH** [comment]
<a href="https://github.com/selfissued"><img src="https://avatars.githubusercontent.com/u/7644414?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Original poster: [selfissued](https://github.com/selfissued)**, on: _Tuesday Oct 06, 2015 at 20:21 GMT_

----

GitHub is giving me a 404 error when I try to access this link – even though I’m logged in to GitHub.

**Comment by equalsJeffH** [comment]
<a href="https://github.com/levangongPayPal"><img src="https://avatars.githubusercontent.com/u/10441380?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Original poster: [levangongPayPal](https://github.com/levangongPayPal)**, on: _Tuesday Oct 06, 2015 at 20:25 GMT_

----

huh, you’re right. For some reasons, it seems it did not take the diagram.
Here it is as an attachment.

Thanks,
Hubert

**Comment by equalsJeffH** [comment]
<a href="https://github.com/equalsJeffH"><img src="https://avatars.githubusercontent.com/u/226571?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Original poster: [equalsJeffH](https://github.com/equalsJeffH)**, on: _Monday Dec 07, 2015 at 19:04 GMT_

----

this remains an open issue the w3c web authn wg will need to address once it begins work. thus setting milestone to ms-fido-v2.0-w3c

**Comment by nadalin** [comment]
@equalsJeffH  can this be closed now ?

**Comment by equalsJeffH** [comment]
No, this should remain open, i argue that having such protocol diagrams are important for folks to be able to figure out what is going on in this spec.  I have digrams in progress, need to be updated (it is on the stack):

https://docs.google.com/presentation/d/1om__oSew4n48MK_Qcc8deq6hCZ6720-Zvv1PdK0CrjA/edit#slide=id.g2b7fa0712_0127

https://docs.google.com/presentation/d/1om__oSew4n48MK_Qcc8deq6hCZ6720-Zvv1PdK0CrjA/edit#slide=id.g2b7fa0712_0158

**Comment by AngeloKai** [comment]
I agree this should be open. Such diagrams would be really helpful. I do wonder whether this is necessary to be resolved before CR. Browser vendors often look at CR as signal for making the implementation on by default. If the issue is truly about helping people understand the spec, we can wait until CR is announced and a lot more people start coming in to review. This way we will know which diagram is more helpful and make tweaks in an effective manner.

**Comment by equalsJeffH** [comment]
I have (finally) begun working on updating these figures -- please see the [updated Registration slide](https://docs.google.com/presentation/d/1om__oSew4n48MK_Qcc8deq6hCZ6720-Zvv1PdK0CrjA/edit#slide=id.g2b7fa0712_0127)

**Comment by equalsJeffH** [comment]
perhaps this figure https://mdn.mozillademos.org/files/15801/MDN%20Webauthn%20Registration%20(r3).png is a reasonable alternative?  where is the source for it I wonder?

**Comment by equalsJeffH** [comment]
@apowers313 appears to be the main person behind https://developer.mozilla.org/en-US/docs/Web/API/Web_Authentication_API which features figures ( [reg](https://mdn.mozillademos.org/files/15801/MDN%20Webauthn%20Registration%20(r3).png) and [authn](https://mdn.mozillademos.org/files/15802/MDN%20Webauthn%20Authentication%20(r1).png) ) that are arguably in a more "approachable" style than the "[crypto-flow-style](https://github.com/w3c/webauthn/issues/24#issuecomment-327830852)" ones I've been working on.  

they would need some work (eg alter color scheme?) and double-checking to ensure they denote the appropriate protocol components

WDYT?

**Comment by apowers313** [comment]
Here's the recolored images exported as SVG (the originals were OmniGraffle):

[WebAuthn Flow - Registration.zip](https://github.com/w3c/webauthn/files/2137998/WebAuthn.Flow.-.Registration.zip)
[WebAuthn Flow - Authentication.zip](https://github.com/w3c/webauthn/files/2137999/WebAuthn.Flow.-.Authentication.zip)

Let me know if they need any fixing up.

**Comment by equalsJeffH** [comment]
@apowers313 - THANKS

see PR #1007
