### ISSUE TITLE
RSA credential public key encoding in "attestation data" incorrectly specified?

### ISSUE THREAD

**Issue by equalsJeffH** [w3c/webauthn#240]
in {#generating-an-attestation-statement} (sec 5.3.3 presently), there is the following text ostensibly regarding the encoding of a conveyed RSA credential public key:

```
That is, [modulus (256 bytes), e (m-n bytes)], where m is the total length of the field. This
 total length should be taken from the object containing this key
```

This is apparently saying that one should convey the cred pub key in an octet string, with the modulus first (of length 256 bytes), then the public exponent of length "m-n" bytes. 

AFAICT, there's some issues with the above:

1) it appears that this encoding is not employing length indications and values, i.e. it is not employing DER or some tag-length-value approach, correct?

2) if answer to (1) is "yes", then the implication is that we are explicitly declaring that for "public key and encoding" value of 0x0102, the modulus is of length 256  (2048 bits), period. (yes?)

3) determining the length of the e value via `(m-n bytes)` is unclear because there is nothing explicitly explaining where the value n comes from. In PKCS#1 (RFC3447), "n" is the **value** of the modulus itself, not the length of the modulus (https://tools.ietf.org/html/rfc3447#appendix-A.1).  Though here we are (so far) fixing the public key modulus length at 256 bytes and so determining the length of the e value should be restated (if we don't change this construction): `(m-256 bytes)`.

4) why are we fixing the pub key length rather than using the common & widely-supported ASN.1-based pub key encoding (typically using DER) of:

```
      RSAPublicKey ::= SEQUENCE {
          modulus           INTEGER,  -- n
          publicExponent    INTEGER   -- e
      }
```

which for a 2048-bit modulus has a total length of 294 bytes, and has the advantage of allowing for authenticators to generate public keys of varying length. We can state a qualifier in the text of something along the lines of "an RSA public key MUST have a modulus of at least 2048 bits".

**Comment by equalsJeffH** [comment]
A stab at addressing this via the ASN.1-based pub key encoding (typically using DER) approach is given in commit [45cf3d8](https://github.com/w3c/webauthn/commit/45cf3d8018356421b480a67a3eb18c6214bf08cb) in branch jeffh-attstn-and-keygen

**Comment by rlin1** [comment]
wait for Vijay's change in attestation before working on this one.

**Comment by equalsJeffH** [comment]
@rlin1 noted:
> wait for Vijay's change in attestation #244 before working on this one.

agreed.
