### ISSUE TITLE
certifyinfo needs to be specified

### ISSUE THREAD

**Issue by gmandyam** [w3c/webauthn#242]
certifyinfo in TPM attestation is not clearly specified currently.  For instance, under verification the spec currently says "verify that the certifyInfo contains a TPMCERTIFY_INFO or TPM_CERTIFYINFO2 structure" but provides no information as to where the definitions of TPMCERTIFY_INFO or TPM_CERTIFYINFO2 can be found.  Similar problem with TPMS_ATTEST.

**Comment by vijaybh** [comment]
Will handle as part of #226
