### ISSUE TITLE
Does "Then asynchronously continue executing the following steps" mean "in parallel"?

### ISSUE THREAD

**Issue by bzbarsky** [w3c/webauthn#253]
That is, are steps 3 and later of https://w3c.github.io/webauthn/#dom-webauthentication-makecredential done "in parallel" in the sense of https://html.spec.whatwg.org/multipage/infrastructure.html#in-parallel or is this a different kind of thing?

This matters, because "reject promise" as defined at https://www.w3.org/2001/tag/doc/promises-guide#shorthand-manipulating means different things when done in an "in parallel" section vs not, and I think you want the "in parallel" meaning here.

**Comment by bzbarsky** [comment]
This applies to https://w3c.github.io/webauthn/#getAssertion step 3 and later as well.

**Comment by vijaybh** [comment]
Fixed by #371
