### ISSUE TITLE
Please coordinate with the HTML spec to extract the relevant bits of the document.domain setter so you can call them

### ISSUE THREAD

**Issue by bzbarsky** [w3c/webauthn#256]
Currently https://w3c.github.io/webauthn/#dom-webauthentication-makecredential step 3 says to do https://www.w3.org/TR/html51/browsers.html#relaxing-the-same-origin-restriction but not quite.  Except it doesn't make it clear _which_ document, and it's not clear whether you actually want the interaction with sandboxing that the document.domain setter has, whether you actually want the behavior to be affected by previous document.domain sets (as the actual document.domain setter is) and so forth.

All this stuff should be clearly defined, ideally by:

1. Defining clearly which document you're working with.
2. Working together with the HTML spec to extract the relevant algorithm for your use.  If this proves impossible, because you actually want somewhat different behavior from the document.domain setter, then the algorithm needs to just be clearly defined.

**Comment by bzbarsky** [comment]
This applies to https://w3c.github.io/webauthn/#getAssertion step 3 too.

**Comment by equalsJeffH** [comment]
Yes, the present spec language for this is a stab-in-the-dark-with-the-hope-of-sparking-helpful-feedback, and it seems to have worked :)

In terms of (2), i.e. the relevant algorithm, it seems to me it is _nominally_ steps 4 - 7 (inclusive) of the domain attribute setter defined hereabouts: https://html.spec.whatwg.org/#dom-document-domain

So, by "extract the algorithm" you mean to say "revise the HTML spec such that the those steps are defined as a distinct algorithm which we an then invoke from the webauthn spec (and which the document.domain setter also utilizes) ?

**Comment by bzbarsky** [comment]
> nominally steps 4 - 7 (inclusive) of the domain attribute setter defined hereabouts

OK.  So if a page is loaded from "https://foo.bar.com" and then sets document.domain to "bar.com", should it be able to use "foo.bar.com" as its rpId?  Sounds to me like you're saying it shouldn't be able to....

> So, by "extract the algorithm" you mean to say

Yes.  Again, assuming the desired behavior is similar enough that this makes sense.

**Comment by equalsJeffH** [comment]
>> nominally steps 4 - 7 (inclusive) of the domain attribute setter defined hereabouts

> OK.  So if a page is loaded from "https://foo.bar.com" and then sets document.domain to "bar.com", should it be able to use "foo.bar.com" as its rpId?  Sounds to me like you're saying it shouldn't be able to....

Our present intent (if it is correct) is that even if "https://foo.bar.com" is loaded and then sets document.domain to "bar.com", it *would* still be able to assert "foo.bar.com" as its rpId.

**Comment by bzbarsky** [comment]
OK, then you need to somewhat modify the HTML algorithm, or extract parts of it, or something.

**Comment by equalsJeffH** [comment]
Ok, thx. We have a stab at such an extraction in this PR: https://github.com/w3c/webauthn/pull/314.  It has this crucial step:
> 5. Let |originalHost| be this <a>Document</a> object’s <a link-for='web'>origin</a>’s <a link-for='url'>host</a>.

..which we hope if correct.  See discussion with @domenic in PR #314.

**Comment by jwatt** [comment]
Why is document.domain being used in WebAuthn? To quote Bobby Holley in https://bugzilla.mozilla.org/show_bug.cgi?id=1329764#c2

> We should absolutely not be building any support for document.domain (or any analogous machinery) into new specs. It mostly breaks the security model of the web, and vendors have gone to great lengths to reduce document.domain support to the bare minimum required for web-compat.

It seems like WebAuthn is one spec where we should have the APIs throw if document.domain has been set to push websites towards using pushMessage instead. That's particularly the case since it's the big sites like FB that we need to push away from document.domain in order to deprecate document.domain, and they're likely to want to have WebAuthn support.

**Comment by bzbarsky** [comment]
This isn't about document.domain per se.  It's about a similar "hey, pretend like I'm a super-domain of my actual domain" setup in a slightly different context.  The idea is that foo.bar.com can generate auth tokens for bar.com, if I understand correctly.

**Comment by equalsJeffH** [comment]
this was fixed by PR #319 (but not auto-closed ;-)
