### ISSUE TITLE
Is _rpId_ supposed to look like an origin serialization, or like a hostname?

### ISSUE THREAD

**Issue by bzbarsky** [w3c/webauthn#259]
https://w3c.github.io/webauthn/#dom-webauthentication-makecredential step 3 has two branches.  the "rpId is not specified" branch will set _rpId_ to a string like "https://foo.bar.com".  The "rpId is specified" branch will set it to a string like "bar.com".

Is this difference purposeful?

**Comment by jyasskin** [comment]
@leshi, are there constraints here based on the old FIDO implementation?

Without constraints, I'd suggest that the origin relaxation steps replace the [host](https://html.spec.whatwg.org/multipage/browsers.html#concept-origin-host) in the original origin, but leave the scheme and port alone.

**Comment by selfissued** [comment]
@equalsJeffH plans to fix this.

**Comment by equalsJeffH** [comment]
fixed by PR #464, closing.
