### ISSUE TITLE
Usability Issue: Account Deletion

### ISSUE THREAD

**Issue by equalsJeffH** [w3c/webauthn#26]
<a href="https://github.com/rlin1"><img src="https://avatars.githubusercontent.com/u/2264687?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Originally submitted by: [rlin1](https://github.com/rlin1)**, on: _Monday Oct 19, 2015 at 15:02 GMT_

----

<pre>
Scenario
•	Using web app

•	User has created FIDO credentials for 2 different accounts at the same RP (i.e. user 
  has registered same authenticator to same RP twice using different accountInfos).

•	User deletes account 1 via the App.  The App will trigger “revocation” (or deletion) 
  of the related  FIDO Credential on the Server (according to fido-web-api).

•	The fido-credential will still be present on the user device as fido-web-api doesn’t allow 
  programmatic deletion of the FIDO credential locally.

•	Notes:
	o	In a 2nd factor scenario that won’t be an issue the server will never send the 
        related credentialID to the app.
	o	In a 1st factor scenario this WILL be an issue if web browser doesn’t have access 
        to synchronized persistent storage (across web browsers).  Example: Use Mobile Phone 
        as authenticator for web browsers on PC1 and PC2 or after cookie deletion etc.  In such 
        a case we would require the user to delete the credential on the authenticator first or 
        on web account and additionally on the authenticator.
</pre>

**Comment by equalsJeffH** [comment]
<a href="https://github.com/rlin1"><img src="https://avatars.githubusercontent.com/u/2264687?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Original poster: [rlin1](https://github.com/rlin1)**, on: _Monday Oct 19, 2015 at 15:21 GMT_

----

Comment from Dirk (via email):
(2) (Deletion API): We've heard many arguments back and forth on this one (including the one you mention here in the document), and I have to admit I just find the "against" arguments more convincing: You need a "local" delete option anyway (for when the RP doesn't know that you have a credential), the delete API call would be unreliable (what if the Authenticator isn't currently available), and some Authenticators just can't do it at all (they don't have local storage). 

Also, this comes with its own drawbacks - it gives the RP more opportunities to make mistakes (like accidentally deleting credentials), gives a man-in-the-middle an opportunity for a downgrade attack (it could inject javascript to delete the credential and then forces the user back to password-based authentication), etc. 

I'm still against this.

**Comment by equalsJeffH** [comment]
<a href="https://github.com/equalsJeffH"><img src="https://avatars.githubusercontent.com/u/226571?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Original poster: [equalsJeffH](https://github.com/equalsJeffH)**, on: _Monday Dec 07, 2015 at 18:57 GMT_

----

 this remains an open issue the w3c web authn wg will need to address once it begins work. thus setting milestone to ms-fido-v2.0-w3c

**Comment by vijaybh** [comment]
See #17
