### ISSUE TITLE
_rpId_ generation allows more relaxation of same-origin restrictions than document.domain does

### ISSUE THREAD

**Issue by bzbarsky** [w3c/webauthn#260]
Providing an rpId of "foo.com" would lead to a single rpId being allowed to be shared by "http://foo.com", "https://foo.com", and "https://foo.com:8080".  The first may not be a problem because this API is secure context only, but is it intended that "https://foo.com" and "https://foo.com:8080" be able to share an rpId?  If not, this needs to be fixed in the spec.  If this is intended, it may be worth a note calling it out, because this is a quite surprising deviation from how same-origin policy normally works.

**Comment by selfissued** [comment]
@equalsJeffH plans to fix this.
