### ISSUE TITLE
Link to WebCrypto API is stale

### ISSUE THREAD

**Issue by bzbarsky** [w3c/webauthn#261]
The link at https://w3c.github.io/webauthn/#biblio-webcryptoapi goes to https://dvcs.w3.org/hg/webcrypto-api/raw-file/tip/spec/Overview.html but the spec now lives at https://w3c.github.io/webcrypto/Overview.html

**Comment by equalsJeffH** [comment]
webauthn as processed by bikeshed is sourcing this info from specref -- https://github.com/tobie/specref -- someone needs to update specref regarding this.

**Comment by equalsJeffH** [comment]
ok, I've enqueued a fix for at least fixing the editors' draft link to webcrypto in specref: https://github.com/tobie/specref/pull/311

**Comment by equalsJeffH** [comment]
this is now fixed in specref via https://github.com/tobie/specref/pull/311 and thus in webauthn automagically via bikeshed.
