### ISSUE TITLE
When talking about "normalizing an algorithm", please just link to it

### ISSUE THREAD

**Issue by bzbarsky** [w3c/webauthn#262]
The spec currently says:

> Let normalizedAlgorithm be the result of normalizing an algorithm using the procedure defined in [WebCryptoAPI]

which forces the reader to follow the link to the bibliography, thence to the webcrypto API spec, and then look for the thing they think you're referencing.  Please just link to https://w3c.github.io/webcrypto/Overview.html#algorithm-normalization-normalize-an-algorithm directly (either instead, or in addition to the link to the bibliography; no opinion on that).

**Comment by equalsJeffH** [comment]
ok, tho the link you provide is to the webcrypto editor's draft. AFAIU we should be linking to https://www.w3.org/TR/WebCryptoAPI/

**Comment by bzbarsky** [comment]
Habit, given that for a lot of W3C specs whatever is in TR is way out of date and shouldn't be used for anything in practice.  I just ran into this with one of the CSS specs...

It's possible that this is not the case for webcrypto.
