### ISSUE TITLE
What does "If normalizedAlgorithm is empty" mean?

### ISSUE THREAD

**Issue by bzbarsky** [w3c/webauthn#266]
https://w3c.github.io/webauthn/#dom-webauthentication-makecredential step 5 says:

> If normalizedAlgorithm is empty

What does that mean, exactly?  "normalizedAlgorithm" is defined inside the loop in step 4, but doesn't really have any obvious meaning outside that loop...

Is the basic intention here to throw if "normalizedParameters" is a length 0 list but cryptoParameters was not length 0?  If so, please say that.

**Comment by equalsJeffH** [comment]
@bzbarsky The text you reference appears to have been added by @vijaybh via PR #196 commit https://github.com/w3c/webauthn/pull/196/commits/83332c83865287ee1d8a89edb90c0a1e1828d6a0.  I share your questions wrt rationale for this step.

**Comment by jyasskin** [comment]
I bet that "normalizedAlgorithm" there is a typo for "normalizedParameters".

**Comment by equalsJeffH** [comment]
Yes, agreed, brilliant :)

**Comment by equalsJeffH** [comment]
However we do not define what to do if both normalizedAlgorithm and cryptoParameters are empty. don't need to fix now, see #361.

**Comment by vijaybh** [comment]
Just popping in to confirm - @jyasskin wins his bet, above. This was a typo.

**Comment by equalsJeffH** [comment]
this was fixed in PR #347
