### ISSUE TITLE
"If extensions was specified" should instead use the "present" terminology

### ISSUE THREAD

**Issue by bzbarsky** [w3c/webauthn#269]
https://w3c.github.io/webauthn/#dom-webauthentication-makecredential step 7 should start with something like:

> If the extensions member of _options_ is present, then process its value ....

with "present" ideally linking to https://heycam.github.io/webidl/#dfn-present

**Comment by bzbarsky** [comment]
This applies to https://w3c.github.io/webauthn/#getAssertion step 4 too.

**Comment by equalsJeffH** [comment]
this was fixed by https://github.com/w3c/webauthn/pull/306/commits/8963f2144585bc435e0b4d22b4cbf2ab2d391f2d and https://github.com/w3c/webauthn/pull/306/commits/3507992a79f2b0a904b25705890b33bf80ddfbd6 which were merged as a part of https://github.com/w3c/webauthn/pull/306
