### ISSUE TITLE
Processing model for extensions is very underdefined

### ISSUE THREAD

**Issue by bzbarsky** [w3c/webauthn#270]
I'm not sure how well this can really be specified, but...

https://w3c.github.io/webauthn/#dom-webauthentication-makecredential step 7 says:

> If an error is encountered while processing an extension, skip that extension and do not produce any extension data for it.

It's not clear what that means.  Can "an error" include ES exceptions?  I see no reason it can't, but then should those be caught or reported?

**Comment by bzbarsky** [comment]
This applies to https://w3c.github.io/webauthn/#getAssertion step 4 too.

**Comment by equalsJeffH** [comment]
ES is "ecmaScript" I believe. also, #290 #295 are related to this one in that they address "extensions".

**Comment by jyasskin** [comment]
Recording another couple missing bits in the extension processing model:

* https://w3c.github.io/webauthn/#makeCredential doesn't look up the extension's key in the registry.
* https://w3c.github.io/webauthn/#client-processing doesn't yet say what type a client-processing algorithm returns.
* https://w3c.github.io/webauthn/#extension-txauth-simple talks about "default forwarding", for which I can't find a definition.

This is *not* a complete list of places where the input, output, and important utility operations are underdefined for extension algorithms. Someone who cares about extensions should re-read their use and definitions and file bugs for problems similar to the above.

**Comment by selfissued** [comment]
https://github.com/w3c/webauthn/pull/389 Addresses the error handling aspects of this and defines a default extension result value so that callers can know that the extension was processed.

**Comment by selfissued** [comment]
PR #389 has been updated to address the ambiguities pointed out by @jyasskin .  In particular, all extensions now have a "Client data" field and none depend upon the undefined "default forwarding" language.

**Comment by selfissued** [comment]
The extension processing model is now longer very undefined, now that PR #389 has been merged in.  We will still find and fix nits (for instance, the JSON string vs. DOMString issue that @jyasskin just pointed out), but we should file other issues for these as we find them and fix them in different PRs.
