### ISSUE TITLE
ScopedCredentialDescriptor can contain BufferSources that are processed async

### ISSUE THREAD

**Issue by bzbarsky** [w3c/webauthn#276]
In https://w3c.github.io/webauthn/#dom-webauthentication-makecredential step 10, the excludeList member of _options_ is asynchronously passed to authenticatorMakeCredential operations.  This member is a sequence of ScopedCredentialDescriptor which are required to have a BufferSource id.  At this point, that buffer source may be being modified concurrently by script, so reading anything from it is unsafe.

Presumably somewhere in here there should be a snapshot taken.

**Comment by bzbarsky** [comment]
This applies to https://w3c.github.io/webauthn/#getAssertion step 7 too, I believe.

**Comment by equalsJeffH** [comment]
Presumably some existing specs define algorithms with such "snapshot" behavior prior to initiating async operations, might you have any pointer(s) to such handy?

**Comment by bzbarsky** [comment]
See https://heycam.github.io/webidl/#dfn-get-buffer-source-copy which crypto api uses in things like encrypt().  Again, please look at the editor's draft version of crypto API for how it's used, because the version in TR does things differently and somewhat bogusly.

**Comment by equalsJeffH** [comment]
I think this issue is now fixed due to `ScopedCredentialOptions.excludeList` being accessed prior to going async. Similarly for `AssertionOptions.allowList` once PR #371 lands.  *Unless* we ought to [get copies of buffer sources](https://heycam.github.io/webidl/#dfn-get-buffer-source-copy) regardless of going async.

**Comment by vijaybh** [comment]
Fixed by #371
