### ISSUE TITLE
Creation of ScopedCredentialInfo in makeCredential should probably be more explicit

### ISSUE THREAD

**Issue by bzbarsky** [w3c/webauthn#277]
In https://w3c.github.io/webauthn/#dom-webauthentication-makecredential step 11 the spec says:

> Create a new ScopedCredentialInfo object named value and populate its fields with the values returned from the authenticator as well as the clientDataJSON computed earlier.

But ScopedCredentialInfo doesn't have a useful place to put a clientDataJSON.  Presumably that should go into the clientData member of the attestation member of the ScopedCredentialInfo?  That needs to be made clear.

In general, I think it would be good to define the interface between this code and https://w3c.github.io/webauthn/#transport-authenticatormakecredential more clearly in terms of which part of the return set of things go where on the object that gets created.  For example, https://w3c.github.io/webauthn/#transport-authenticatormakecredential says that it needs to return

> The fields of the attestation structure WebAuthnAttestation, including information about the attestation format used.

but it has no way to return the clientDataJSON, because it doesn't have it...

Also, is authenticatorMakeCredential  expected to create the ArrayBuffer for the new ScopedCredentials's id member?  Or is that the job of makeCredential?  Presumably the latter, right?  Which global is that ArrayBuffer created in?   Presumably this creation step needs to happen off a task queued back to some task queue, since it's going to need to create ES objects, so can't happen on random background threads.  Which task queue?  That matters in terms of event ordering with other things.  Which globals are used for the various other objects involved in this ScopedCredentialInfo?

**Comment by equalsJeffH** [comment]
@bzbarsky wrote:
> ScopedCredentialInfo doesn't have a useful place to put a clientDataJSON. Presumably that should go into the clientData member of the attestation member of the ScopedCredentialInfo? That needs to be made clear.

fixed by PR #321 (merged)

> In general, I think it would be good to define the interface between this code and https://w3c.github.io/webauthn/#transport-authenticatormakecredential more clearly in terms of which part of the return set of things go where on the object that gets created. For example, https://w3c.github.io/webauthn/#transport-authenticatormakecredential says that it needs to return
>
> >    The fields of the attestation structure WebAuthnAttestation, including information about the attestation format used.
>
> but it has no way to return the clientDataJSON, because it doesn't have it...

fixed by PR #321 (merged)

> Also, is authenticatorMakeCredential expected to create the ArrayBuffer for the new ScopedCredentials's id member? Or is that the job of makeCredential? Presumably the latter, right? 

Yes, as of merged PR #347.

> Which global is that ArrayBuffer created in? Presumably this creation step needs to happen off a task queued back to some task queue, since it's going to need to create ES objects, so can't happen on random background threads. Which task queue? That matters in terms of event ordering with other things. Which globals are used for the various other objects involved in this ScopedCredentialInfo?

This is not yet addressed AIUI. I'll grep whatwg.org for 'global' and 'task queue' examples and try to formulate an answer, tho any additional hints/pointers will be appreciated. :)

**Comment by bzbarsky** [comment]
For the "which global" question, see https://html.spec.whatwg.org/multipage/webappapis.html#realms-settings-objects-global-objects for the different kinds of globals that exist at a point when an API is called.  Note that you will presumably need to capture which global to use at call time, then pass it along to your queued task.

For the "which task queue" question, I guess the real question is "which task source?"  See https://html.spec.whatwg.org/multipage/webappapis.html#task-source

In general, a spec can just make up a task source, or use one another spec defines, if it wants specific ordering guarantees with tasks from that other spec.

**Comment by vijaybh** [comment]
The "which global" question seems to also be covered by #293 (though that issue is worded in a more general way to cover all ArrayBuffer creations).

**Comment by equalsJeffH** [comment]
An attempt at resolving the "which global" / "which task source" questions is at https://github.com/w3c/webauthn/pull/371/commits/c49cb0f3412994c095cf1304801e376bfee464da for `makeCredential()`
