### ISSUE TITLE
"might be present on this authenticator" could use a clearer definition

### ISSUE THREAD

**Issue by bzbarsky** [w3c/webauthn#280]
https://w3c.github.io/webauthn/#getAssertion step 7 says:

> execute a platform-specific procedure to determine which, if any, credentials listed in allowList might be present on this authenticator

It's not clear to me what this means.  Does the "id" of the ScopedCredentialDescriptor need to match something?  Does the type?  This seems impossible to implement interoperably as written.

**Comment by equalsJeffH** [comment]
@bzbarsky does this https://github.com/w3c/webauthn/commit/b3dba2c356f231ab3c96608cfcbf96fe3ca1df7f address this issue?  the latter was merged to master in PR #371

**Comment by bzbarsky** [comment]
It still seems unclear what an interoperable implementation here would look like, but at least now it's clearer than id and type are, or can be, involved....

**Comment by equalsJeffH** [comment]
The present language is (step 16.2 of https://www.w3.org/TR/2017/WD-webauthn-20170811/#getAssertion (WD-06):
> If options.allowCredentials is not empty, execute a platform-specific procedure to determine which, if any, public key credentials described by options.allowCredentials are bound to this authenticator, by matching with rpId, options.allowCredentials.id, and options.allowCredentials.type. ...

Am closing this issue. if problems arise, eg the upcoming interop, due specifically to unclarity in this particular alg step, please re-open and provide details.
