### ISSUE TITLE
What does it mean to "get assertions" in getAssertion step 7?

### ISSUE THREAD

**Issue by bzbarsky** [w3c/webauthn#281]
https://w3c.github.io/webauthn/#getAssertion step 7 says:

> For each credential C within the credentialList that has a non-empty transports list, optionally use only the specified transports to get assertions using credential C.

What does that actually mean?  Shouldn't this be handled by authenticatorGetAssertion?  Or is this a limitation on which authenticators should be talked to at all, and the clause means to go on to the next authenticator?

**Comment by vijaybh** [comment]
Fixed by #371
