### ISSUE TITLE
Why are some of the attestation interfaces [SecureContext] while others are not?

### ISSUE THREAD

**Issue by bzbarsky** [w3c/webauthn#286]
I would expect them all to be SecureContext or all to not be SecureContext.

**Comment by equalsJeffH** [comment]
heh, good catch. offhand, I think those two interfaces were merged-in after I went through and applied `[SecureContext]` to all interfaces (per @mikewest).

**Comment by vijaybh** [comment]
This should be addressed by #244 which aims to make attestation an ArrayBuffer.

**Comment by equalsJeffH** [comment]
Assigning @leshi since he is presently tackling #244
