### ISSUE TITLE
Which of the attestation format interfaces are expected to be exposed in UAs?

### ISSUE THREAD

**Issue by bzbarsky** [w3c/webauthn#287]
Does a UA conforming to this specification expose all the attestation format interfaces (as properties on the global) even though it may never return any instances of them?  Does it only expose the ones it might return instances of?  Are both behaviors OK?  This is not clear from the spec.

**Comment by vijaybh** [comment]
This should be addressed by #244 which aims to make attestation an ArrayBuffer.
