### ISSUE TITLE
Is there a reason "WebAuthnAssertion" is not "WebAuthenticationAssertion"?

### ISSUE THREAD

**Issue by bzbarsky** [w3c/webauthn#288]
Is there a particular reason to try to save a few characters here?

**Comment by bzbarsky** [comment]
Same for WebAuthnAttestation.

**Comment by equalsJeffH** [comment]
fixed by pr #317 https://github.com/w3c/webauthn/commit/6267cc1e81ae9999f11d75f37b4f9a3b558ce6dc
