### ISSUE TITLE
Can the "attestation" of a WebAuthnAttestation be a non-object?

### ISSUE THREAD

**Issue by bzbarsky** [w3c/webauthn#289]
Right now this attribute is specified to be `any`, but are there situations in which it's not an object?

**Comment by equalsJeffH** [comment]
Instead of `any` might we declare it `object` (that would be correct idl-wise?) ?

**Comment by bzbarsky** [comment]
`object` would be correct if it's always guaranteed to be an object, yes.

**Comment by vijaybh** [comment]
This should be addressed by #244 which aims to make attestation an ArrayBuffer.

**Comment by AngeloKai** [comment]
Since [#224](https://github.com/w3c/webauthn/issues/244) already address the issue, can we mark this issue as closed?

**Comment by equalsJeffH** [comment]
we will close this by reference in a commit message related to an actual change in the spec that addresses this. that's been our working practice.
