### ISSUE TITLE
encodedClientData should be clientDataJSON ?

### ISSUE THREAD

**Issue by equalsJeffH** [w3c/webauthn#29]
<a href="https://github.com/equalsJeffH"><img src="https://avatars.githubusercontent.com/u/226571?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Originally submitted by: [equalsJeffH](https://github.com/equalsJeffH)**, on: _Monday Dec 07, 2015 at 20:11 GMT_

----

section 3.1 of signature-format says down near end: "The client platform SHOULD also preserve the exact encodedClientData string used to create [clientDataHash],"

also, in S 3.2.2 of key-attestation, it says " The client platform MUST also preserve the exact encodedClientData string (see [FIDOSignatureFormat]),"

encodedClientData should be clientDataJSON  in both places ?

**Comment by vijaybh** [comment]
Fixed as part of #76 and #77
