### ISSUE TITLE
What does "which has no other operations in progress" mean in practice?

### ISSUE THREAD

**Issue by bzbarsky** [w3c/webauthn#292]
https://w3c.github.io/webauthn/#op-make-cred says:

> This operation must be invoked in an authenticator session which has no other operations in progress. 

What does that mean?  I see nothing in the callers enforcing this, at first glance...

**Comment by bzbarsky** [comment]
Same thing in https://w3c.github.io/webauthn/#op-get-assertion

**Comment by equalsJeffH** [comment]
see also #283

**Comment by equalsJeffH** [comment]
@jcjones  notes see also #316

**Comment by equalsJeffH** [comment]
see also #380

**Comment by equalsJeffH** [comment]
see also #537

**Comment by nadalin** [comment]
see also #537

**Comment by equalsJeffH** [comment]
during 11-Oct-2017 meeting, we feel that this is more of an impl considerations item.  making normative spec language at this time is fraught.

**Comment by equalsJeffH** [comment]
@jcjones notes in webauthn f2f tpac 2017-11-09 : this is not yet addressed in the spec.  we could change the language somewhat along the lines of " should call abort on the authnr before continuing with this operation "  or something along those lines.
