### ISSUE TITLE
Timeouts should be in ms not seconds

### ISSUE THREAD

**Issue by vijaybh** [w3c/webauthn#299]
See comment on w3ctag/spec-reviews#97 which points to https://w3ctag.github.io/design-principles/#milliseconds

**Comment by jcjones** [comment]
Would we like to keep this as an `unsigned long` and rename `timeoutSeconds` to `timeoutMilliseconds` ?

**Comment by vijaybh** [comment]
Yes, I think so. Description text would need minor updates as well.

**Comment by vijaybh** [comment]
Addressed by #333
