### ISSUE TITLE
Update attestation format identifiers in registry to match spec

### ISSUE THREAD

**Issue by vijaybh** [w3c/webauthn#300]
See https://github.com/w3ctag/spec-reviews/issues/97#issuecomment-257799820 as well as #222

**Comment by equalsJeffH** [comment]
ok, there are several nuances to this issue and also #222 ...
1.  the TAG feels the (proposed) attestation format identifiers for the Android attestation formats, presently used in [draft-hodges-webauthn-registries](https://xml2rfc.tools.ietf.org/cgi-bin/xml2rfc.cgi?modeAsFormat=html/ascii&url=https://raw.githubusercontent.com/w3c/webauthn/master/draft-hodges-webauthn-registries.xml#rfc.section.4.2) is "really ugly":  goog-android and goog-android2

2.  @vijaybh is implicitly noting here that the WebAuthn draft presently has different attstn format IDs for the Android attstn formats: android-key and android-safetynet   -- and this issue #300 seems to be suggesting that we adopt the latter attstn format IDs in draft-hodges-webauthn-registries.

3.  @gmandyam has lobbied for special designation for proprietary attestation formats, that is what #222 is nominally regarding. 

Seems to me, we need to decide issue #222 and then edit the specs appropriately.

**Comment by selfissued** [comment]
Pull request https://github.com/w3c/webauthn/pull/386 addressed this issue.
