### ISSUE TITLE
Should use "RS1" instead of "RSA1_5"

### ISSUE THREAD

**Issue by rlin1** [w3c/webauthn#304]
In section TpmAttestation:
At this time we are using the strings as defined in https://www.w3.org/TR/WebCryptoAPI/#jwk-mapping.
The correct string for RSASSA-PKCS1-v1_5 is "RS1".

**Comment by rlin1** [comment]
Hmmm: When looking up RFC7518, I only find "RSA1_5" (see https://tools.ietf.org/html/rfc7518, page 11 section 4.1).

**Comment by rlin1** [comment]
Eventhough ES256, RS256 etc. are in sync between WebCryptoAPI and RFC7518, "RS1" / "RSA1_5" are different there.

**Comment by rlin1** [comment]
Not sure what to do about this inconsistency.

**Comment by equalsJeffH** [comment]
I've been working trough these issues in #123 -- this seems to be a duplicate -- shall we close this one (after transferring any of the above comments that are helpful in the context of #123) ?

**Comment by rlin1** [comment]
Does RSA1_5 relate to RSA as encrypion algorithm?

**Comment by nadalin** [comment]
The RS1 in both Web Crypto and in JOSE refers to  RSASSA-PKCS1-v1_5 with SHA-1. I though we all agreed to keep in line with JOSE/JWK, in this case it aligns with Web Crypto and JOSE/JWK, I agree we can close this and move this over to #123

**Comment by vijaybh** [comment]
Removing duplicate tag because #123 was fixed without fixing this. I agree RSA1_5 isn't right, but RS1 doesn't exist in JWA any more. We need a reference for an identifier meaning RSASSA PKCS#1v1.5 with SHA-1, unless we just want to make up our own.

**Comment by jyasskin** [comment]
"RSA1_5" and "RS1" don't appear in https://w3c.github.io/webauthn/; where's the problem?

Also, should a new standard really be defining uses of SHA-1?

**Comment by vijaybh** [comment]
My mistake, I was looking at the wrong version. This got fixed as part of #321 when I dropped TPM 1.2 support. Closing.
