### ISSUE TITLE
"NotAllowedError" is in WebIDL editors draft but not in WebIDL Level 1

### ISSUE THREAD

**Issue by equalsJeffH** [w3c/webauthn#305]
"NotAllowedError" is in WebIDL editors draft but not in WebIDL Level 1

webidl editors draft: https://heycam.github.io/webidl/#notallowederror

webidl level 1 (Recommendation): https://www.w3.org/TR/WebIDL-1/#h-idl-domexception-error-names

**Comment by AngeloKai** [comment]
As long as the NotAllowedError is implemented by all three browsers and it shows up on MDN, I don't consider this an issue. @jcjones 

Of course, for sanity sake, we can also try to put this error back in WebIDL Level 1. @travisleithead

**Comment by equalsJeffH** [comment]
this issue is in reference to #302

**Comment by equalsJeffH** [comment]
@AngeloKai suggested:
> we can also try to put ["NotAllowedError"] back in WebIDL Level 1. 

well, WebIDL Level 1 is now a Recommendation, so that likely will not occur.  this issue is essentially an editorial bookkeeping one and is not of major concern as you noted above wrt implementation status.

**Comment by equalsJeffH** [comment]
@AngeloKai noted:
> As long as the NotAllowedError is implemented by all three browsers and it shows up on MDN, I don't consider this an issue. 

I don't know about actual impl status in browsers, but `NotAllowedError` is not as yet listed on https://developer.mozilla.org/en-US/docs/Web/API/DOMException#Error_codes

**Comment by AngeloKai** [comment]
@kpaulh @jcjones does either of you know if Chrome or Firefox has implemented the "NotAllowedError". If not, maybe I can file a bug on this on Bugzilla. Once the bug is closed, I will make a edit change on MDN. Edge has already implemented it.

**Comment by jyasskin** [comment]
Chrome has it: https://cs.chromium.org/chromium/src/third_party/WebKit/Source/core/dom/DOMException.cpp?type=cs&q=NotAllowedError+file:WebKit&l=148.

**Comment by equalsJeffH** [comment]
looks like NotAllowedError is supported in Firefox: https://dxr.mozilla.org/mozilla-central/source/xpcom/base/ErrorList.h#532-533

**Comment by AngeloKai** [comment]
@equalsJeffH WebKit appears to support this as well: https://bugs.webkit.org/show_bug.cgi?id=158393. Unfortunately, I don't have a Mac right next to me to test it #PoliticalCorrectThumbUpfromWindows. Anyway, I will submit a edit change to MDN to make the NotAllowedError official.

**Comment by equalsJeffH** [comment]
ok, thx, so we can use `NotAllowedError` in the spec tho it'd be best (i suppose) to reference https://heycam.github.io/webidl/#notallowederror for it, and the WebIDL Level 1 spec for the other DOMExceptions.

**Comment by jyasskin** [comment]
I've added it to [MDN](https://developer.mozilla.org/en-US/docs/Web/API/DOMException).

**Comment by selfissued** [comment]
This affects interop, so we should decide this for the Implementer's Draft.

**Comment by equalsJeffH** [comment]
this issue is only about details wrt referencing where "NotAllowedError" is defined (and whether or not it is implemented (it seems it largely is impl'd) and does not affect interop in and of itself. :)   So I would remove [priority:implementation] label and re-add [type:editorial]

**Comment by equalsJeffH** [comment]
I had noted:
> this issue is only about details wrt referencing where "NotAllowedError" is defined (and whether or not it is implemented (it seems it largely is impl'd) 

I note that "NotAllowedError" is auto-linking to the WebIDL editor's draft (as are all webidl autolinks in the webauthn spec). 

so given noting both of the above, am closing this issue.
