### ISSUE TITLE
key-attestation: KeyHandle in attestaion rawData type="packed"

### ISSUE THREAD

**Issue by equalsJeffH** [w3c/webauthn#31]
<a href="https://github.com/equalsJeffH"><img src="https://avatars.githubusercontent.com/u/226571?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Originally submitted by: [equalsJeffH](https://github.com/equalsJeffH)**, on: _Tuesday Dec 08, 2015 at 00:07 GMT_

----

section "3.4.1.1 Attestation rawData (type="packed")" -- in the rawData table, after the public key and before clientDataHash length, there is a KeyHandle and its length, like so..

```
2 	        Byte length l of KeyHandle
(length) 	KeyHandle (l bytes)

```
What is this for?  is it extraneous?  it is not mentioned elsewhere in this spec or in the other two specs.

**Comment by equalsJeffH** [comment]
<a href="https://github.com/rlin1"><img src="https://avatars.githubusercontent.com/u/2264687?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Original poster: [rlin1](https://github.com/rlin1)**, on: _Friday Jan 08, 2016 at 09:01 GMT_

----

It is the KeyID and reflected in the Credential structure returned by makeCredential.

**Comment by vijaybh** [comment]
Stamp out references to term KeyHandle

**Comment by rlin1** [comment]
and replace by CredentialID
