### ISSUE TITLE
Consider scoping Account and ClientData

### ISSUE THREAD

**Issue by kpaulh** [w3c/webauthn#312]
They may be too generically named.

**Comment by equalsJeffH** [comment]
hm, am not sure why that might be the case. Are they not qualified as Navigator.authentication.{Account,ClientData} ?

**Comment by mikewest** [comment]
No. `dictionary Account` and `dictionary ClientData` define global names (as do all the interfaces, etc).

**Comment by equalsJeffH** [comment]
thx @mikewest & @kpaulh 

how do these renaming suggestions look?
> Account -> RelyingPartyAccount
>
> ClientData -> WebAuthnClientData or AuthenticationClientData  (see also #311 #310 #288)

**Comment by kpaulh** [comment]
Those look good to me. Thanks, Jeff!

**Comment by equalsJeffH** [comment]
See PR #344 for further discussion, e.g., https://github.com/w3c/webauthn/pull/344#pullrequestreview-23139144
