### ISSUE TITLE
Should a FIDOAssertion on an Android platform use AndroidAttestationClientData?

### ISSUE THREAD

**Issue by equalsJeffH** [w3c/webauthn#32]
<a href="https://github.com/levangongPayPal"><img src="https://avatars.githubusercontent.com/u/10441380?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Originally submitted by: [levangongPayPal](https://github.com/levangongPayPal)**, on: _Wednesday Dec 09, 2015 at 01:08 GMT_

----

Section 3.4.3.3 indicates that the Android attestation statement uses an extended version of the clientData structure defined in the Signature spec (called AndroidAttestationClientData).

On Android platform, should a FIDOAssertion also use the same definition or stick to the structure defined in the Signature spec?

**Comment by vijaybh** [comment]
Should be fixed in #76. Please open new issues if this is not sufficient.
