### ISSUE TITLE
overall security considerations section or document

### ISSUE THREAD

**Issue by equalsJeffH** [w3c/webauthn#322]
Presently, the webauthn spec only has security (and privacy) considerations (sec cons) for Attestation. There are actually much more broad sec cons to document, especially given this is both a Web API and a cryptographic protocol spec.  For an example of comprehensive sec cons that are largely applicable to WebAuthn, see: 

https://fidoalliance.org/specs/fido-uaf-v1.1-rd-20161005/fido-security-ref-v1.1-rd-20161005.html

**Comment by equalsJeffH** [comment]
see also: https://www.w3.org/TR/security-privacy-questionnaire/

**Comment by nadalin** [comment]
I believe if we wanted to point to the FIDO document there would be no IPR issues but a logistical issue, so to use text from the FIDO document we would have to get the document as a contribution from FIDO much like the original specifications.

**Comment by equalsJeffH** [comment]
Also, the spec ought to have a separate "privacy considerations" section.

**Comment by equalsJeffH** [comment]
an [overall security considerations section](https://w3c.github.io/webauthn/#security-considerations) was recently added to the spec via PR #681.  however, IMO, to close this issue it ought to be enhanced to explain that the present web authn sec cons are incomplete, update the ref to [[FidoSecRef]]  to a newer version, and to please refer to [[FidoSecRef]] for further info.  we could/should then open another issue regarding having thorough webauthn-specific security considerations.

WDYT?

**Comment by equalsJeffH** [comment]
on 29-Nov-2017 webauthn call: https://github.com/w3c/webauthn/issues/322#issuecomment-347936349 sounds like nominally OK plan, for attempting to attain CR maturity level.
