### ISSUE TITLE
tokenBinding member of ClientData should be tokenBindingId

### ISSUE THREAD

**Issue by equalsJeffH** [w3c/webauthn#323]
Suggest renaming `tokenBinding` member of ClientData to `tokenBindingID`

from https://tools.ietf.org/html/draft-ietf-tokbind-protocol-11#section-5:
```
Security tokens can be bound to the TLS layer either by embedding the 
Token Binding ID in the token [or other protocol atrifacts such as protocol
 message components] ...
```

**Comment by selfissued** [comment]
Let's change this to tokenBindingID now and be done with it.

**Comment by selfissued** [comment]
We will do this.
