### ISSUE TITLE
timeoutSeconds options should just be timeout in ms?

### ISSUE THREAD

**Issue by bfgeek** [w3c/webauthn#324]
https://w3c.github.io/webauthn/#dom-scopedcredentialoptions-timeoutseconds
https://w3c.github.io/webauthn/#dom-assertionoptions-timeoutseconds

As per:
https://w3ctag.github.io/design-principles/#milliseconds

The web doesn't have any apis in seconds. milliseconds should be used instead?

**Comment by bfgeek** [comment]
Just `timeout` is used in other apis.

https://w3c.github.io/web-nfc/#the-nfcpushoptions-dictionary

**Comment by vijaybh** [comment]
Closely related to #299 and should be fixed at the same time.

**Comment by equalsJeffH** [comment]
thx @vijaybh -- i marked as duplicate but hadn't ref'd #299 doh

**Comment by vijaybh** [comment]
Addressed by #333
