### ISSUE TITLE
"rp" isn't a widely enough known acronym?, should be relyingParty instead?

### ISSUE THREAD

**Issue by bfgeek** [w3c/webauthn#325]
This is pure bikeshedding, but I wonder if "rp" is a widely enough known acronym? I'd argue not, and attributes should expand this, e.g. 

https://w3c.github.io/webauthn/#dom-assertionoptions-rpid -> `relyingPartyId`
https://w3c.github.io/webauthn/#dom-scopedcredentialoptions-rpid -> `relyingPartyId`
https://w3c.github.io/webauthn/#dom-account-rpdisplayname -> `relyingPartyDisplayName`

**Comment by nadalin** [comment]
RP is very widely known but I have no issue with relyingParty except the verboseness

**Comment by equalsJeffH** [comment]
fyi/fwiw, to expand on @nadalin's reply: "RP"/"Relying Party" is a term of art used throughout the greater "[federated] identity" (and authentication) protocol community {SAML, OpenID [Connect], OAuth, FIDO, etc}.  I've no objection to spelling it out. See also #180.

**Comment by equalsJeffH** [comment]
@AngeloKai asked:
> can you give some examples of the word "rp" used in OAuth or other established spec.

see e.g.:
https://www.bing.com/search?q=site%3Aopenid.net%20"rp"
https://www.bing.com/search?q=site%3Aopenid.net+%22relying+party%22
https://www.bing.com/search?q=site%3Amicrosoft.com%20"rp"%20"relying%20party"

**Comment by selfissued** [comment]
This is widely known and proposes an unnecessary change that makes the spec no better.  I am closing the issue on this basis.
