### ISSUE TITLE
hashAlg -> hashAlgorithm?

### ISSUE THREAD

**Issue by bfgeek** [w3c/webauthn#326]
The whole word "algorithm" is used elsewhere in the spec:
https://w3c.github.io/webauthn/#dom-scopedcredentialparameters-algorithm

But is abbreviated in clientData, should be consistent?
https://w3c.github.io/webauthn/#dom-clientdata-hashalg

**Comment by nadalin** [comment]
agree for consistency

**Comment by selfissued** [comment]
This seems like a reasonable name change request for consistency reason.  Let's do this for the Implementer's Draft and then close the issue.

**Comment by selfissued** [comment]
We will do this.

**Comment by equalsJeffH** [comment]
will fix in #464

**Comment by equalsJeffH** [comment]
actually, will do this in another PR, like a sweep-up-all-the-outstanding-renaming-stuff PR.  #464 is complex enough.
