### ISSUE TITLE
excludeList and allowList should be excludeCredentials and allowCredentials

### ISSUE THREAD

**Issue by bfgeek** [w3c/webauthn#327]
In dictionary types a sequence list is typically a plural name, e.g.
https://webbluetoothcg.github.io/web-bluetooth/#dictdef-requestdeviceoptions

https://w3c.github.io/webauthn/#dom-assertionoptions-allowlist -> `allowCredentials`
https://w3c.github.io/webauthn/#dom-scopedcredentialoptions-excludelist -> `excludeCredentials`

?

**Comment by selfissued** [comment]
This seems like a reasonable renaming request, for consistency reasons.  Let's do this for the Implementer's Draft and then close the issue.
