### ISSUE TITLE
"ScopedCred" enum should be "scoped-cred"

### ISSUE THREAD

**Issue by bfgeek** [w3c/webauthn#328]
https://w3c.github.io/webauthn/#dom-scopedcredentialtype-scopedcred

As per 
https://w3ctag.github.io/design-principles/#casing-rules

**Comment by bfgeek** [comment]
or even better `scoped-credential` to be consistent?

**Comment by equalsJeffH** [comment]
see also: #296

**Comment by vijaybh** [comment]
See also #291

**Comment by selfissued** [comment]
`scoped-credential` seems reasonable.  We should address this renaming issue for the Implementer's Draft, since it affects the API.

**Comment by equalsJeffH** [comment]
see also #296

**Comment by selfissued** [comment]
This is related to issue #328 and PR #384

**Comment by jyasskin** [comment]
I believe this was fixed by #432.

**Comment by equalsJeffH** [comment]
yep, thx, closing.
