### ISSUE TITLE
Too generic names?

### ISSUE THREAD

**Issue by bfgeek** [w3c/webauthn#329]
A lot of the IDL names are a little too generic in the spec?

E.g. 
`Attachment` -> `CredentialAttachment` ?
`Transport` -> ???
`Account` -> ???
The above don't particularly matter as they aren't exposed...

But a closer look at:
`clientData` -> ???
`getAssertion` - no idea what this is doing from the method name?

**Comment by equalsJeffH** [comment]
see also #312

**Comment by selfissued** [comment]
This (and other renaming issues) affects the API, and so should be decided for the Implementer's Draft.

**Comment by selfissued** [comment]
@equalsJeffH will make proposals.

**Comment by equalsJeffH** [comment]
only two left to address are..

Attachment -> CredentialAttachment ?
Transport -> ???

**Comment by AngeloKai** [comment]
@equalsJeffH @bfgeek I'd prefer having a concrete proposal if we were to make the code change. CredentialAttachment seems fine to me. For transport, I don't see major problem with it. Let's set a timeline of a week. If no one proposes a concrete proposal about the name change within a week, we should just close this.

**Comment by bfgeek** [comment]
I'm not going to propose names for this working group as it's outside my area of expertise. Generic names are generally bad, as you aren't within a silo when you write a spec, you need to play name with the rest of the web platform.

For example, which would you name `Transport` if RTC already claimed this name? E.g.  `RTCIceTransportPolicy` was named `Transport` for some reason.

The TAG will probably have similar feedback to this effect.

**Comment by rlin1** [comment]
authenticatorAttachment and authenticatorTransport?

**Comment by equalsJeffH** [comment]
@rlin -- works for me :)
