### ISSUE TITLE
Key-Attestation: no point compression in the Packed attestation

### ISSUE THREAD

**Issue by equalsJeffH** [w3c/webauthn#34]
<a href="https://github.com/levangongPayPal"><img src="https://avatars.githubusercontent.com/u/10441380?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Originally submitted by: [levangongPayPal](https://github.com/levangongPayPal)**, on: _Thursday Dec 10, 2015 at 00:44 GMT_

----

What is the reasoning for not supporting point compression for the EC key in the packed attestation?

**Comment by vijaybh** [comment]
Because it's not widely supported.
