### ISSUE TITLE
Client arguments should be specified with "partial dictionary AuthenticationExtensions"

### ISSUE THREAD

**Issue by jyasskin** [w3c/webauthn#346]
https://w3c.github.io/webauthn/#dictdef-authenticationextensions says
> This is a dictionary containing zero or more extensions as defined in [§8 WebAuthn Extensions](https://w3c.github.io/webauthn/#extensions).

However, section 8 doesn't define any extensions to this dictionary. I suspect that the [client argument](https://w3c.github.io/webauthn/#client-argument) for each extension should actually be the type of a new dictionary member on `AuthenticationExtensions`. e.g.:

> 9.1. FIDO AppId
> ...
> ```idl
> partial dictionary AuthenticationExtensions {
>   BufferSource fido_appid;
> };
> ```

(In this case the client processing would check that the buffer contained valid UTF-8.)

Alternately, you could specify AuthenticationExtensions as a

```idl
typedef record<DOMString, any> AuthenticationExtensions
```

And have the client processing do any type checking manually. This would work better if any extension names need to include `.`s.

**Comment by selfissued** [comment]
It's not clear to me that there's an actual problem with the way it's specified now.  Is there a compelling reason for a change (and if so, will that change result in an API change) or can we simply decide that the way it is now is fine.  If it would result in an API change, we need to decide this for the Implementer's Draft.

**Comment by selfissued** [comment]
@jyasskin - could you please review this issue in light of PR #389 having been merged and let us know if there's anything left to do, and if so, what?  Thanks.

**Comment by jyasskin** [comment]
Ideally, client extension inputs would include IDL like:

```idl
partial dictionary AuthenticationExtensions {
  DOMString appid;
};
```

or

```idl
partial dictionary AuthenticationExtensions {
  BufferSource txAuthGeneric;
};
```

or

```idl
partial dictionary AuthenticationExtensions {
  AuthenticatorSelectionList authnSel;
};
```

For everything except `txAuthGeneric`, I think the text you have is clear enough for all implementers to write the same IDL themselves, so this shouldn't have `priority:implementation`.

**Comment by jyasskin** [comment]
This was fixed by changing [`AuthenticationExtensions` to `record<DOMString, any>`](https://w3c.github.io/webauthn/#iface-authentication-extensions).

**Comment by selfissued** [comment]
This design is being used as part of addressing #626 and #738
