### ISSUE TITLE
Add getAuthenticatorInfo to the Authenticator Model section

### ISSUE THREAD

**Issue by AngeloKai** [w3c/webauthn#349]
Both the attachment parameter and the verification-gesture parameter requires the client to query the authenticator for capabilities prior to the official makeCredential and getAssertion call. Should we add a getAuthenticatorInfo operation to the model section?

**Comment by selfissued** [comment]
This proposes an API change.  Therefore, we should decide it for the Implementer's Draft.

**Comment by jyasskin** [comment]
In #410 I suggest replacing the whole section with a reference to CTAP (https://github.com/fido-alliance/fido-2-specs/blob/master/fido-client-to-authenticator-protocol.html). However, since that's private to FIDO, it's hard to evolve these in parallel. If the FIDO folks can't make their editor's draft public, then it'd still help to explicitly say that the interface is copied from there so that readers know that conflicts should be resolved in favor of CTAP.

**Comment by AngeloKai** [comment]
@jyasskin Agreed. AFAIK the CTAP spec is not going to be made public anytime soon. We should include the links so readers know where the spec comes from. However, we should also make it clear that as long as the authenticator implements the interfaces described in that section, the Web API should work as well. There's always the possibility that a new CTAP 2.0 shows up.

**Comment by selfissued** [comment]
I'm OK with the section saying that the Authenticator Model will be authoritatively defined by the FIDO 2 CTAP spec.  But until a version of that is public that's in sync with WebAuthn, we really can't delete it from WebAuthn.  It explains too much that would otherwise be just a mystery.

**Comment by equalsJeffH** [comment]
See also #176 "clarify nomality of authenticator model"

**Comment by jyasskin** [comment]
In #410 I concluded that I was wrong about where the canonical interface should be defined, so 👍 to defining getAuthenticatorInfo here.

**Comment by equalsJeffH** [comment]
concur w/ @jyasskin

**Comment by equalsJeffH** [comment]
note that [authenticatorGetInfo() is defined in the CTAP draft spec in section 4.4](https://fidoalliance.org/specs/fido-v2.0-rd-20161004/fido-client-to-authenticator-protocol-v2.0-rd-20161004.html#authenticatorgetinfo)

**Comment by AngeloKai** [comment]
@equalsJeffH do you have a more recent version of the CTAP spec?

**Comment by equalsJeffH** [comment]
@AngeloKai: will send info directly.

**Comment by selfissued** [comment]
@equalsJeffH will create a PR

**Comment by AngeloKai** [comment]
We agreed on the TPAC WebAuthn WG F2F that this should be moved to PR.

**Comment by rlin1** [comment]
Note that the RD version of CTAP2 is now available online at: https://fidoalliance.org/specs/fido-v2.0-rd-20170927/fido-client-to-authenticator-protocol-v2.0-rd-20170927.html

**Comment by AngeloKai** [comment]
Closing as discussed on the call.

**Comment by AngeloKai** [comment]
Closing because CTAP2 describes this in detail.
