### ISSUE TITLE
References to "algorithm" and "alg" should be same string

### ISSUE THREAD

**Issue by jovasco** [w3c/webauthn#351]
*ScopedCredentialParameters* uses "algorithm" and *Packed Attestation Statement* uses "alg".

The first string is passed to and the second string passed from the authenticator. They should use the same string either "algorithm" or "alg" mostly for consistency and readability but there are space considerations as well: now we need 2 string constants in the applet.

I understand this is done for brevity of the reply but I question if this actually makes a useful difference:  an attestation reply should be approaching 1k depending on the certificate, so what do the 6 bytes matter? or the 50 or so you might save over all the strings?

And if that matters, why not do it for the incoming data as well? Each byte there adds just as much to the round trip delay.

**Comment by zcorpan** [comment]
One possible reason for spelling it "alg" is to avoid misspellings of "algorithm". 🙂

**Comment by jovasco** [comment]
Excellent reason :)

**Comment by selfissued** [comment]
Given space/bandwidth constraints of some authenticator communication channels, we should use the shorter form "alg" in both cases.

**Comment by selfissued** [comment]
We should change this to "alg" in PublicKeyCredentialParameters since it's sent on the wire to the authenticator.
