### ISSUE TITLE
Track rename issues to maintain consistency

### ISSUE THREAD

**Issue by AngeloKai** [w3c/webauthn#353]
A number of renaming request has been added to the issue list. Opening up this issue to track all the related request so we have a holistic view of all the changes requested: 

- https://github.com/w3c/webauthn/issues/326:
   - hashAlg -> hashAlgorithm 
- https://github.com/w3c/webauthn/issues/329: 
   - Attachment -> CredentialAttachment 
   - getAssertion -> ? 
- https://github.com/w3c/webauthn/issues/312:
   - Account -> RelyingPartyAccount
   - ClientData ->  AuthenticationClientData
- https://github.com/w3c/webauthn/issues/329: 
   - Attachment -> CredentialAttachment 
   - getAssertion -> ? 
- https://github.com/w3c/webauthn/issues/328:
   - ScopedCred -> scoped-cred
- https://github.com/w3c/webauthn/issues/296:
   - Too much to list at once 
- https://github.com/w3c/webauthn/issues/291:
   - ScopedCred -> ScopedCredential 
- https://github.com/w3c/webauthn/issues/327:
   - allowList -> allowCredentials
   - excludeList -> excludeCredentials
- https://github.com/w3c/webauthn/issues/325:
   - rpId -> relyingPartyId
   - rpDisplayName -> relyingPartyDisplayName
- https://github.com/w3c/webauthn/issues/323:
   - tokenBinding -> tokenBindingID

Please feel free to keep adding issues on this thread.

**Comment by AngeloKai** [comment]
Additional issues related to renaming: 

- https://github.com/w3c/webauthn/issues/80:
    - script / browser scripts / javascript / etc. -> RP client-side component 
    - the server / server / servers / WebAuthn Relying Party's server -> RP server-side component
- https://github.com/w3c/webauthn/issues/180: 
    - Relying Party -> WebAuthn Relying Party 
- https://github.com/w3c/webauthn/issues/351: 
    - Use the same reference when talking about algorithm and alg

**Comment by equalsJeffH** [comment]
@AngeloKai thanks for this shepherding effort. 

wrt #180, it should more accurately be described as..
* Relying Party -> WebAuthn Relying Party [at 1st use of [RP] in major sections]

**Comment by equalsJeffH** [comment]
perhaps we ought to edit the list in the original post rather than have a disjointed list spread across multiple posts?

that said, we should include pointers to relevant PRs, e.g.:

* PR #344 has further discussion of #312

**Comment by vijaybh** [comment]
Possible link to #60 since we are discussing rationalizing namespace wrt Credential Management.

**Comment by equalsJeffH** [comment]
a convenient way to group issues/PRs is to use the github.com "label" functionality. So I've created "subtype:" labels, e.g., "subtype:renaming", and assigned the latter to all the issues/PRs listed above at this time.  that makes it one-click easy to get a list of so-labeled items.

**Comment by selfissued** [comment]
We should verify that all the renaming issues use the https://github.com/w3c/webauthn/labels/subtype%3Arenaming lablel and then close this issue.

**Comment by equalsJeffH** [comment]
AFAIK we are consistently using the "subtype:renaming" label and so am closing this issue.
