### ISSUE TITLE
Fetch intergration for WebAuthn API

### ISSUE THREAD

**Issue by AngeloKai** [w3c/webauthn#354]
As many of you know, the Fetch API is getting used more and more across the web. Integration with the Fetch API could help drive more usage for this API and give additional security protection for the credentials generated. The [Credential Management API ](https://w3c.github.io/webappsec-credential-management/#fetch-integration) has also integrated with Fetch and took up a namespace in the Fetch spec already. Opening up an issue to keep track of Fetch integration. If we decide this is out of scope for this version, we can certainly close this.

**Comment by selfissued** [comment]
If doing this will change the API, we should determine the impact of the change before the Implementer's Draft.  If it's strictly an addition that can be added later, we can decide to proceed without it for now.

**Comment by jyasskin** [comment]
FWIW, #384 (https://api.csswg.org/bikeshed/?url=https://raw.githubusercontent.com/battre/webauthn/cm-api-strawman/index.bs#iface-scopedcredential) doesn't propose to hide the signature from Javascript, so it doesn't need `PasswordCredential`'s Fetch involvement, just like `FederatedCredential` doesn't need it.

https://github.com/whatwg/fetch/pull/237#issuecomment-194765426 does anticipate extending Fetch for FIDO, but I suspect they didn't realize that it was safe to expose WebAuthn's response to JS.

@mikewest, do you agree with me that it'd be ok to just close this?

**Comment by mikewest** [comment]
FWIW, we're having a healthy debate internally around whether the XSS protections offered to `PasswordCredential` are worth the pain of forcing developers through Fetch, or whether we're making perfect the enemy of the good.

If y'all reach similar conclusions with `ScopedCredential`, then you won't need Fetch integration. If you do need Fetch integration, I think you'll be able to piggyback on what's there for `PasswordCredential` simply by defining a body extraction algorithm. Should be straightforward.

**Comment by AngeloKai** [comment]
We can continue debating whether this is necessary. I am leaning toward fetch integration for now due to my interest in delivering a clean networking surface. Either adding fetch integration or not should not impact this API surface but rather just impact the Fetch spec. Therefore I removed the implementation tag.

**Comment by jyasskin** [comment]
There's an API effect here if you decide you want to hide some data from JS in order to defend against XSS, like PasswordCredential attempts. If you can expose all the data (as you're doing now), then there's no need for an API change here when you add Fetch support.

**Comment by AngeloKai** [comment]
Agreed with @jyasskin. Closing the issue.
