### ISSUE TITLE
User Verification definition needs to be refined

### ISSUE THREAD

**Issue by gmandyam** [w3c/webauthn#357]
As per WD-04:  https://www.w3.org/TR/webauthn/#terminology, the definition of User Verification does not address whether the verification takes place within the authenticator boundary.  Recommend adding the following sentence immeidately after 'Note that invocation of said operations implies use of key material managed by the authenticator':  
"Therefore the user verification operation must take place within the restricted operating environment of the authenticator itself."

**Comment by vijaybh** [comment]
IMO it would be better to say something like "In other words, user verification and use of credential private keys must occur within a single logical security boundary" so we do not write in assumptions about authenticator construction. For example, you could do the two operations under different ROEs with an authenticated secure channel between them.

**Comment by gmandyam** [comment]
@vijaybh 

I like that wording.  Do you mind if I create a PR for this?

**Comment by equalsJeffH** [comment]
@gmandyam, I went ahead and did it because there were other associated things to weave in, hope that's ok, please see #365.
