### ISSUE TITLE
Editorial: use more elaborate variable names

### ISSUE THREAD

**Issue by annevk** [w3c/webauthn#359]
Can we just spell out what rp in rpId stands for? Or is it a widely understood term of art that I don't know about? Each time I see that I'm confused.

**Comment by annevk** [comment]
(Also because it sometimes holds a host and was also used as an origin at some point.)

**Comment by jyasskin** [comment]
"rp" stands for ["Relying Party"](https://w3c.github.io/webauthn/#relying-party), which seems to be widely used in the OAuth and maybe federated-identity community. I've no objection to spelling it out.

**Comment by equalsJeffH** [comment]
fwiw, "RP"/"Relying Party" is definitely a term of art used throughout the greater "[federated] identity" (and authentication) protocol community {SAML, OpenID [Connect], OAuth, FIDO, etc}.  

given we have an overall tracking issue for this overall topic of "use more elaborate variable names" #353, as well as the label [[subtype:renaming](https://github.com/w3c/webauthn/labels/subtype%3Arenaming)], plus this being essentially a duplicate of #325, shall we close it?

**Comment by annevk** [comment]
Fair.

**Comment by AngeloKai** [comment]
@equalsJeffH can you give some examples of the word "rp" used in OAuth or other established spec.

**Comment by equalsJeffH** [comment]
"rp" is an acronym :)
as I noted in https://github.com/w3c/webauthn/issues/325#issuecomment-282518587, I've no objection to spelling it out.  further answer to your question is over in #325 (since we've closed this issue as a duplicate).

**Comment by selfissued** [comment]
The terminology section of OpenID Connect Core http://openid.net/specs/openid-connect-core-1_0.html#Terminology includes a definition for "Relying Party (RP)".  Lots of other identity specs use the term Relying Party (RP) as well.  I believe that "RP" is well-understood in identity contexts.
