### ISSUE TITLE
define what to do if both normalizedAlgorithm and cryptoParameters are empty

### ISSUE THREAD

**Issue by equalsJeffH** [w3c/webauthn#361]
in this makeCredential() alg step..
> If |normalizedParameters| is empty and {{cryptoParameters}} was not empty,
>    cancel the timer started in step 2, return [=a promise rejected with=] with
>    a {{DOMException}} whose name is "{{NotSupportedError}}", and terminate this
>    algorithm.

..we do not define what to do if both normalizedAlgorithm and cryptoParameters are empty.

**Comment by selfissued** [comment]
Given that this behavior will affect interop, we should decide it for the Implementer's Draft.

**Comment by equalsJeffH** [comment]
no longer applicable
