### ISSUE TITLE
Constrain the "reasonable range" of timeouts

### ISSUE THREAD

**Issue by jyasskin** [w3c/webauthn#364]
https://w3c.github.io/webauthn/#makeCredential says:
> If the timeout member of options is present, check if its value lies within a reasonable range as defined by the platform

I believe the spec should constrain that range somewhat. For example, to say that the range must allow timeouts between 1s and 10s.

**Comment by equalsJeffH** [comment]
Seems like an implementation consideration?

**Comment by equalsJeffH** [comment]
@jcjones says in https://github.com/w3c/webauthn/pull/347#discussion_r103741955:
Straw man: I chose [15,120] seconds as the range for timeouts in the first Firefox implementation. Under 15 seconds seems too short to dig out a security key, and making things blink for more than two minutes seemed cruel.
