### ISSUE TITLE
Credential CBOR

### ISSUE THREAD

**Issue by apowers313** [w3c/webauthn#366]
A few thoughts on simplifying the attestation credential CBOR in [Section 5.3.1](https://www.w3.org/TR/webauthn/#sec-attestation-data):
* Convert the CBOR map to a CBOR array / list with values at well-known positions in the array: 0 = alg; 1 = x; 2 = y; etc. This makes the final size smaller, since CBOR maps use strings for the indexes. Currently the difference is only two bytes ("alg" = 3 bytes; "x" = 1 byte; "1" = 1 byte; total 5 bytes as opposed to 3 bytes when using array indexes), but if new algorithms are added that have long strings for keys it may make a bigger difference.
* The CDDL currently specifies using "biguint" and "uint" for the various crypto parameters. These are essentially [semantically tagged](https://tools.ietf.org/html/rfc7049#section-2.4) byte strings. I would suggest just using byte strings instead of "biguint" and "uint". Although the current spec is is more semantically correct, adding semantic tags is just extra overhead and only creates difficulties when trying to encode / decode with off-the-shelf CBOR libraries.

**Comment by equalsJeffH** [comment]
this comment on now-merged-and-closed PR #321 is perhaps apropos to this issue: https://github.com/w3c/webauthn/pull/321#discussion_r96979991

**Comment by selfissued** [comment]
When we're representing keys in CBOR, I believe that we should use the COSE_Key format defined in https://tools.ietf.org/html/draft-ietf-cose-msg-24 (which is about to become an RFC).  As a rule, we should avoid defining different data formats when standard ones are defined that will work well for our application.

**Comment by apowers313** [comment]
@selfissued I assume you're talking about the COSE_Key format illustrated in [Section C.7.1](https://tools.ietf.org/html/draft-ietf-cose-msg-24#page-118)?

**Comment by selfissued** [comment]
Yes, and defined in [Section 7](https://tools.ietf.org/html/draft-ietf-cose-msg-24#section-7) .

**Comment by apowers313** [comment]
@selfissued Is it just me, or do the key parameters in [Section 13](https://tools.ietf.org/html/draft-ietf-cose-msg-24#section-13) (and specifically 13.1) only describe how to use COSE for EC and not RSA?

**Comment by selfissued** [comment]
Good point.  I should have mentioned that that's why https://tools.ietf.org/html/draft-jones-cose-rsa exists.  It's being sponsored by Security Area Director Kathleen Moriarty to become an RFC.  The FIDO use cases were part of the motivation for Kathleen agreeing to sponsor this. :-)

**Comment by selfissued** [comment]
Vijay had suggested that we state that only the required fields will be used.  I agree with that.

On the 15-Mar-17 working group call, we agreed to use the COSE Key representation.

**Comment by selfissued** [comment]
We need to change to the COSE_Key key representation for the Implementer's Draft.

**Comment by equalsJeffH** [comment]
we changed to cose_key so closing this
