### ISSUE TITLE
Add keyStorage enum to ScopedCredentialOptions

### ISSUE THREAD

**Issue by AngeloKai** [w3c/webauthn#367]
Authenticators with cross-platform roaming capability may or may not store key materials within the authenticator boundary. If an authenticator doesn't store key material, the RP needs to do additional actions of storing keys. Additionally, in our current spec, getAssertion call can be initiated by only providing RP ID and that means the call isn't initiated with any key material at all. 

Therefore, I propose we add a new enum called keyStorage to the options dictionary, with two values: "client" and "server". If the former value is supplied, the authenticator must store key material. If the latter value is supplied, the authenticator won't store any value at all and the server will take care of storing the key materials. If no value is supplied, that means the RP doesn't care about storage and is ok with this cornercase.

**Comment by gmandyam** [comment]
@AngeloKai 

Will there be provisions in the PR for non-roaming authenticators to ignore a keyStorage option where "server" is specified?  Or would the makeCredential() fail if the authenticator cannot export key meaterial to the RP?

Also, "client" as an option is misleading.  "Client" is Webauthn is defined as "Conforming User Agent" - not the same as authenticator (in fact it is clearly distinct).

**Comment by rlin1** [comment]
I don't think that authenticator typically would want to implement both options.
I one authenticator can store the key material locally, then there is no need and no benefit (IMHO) to store the key wrapped at the RP.

So rather than introducing yet another concept of dynamically controlling the authenticator behavior, we should assume a static key storage location, i.e. one AAGUID will always store keys in the same way (either locally or remotely in wrapped form).
If we do so, the already have the ability for the RP to select authenticator based on AAGUIDs - and hence no need to further complicate the API.

**Comment by equalsJeffH** [comment]
@AngeloKai wrote:
> Authenticators with cross-platform roaming capability may or may not store key materials within the authenticator boundary

what you mean by "key materials" is actually the [credential private key](https://w3c.github.io/webauthn/#credential-private-key), yes?

> If an authenticator doesn't store key material, the RP needs to do additional actions of storing keys.

The implicit assumption in the spec has been that such authenticators (authnrs) would simply use their wrapped private keys as the credential ID they return to the RP.  This is how most (all?) U2F authenticators work today, yes? 

from the U2F Raw Messages spec:
> A key handle ... This a handle that allows the U2F token to identify the generated key pair. U2F tokens MAY wrap the generated private key and the application id it was generated for, and output that as the key handle. 

The RP always needs to retain the Credential ID returned by makeCredential() and so it is transparent to the RP whether or not it is storing the credential private key.

This is another candidate item to spell out more clearly in the spec in an "implementation considersations" section.

**Comment by equalsJeffH** [comment]
@vijaybh replied to my above observations here: https://github.com/w3c/webauthn/pull/378#issuecomment-288467611

I am assuming further discussion of this issue is occurring in the PR #378 and not here in this issue.

**Comment by jyasskin** [comment]
Fixed by #429.
