### ISSUE TITLE
follow Bluetooth and NFC brand usage guidance

### ISSUE THREAD

**Issue by equalsJeffH** [w3c/webauthn#373]
Bluetooth has a "Bluetooth Brand Guide" whose guidance we ought to follow editorially.  NFC is likely to have similar guidance.

**Comment by selfissued** [comment]
Specific changes should be proposed.  Otherwise, this issue is far from actionable.

**Comment by equalsJeffH** [comment]
The first (admittedly only implied) action is for someone to sign up to review the "Bluetooth Brand Guide" and then propose (or just make) whatever editorial changes we need to be in compliance.  Same wrt NCF  and USB.

**Comment by wseltzer** [comment]
Since we're making nominative references, I don't have legal worries.

**Comment by equalsJeffH** [comment]
Ok, thx @wseltzer, I suggest we go ahead and close this so we do not re-discuss yet again on some future call - yes?
