### ISSUE TITLE
Credential.id currently assumed to be RP unique

### ISSUE THREAD

**Issue by equalsJeffH** [w3c/webauthn#38]
<a href="https://github.com/rlin1"><img src="https://avatars.githubusercontent.com/u/2264687?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Originally submitted by: [rlin1](https://github.com/rlin1)**, on: _Friday Jan 08, 2016 at 12:04 GMT_

----

getAssertion returns Assertion.  Assertion includes id as the only method to map it to a specific user account.
Until now FIDO assumed the pair of (AAID/AAGUID/attestationCertificateKeyIdentifier, KeyID) to be RP unique.  
In FIDO2 KeyID has been replaced by Credential.id.
At this time there is no guaranteed way to derive the AAGUID from a FIDOAssertion.
As a result we implicitly assume KeyID (i.e. Credential.id) to be RP unique.

**Comment by equalsJeffH** [comment]
<a href="https://github.com/rlin1"><img src="https://avatars.githubusercontent.com/u/2264687?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Original poster: [rlin1](https://github.com/rlin1)**, on: _Friday Jan 08, 2016 at 12:06 GMT_

----

We could resolve that by making extension "fido.aaguid" mandatory to be included in FIDOAssertion.authenticatorData.
Other opinions?

**Comment by vijaybh** [comment]
Closely related to #16 and could be answered with the same text quoted there. Will look to see if this can be made clearer with editorial changes.
