### ISSUE TITLE
Should the WebAuth API have a cancel() method?

### ISSUE THREAD

**Issue by kpaulh** [w3c/webauthn#380]
Hey gang,

The spec details an authenticatorCancel method, but the client doesn't necessarily know when to invoke it. We have seen a couple scenarios where not having a way to cancel an existing authenticator operation from Javascript might present an undesirable user experience. 

For example, having multiple tabs that are attempting operations and losing focus on one. The user opens two registration tabs. The device will blink until it receives two taps.
 
Since promises aren't themselves cancelable, it seems that a cancel() method is the best option - assuming these use cases are concerning enough to warrant one. (We're not entirely convinced that they are). We also briefly considered having smaller timeouts, say, 10 seconds, but this presents problems for bluetooth authenticators. 

Thoughts?

**Comment by jyasskin** [comment]
I believe @jakearchibald is working on promise cancellation in the context of `fetch()` and may be able to say how WebAuth can match that.

**Comment by jakearchibald** [comment]
We plan to represent cancellation by rejecting with an `AbortError`. Here's the latest proposal https://github.com/whatwg/fetch/issues/447#issuecomment-281731850.

**Comment by vijaybh** [comment]
It seems that this puts good UI at the mercy of every web developer. This seems wrong.

The UA could for example cancel operations when a tab is occluded. But it seems like that would not require a Javascript method for the webpage to do so?

**Comment by equalsJeffH** [comment]
see also #318 "Define what happens when the Document loses focus"

**Comment by kpaulh** [comment]
I think you meant #316. I see. Right, the browser could certainly handle losing focus.
However, as another example, we also have scenarios involving in-page Javascript that can change UI without navigation or losing focus that I believe is currently being used for some security-key related flows.

**Comment by kpaulh** [comment]
@mikewest boiled down the `fetch` proposal for canceling promises into a pretty simple mechanism with [https://github.com/whatwg/dom/pull/434](url). Rather than adding an explicit cancel() method, we would  `makeCredential` and `getAssertion` accept a `CancellationSignal`.

I believe this is a pretty good fit for our use-case - if we decided this was something we needed to do.

**Comment by jyasskin** [comment]
The PR moved to https://github.com/whatwg/dom/pull/437.

**Comment by equalsJeffH** [comment]
@jyasskin notes on call today that the web platform folks are working on a general cancellation mech and it will likely be another option -- @AngeloKai sez he'll talk with their fetch folks to see what the status is on what's mentioned in  https://github.com/w3c/webauthn/issues/380#issuecomment-292223973

**Comment by mikewest** [comment]
Looks like this has solidified into https://dom.spec.whatwg.org/#aborting-ongoing-activities.

**Comment by jakearchibald** [comment]
It sure has! Is it suitable for what you need?

**Comment by AngeloKai** [comment]
@mikewest The PR looks enough for this need. Looking through the PR, it looks like we still need to add a few sentences in our algorithm section about how we accept the AbortSignal.

**Comment by AngeloKai** [comment]
Because the issue has to do with changing the algorithm and this issue would impact cornercase user experience, I am moving the issue back to WD07.

**Comment by jcjones** [comment]
Closed by #544
