### ISSUE TITLE
daaKey format? (ECPointToB -> ECPoint2ToB)

### ISSUE THREAD

**Issue by sjparkRaon** [w3c/webauthn#385]
The format of daaKey in packedStmtFormat is not in the format eccPubKey.

I think it should be ECPoint2ToB instead of ECPointToB.
(reference to [https://fidoalliance.org/specs/fido-uaf-v1.1-id-20170202/fido-ecdaa-algorithm-v1.1-id-20170202.html#encoding-ecpoint2-values-as-byte-strings-ecpoint2tob])

Thank you for your guide.

**Comment by rlin1** [comment]
I think we have two options here
a) directly encoding the full ECDAA Issuer public key here, in this case it would be ECPoint2ToB result or
b) use the c value of the public key (as defined in section 3.3 step 3.5) in which case it would be the result of BigNumberToB.

using b) is shorter (less bytes) and avoids accidentally "forgetting" to verify the ECDAA Issuer public key to the trust store.  So I prefer option b at this time - other opinions welcome.

**Comment by rlin1** [comment]
see PR #381

**Comment by sjparkRaon** [comment]
Yes, I understand your comment.

I am waiting for final specification.

 

Thank you for your guide.

**Comment by vijaybh** [comment]
I believe this is addressed in #381, with option (b) as enumerated by Rolf.

**Comment by sjparkRaon** [comment]
May I have a question about TPM?

 

I wonder how to unmarshaling about TPM types (e.g. TPMS_ATTEST,TPMT_PUBLIC,TPMT_SIGNATURE). 

So I summarize several questions.

 

-       What is the endian for unmarshal for TPM types (eg TPMS_ATTEST, TPMT_PUBLIC, TPMT_SIGNATURE)?

-       Is the standard for this part "TSS System Level API and TPM Command Transmission Interface Specification"?

 

Please answer about those question.

 

Thank you for your guide.
