### ISSUE TITLE
Consider empty allowLists

### ISSUE THREAD

**Issue by jyasskin** [w3c/webauthn#387]
https://w3c.github.io/webauthn/#getAssertion currently says:

> 11. For each authenticator currently available on this platform, perform the following steps:
>     1. Let *credentialList* be a new list.
>     1. If `options.allowList` is not empty, execute a platform-specific procedure to determine which, if any, credentials in `options.allowList` are present on this authenticator by matching with `options.allowList.id` and `options.allowList.type`, and set *credentialList* to this filtered list.
>     1. If *credentialList* is empty then continue.

If `allowList` is empty, `credentialList` remains empty, and every authenticator is skipped, which makes the call less than useful. However, not all examples include an `allowList` (e.g. https://w3c.github.io/webauthn/#sample-extensions), and the [`AssertionOptions`](https://w3c.github.io/webauthn/#dictdef-assertionoptions) definition defaults it to the empty list instead of making it required. #378 also wants to remove the technical need to pass an ID through the `allowList` for every `getAssertion()` call.

I think the spec should either consistently avoid empty `allowList`s or make them work, but I don't have an opinion which.

**Comment by selfissued** [comment]
This affects interop and so should be decided for the Implementer's Draft.

**Comment by equalsJeffH** [comment]
@jyasskin wrote:
> If `allowList` is empty [when getAssertion() is called], `credentialList` remains empty, and every authenticator is skipped...

Good catch, thx. My understanding is that we need to make empty `allowList` work, and the semantics ought to be that if the `allowList`is empty, the RP is saying "please use any credential you may have associated with my RP ID", and on the client side a platform-specific procedure is used to determine whether any such credentials exist.  Yes?

**Comment by jyasskin** [comment]
That sounds roughly right. Would it help to explicitly distinguish credentials that can be generated with just the RP ID vs credentials that can't be generated without the RP providing the credential's ID?

**Comment by vijaybh** [comment]
Right, this was the intention. @jyasskin, the distinction you mention is what #378 was trying to capture - that PR is providing a way for an RP to telegraph that they will be calling getAssertion with an empty allowList, so the client should only create a credential that would be usable in this way.
