### ISSUE TITLE
Define AuthenticatorVersion extension

### ISSUE THREAD

**Issue by equalsJeffH** [w3c/webauthn#39]
<a href="https://github.com/rlin1"><img src="https://avatars.githubusercontent.com/u/2264687?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Originally submitted by: [rlin1](https://github.com/rlin1)**, on: _Friday Jan 08, 2016 at 12:16 GMT_

----

At this time only TPMs include the AuthenticatorVersion.
We want the ability to include the AuthenticatorVersion in attestation "packed" and also FIDOAssertion.authenticatorData.

**Comment by equalsJeffH** [comment]
<a href="https://github.com/rlin1"><img src="https://avatars.githubusercontent.com/u/2264687?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Original poster: [rlin1](https://github.com/rlin1)**, on: _Friday Jan 08, 2016 at 12:17 GMT_

----

Proposed extension ID: "fido.aversion".  Contents is an unsigned long value.

**Comment by vijaybh** [comment]
Only way to get a new attestation is to get a new credential. RPs will most likely just let the user in (perhaps after additional verification) and ask them to create a new credential.
