### ISSUE TITLE
Protect against TLS MiTM by including TLS cert chain in signature

### ISSUE THREAD

**Issue by leshi** [w3c/webauthn#391]
While I know token binding can do this as well, this doesn't necessarily require the server (or client) to modify as much of the stack.

The idea is that the client includes the cert chain info in the client data, the token signs over this.  Server can verify that the client saw the expected chain.  If it doesn't, the server may have a bit more info on who's doing a man in the middle than it might otherwise know with token binding.

h/t to Sam Srinivas

**Comment by selfissued** [comment]
Changing the signature calculation would break interop.  Therefore we should decide this before the Implementer's Draft.

**Comment by rlin1** [comment]
I think MITM protection is very important and TokenBinding is not ubiquituous yet. 
So I am in favor of this addition.

**Comment by sampaths** [comment]
We should allow for the ability to choose what part of the cert chain should be included. A typical large entity, say www.bigcompany.com would have a TLS terminating front end in a CDN which may be using multiple valid www.bigcompany.com certs across instances of the front end. 

The backend server doing the webauth validation would not know which particular cert is being used -- but it will know something about the cert chain which is shared across all valid certs for Bigcompany.com  -- for eg, the intermediate CA etc. If we include just that part of the cert chain which is common across all www.bigcompany.com certs then the purpose is served. 

We should think about API options where the server can specify what parts of the chain it wants inside the signed object.

**Comment by agl** [comment]
Browsers (at least Chrome) do not have a concept of the certificate chain for an origin. Pages can be loaded from disk cache, so there might not an active TLS connection at the time that the Javascript is running. Also, as sampaths notes, an origin can have many certificate chains (even at the same time).

**Comment by equalsJeffH** [comment]
I agree that MITM/replay protection is important but this approach is (not immediately obviously) complex as noted by @agl and implied by @sampaths. Token binding / Channel ID / TLS Channel binding are all _more-or-less_ standardized-and-implemented approaches and I'm thinking we should rely on them at our specification level, and work to usher along implementations as we can.

**Comment by agl** [comment]
From the weekly call: closing with no action.

**Comment by mrts** [comment]
Is there really a need to include the certificate chain? As far as I can see and as suggested in the mailing list, certificate fingerprint is sufficient. Here's a detailed proposal for including it in `clientDataJSON` with a semi-formal proof that it mitigates the attack:

https://gitlab.com/mrts/webauthn-additions/wikis/Mitigation-for-man-in-the-middle-attack-against-WebAuthn-by-a-powerful-attacker

And here's the successful attack scenario:
https://gitlab.com/mrts/webauthn-additions/wikis/Man-in-the-middle-attack-against-WebAuthn-by-a-powerful-attacker

See also discussion in the mailing list. Any feedback regarding the proposal would be greatly appreciated.

Note that this is no longer only a theoretical issue in the light of the recent ICANN alert regarding attacks on the Domain Name System:
https://www.icann.org/news/announcement-2019-02-15-en

Use of Token Binding would protect the authentication flow against man-in-the-middle attacks. However, Token Binding is not widely supported by browsers, Chrome is deprecating it and proxy usage is problematic; the server application can see if token binding is missing but it is not obvious if that is malicious or a proxy has stripped it off. So as of now, two years later, there is no protection against this attack by browsers and nothing concrete is on horizon (please correct me if I'm wrong).

What was the rationale of closing this during the weekly call?
