### ISSUE TITLE
U2F Attestation only lists Basic Attestation as supported

### ISSUE THREAD

**Issue by rlin1** [w3c/webauthn#392]
See section 7.6 "FIDO U2F Attestation Statement Format"
Attestation types supported: Basic

In principle the authenticator could also generate self-signed attestation certificates which meet the definition of self-attestation as described in section 5.3.3.
Plus the current Mozilla Firefox U2F implementation uses this concept.

So I suggest adding self-attestation of the list of supported attestation types in section 7.6.

**Comment by equalsJeffH** [comment]
we should do this

**Comment by emlun** [comment]
Now the spec instead doesn't say how to detect when the `fido-u2f` attestation statement format uses self attestation. It seems like that would be when `attStmt.x5c[0]` is self-signed, correct? Either way I think the verification procedure in [§7.6][1] should make some mention of self attestation, as currently

- the only occurence of the word "self" in §7.6 is in the list of supported attestation types; and
- the final step of the verification procedure says to always return attestation type Basic. While this is technically correct as the returned `x5c` is indeed the entire trust path, it is confusing.

[1]: https://www.w3.org/TR/webauthn/#fido-u2f-attestation
