### ISSUE TITLE
rename "attestation data" to be "attested credential"

### ISSUE THREAD

**Issue by equalsJeffH** [w3c/webauthn#393]
Presently it is difficult to trace through the spec and find where amongst the returned Attestation Object lies the `credential` (returned by authenticatorMakeCredential()). and it is not intuitive to search the text for "attestation data" when looking for the credential object and its components that's created as a result of makeCredential() (or likely-soon-to-be create()).

See figure 3 -- the returned credential object and its components is presently `AttestationObject.AuthData.AuthenticatorData.{AAGUID, cred PK length, credential id, credential public key}`, however one cannot simply textually search the spec and figure this out (yet), because most all of that mega-datastructure is defined in tables (without names for the components) and is not specified in webIDL and thus not hyperlinked. [Figure 3](https://w3c.github.io/webauthn/#fig-attStructs) is the only way to presently really figure it out. 

Although aspects of this will be resolved by PR #384, other aspects depend on resolution of #233. Part of resolving #233 ought to be renaming "attestation data" to be (i suggest) "attested credential (attestedCredential)" or perhaps "attested credential data (attestedCredentialData)" .  Note that we are using the term "attested credential public key" in section [Credential Attestation](https://w3c.github.io/webauthn/#cred-attestation) (presently 5.3).

**Comment by selfissued** [comment]
I think we should do this, since it will be clearer.

**Comment by rlin1** [comment]
+1

**Comment by equalsJeffH** [comment]
part of fixing this is where we say..

> The attestationObject attribute contains an attestation object. The
   contents of this object are determined by the attestation statement
   format used by the authenticator.

..to rather say something like..
>  [ acknowledging that the authnData portion of attstnObj is constant, and it is only the attStmt portion of attstnObj that differs based on attStmt format type ]

..because the former is incorrect in that it is saying the attstnObj's format is determined by the attestation statement format, where it is actually only a component of the attstnObj that varies per attestation stmt format.

**Comment by jcjones** [comment]
Agreed.

**Comment by AngeloKai** [comment]
Confirmed at the WG that this doesn't impact API  interface.
