### ISSUE TITLE
Structure of Credential ID

### ISSUE THREAD

**Issue by equalsJeffH** [w3c/webauthn#40]
<a href="https://github.com/leshi"><img src="https://avatars.githubusercontent.com/u/1407369?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Originally submitted by: [leshi](https://github.com/leshi)**, on: _Thursday Jan 14, 2016 at 22:33 GMT_

----

From the current Web API spec <https://www.w3.org/Submission/2015/SUBM-fido-web-api-20151120/>:
> The id attribute contains an identifier for the credential, chosen by the platform with help from the authenticator. This identifier is used to look up credentials for use, and is therefore expected to be globally unique with high probability across all credentials of the same type. This API does not constrain the format or length of this identifier, except that it must be sufficient for the platform to uniquely select a key.

The Platform/Client will want to specify various metadata wrt to the id.  For example, which transports the id should be sent over.  Since various Platforms/Clients should be able to understand the metadata (i.e., Windows should be able to tell Android that an id is only useful over USB and should not be sent over BLE), the format of this metadata should be standardized.

It's not clear where this standardization should take place.  One option is to make the Credential ID be an object in the Web API.

**Comment by vijaybh** [comment]
Possibly related to #6.

**Comment by vijaybh** [comment]
RPs should write defensive code that blocks credential IDs that are ridiculously large.
