### ISSUE TITLE
How to unmarshal in TPM Structure.

### ISSUE THREAD

**Issue by sjparkRaon** [w3c/webauthn#400]
I wonder how to unmarshaling about TPM types (e.g. TPMS_ATTEST,TPMT_PUBLIC,TPMT_SIGNATURE). 
So I summarize several questions.

-	What is the endian for unmarshal for TPM types (eg TPMS_ATTEST, TPMT_PUBLIC, TPMT_SIGNATURE)?
-	Is the standard for this part "TSS System Level API and TPM Command Transmission Interface Specification"?

Thank you for your guide.

**Comment by vijaybh** [comment]
The correct reference is [TPMv2-Part2], as noted in the TPM attestation section of the spec. This spec includes a reference implementation in C, so the behavior is unambiguously defined.
