### ISSUE TITLE
attObj and Figure 3 [[#fig-attStructs]] do not agree

### ISSUE THREAD

**Issue by equalsJeffH** [w3c/webauthn#401]
in [5.3.4. Generating an Attestation Object](https://w3c.github.io/webauthn/#generating-an-attestation-object), we have this CDDL description:
```
attObj = {
            authData: bytes,
            $$attStmtType
         }

attStmtTemplate = (
                      fmt: text,
                      attStmt: bytes
                  )

; Every attestation statement format must have the above fields
attStmtTemplate .within $$attStmtType
```
Tho, in [Figure 3](https://w3c.github.io/webauthn/#fig-attStructs), the `Attestation Object` is illustrated (in part) as having this core structure:
```
ATTESTATION OBJECT
                     [ "fmt": "packed", ... | "authData": ... | "attStmt": ...  ]
```
If nothing in the rest of the spec is depending upon the ordering illustrated in [Figure 3](https://w3c.github.io/webauthn/#fig-attStructs), then perhaps, if I am correct that this is an issue, we can just adjust Figure 3 to reflect reality?  

A cursory look thru the rest of the spec seems to indicate that we can just repair Figure 3 to be something like:

```
ATTESTATION OBJECT
                     [  "authData": ... |  "fmt": "packed"  |  "attStmt": ... ]
```

**Comment by vijaybh** [comment]
+1, I had meant to make this change as part of the CDDL PR and just forgot.

**Comment by equalsJeffH** [comment]
there's also some other things in that figure that are messed up, eg "credential ID" and "credential public key" overrunning each other up in the so-called attestation data object. see also #393.

**Comment by selfissued** [comment]
Let's get this fix in for WD-05.  There's no reason not to.
