### ISSUE TITLE
Should we remove the algorithm from FIDOCredentialInfo?

### ISSUE THREAD

**Issue by equalsJeffH** [w3c/webauthn#41]
<a href="https://github.com/vijaybh"><img src="https://avatars.githubusercontent.com/u/9886086?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Originally submitted by: [vijaybh](https://github.com/vijaybh)**, on: _Friday Jan 15, 2016 at 21:48 GMT_

----

The public key returned by makeCredential is not meant to be examined by the client, it is only relevant to the RP. So it seems better to return it in a compact format as is done by EAP, and not bother with algorithm at all.

**Comment by equalsJeffH** [comment]
<a href="https://github.com/rlin1"><img src="https://avatars.githubusercontent.com/u/2264687?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Original poster: [rlin1](https://github.com/rlin1)**, on: _Friday Mar 04, 2016 at 23:09 GMT_

----

Public Key is an object which already includes the alg

**Comment by equalsJeffH** [comment]
<a href="https://github.com/equalsJeffH"><img src="https://avatars.githubusercontent.com/u/226571?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Original poster: [equalsJeffH](https://github.com/equalsJeffH)**, on: _Friday Mar 04, 2016 at 23:09 GMT_

----

need to adj the type of the public key to structured type and remove the alg identifier

**Comment by leshi** [comment]
Closing as per pull req #56
