### ISSUE TITLE
Replace Authenticator Model with CTAP

### ISSUE THREAD

**Issue by jyasskin** [w3c/webauthn#410]
The [WebAuthn Authenticator model](https://w3c.github.io/webauthn/#authenticator-model) looks like the same interface as [CTAP's Authenticator API](https://fidoalliance.org/specs/fido-v2.0-rd-20161004/fido-client-to-authenticator-protocol-v2.0-rd-20161004.html#authenticator-api), but less precisely specified. If that's correct, I think it would be cleaner to have the WebAuthn spec define just the behavior of the Client (UA), and call out to CTAP when it needs the authenticator to do something.

**Comment by equalsJeffH** [comment]
see also #176 "clarify normality of authenticator model - is it actually authenticator API ?"

**Comment by equalsJeffH** [comment]
After thinking about it some, I am going to venture a guess that the overall intention of having the [WebAuthn Authenticator model](https://w3c.github.io/webauthn/#authenticator-model) defined "somewhat fuzzily" is that it gives platform developers wiggle-room for defining their specific authenticator APIs.  It seems that [CTAP's Authenticator API](https://fidoalliance.org/specs/fido-v2.0-rd-20161004/fido-client-to-authenticator-protocol-v2.0-rd-20161004.html#authenticator-api) is a particular instance of such an API.   

So I suppose that the platform folks and authenticator vendors here ought to weigh-in on whether they would be prefer to have the WebAuthn Authenticator model](https://w3c.github.io/webauthn/#authenticator-model) defined in this somewhat fuzzy fashion, or whether they feel having CTAP's API become the normative authenticator API is the way to go.

**Comment by selfissued** [comment]
I think I agree that we want to leave the fuzzy authenticator model definition in WebAuthn because not all authenticators will use the CTAP interface.  Some will be built directly into the platform.  That said, we should ensure that the WebAuthn authenticator model and the CTAP one correspond in the future.

**Comment by AngeloKai** [comment]
@selfissued Agreed. The reality is all three implementers at the table are probably supporting different authenticator model during the initial launch and will gradually converge to support the same set of authenticators.

**Comment by jyasskin** [comment]
Also, as filed in https://github.com/fido-alliance/fido-2-specs/issues/239, CTAP doesn't do a better job of specifying the behavior of these algorithms; it's just a little better at listing parameters. I think this issue turns out to have been misguided, and that we should just clean up the specification in WebAuthn and treat it as the ruling spec.

**Comment by equalsJeffH** [comment]
@jyasskin said:
> ...we should just clean up the specification in WebAuthn and treat it as the ruling spec.

might you more precisely spell out what this means to you? thx :)

**Comment by jyasskin** [comment]
:) I should file a collection of issues. Roughly:
1. Interfaces like https://w3c.github.io/webauthn/#op-make-cred should give precise types for the parameters and return values. These types should probably be CBOR specified with CDDL, but could be WebIDL.
2. The algorithms in https://w3c.github.io/webauthn/#op-make-cred should number their steps, and the steps should be precise about how the authenticator should act. The current precision is close, but for example it should describe the difference between storing the key and encrypting it into the credential ID. Calling out to existing FIDO specs is totally fine.
3. Specs like CTAP should describe how to convert the parameters from WebAuthn's types to transferrable types, transfer them, and then convert back to WebAuthn's types in order to call the algorithm bodies, and similarly for the results.

**Comment by equalsJeffH** [comment]
Ah, ok, thanks, that helps. 

> 1. Interfaces like https://w3c.github.io/webauthn/#op-make-cred should give precise types for the parameters and return values. These types should probably be CBOR specified with CDDL, but could be WebIDL.

and/or define how the WebIDL types are mapped to the CDDL/CBOR types?

> 2. The algorithms in https://w3c.github.io/webauthn/#op-make-cred should number their steps, and the steps should be precise about how the authenticator should act. The current precision is close, but for example it should describe the difference between storing the key and encrypting it into the credential ID. 

what we've been told here by folks that ship both browsers and platforms, is that the above stuff ought to be to some degree fuzzy because their platform folks have their own approaches for developing such stuff and if it is spec'd too precisely they will feel hemmed-in. 

> Calling out to existing FIDO specs is totally fine.

well, [U2F](https://fidoalliance.org/specs/fido-u2f-v1.1-id-20160915/) might be palatable, but apparently [the UAF spec set](https://fidoalliance.org/specs/fido-uaf-v1.1-id-20170202/) is overall too precisely spec'd for some audiences (it had to be because it is how-to-implement-a-full-pswdless-and-2ndFactor-stack-without-any-existing-platform-support). However, it would seem that UAF can be usefully used as an example of how to do certain things, e.g., as we have been doing for authnr selection.

> 3. Specs like CTAP should describe how to convert the parameters from WebAuthn's types to transferrable types, transfer them, and then convert back to WebAuthn's types in order to call the algorithm bodies, and similarly for the results.

sorry, I do not understand the significance/semantics/underpinnings of "transferrable" and "transfer them"...?

**Comment by jyasskin** [comment]
1. If the authenticator model's interface is in terms of WebIDL types, then CTAP would define how to convert the WebIDL values into CBOR and back, in order to transmit them over BT, USB, or NFC. If the authenticator model's interface is in terms of CDDL/CBOR types, then WebAuthn's algorithms need to produce the appropriate CBOR data before calling them. A generic WebIDL<->CBOR mapping might be the most concise way to specify some of that, but it's probably not essential.

2. Yeah, it might be that certain steps need to allow multiple options. I did something like that with https://webbluetoothcg.github.io/web-bluetooth/#same-attribute. I think we should still be explicit about where we're allowing implementation variation, and we should put constraints on the allowable behavior. For example, using DES to encrypt the private key into the credential ID should probably not be allowed.

3. For example, https://fidoalliance.org/specs/fido-v2.0-rd-20161004/fido-client-to-authenticator-protocol-v2.0-rd-20161004.html#message-and-packet-structure specifies how the Client should take a command, which has a numeric identifier and a CBOR payload, and encode it into the USB HID protocol, and it also somewhat implicitly specifies how to identify the command and reconstruct the CBOR payload on the USB device side.

**Comment by equalsJeffH** [comment]
ok, thanks, all the above helps :)

**Comment by AngeloKai** [comment]
We should probably address this after https://github.com/w3c/webauthn/issues/349 is addressed.

**Comment by nadalin** [comment]
@AngeloKai this just seems to be editorial

**Comment by selfissued** [comment]
Closed with no action per the 28-Feb-18 working group call.
