### ISSUE TITLE
UVM should be "method" rather than "mode" ?

### ISSUE THREAD

**Issue by equalsJeffH** [w3c/webauthn#411]
In [FIDO Registry spec](https://fidoalliance.org/specs/fido-uaf-v1.1-id-20170202/fido-registry-v1.1-id-20170202.html), UVM is "User Verification Method", whereas here in webauthn spec it is "[user verification mode](https://w3c.github.io/webauthn/#sctn-uvm-extension)". I suggest we just s/method/mode/ as appropriate in webauthn spec.

**Comment by selfissued** [comment]
I'll add this correction to PR #389, given I'm already editing this part of the spec.

**Comment by selfissued** [comment]
This was addressed in PR #389 .
