### ISSUE TITLE
What does store() do?

### ISSUE THREAD

**Issue by leshi** [w3c/webauthn#415]
We should specify what `store()` does.

**Comment by jyasskin** [comment]
`store()` is intended to tell the browser that a particular Credential "worked" to authenticate with the current site. https://github.com/w3c/webappsec-credential-management/pull/77 starts to explain this in the Credential Management spec, but I think there's more to do over there, to say that the credential store actually holds information used to find credential sources to offer to the user in the [chooser](https://w3c.github.io/webappsec-credential-management/#user-mediated-selection), and then [[Store()]] here will be able to say that it records some metadata from the ScopedCredential into the credential store.

None of this behavior is visible to Javascript—it just describes how the browser can create some UI—so I don't think it's urgent to nail it down.

**Comment by AngeloKai** [comment]
fixed by https://github.com/w3c/webauthn/pull/631
