### ISSUE TITLE
Correct uses of "JSON string" versus "DOMString" and other string terminology usage

### ISSUE THREAD

**Issue by selfissued** [w3c/webauthn#417]
@jyasskin pointed out in his comment https://github.com/w3c/webauthn/pull/389#pullrequestreview-33915025 that some uses of "JSON string" should be changed to "DOMString".  We should review uses of these terms, as well as "CBOR string", uses of "UTF-8", and other string encoding/decoding language to make it consistent and correct.

**Comment by nadalin** [comment]
@selfissued can you create a PR to do this ?

**Comment by nadalin** [comment]
@selfissued verify that this has been covered in previous and if so close

**Comment by rlin1** [comment]
This USVString: http://docs.w3cub.com/dom/usvstring/
