### ISSUE TITLE
ED512 Support

### ISSUE THREAD

**Issue by equalsJeffH** [w3c/webauthn#42]
<a href="https://github.com/apowers313"><img src="https://avatars.githubusercontent.com/u/5661534?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Originally submitted by: [apowers313](https://github.com/apowers313)**, on: _Tuesday Feb 09, 2016 at 06:15 GMT_

----

Key Attestation Section 3.5 [refers to ED512](https://github.com/fido-alliance/fido-2-specs/blob/master/fido-key-attestation.html#L978-L1020). Since ED512 isn't one of the algorithms [that must be supported by a FIDO server](https://github.com/fido-alliance/fido-2-specs/blob/master/fido-key-attestation.html#L668-L671), it seems like this might be a leftover artifact of #94 and due for removal.

**Comment by equalsJeffH** [comment]
<a href="https://github.com/equalsJeffH"><img src="https://avatars.githubusercontent.com/u/226571?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Original poster: [equalsJeffH](https://github.com/equalsJeffH)**, on: _Tuesday Feb 09, 2016 at 17:04 GMT_

----

added ms-fido-v2.0-w3c milestone -- we need to address this in the newly officially-formed W3C Web Authentication WG (WebAuthn) context.

**Comment by vijaybh** [comment]
This text will be gone soon.
