### ISSUE TITLE
ECDAA verification algorithm in TPM Attestation Statement Format

### ISSUE THREAD

**Issue by sjparkRaon** [w3c/webauthn#433]
I wonder what is ECDAA verification algorithm in TPM Attestation Statement Format.
In draft specification it linked in FIDO ECDAA. but TPM Part1 Architecture specifies EC Schnorr Signature Validation. (i.e ECDAA signature algorithm in TPM is modified Schnorr Sign)

If it follows in FIDO ECDAA, then i wonder how to resolve credentials (R,S,T,W).
Thank you for your advice.

**Comment by equalsJeffH** [comment]
@rlin -- can we close this?

**Comment by rlin1** [comment]
the TPM needs to follow the signing procedure as described in FIDO ECDAA algorithm spec section "3.5.3 ECDAA-Sign Split between TPM and ASM".
The verification then needs to be according to FIDO ECDAA algorithm spec section "3.6 ECDAA-Verify Operation".

**Comment by rlin1** [comment]
can be closed IMHO.

**Comment by selfissued** [comment]
Closing, per decision on the 7-Mar-18 call.

**Comment by equalsJeffH** [comment]
really closing this per https://github.com/w3c/webauthn/issues/433#issuecomment-371238377 and https://github.com/w3c/webauthn/issues/433#issuecomment-369525077
