### ISSUE TITLE
ctsprofilematch in SafetyNet documentation not sufficiently defined

### ISSUE THREAD

**Issue by gmandyam** [w3c/webauthn#436]
As per https://developer.android.com/training/safetynet/attestation.html:  "If the value of "ctsProfileMatch" is true, then the profile of the device running your app matches the profile of a device that has passed Android compatibility testing."

What constitutes passing Android compatibility testing?  For instance, does this mean that the CTS Verifier has successfully run on the platform instance?  Can this ctsProfileMatch be set if the CTS Verifier has not been run (which is allowed under certain conditions as per Sec. 10.2 of https://source.android.com/compatibility/android-cdd.pdf)?

**Comment by equalsJeffH** [comment]
This seems to me to be a question/issue for the Android folks.   

Is your concern, wrt webauthn, that the webauthn spec lacks a concise reference to appropriate Android documentation that answers your questions above?

**Comment by gmandyam** [comment]
@equalsJeffH 

Yes.  Ideally a pre-registed attestation format would be accompanied by a complete specification.  In this case, the referenced specification appears to be incomplete.

**Comment by nadalin** [comment]
@equalsJeffH @gmandyam  this is an issue with the SafetyNet specs not WebAuthn, so this should be closed

**Comment by equalsJeffH** [comment]
@gmandyam please submit bug reports to android folks wrt their incomplete specs.
