### ISSUE TITLE
basicIntegrity in SafetyNet documentation not sufficiently defined

### ISSUE THREAD

**Issue by gmandyam** [w3c/webauthn#437]
As per https://developer.android.com/training/safetynet/attestation.html, the normative text states:  "If the value of "basicIntegrity" is true, then the device running your app likely wasn't tampered with, but the device has not necessarily passed Android compatibility testing. "

The meaning of this flag is not clear.  For instance -
What is done by the platform to determine the value of this flag?  How often is this flag updated?   Under what conditions will this flag be set to "true" when the device has been tampered with?

**Comment by equalsJeffH** [comment]
This seems to be an issue for Android. Also, the webauthn spec does not (at this time) do anything with "basicIntegrity".

**Comment by gmandyam** [comment]
@equalsJeffH 

I don't think the WebAuthn spec has specific guidance for the RP to ignore basicIntegrity either.  I assume procedures for verification that are outlined in the spec are not meant to prohibit RP's from considering all information that is returned in an attestation statement.

**Comment by nadalin** [comment]
@equalsJeffH @gmandyam this is an issue with the SafetyNet specs not WebAuthn, so this should be closed and get Google to fix their documentation

**Comment by gmandyam** [comment]
@nadalin 
SafetyNet appears in as a pre-registered attestation format in the spec.  I think a suitable solution is to remove SafetyNet from the spec, and only add it back in when sufficient documentation is provided.

**Comment by nadalin** [comment]
@gmandyam There is nothing wrong with a pre-registered attestation format, if the referenced specification is not enough to implement then people will not implement, we can't fix SafetyNet specification in WebAuthn

**Comment by selfissued** [comment]
Removing SafetyNet would have the practical consequence of decreasing the interoperability of implementations.  That's not good for anyone.  We should keep it - just like we're keeping the TPM attestation format, which is also there to increase interoperability.

**Comment by gmandyam** [comment]
@selfissued 

How can we ensure interop of an attestation format when the attestation format is not sufficiently defined?  TPM (in comparison) is a complete specification that has been vetted by many companies.  This is not the case with SafetyNet.

**Comment by gmandyam** [comment]
@nadalin 
There is something wrong with pre-registered attestation formats that are incomplete.  We should not be adding attestation formats without expert review.

**Comment by selfissued** [comment]
It's fine to ask the Googlers for the additional information needed to make this interoperable and assign it to them.  That's the right solution.  Removing a commonly-used format would hurt WebAuthn, and thus, is the wrong solution.

**Comment by gmandyam** [comment]
@selfissued 

This is exactly what I am doing - asking for the missing information from the Google 'specification'.  Note that there is no official liaison relationship defined between the W3C and Google, so I don't see any official way to request the missing information other than on the repo.  

Regarding "commonly-used", what criteria are you using to make this determination?  As far as I can tell, Android O attestation will form the basis for FIDO 2.0.

**Comment by jyasskin** [comment]
3 thoughts. Note that I'm not involved in defining that field, and I don't have an opinion on whether SafetyNet needs to be in the pre-registered attestation format:
1. https://developer.android.com/training/safetynet/attestation.html#possible-results elaborates on what kinds of circumstances result in `basicIntegrity` being true or false. Does that help at all?

2. This resembles some anti-malware efforts I've looked at, where if you're too precise about what makes something malware or if you freeze the definition, that allows malware to circumvent the protection.

3. The Verification Procedure in https://w3c.github.io/webauthn/#android-safetynet-attestation says to check the `ctsProfileMatch` field, not the `basicIntegrity` field, so maybe it doesn't matter if `basicIntegrity` is badly-specified.

**Comment by ve7jtb** [comment]
FYI this is a link to the Android Compatibility testing.  https://source.android.com/compatibility/

Someone from Google should comment, but in looking at saftyNet attestations for other things my conclusion was that ctsProfileMatch is required to trust the attestation.   A device that docent have that can't really be trusted.   basicIntegrity is a best effort to provide some integrity checks on uncertified devices, and not something that we should be using as a security attestation, it is in my opinion not really better than nothing as it is more likely to provide a false sense of security.  

I believe there are some large asian manufacturers that don't have CTS certification or license GMS so those would not be able to have a trusted soft authenticator, if they support NFC or BT people have other options.  

I think what we have checking ctsProfileMatch and ignoring basicIntegrity is fine.  
Better defining basicIntegrity for uncertified devices is not going to help anyone.

John B.

**Comment by equalsJeffH** [comment]
shall we close this issue?

**Comment by gmandyam** [comment]
No-one from Google has contradicted @ve7jtb 's interpretation, so I will assume that he is correct and the current verification procedure for SafetyNet as written is adequate.  Am closing.

**Comment by ve7jtb** [comment]
I recommend we close this issue
