### ISSUE TITLE
Android SafetyNet Attestation lacks information on authenticator provenance

### ISSUE THREAD

**Issue by gmandyam** [w3c/webauthn#438]
As per current attestation definition in https://w3c.github.io/webauthn/#terminology, "In the WebAuthn context, attestation is employed to attest to the provenance of an authenticator and the data it emits; including, for example: credential IDs, credential key pairs, signature counters, etc."

There does not seem to be specific information in the SafetyNet attestation definition (https://developer.android.com/training/safetynet/attestation.html) that describes provenance of the authenticator and its associated data.

**Comment by equalsJeffH** [comment]
Seems to me to be a case of needing impl-cons and sec-cons wrt https://w3c.github.io/webauthn/#android-safetynet-attestation

**Comment by gmandyam** [comment]
@equalsJeffH 

I don't think it is that simple.  The current text in https://w3c.github.io/webauthn/#android-safetynet-attestation states that the caller of the SafetyNet API is "typically an application running on the Android platform".  I assume therefore that such an application is the authenticator itself, and if the SafetyNet token cannot attest to its provenance then it is not a valid attestation.  

An alternative could be that the application in this case creates a Webauthn packed attestation, and includes the SafetyNet token as an extension.  If this is the approach necessary to satisfy the Webauthn requirements for attestation (as per the terminology section) for an Android SW authenticator, then the SafetyNet token should be removed from the list of acceptable Webauthn attestation formats.

**Comment by nadalin** [comment]
@equalsJeffH @gmandyam this is an issue with the SafetyNet specs not WebAuthn, so this should be closed and get Google to fix their documentation

**Comment by ve7jtb** [comment]
The saftynet attestation gives you the identity of the app.   To turn that into something useful there needs to be a registry of authenticator apps to look up the additional meta-data.  
Safetynet is not WebAuthn specific, is ther a requirement that safetynet look up the other meta data to include in the JWT?

The app could wrap the JWT but you need to look up the app info someplace anyway to validate it.
The practical question is if you use the app hash of the developer cert and the APK name directly to look it up or hand back a name that can be looked up in the meta-data service to find cert hash and APK name to validate and get meta-data.  

I guess Google could crate a new safetynet attestation format that pulled that info in to the attestation from some service but that is not a insignificant ask.   

I know I have been asking for extensions for some time for other things in the attestation:)

John B.

**Comment by gmandyam** [comment]
Provided explanatory text in https://github.com/w3c/webauthn/pull/643

**Comment by equalsJeffH** [comment]
merged PR #643 -- closing this issue.
