### ISSUE TITLE
Make AuthenticatorSelectionCriteria more complete.

### ISSUE THREAD

**Issue by rlin1** [w3c/webauthn#441]
We have an extension for selecting the authenticator based on a list of AAGUIDs, then we recently added the more generic AuthenticatorSelectionCriteria.

We should move the extension into this new AuthenticatorSelectionCriteria in order to concentrate all authenticator selection related criteria (authenticator policy) into one single entity.

**Comment by rlin1** [comment]
See branch authnr-sel-addtl-fields

**Comment by nadalin** [comment]
@rlin1 please close as PR was merged

**Comment by nadalin** [comment]
@rlin1 moving this to next level as all authenticator selection criteria enhancements are for next release

**Comment by rlin1** [comment]
Christiaan Brand: want to prevent fragmentation and hence only want generic authenticator selection criteria - not by AAGUID.
Regarding selecting TEE (or SE) backed authenticators: Not a real issue as there might be other ways on the platform to determine whether TEE backed authenticator would be available on the platform.
When making the final decision, the RP can look into attestation to verify whether the keyProtection requirement is met.

**Comment by rlin1** [comment]
Decision:Keep open for now and re-visit later.

**Comment by nadalin** [comment]
Per 03/07/19 F2F Close
