### ISSUE TITLE
Add biometric accuracy to AuthenticatorSelectionCriteria

### ISSUE THREAD

**Issue by gmandyam** [w3c/webauthn#445]
Regarding https://w3c.github.io/webauthn/#authenticatorSelection, add criteria for biometric accruacy.

Suggestion is 

dictionary BiometricAccuracy {
double FRR;  //Maximum allowable False Rejection Rate
double FAR; //Maximum allowable False Acceptance Rate
double EER;// Maximum allowable equal error rate
};

UA would raise exception if available authenticator is a biometric, its accuracy is known, and the authenticator cannot satisfy the limits provided in the selection criteria.

**Comment by rlin1** [comment]
I suggest adding such changes to branch authnr-sel-addtl-fields and the related PR #442

**Comment by nadalin** [comment]
Closing for now as there is no interest
