### ISSUE TITLE
Add required key protection to AuthenticatorSelectionCriteria

### ISSUE THREAD

**Issue by gmandyam** [w3c/webauthn#446]
Regarding https://w3c.github.io/webauthn/#authenticatorSelection, add criterion for required key protection.

Suggestion is to define
enum KeyProtection {
"SW",
"HW",
"TEE",
"SE"}

If requireResidentKey=false, then this criterion will be ignored.  If requireResidentKey=true, then the UA will raise exception if the key protection level does not meet level specified.

**Comment by jyasskin** [comment]
For the web, we'll probably want to spell out the acronyms. What do they stand for?

I suspect these are still relevant for `requireResidentKey==false`: they'd describe how the encrypt-to-self key is protected.

**Comment by gmandyam** [comment]
@jyasskin 

"SW" = software protection, "HW" = hardware protection, "TEE" = trusted execution environment, "SE" = secure element

**Comment by rlin1** [comment]
I suggest adding such changes to branch authnr-sel-addtl-fields

**Comment by rlin1** [comment]
See branch authnr-sel-keyprotection

**Comment by nadalin** [comment]
Closing for now as there is no interest
