### ISSUE TITLE
Add required matcher protection to AuthenticatorSelectionCriteria

### ISSUE THREAD

**Issue by gmandyam** [w3c/webauthn#447]
Regarding https://w3c.github.io/webauthn/#authenticatorSelection, add criterion for required matcher protection.  This field will describe the RP requirement for what type of environment the matching algorithm used for user verification is performed. 

Suggestion is to define
enum MatcherProtection {
"SW",
"TEE",
"HW"}

**Comment by jyasskin** [comment]
I believe we haven't yet added the "check it's the same user" requirement to the selection criteria (after removing it from the assertion in #431). Would it make sense to incorporate this enum into that, or is it logically orthogonal?

**Comment by rlin1** [comment]
User Verification Method and MatcherProtection are orthogonal.

**Comment by rlin1** [comment]
I suggest adding such changes to branch authnr-sel-addtl-fields and the related PR #442

**Comment by rlin1** [comment]
See branch authnr-sel-matcherprotection

**Comment by nadalin** [comment]
Closing for now as there is no interest
