### ISSUE TITLE
Fix the licensing statement

### ISSUE THREAD

**Issue by wseltzer** [w3c/webauthn#45]
Not sure why the draft has a public domain declaration, but W3C specs should be under the W3C Document License, https://www.w3.org/Consortium/Legal/2015/doc-license

**Comment by jcjones** [comment]
This was lost by a merge error, so keep this open while @vijaybh produces a follow-on fix.

**Comment by wseltzer** [comment]
It turns out that this is specified in an include file in bikeshed itself. I've made a pull request there https://github.com/tabatkins/bikeshed/pull/651

**Comment by wseltzer** [comment]
Fixed
