### ISSUE TITLE
"WebAuthn Authenticator model" seemingly prohibits random AAGUIDs (minor)

### ISSUE THREAD

**Issue by agl** [w3c/webauthn#452]
(This is a pedantic nit:)

The [section](https://www.w3.org/TR/2017/WD-webauthn-20170505/#authenticator-model) describing the authenticator model specifies that the AAGUID is a 128-bit string, and that it must be chosen to be:

> different (with probability 1-2<sup>128</sup> or greater) from the AAGUIDs of all other types of authenticators

However, once there exist two AAGUIDs in the world then choosing a random, 128-bit number is not sufficient to meet this requirement. (Because a random number would have a 2/2<sup>128</sup> chance of colliding with one of the other AAGUIDs in the world.)

It seems that this section is trying to say that random AAGUIDs are ok, but may have inadvertently, technically, forbidden them.

**Comment by nadalin** [comment]
@selfissued can you review this and make a wording proposal
