### ISSUE TITLE
Privacy section may wish to discuss recommended user-agent responses to leaks

### ISSUE THREAD

**Issue by agl** [w3c/webauthn#454]
In the [privacy section](https://www.w3.org/TR/2017/WD-webauthn-20170505/#sec-attestation-privacy), the  document may wish to recommend responses to privacy leaks by authenticators.

For example, if an authenticator manufacturer ships devices that perform basic attestation, but with unique serial numbers for the device, the user-agent may want to suppress the attestation data from that family of devices in the future. However, attestation is required in the protocol, so should the user-agent fabricate an attestation from a fictitious manufacturer in this case? Or perhaps it should make up a new attestation statement format identifier?

(Choosing not to specify this in the document is a reasonable decision, esp if the document explicitly says that. In that case, user-agents will make a decision at the time, should the situation arise, based on minimising impact to users.)

**Comment by AngeloKai** [comment]
I remembered in the last WG F2F Rolf and Jeff mentioned they intend to expand the current privacy section.

**Comment by equalsJeffH** [comment]
well, I think we were talking more in regards to security considerations.

**Comment by AngeloKai** [comment]
I talked with @equalsJeffH. I think there's a bit of difference of interpretation to how our issue assigning process works. Since I'd like to have more stale issues to be resolved, I self-assigned myself to the issue.

**Comment by agl** [comment]
Closing this because we now have `AttestationConveyancePreference` and the `none` attestation, which gives a reasonable answer for what to do here.

**Comment by emlun** [comment]
See also: #636, #693, #741

**Comment by emlun** [comment]
@agl Does this mean that inline [Issue 2][iss] is solved and can be removed?

>ISSUE 2 @balfanz wishes to add to the "direct" case: If the authenticator violates the privacy requirements of the attestation type it is using, the client SHOULD terminate this algorithm with an "AttestationNotPrivateError".

[iss]: https://w3c.github.io/webauthn/#issue-62a76e68
