### ISSUE TITLE
ensure non-native Signature Assertions are passed-through

### ISSUE THREAD

**Issue by equalsJeffH** [w3c/webauthn#465]
add support for UAF signature and assertion formats -- this will facilitate the **millions of already-deployed UAF-capable smartphones** to be usable with a WebAuthn-capable browser via CTAP (yes, a separate step is enabling the already-deployed UAF-capable smartphones to speak CTAP, which is possible)

this issue is addressed by these open PRs: #407 #408

**Comment by rlin1** [comment]
Proposal: Rephrase title to "ensure non-native signature assertions are being passed through"

**Comment by nadalin** [comment]
@rlin1 Please create a PR

**Comment by rlin1** [comment]
two changes:
a) ensure existing language in the spec does not preclude other assertions to go through
b) reference a specific assertion format that should be passed through (UAF).
