### ISSUE TITLE
authenticatorMakeCredential() description of input  PublicKeyCredentialType and cryptographic parameters is imprecise

### ISSUE THREAD

**Issue by equalsJeffH** [w3c/webauthn#467]
[authenticatorMakeCredential()](https://w3c.github.io/webauthn/#op-make-cred) description of input  PublicKeyCredentialType and cryptographic parameters is imprecise. it currently says:
> The PublicKeyCredentialType and cryptographic parameters requested by the Relying Party, with the cryptographic algorithms normalized as per the procedure in Web Cryptography API §algorithm-normalization-normalize-an-algorithm.

Given current steps 8 & 9 in {#createCredential} section, the above should say something more like:
> A sequence of pairs of PublicKeyCredentialType and cryptographic algorithms (a dictionary type) requested by the Relying Party, where the cryptographic algorithms are normalized as per the procedure in Web Cryptography API §algorithm-normalization-normalize-an-algorithm. This sequence is is ordered from most preferred to least preferred. The platform makes a best-effort to create the most preferred credential that it can.

**Comment by selfissued** [comment]
This looks good to me.

**Comment by jcjones** [comment]
LGTM. 👍

**Comment by AngeloKai** [comment]
LGTM.
