### ISSUE TITLE
The FIDO Metadata Service needs a non-FIDO analogous mechanism

### ISSUE THREAD

**Issue by jcjones** [w3c/webauthn#47]
Right now the WebAuthn specification utilizes the FIDO Metadata Service to determine facts about authenticators, such as characteristics and certificates. We should consider developing a similar capability that does not depend on one organization.

**Comment by rlin1** [comment]
There are specification for
a) Metadata Statements, i.e. a way how to describe authenticator characteristics and
b) Metadata Service, i.e. how to provide a list of authenticators with pointers to their respective authenticator characteristics.

These specs are not dependent on any specific service provider - they just describe the format.

**Comment by nadalin** [comment]
These specifications are out of scope for this WG but if these can be referenced then we should do so.

**Comment by vijaybh** [comment]
The spec just says FIDO metadata service is an example of the kind of place you can get data to make a trust decision. An RP may choose to use this, another service or none at all. Clarify text to say this.
