### ISSUE TITLE
restrict webauthn support to "valid domains" ?

### ISSUE THREAD

**Issue by equalsJeffH** [w3c/webauthn#474]
per [URL](https://url.spec.whatwg.org/), the [host](https://url.spec.whatwg.org/#concept-host) component of a [tuple origin](https://html.spec.whatwg.org/#concept-origin-tuple) [[HTML](https://html.spec.whatwg.org/)] "is a domain, an IPv4 address, an IPv6 address, an opaque host, or an empty host". 

In HSTS [[RFC6797](https://tools.ietf.org/html/rfc6797)] we decided to support HSTS Policy for only hosts expressed as domain names:
```
Appendix A.  Design Decision Notes
[...]

   4.  HSTS Hosts are identified only via domain names -- explicit IP
       address identification of all forms is excluded.  This is for
       simplification and also is in recognition of various issues with
       using direct IP address identification in concert with PKI-based
       security.
```

Thus, shall we add restrictions to this effect to WebAuthn?

Proposed update to the "Let |effectiveDomain| be ..." step in both #createCredential and #getAssertion algs:
```
1. Let |effectiveDomain| be the |callerOrigin|'s [=effective domain=]. 
    If [=effective domain=] is not a [=valid domain=], then return a
    {{DOMException}} whose name is "{{SecurityError}}" and terminate this algorithm.

    Note: [=host=] formats other than [=domain=] -- i.e., [=ipv4 address=],
        [=ipv6 address=], [=opaque host=], or [=empty host=] -- are disallowed.
```
See also: https://url.spec.whatwg.org/#valid-domain

**Comment by jcjones** [comment]
This change also looks good as-is. 👍

**Comment by herrjemand** [comment]
@equalsJeffH by "valid domain", are you referring to: https://url.spec.whatwg.org/#valid-domain-string?

**Comment by nadalin** [comment]
mike to create pr

**Comment by equalsJeffH** [comment]
@herrjemand, I could go either way on this, I think given the way the URL and HTML specs are presently written that using either `[=valid domain=]` or `[=valid domain string=]` is correct.

**Comment by jcjones** [comment]
Out of the two, I would prefer "valid domain string", as WD-06 types RP ID as a "domain string" elsewhere.
