### ISSUE TITLE
Public draft images return 404

### ISSUE THREAD

**Issue by herrjemand** [w3c/webauthn#486]
Reading through the public draft on w3c(https://www.w3.org/TR/webauthn/), I found that image links are returning 404. Works fine on github(https://w3c.github.io/webauthn/) though. 
https://www.w3.org/TR/webauthn/images/fido-attestation-structures.svg
https://www.w3.org/TR/webauthn/images/fido-signature-formats-figure2.svg
https://www.w3.org/TR/webauthn/images/fido-signature-formats-figure1.svg

**Comment by herrjemand** [comment]
Same issue for CredAPI https://www.w3.org/TR/credential-management-1/#user-mediated-selection

**Comment by equalsJeffH** [comment]
this was discussed in this thread: https://lists.w3.org/Archives/Public/public-webauthn/2017May/0174.html

sam W. reported in: https://lists.w3.org/Archives/Public/public-webauthn/2017May/0184.html
> The first-pass advice from those more familiar with the tools is 
"publish another WD".  If that fails, we can try to debug further.

..though no one has republished WD-05 as yet.  :(

**Comment by AngeloKai** [comment]
@equalsJeffH I will try republishing later tonight. Wendy helped me out last time because there was a bug with the publication. @wseltzer is there any caveat with re-publishing, such as I should remove the old link first?

**Comment by wseltzer** [comment]
Aha, the problem is that the links to images aren't absolute, so we either need to upload them to the w3.org site or use absolute references.

**Comment by AngeloKai** [comment]
@wseltzer Can you please let me know how I should upload the images? We can also try the absolute references approach but keeping things under w3c control is probably a good idea.

**Comment by equalsJeffH** [comment]
> We can also try the absolute references approach but keeping things under w3c control is probably a good idea.

the images are spec-version-specific, so really need to be submitted along with the rendered spec itself.  It appears we did this successfully in all the prior public working draft releases, so there is perhaps some magic to perform at publication time?  we may need to ask @vijaybh since IIRC he pub'd the prior ones.

**Comment by wseltzer** [comment]
ok, for this draft, fixed by uploading the images to the WD-specific directory (
https://www.w3.org/TR/2017/WD-webauthn-20170505/) from whence they also show up in the /TR page.

**Comment by herrjemand** [comment]
Thanks @wseltzer! It werkes!

**Comment by AngeloKai** [comment]
Just for record keeping purpose, the reason why we didn't submit it through echnida is because of the following issue:

**Comment by jyasskin** [comment]
Filed in specberus as https://github.com/w3c/specberus/issues/622.

**Comment by tripu** [comment]
(I edited https://github.com/w3c/webauthn/issues/486#issuecomment-306911763 right now just to wrap  chunks of HTML in backticks, so that the markup is shown.)
