### ISSUE TITLE
MakeCredentialOptions should be MakePublicKeyCredentialOptions

### ISSUE THREAD

**Issue by equalsJeffH** [w3c/webauthn#488]
`AssertionOptions` became `PublicKeyCredentialRequestOptions`

`ScopedCredentialOptions` became `MakeCredentialOptions`

MakeCredentialOptions should be MakePublicKeyCredentialOptions for consistency and clarity.

**Comment by nadalin** [comment]
Mike to create PR and merge

**Comment by selfissued** [comment]
I will create a PR for this

**Comment by jcjones** [comment]
:+1: let's do it

**Comment by selfissued** [comment]
This was addressed by PR #511 .
