### ISSUE TITLE
CredentialCreationOptions can't have a nullable MakeCredentialOptions

### ISSUE THREAD

**Issue by qdot** [w3c/webauthn#490]
The CrednetialCreationOptions dictionary definition lists the MakeCredentialOptions member as nullable. According to the WebIDL spec, dictionary type members of dictionaries cannot be nullable.

https://www.w3.org/TR/WebIDL-1/#idl-nullable-type

**Comment by equalsJeffH** [comment]
@mikewest @battre  --  do you know why https://w3c.github.io/webauthn/#credentialcreationoptions-extension and https://w3c.github.io/webauthn/#credentialrequestoptions-extension are using nullable types, and whether it is legit or not? thx.

**Comment by jyasskin** [comment]
FWIW, I don't see a good reason to make those fields nullable. They're already optional because they don't say `required`, and we don't need to be able to spell "not there" both `undefined` and `null`.

**Comment by equalsJeffH** [comment]
Ok, so we can just delete the "?"s in both of..
```
partial dictionary CredentialCreationOptions {
    MakeCredentialOptions? publicKey;
};

partial dictionary CredentialRequestOptions {
    PublicKeyCredentialRequestOptions? publicKey;
};
```

..and we are good?

**Comment by battre** [comment]
We need these to be nullable because we extend the CredentialCreationOptions type that is shared by all profiles of the Credential Management API.

The following would have a nulled publicKey but would be valid:
navigator.credentials.create({password: {...}});

**Comment by jyasskin** [comment]
@battre: `navigator.credentials.create({password: {...}})` creates a dictionary with a [not present](https://heycam.github.io/webidl/#dfn-present) `publicKey` member, not a `null` one. You only need these fields to be nullable in the dictionary if you want to enable and give a meaning to `navigator.credentials.create({publicKey: null})`, which I don't think you do.

**Comment by battre** [comment]
That makes sense. Thanks for educating me.
