### ISSUE TITLE
update #credentialcreationoptions-extension & #credentialrequestoptions-extension section titles

### ISSUE THREAD

**Issue by equalsJeffH** [w3c/webauthn#497]
update #credentialcreationoptions-extension & #credentialrequestoptions-extension section titles such that they are not confused with (webauthn) "extensions". e.g.:

### `CredentialRequestOptions` Dictionary Extension ### {#credentialrequestoptions-extension}

**Comment by AngeloKai** [comment]
I get the interest in furthering clarifying this. Perhaps an easy fix is to get the word 'extension" from the section titles?

**Comment by equalsJeffH** [comment]
i would rather just add "Dictionary" to the titles as illustrated above.

**Comment by equalsJeffH** [comment]
might as well fix this for CR. PR #734 is now open.
