### ISSUE TITLE
Specify how to handle authenticators that are plugged after registration/signing is requested

### ISSUE THREAD

**Issue by kpaulh** [w3c/webauthn#508]
The spec's algorithms specify enumerating all available authenticators and then calling the respective authenticator methods on them. It appears not to allow users to attach any authenticators in the middle of this process, which currently is common behavior.

One solution might be to be notified whenever new authenticators show up and dispatch authenticatorMakeCredential / authenticatorGetAssertion on the latecomer.

**Comment by pzboyz** [comment]
The UX for people with USB and BLE authenticators should be carefully thought through. 

Maybe the whole problem is solved simply having the RP prompt (if the UI allows it) the user at the time when it needs to connect to the Authenticator to tap, activate or enable the Authenticator and then hit an OK button.

**Comment by equalsJeffH** [comment]
issue #613 duplicates this one, is more recent, let's consolidate discussion there. marking this as a duplicate and closing.
