### ISSUE TITLE
AAGUID extension underspecified

### ISSUE THREAD

**Issue by rlin1** [w3c/webauthn#51]
The description of AAGUID extension in attestation certificate in FIDO 2 is little under-specified. See https://www.w3.org/Submission/2015/SUBM-fido-key-attestation-20151120/#attestation-statement-certificate-requirements

Look at he extension value for Extension OID 1.3.6.1.4.1.45724.1.1.4 (id-fido-gen-ce-aaguid).

**Comment by rlin1** [comment]
Proposal: as AAGUID is treated as a string in the spec, let the extension reflect that by specifying some string type, e.g. UTF8string.

**Comment by vijaybh** [comment]
Remove the "encoded as CBOR string" part.
