### ISSUE TITLE
Update Attestation Object figure to match the spec

### ISSUE THREAD

**Issue by selfissued** [w3c/webauthn#518]
In Figure 3 at https://w3c.github.io/webauthn/#fig-attStructs:

- Add "uv" as bit 2 of the flags.
- Rename "tup" to "up" in bit 0 of the flags.
- After PR #514 has been merged, change the text "variable length (CBOR)" to "variable length (COSE_Key)".

**Comment by nadalin** [comment]
@equalsJeffH can you please look at this and create a PR so we can get this merged ?

**Comment by selfissued** [comment]
Figure 1 "Authenticator data layout" in Section 5.1 also needs to be updated to rename TUP to UP and to add the UV bit.

**Comment by selfissued** [comment]
This was closed by PR #514 .
