### ISSUE TITLE
Public Key Infrastructures and Web Authentication

### ISSUE THREAD

**Issue by AdamSobieski** [w3c/webauthn#521]
Discussed are public key infrastructures and X.509 certificates as components of user authentication and digital signing scenarios through a web browser.

## Operating Systems and Banks

During the installation of operating systems, users may initialize digital wallets and app store experiences.  As users enter their credit card, debit card or bank account information, this is an opportunity for operating system vendors or banks to authenticate users, their real names provided and, along with bank accounts, authenticated.  After such authentications, operating system vendors or banks can provide users with X.509 certificates utilizing their real names.

Obtaining such X.509 certificates may be free or cost one penny.  Depending upon the region, a transaction may be required to authenticate users' real names and bank accounts.  If banking API's support authentication of users' names and billing addresses without transactions, then the X.509 certificates under discussion could be free.

## Scenarios

Scenarios considered include using such X.509 certificates to:

1. authenticate users and users' real names when creating or updating social media accounts.
2. digitally sign web-based email messages (e.g. Hotmail, Gmail, etc.).

## Questions

1. Are the above scenarios supported by the WebAuthn and WebCrypto (or other relevant) API's?
2. Can web developers, including with user permission, access certificates from operating system platforms or across domains?
3. Can web developers specify a list of certificate authorities (e.g. operating system vendors or banks) to filter certificates for user selection? (see also: #461)
4. What about three-party solutions where both operating system vendors and banks sign users' certificates?

**Comment by AdamSobieski** [comment]
X509 certificates commonly utilize _issued by_ and _issued to_ information.  Regarding question 2 (see also: #458), which broaches cross-domain keys, options include extending X509 certificates to include _issued for_ information, a sequence of domains with wildcards, to specify the domains which a certificate is intended for.

Operating system vendor-provided certificates could utilize the wildcard value "*" for _issued for_ and thus would be available for users to select for every domain.

https://www.ietf.org/rfc/rfc5280.txt
https://en.wikipedia.org/wiki/Wildcard_certificate

**Comment by AdamSobieski** [comment]
Regarding scenario 1, this seems to involve a new user permission, where a permission request event, an alert or popup, occurs with text resembling: "This website wants to know your real name."

**Comment by equalsJeffH** [comment]
scnario (1) in https://github.com/w3c/webauthn/issues/521#issue-248130789 is begging the question of "level of assurance (LOA)". Please see NIST SP-800-63-3 "Digital Identity Guidelines".

"identity" is out-of-scope for webauthn. we are just doing peer-entity authentication.  Whether a user "name" attribute supplied by a webauthn relying party (RP) during a registration ceremony has any assurance of "officialness" is the responsibility of said RP.  This is intersecting with webauthn but orthogonal.  Closing this issue.

**Comment by geraldkrug** [comment]
http://g-d-k.com/authn/example/index.php
