### ISSUE TITLE
Not necessary to pass AuthenticatorSelectionCriteria members to authenticatorMakeCredential()

### ISSUE THREAD

**Issue by equalsJeffH** [w3c/webauthn#524]
In reviewing the present state of [webauthn](http://w3c.github.io/webauthn/) in the context of reviewing some CTAP changes, I (finally, sigh) noticed that we are passing `options.authenticatorSelection.rk` and `options.authenticatorSelection.uv` to   authenticatorMakeCredential(). 

This is unnecessary [IIUC](http://onlineslangdictionary.com/meaning-definition-of/iiuc).  Note that `options.authenticatorSelection` members are used in step 21 of  [#createCredential](http://w3c.github.io/webauthn/#createCredential) in order to select authenticators having the desired characteristics.  It is subsequently not necessary to inform these authnrs to behave in a certain way, because they only behave in whatever their stated behavior fashion is (and as is reported in some platform-specific manner to the webauthn client). For example, this is how UAF authenticators behave (and essentially how authnr selection in UAF works). 

_Unless_ the authnr model postulated by webauthn is different from U2F and UAF in that authnrs may alter their key storage and user verification behavior on a per-requested credential basis?  (I am hoping not).

If the answer to the above question is "authnr model not different from U2F & UAF in these aspects", then the resoluition of this issue is to craft a PR which obviates passing  `options.authenticatorSelection.rk` and `options.authenticatorSelection.uv` to   authenticatorMakeCredential(). 

Note that a similar PR will need to be crafted for the CTAP spec.

**Comment by equalsJeffH** [comment]
fwiw, passing options.authenticatorSelection.rk and options.authenticatorSelection.uv to authenticatorMakeCredential() was added in these two recently-merged PRs:

https://github.com/w3c/webauthn/pull/502 add requireResidentKey param to the invocation step of authenticatorMakeCredential 

https://github.com/w3c/webauthn/pull/460 Adds requireUserVerification option in AuthenticatorSelectionCriteria

**Comment by selfissued** [comment]
They are passed dynamically to allow authenticators, for instance, to support both resident keys and non-resident keys.  Likewise, it's fine for authenticators supporting user verification to use this functionality to only provide user presence, when UV isn't needed.

I understand your point, but particularly for software authenticators, I suspect that many will be able to tailor their functionality to that requested.  Let's experiment with it this way for now, and if the authenticator vendors say that you're right, I'm fine pulling this later.

**Comment by nadalin** [comment]
@equalsJeffH to review and commnet

**Comment by AngeloKai** [comment]
This should be looked at with https://github.com/w3c/webauthn/issues/536

**Comment by AngeloKai** [comment]
Software authenticators such as Windows Hello can alter behaviors differently based on what inputs they accept, including key storage and user verification behaviors. This behavior is different from UAF and U2F authenticators'. @equalsJeffH can we close the issue?

**Comment by equalsJeffH** [comment]
@AngeloKai wrote:
> Software authenticators such as Windows Hello can alter behaviors differently based on what inputs they accept, including key storage and user verification behaviors

**A)** Ok, so that means that we are altering the "authenticator model" from what it was/is in U2F & UAF. The latter is that authnrs' behaviors are fixed and describable by relatively simple metadata.  We are now saying that (some) authnrs' behavior is tailorable by RPs at createCredential() and (it seems?) getAssertion() times.  

**B)** This alteration to the "authnr model" is nominally ok by me, though I argue that we need to comprehensively craft the approach (i.e., have a framework), and the approach needs to be extensible, ideally without altering the webauthn API.  I.e., over time folks will invent new authnr characteristics. As they are invented, they will need identifiers assigned such that they can be reasoned about and RPs can selectively employ them or not. If the webauthn API has to change to reflect newly-characterized authnr behaviors, then that's suboptimal.

The present approach in webauthn, i.e., [authenticatorSelection](https://w3c.github.io/webauthn/#authenticatorSelection), requires alteration of the webauthn API in that we're adding items to the latter dictionary, which is an API change whenever something new is added.  Also, these tailorable characteristics such as rk (requireResidentKey) and uv (requireUserVerification) are not documented/cataloged in the same place as other authenticators (see [fido-registry "authenticator characteristics"](https://fidoalliance.org/specs/fido-uaf-v1.1-id-20170202/fido-registry-v1.1-id-20170202.html#authenticator-characteristics)). This is an issue for FIDO authnr interop & security certification program, which needs to keep track of these characteristics in order to factor them into said program.  

**C)** There are technical issues with the present [authenticatorSelection](https://w3c.github.io/webauthn/#authenticatorSelection)-based approach. 

**wrt (A)**, we need to properly explain this in the webauthn spec and IMHO it is not at this time. 

**wrt (B)**, we should have an approach that leverages an authnr characteristics registry (perhaps the existing one) such that these issues are addressed.  Doing so will also make it easier for us to enable use of already-fielded authnrs via the webauthn API. Also, adding denotation of such characteristics, one by one as they come up, to the API is error-prone. See below for technical issues with the present approach, eg (1). 

**wrt (C)**:

1. [#createCredential](https://www.w3.org/TR/2017/WD-webauthn-20170811/#createCredential)  step 21 checks for both `authenticatorSelection.rk` and `authenticatorSelection.uv` but in step 24.3 only `rk` is passed to the authenticatorMakeCredential operation. see also #536.

2. Ostensibly, IIUC, one wants/needs to pass `authenticatorSelection.uv` in the [#getAssertion](https://www.w3.org/TR/2017/WD-webauthn-20170811/#getAssertion) call, but [authenticatorSelection](https://w3c.github.io/webauthn/#authenticatorSelection) is part of [MakePublicKeyCredentialOptions](https://www.w3.org/TR/2017/WD-webauthn-20170811/#dictionary-makecredentialoptions), which is not passed at all to [#getAssertion](https://www.w3.org/TR/2017/WD-webauthn-20170811/#getAssertion).  

3. CTAP expects `up` (user presence test) and `uv` to be passed to authenticatorGetAssertion, but there is no presently specified means for that to be done in [#getAssertion](https://www.w3.org/TR/2017/WD-webauthn-20170811/#getAssertion). This was apparently an omission in PR #460 that we missed in review. 

4. allocating these feature/characteristics as individual booleans seems heavy-weight and clunky, to me anyway.  One can set bit flags in javascript just like in C, and WebIDL has the requisite unsigned integers to accommodate series of bit flags. 

    Or, we already have the [User Verification Method Extension (uvm)](https://www.w3.org/TR/2017/WD-webauthn-20170811/#sctn-uvm-extension) which defines a structure to convey bit fields encoded in CBOR and meshes with [fido-registry "authenticator characteristics"](https://fidoalliance.org/specs/fido-uaf-v1.1-id-20170202/fido-registry-v1.1-id-20170202.html#authenticator-characteristics).  We could update the UVM extension to take a `uvmFormat` as an input in order to convey authenticator feature requests (such as `uv` and `up`).

**Comment by rlin1** [comment]
Some comments:
a) we should define whether up is expected to be set (or ignored) when uv is set.  The flags "up" and "uv" are not fully orthogonal, it is more like an enumeration with 3 values: nothing=0, up=1, uv=2.  We also should be clear whether a bit should be (1) used by the platform to select an authenticator or (2) by an authenticator to influence its behavior.
b) This bit-fiddling stuff limits extensibility and makes it more difficult to understand - especially once we have the need to add more things which are hard to be represented as a set of bit flags (like enumerations).
c) The UVM approach is much cleaner.  We are adding more complication by modeling some things through a bit field and others through CBOR - especially when those things are closely related.  
d) We are in the way to add more capabilities for authenticatorSelection and are now starting to add things for authenticatorInfluencing.  It will likely make things easier to understand for platform and authenticator developers if we would distinguish authenticatorSelection (by the platform) and authenticatorInfluencing in the parameters and support more generic concepts of encoding individual fields (than just another set of bits).

**Comment by equalsJeffH** [comment]
notes from discussion in Sydney regarding this -- I have these four issues to submit on webuthn and CTAP as noted: 

I gave preso on webauthn issue #524 & ctap issue #318
 AIs:                                                       ***!!!
 1. sub issue on CTAP & webauthn clarify authn model that UP, UV are selectable at getAssn() & makeCred() times
 
 2. sub issue on CTAP that getAssn step 4 is unclear wrt what happens if both UP & UV are set
  also wht about default authnr behavior and RPs needing to change code to instruct authnrs?  dirk asserts the default values for up and uv handle that, but this is mmodel change in that what about an RP that is utilizing UAF authnrs with default UV behavior?

 3. submit webauthn issue for Ostensibly, IIUC, one wants/needs to pass authenticatorSelection.uv in the #getAssertion call, but authenticatorSelection is part of MakePublicKeyCredentialOptions, which is not passed at all to #getAssertion.
 
 4. submit webauthn issue for CTAP expects up (user presence test) and uv to be passed to authenticatorGetAssertion, but there is no presently specified means for that to be done in #getAssertion. This was apparently an omission in PR #460 that we missed in review.

**Comment by emlun** [comment]
@equalsJeffH

>[...] the approach needs to be extensible, ideally without altering the webauthn API. I.e., over time folks will invent new authnr characteristics.

Isn't this part solved by authenticator extensions?

**Comment by equalsJeffH** [comment]
@emlun 
> Isn't this part solved by authenticator extensions?

It *could* (technically) be solved using an extension, if said extension was uniformly employed for authenticator/authnrFeature selection. However, as noted in https://github.com/w3c/webauthn/issues/524#issue-248868185, we are adding (in an essentially ad-hoc fashion) parameters to the [#createCredential](https://w3c.github.io/webauthn/#createCredential) (aka `[[Create]]`) method.  Also, arguments are being made (issue #629) to add similar parameters to the [#getAssertion](file:///Users/jehodges/documents/work/standards/W3C/webauthn/index-jeffh-fixup-algs-contd-3-7b272f1.html#getAssertion) (aka `[[DiscoverFromExternalSource]]`) method.

Also, various parties have stated on the record that they will not honor or pass-through extensions (for at least the time being), so relying on extensions for what some may regard as critical features is suboptimal. 

What this issue is arguing for is having a more carefully-designed, extensible, authenticator and authenticator feature selection mechanism.  This will perhaps become more important as folks gain experience and feel they need to add to the present set of selectable-via-webauthn-api authenticator features.

**Comment by emlun** [comment]
@equalsJeffH How much of this is still unresolved with #644 merged?

**Comment by equalsJeffH** [comment]
while not having gone through this discussion in gory detail, I highly suspect this is all moot at this point and we can close this as ancient history....

**Comment by emlun** [comment]
Agreed, all three of `requireResidentKey`, `requireResidentKey` and `requireUserVerification` are used in the `authenticatorMakeCredential` algorithm.

**Comment by nadalin** [comment]
@equalsJeffH Please review and close if appropriate
