### ISSUE TITLE
Include Constants for COSE Algorithm Numbers

### ISSUE THREAD

**Issue by jcjones** [w3c/webauthn#529]
It might be nice for implementations to be able to use constants to refer to the `-7` and `-257` values for [the COSE algorithm shorts](https://www.iana.org/assignments/cose/cose.xhtml#algorithms) rather than having to use magic numbers in their JS.

**Comment by AngeloKai** [comment]
Don't we already use long instead of [constants](https://heycam.github.io/webidl/#idl-constants) in timeout?

**Comment by AngeloKai** [comment]
@selfissued do you mind taking a look? This has to do with COSE keys.

**Comment by nadalin** [comment]
@selfissued please look at this and see if this is something that makes sense

**Comment by selfissued** [comment]
Closing, per @jcjones 's comments on the 28-Feb-18 call.
