### ISSUE TITLE
#createCredential step 12 incorrectly refers to a timer

### ISSUE THREAD

**Issue by equalsJeffH** [w3c/webauthn#535]
> 12. If |credTypesAndPubKeyAlgs| is empty and |options.pubKeyCredParams| is not empty, cancel the timer started in step 2, return a `DOMException`...

should, i think, be: 
> 12. If |credTypesAndPubKeyAlgs| is empty and |options.pubKeyCredParams| is not empty, return a `DOMException`...

**Comment by nadalin** [comment]
also see #498

**Comment by herrjemand** [comment]
Can be closed per #535

**Comment by nadalin** [comment]
@equalsJeffH please close

**Comment by equalsJeffH** [comment]
also, this is addressed in PR #498, closing.
