### ISSUE TITLE
parameter lists in #createCredential and #op-make-cred do not match

### ISSUE THREAD

**Issue by equalsJeffH** [w3c/webauthn#536]
[#createCredential](https://www.w3.org/TR/webauthn/#createCredential) is missing `options.authenticatorSelection.uv` in step 24.3, and is in different order than [#op-make-cred](https://www.w3.org/TR/webauthn/#op-make-cred)

**Comment by equalsJeffH** [comment]
yes, this is a still-valid issue.

**Comment by equalsJeffH** [comment]
will address in PR #498

**Comment by nadalin** [comment]
@equalsJeffH This seems like a breaking change as it will change the IDL

**Comment by equalsJeffH** [comment]
@nadalin: 
> This seems like a breaking change as it will change the IDL

yes, thx, it adds `|options|.{{MakePublicKeyCredentialOptions/authenticatorSelection}}.{{AuthenticatorSelectionCriteria/requireUserVerification}}` to the argument list when `authenticatorMakeCredential()` is called. Not having it is a bug.  PR #498 fixes this.
