### ISSUE TITLE
Make create() and get() abortable

### ISSUE THREAD

**Issue by balfanz** [w3c/webauthn#537]
We need to make sure that create() and get() are abortable: For example, imagine a web page that gives users the ability to dismiss a dialog or popup that takes the user through an Authenticator registration or assertion-generation process. When the user dismisses that dialog or popup, the Authenticator should be notified to, say, stop blinking, callbacks waiting for the create() or get() results should be rejected, etc.

Presumably, we need to add an AbortSignal parameter to both calls to accomplish this: https://dom.spec.whatwg.org/#aborting-ongoing-activities

**Comment by AngeloKai** [comment]
Adding this parameter is discussed here: https://github.com/w3c/webauthn/issues/380. I'd expect that on spec level, we just need to extend the WHATWG HTML spec.

**Comment by equalsJeffH** [comment]
see also issue #283 
issue #316 may be related.

fwiw, terminology-wise, "abort(able)" is being used equivalently to "cancel(able)", both here in webauthn, and in whatwg-land, eg in the [abort/cancel proposal in DOM, Fetch, et al.](https://github.com/whatwg/fetch/issues/447): https://github.com/whatwg/fetch/issues/447

The latter is being implemented now, and is perhaps (ie needs investigation) what we ought to use our abort/cancel functionality. See: https://github.com/whatwg/fetch/issues/447#issuecomment-316378856, https://github.com/whatwg/fetch/issues/447#issuecomment-324038255

**Comment by AngeloKai** [comment]
Resolving this issue would also resolve https://github.com/w3c/webauthn/issues/116

**Comment by nadalin** [comment]
@AngeloKai Where do we stand with this ?

**Comment by jcjones** [comment]
Closed by #544
