### ISSUE TITLE
note that "credential public key" is the same as "user's public key" 

### ISSUE THREAD

**Issue by equalsJeffH** [w3c/webauthn#540]
One of the things that jumped out to me in [Denis Pinkas' webauthn review](https://lists.w3.org/Archives/Public/public-webauthn/2017Jul/0052.html) was his noting that we have two very similar terms in "[public key credential](https://w3c.github.io/webauthn/#public-key-credential)" and "[credential public key](https://w3c.github.io/webauthn/#credential-public-key)" and that there lurks potential confusion for readers other than us'ns. 
	
In both UAF and [U2F](https://fidoalliance.org/specs/fido-u2f-v1.2-ps-20170411/fido-u2f-raw-message-formats-v1.2-ps-20170411.html#registration-response-message-success),  this is referred to as the "user public key".  

I suggest we change "credential public key" to "user public key"  sooner rather than later. 

AFAICT this will not alter the API surface at all (because the user public key is not directly defined in the WebIDL) and is only an editorial change.  Also, we will have to update the [attestation object figure 3](https://w3c.github.io/webauthn/#fig-attStructs).

**Comment by AngeloKai** [comment]
What does "user public key" mean? Which one of the two terms ("public key credential" and "credential public key") does "user public key" refer to? I agree this would be a small change and would not alter the surface. But I really don't understand what the term is and how the term helps understanding.

**Comment by akshayku** [comment]
@AngeloKai "user public key" refers to "credential public key". 
Although it pretty clear to me, if it creates confusion, I would go for similarity between UAF/U2F.

**Comment by equalsJeffH** [comment]
I do not any longer feel we ought to change the "credential public key" term to be "user's public key" -- however I think we ought to clarify editorially that "credential public key" is the same as "user's public key"
