### ISSUE TITLE
Must returned extensions be mathematically proper subsets of requested extensions?

### ISSUE THREAD

**Issue by emlun** [w3c/webauthn#541]
Step 5 of [§ 6.1. Registering a new credential][reg] and step 7 of [§ 6.2. Verifying an authentication assertion][ass] both read (with minor editorial differences):

>5. Verify that the `clientExtensions` in _C_ is a proper subset of the extensions requested by the RP and that the `authenticatorExtensions` in _C_ is also a proper subset of the extensions requested by the RP.

In mathematics, a _proper subset_ is [necessarily not equal to its superset][wolfram]. This doesn't seem right here, however. For example if the RP requests exactly one extension, this requirement would require the client to always ignore that one extension.

Is this the intended result, or should the "proper" qualification be dropped?

[reg]: https://www.w3.org/TR/webauthn/#registering-a-new-credential
[ass]: https://www.w3.org/TR/webauthn/#verifying-assertion
[wolfram]: http://mathworld.wolfram.com/ProperSubset.html

**Comment by AngeloKai** [comment]
You are correct. The "proper" qualification should be dropped. Filing a PR right now.

**Comment by emlun** [comment]
Cool, thanks!

**Comment by AngeloKai** [comment]
The PR fixes the issue.
