### ISSUE TITLE
.store() is confusing

### ISSUE THREAD

**Issue by leshi** [w3c/webauthn#551]
As defined, webauthn inherits the default implementation of .store() from CredMan.  Unfortunately, this means that .store() is a NOOP, but actually resolves.  It does not throw.  That means a caller will be confused in that they will call .store(), not see anything blow up, and not really realize that the .store() had no effect.

**Comment by AngeloKai** [comment]
We should potentially find a way for PublicKeyCredential to not inherit the .store() method. .store() has no logical meaning the external authenticator world. @mikewest thoughts? I am not aware of anything in Web IDL that allows this. Maybe add unscopable to credman?

**Comment by jyasskin** [comment]
The code you're worried about is `navigator.credentials.store({publickey: ...})`, right? Clearly we can't remove `.store` from `navigator.credentials` only if its arguments have a `publickey` field. We could arrange for it to throw an exception instead of being a no-op, and like that idea. I think we discussed it before and decided that the current behavior was acceptable, but that might have just been "acceptable for the credential-manager merge; we'll fix it up later."

**Comment by mikewest** [comment]
It should be straightforward to add an implementation of the [`[[Store]](credential)`](https://w3c.github.io/webappsec-credential-management/#dom-credential-store-slot) method to WebAuthn that returned some sort of error condition, and to change Credential Management's [storage algorithm](https://w3c.github.io/webappsec-credential-management/#algorithm-store) to interpret that condition as cause for rejecting the promise. Would that be enough to address this from y'all's side?

**Comment by nadalin** [comment]
@mikewest @AngeloKai  I believe that will do it, so if you open and issue can you link to it here amd @AngeloKai can close this ?

**Comment by AngeloKai** [comment]
@nadalin I think what @mikewest was saying is that 1) webauthn needs to add some text about [[Store]] and how it would return a error condition, 2) credman can then go ahead to update the storage mechanism. I will try to squeeze in some time to file a PR for this between today and tomorrow, though this week is very busy for us over at Edge.

**Comment by christiaanbrand** [comment]
Angelo, are you still doing this?

**Comment by equalsJeffH** [comment]
ok, so at webauthn mtg 11-Oct-2017 decided that we will impl @mikewest's https://github.com/w3c/webauthn/issues/551#issuecomment-328453389 approach and add a store() impl that throws and error. and separately need to modify credman's default store() impl to do the right thing with that error.

**Comment by equalsJeffH** [comment]
note that the credman issue corresponding to this is https://github.com/w3c/webappsec-credential-management/issues/107 -- reopening this as we need to ensure w3c/webappsec-credential-management#107 is addressed soon since we already made this change in webauthn (see webauthn PR #631).

**Comment by AngeloKai** [comment]
The corresponding credman pull request is merged: https://github.com/w3c/webappsec-credential-management/pull/108

**Comment by nadalin** [comment]
@equalsJeffH Please verify

**Comment by equalsJeffH** [comment]
@nadalin - verified. closing this issue.
