### ISSUE TITLE
include public key in result from create()

### ISSUE THREAD

**Issue by balfanz** [w3c/webauthn#557]
As agreed at the last face-to-face, we should add the generated public key in a web-friendly format (i.e., JWK) to the result of navigator.credentials.create().

**Comment by balfanz** [comment]
Proposal: we can add a field `publicKey` to [`AuthenticatorAssertionResponse`](https://github.com/w3c/webauthn/blob/14c2733ca6a4a9568e4c48fef1b870448818e811/index.bs#L1058)

**Comment by akshayku** [comment]
Not having publicKey in AuthenticatorAssertionResponse cryptographically ties assertion signature to authenticatorMakeCredential response as you need that public key to verify the assertion signature instead of just credentialID matching. 

IMO, it provides better security as it minimizes RP chance of getting fooled by attacker who uses its own public key in authenticatorGetAssertion response but tries to fool RP by using same credentialID. It also minimizes risk as currently attacker also has to attack the user at credential creation time. 

It also plays well with U2F interop story. 

 Thoughts?

**Comment by leshi** [comment]
I think Dirk meant ```AuthenticatorAttestationResponse```

**Comment by nadalin** [comment]
@leshi to create PR

**Comment by idamlaj** [comment]
balfanz/leshi: 

It's difficult for me to rationalize this change. Can you please add some rationale to the PR?

Is the purpose of this change to simplify the credential creation process for the relying party? If so, the measurement for this is the complexity of the [credential creation algorithm](https://w3c.github.io/webauthn/#registering-a-new-credential). 

Does this change remove steps or add steps here?

**Comment by AngeloKai** [comment]
I believe this PR https://github.com/w3c/webauthn/pull/321/files removed publicKey.

**Comment by AngeloKai** [comment]
Meeting minutes on this topic from the F2F last Feb: https://www.w3.org/2017/02/13-webauthn-minutes.html#item02

**Comment by leshi** [comment]
@idamlaj: we miss you on the call ;) Join there for all the fun discussions and heart-wrenching emotions.  The goal of this proposal is to not make relying parties that don't care about attestation parse the attestation to get the public key.  There are two things that all RPs will care about: 1) credential ID and 2) the public key.  (1) was already pulled out to the top level result of .create() -- this is done by the browser, now we need to do the same with (2) -- it will need to be done by the browser after pulling out (1).

@AngeloKai: Thanks for finding those!  That was super helpful! :) . That PR is HUGE!!  Maybe we avoid such large PRs in the future?  I looked at the meeting minutes and the PR discussion and did not find any explanation for why the public key was a casualty in the PR.  Did I miss something?

**Comment by emlun** [comment]
>The goal of this proposal is to not make relying parties that don't care about attestation parse the attestation to get the public key. There are two things that all RPs will care about: 1) credential ID and 2) the public key.

Weighing in as an RP implementer: What would really be the difference between parsing a `publicKey` property on the root object as opposed to parsing the authenticator data? If you don't care about attestation trust it's already perfectly possible to get at the public key without parsing the attestation statement, if that's what you mean.

Either way it seems unlikely to me that any one "friendly format" would be easily usable for all RP implementation platforms (Java, JavaScript, Python, Ruby, ...), so I'm not sure about the value of duplicating the data. It would also complicate RP implementation with having to decide what to do if the copies disagree.

**Comment by AngeloKai** [comment]
The argument for removing the publicKey is the following: The client shouldn't have to worry about key parsing. Although this adds a complexity to the server side, most servers are already equipped to handle complexity. @equalsJeffH also pointed out that we had some discussions regarding pushing the complexity to the server side and can add more explanation. By putting publicKey in the blob, it forces people to parse it and provide additional security protection. 

The below ae the minutes around the description about removing public key (Actually I think I wrote down the minutes here so I wish I wrote it down more comprehensively): 

> https://github.com/w3c/webauthn/issues/321
> We will start by looking at 321 
> Vijay is leading the discussion for PR 321 
> Vgb: we will look at the diff first instead of going through all of the changes 
> Dirk: the public key is no longer returned by makeCredential 
> Now the returned object from makeCredential is only clientDataJSON and attestationObject 
> The logic behind the change is that the client shouldn't have to worry about the key parsing. It'd be best if only a blob is returned. 
> Another change is regarding U2F attestation format 
> Alexei: credential ID is missing 
> Vgb: he will ensure the Cred ID is available there and will fix this problem later 
> Richard Barnes: I think the logic is backward 
> Richard's main concern is that there are certain common attributes cross all authenticators. 
> JeffH: there have been discussions where we decide to push the complexity back to the server side 
> Richard: I agree that for the browser, it should just give back the attestation blob 
> Vgb: what we learned is that most servers are already equipped to handle the complexity 
> Richard: the assumption of Vgb"s argument is all the relying parties care about attestation 
> Vgb: however, we have to think about what the solution to this problem is. Which step will take care of the complexity, the RP, browser, authenticator? 
> Dirk: the browser should take care of the complexity. Another point is that we shouldn't have to worry about making a distinction between server and the frontend JS. 
> Because whether server and JS script takes care of the compleixty is going to shift over time 
> Vgb: we are looking at figure 3 
> All parts of the attestation data is standard component 
> Alexei: why the attestation format, data, and statement is in binary format instead of JS object 
> ... U2F attestaiton has additional complexity because it doesn't have AAGUID, counter, etc. 
> <jeffh> The Concise Binary Object Representation (CBOR) data format (RFC7049) implemented in pure JavaScript: https://github.com/paroga/cbor-js 
> Vgb: the complexity is either going to be on the authenticator or the RP either way. 
> wendy, do you mean who is at the F2F 
> Vgb: one point made in the past: should we make the API a bit opninate to force people to parse attestation to have additional secuirty protection 
> For RPs who don't care about attestation, they don't have to parse it. 
> Richard: let's land 321 first. I and Dirk will look at it and see if we can make it better 
> <jcj_moz> scribenick: jcj_moz 
> nadalin: We're going to merge 321, and then people can comment on it, and we'll resolve the comments in WD-05. We can merge this and put out WD-04.

**Comment by nadalin** [comment]
@AngeloKai @emlun @balfanz So is this a close no action now ?

**Comment by balfanz** [comment]
Hi Angelo, 

thanks for pointing to the meeting notes again. :-) I'll highlight the relevant passages:

> Dirk: the browser should take care of the complexity. Another point is that we shouldn't have to worry about making a distinction between server and the frontend JS
> ...
> Richard: [...] I and Dirk will look at it and see if we can make it better

If you recall, my point there (which, IIRC, was met with no objections in the room) was that we don't know where and how the public key will be consumed - server side, client side, what programming language the server will be written in (the server may very well be written in JS), how they split up the work, etc. 

So if you have an RP that doesn't care about the various attestation formats, the best/most consistent/most neutral thing for a Web API to do is to return the newly-generated public key in a web-friendly format, i.e., as a JWK.

Richard, who was of the same opinion, said that he and I would make a PR that added the public key. Now, it's on him and me that hasn't happened yet, but I wanted to at least file the issue to remind ourselves that this is outstanding work- not to relitigate the underlying question.

**Comment by emlun** [comment]
Wouldn't a RP that doesn't care about attestation formats (and therefore does not parse them) be violating the MUST in [§6.1 Registering a new credential](http://w3c.github.io/webauthn/#registering-a-new-credential)?

**Comment by jyasskin** [comment]
@emlun Maybe that's a bug in the RP algorithm. Discussing it would derail this thread, so I created a new one at #576.

**Comment by balfanz** [comment]
@jyasskin - any advice on how to word this? I assume something about JWKs, but I'm not fluent in whatever programming language this spec is written in. :-)

**Comment by akshayku** [comment]
Does it need to be JWK?? Why cannot it remain in COSE_KEY format? That way we will be consistent everywhere.

**Comment by emlun** [comment]
If it's just going to be the same COSE_key blob duplicated, why not just parse it out of the authenticator data instead?

**Comment by balfanz** [comment]
I think it should be a JWK, since we're designing a web API. On the web, [we use JWKs to represent keys](https://w3c.github.io/webcrypto/Overview.html#dfn-SubtleCrypto-method-exportKey).

**Comment by AngeloKai** [comment]
@selfissued can you please take a look at this issue? @balfanz

**Comment by rlin1** [comment]
We should just make sure the platform extracts this public key from authenticatorData.attestationData as opposed to look deeply inside the binary attestation generated by the authenticator.

**Comment by balfanz** [comment]
Discussion on the call on 10/11 suggested that the key should be returned as a JsonWebKey dictionary.

**Comment by equalsJeffH** [comment]
it seems easy to parse out the cred ID length, the cred ID, and the cred public key from the attObj (attestation object):

37 bytes gets to attested cred data
16 size of AAGUID 
--
53 bytes is index of cred ID length (L). 
53 + L = index of cred public key (in cose-key format)

**Comment by jcjones** [comment]
We discussed that instead of duplicating data, to instead add operations (getters) to obtain web-friendly forms (such as a CryptoKey object).

However, there's still no consensus to proceed with this, so we're closing this issue.

**Comment by equalsJeffH** [comment]
this discussion has resurfaced in https://github.com/w3c/webauthn/issues/1363
