### ISSUE TITLE
#registering-a-new-credential step 10 breakage

### ISSUE THREAD

**Issue by equalsJeffH** [w3c/webauthn#561]
[#registering-a-new-credential](https://w3c.github.io/webauthn/#registering-a-new-credential) step 10 is presently:
```
10. Verify that |attStmt| is a correct, validly-signed attestation statement, 
using the attestation statement format |fmt|'s
verification procedure given [=authenticator data=] |authData| 
and the [=hash of the serialized client data=] computed in step 6.
```
Issues with step 10:
1. the first is that |attStmt| is not what is signed over.  Rather, [[=authenticator data for the attestation=]](https://w3c.github.io/webauthn/#authenticator-data-for-the-attestation) and [[=hash of the serialized client data=]](https://w3c.github.io/webauthn/#collectedclientdata-hash-of-the-serialized-client-data) are what is signed over.  |attStmt| simply conveys the |sig| value.  E.g., see the Signing Procedure in [#packed-attestation](https://w3c.github.io/webauthn/#packed-attestation). 

2. it does not clearly/properly reference the attestation stmt format sections, nor the attstn stmt format registry, where the signature verification procedures are defined.

suggest for step 10:
```
10. Verify that |attStmt| is a correct [=attestation statement=], conveying 
a valid [=attestation signature=], by 
using the [=attestation statement format=] |fmt|'s
[=attestation statement format=], given [=authenticator data=] |authData| 
and the [=hash of the serialized client data=] computed in step 6.
Each [=attestation statement format=]'s verification procedure is given by
the format's specification. See [[#defined-attestation-formats]] for the initially-
defined formats, and [[!WebAuthn-Registries]] for the up-to-date list.
```

**Comment by equalsJeffH** [comment]
refining/fixing suggestion for step 10:
```
10. Verify that |attStmt| is a correct [=attestation statement=], conveying 
a valid [=attestation signature=], by 
using the [=attestation statement format=] |fmt|'s
verification procedure, given |attStmt|, [=authenticator data=] |authData| 
and the [=hash of the serialized client data=] computed in step 6.
Each [=attestation statement format=]'s verification procedure is given by
the format's specification. See [[#defined-attestation-formats]] for the initially-
defined formats, and [[!WebAuthn-Registries]] for the up-to-date list.
```

need to also fix the ags defined in [#verification-procedures](http://w3c.github.io/webauthn/#verification-procedures) to match.

the [#verification-procedures](http://w3c.github.io/webauthn/#verification-procedures) may also need the RP's expected RP ID value passed-in.

**Comment by emlun** [comment]
Personal anecdote: I as an implementer personally had no issue with the present formulation. The fact that `attStmt` is not the bytes signed over was not a cause of confusion for me as I found it clear that the `attStmt` is a polymorphic container for the signature.

I agree that a link to the definition of the [attestation statement][attStmt] or some such could be useful, though.

>the #verification-procedures may also need the RP's expected RP ID value passed-in.

The correctness of the RP ID is already verified in step 8 of [§6.1][reg] and [§6.2][auth], so the RP ID shouldn't be needed again in the signature verification step (other than the hash in the authenticator data).

[reg]: https://www.w3.org/TR/webauthn/#registering-a-new-credential
[auth]: https://www.w3.org/TR/webauthn/#verifying-assertion
[attStmt]: https://www.w3.org/TR/webauthn/#attestation-statement

**Comment by nadalin** [comment]
@emlun so does this just become an editorial change to add the definition of the attestation statement?

**Comment by emlun** [comment]
I don't call any shots, I just wanted to weigh in with that I as an RP implementer don't think the longer wording is necessary for it to be understandable and unambiguous. I'm only one data point, but yes, my suggestion would be to leave the wording as is and just add a proper reference to the definition of the attestation statement.

**Comment by emlun** [comment]
With #635 merged, can we close this?

**Comment by equalsJeffH** [comment]
@emlun wrote:
> With #635 merged, can we close this?

well, if the re-formulation of step 10 given in https://github.com/w3c/webauthn/issues/561#issuecomment-328684717 is not itself incorrect, I would be inclined to use it because not everyone is as smart as @emlun :)  and the current statement in step 10 that "attStmt is a correct, validly-signed attestation statement" is misleading. 

If the re-formulation of step 10 is correct (someone please review it?), then it is a simple cut-and-paste.   I re-reviewing, I now would make the 2nd proposed sentence a "Note:".

**Comment by emlun** [comment]
Gotcha, I'll do that. :)
