### ISSUE TITLE
Safetynet attestation does not return byte array as a response.

### ISSUE THREAD

**Issue by Kieun** [w3c/webauthn#563]
Section 7.5 describes Android Safetynet attestation statement format. 
The "response" value is defined as a byte string (Major type2 ). However, Safetynet API returns String instead of byte array. 
See following getJwsResult() method.
[https://developers.google.com/android/reference/com/google/android/gms/safetynet/SafetyNetApi.AttestationResponse](url)
So, we need to change response type from a byte string (Major type 2) to a text string (Major type 3).

**Comment by AngeloKai** [comment]
@christiaanbrand can you please look at this issue?
