### ISSUE TITLE
Consider dropping requirement for TUP on create()

### ISSUE THREAD

**Issue by balfanz** [w3c/webauthn#564]
Currently, the spec requires that Authenticators test for user presence when creating a new keypair. 

The user experience on existing platforms (TouchID on iOS, Fingerprint on Android) for equivalent use cases (turn on TouchID for Amazon orders, turn on TouchID when logging into Mint, etc.) does not do this - it's often a simple switch in the apps' UI.

We should go with the Industry standard here and allow RPs to turn on FIDO authentication (i.e., call create()) without a test of user presence. If an RP really wants this behavior (not register a key unless the user is present), it can call create(), followed by get() (which will continue to require TUP), before it registers the generated key).

**Comment by nadalin** [comment]
@balfanz you are asking for additional calls, not sure the rationale is here since we have long talked about TUP

**Comment by balfanz** [comment]
Just to clarify - I'm not asking for additional calls, just that we consider changing the semantics of create(); essentially remove [one line](https://github.com/w3c/webauthn/blob/db1be8059b02cb8981fbe0229f6d1eebaedb9505/index.bs#L1660) from the spec.

**Comment by nadalin** [comment]
@balfanz but you are requiring me to do a get() and I could have failed on the create() so extra call and now I have gone through the create with something I may not want to use

**Comment by balfanz** [comment]
Oh, **_that_** additional call. Yes, I think it's ok to optimize for the common case (make that cheaper both for the user and the RP), and make the rare case more expensive.

**Comment by akshayku** [comment]
This proposal can create silent resident keys and fill up the authenticator storage which is very scarce.

**Comment by akshayku** [comment]
Let's not optimize here unnecessarily.

**Comment by balfanz** [comment]
I'm worried that the webauthn experience will be worse than existing mechanisms (TouchID, Fingerprints on Android) when addressing the same use cases. 

"Bypass your password next time you use this (web)app, and use your fingerprint instead" is such an existing use case. Today, users are used to just turn on this kind of feature, without having to show a test of user presence at that point.

re/ resident keys: any suggestions on how to address that? Resident keys on external Authenticators is a new use case, one where users don't have pre-conceived notions on how it should work.

**Comment by nadalin** [comment]
@balfanz @akshayku  seems like we should close this no action as leaving this the way it is does not give us issues of creating unwanted keys

**Comment by christiaanbrand** [comment]
Can we make it optional for platform (built-in) authenticators to require a TUP? They won't have the issue of getting filled up with credentials, right? And the UX is much better.

**Comment by akshayku** [comment]
Adding a FIDO experience for TouchID, Fingerprints on Android is a new scenario and once in a life time event. Arguably IMO, experience is not bad and is consistent with whole FIDO security promise and user experience. 

Regarding resident keys, on both platform as well as cross platform authenticators, should absolutely require a touch so that not any malware can fill up the authenticator storage. It is a problem for both type external as well as internal authenticators. 

Current design is clean and similar to U2F experience and we should not over-optimize the experience here as well as protect against malwares just messing up the authenticators silently.

**Comment by idamlaj** [comment]
I support dropping the TUP requirement for platform (built-in authenticators).

We should do this only if excludeCredentials.length == 0, otherwise a relying party may silently query for credentials via the excludeCredentials parameter.

**Comment by nadalin** [comment]
@idamlaj are you in favor of removing this or making it optional ?

**Comment by akshayku** [comment]
Let's make it optional for only platform authenticators. Let each platform device what behavior it wants.

**Comment by nadalin** [comment]
@akshayku @idamlaj  @christiaanbrand Looks like support to wrap this up as making this optional

**Comment by rlin1** [comment]
I have some open question regarding this topic.
1. The distinction between bound authenticators and roaming authenticators is not a static as one might think.  Let's assume a bound authenticator in a smartphone.  Let's further assume that smartphone supports CTAP protocol and is connected to some laptop using CTAP.  This makes the bound authenticator a roaming authenticator.  Would that authenticator now need to ask for a TUP when creating a new credential?
2. If the bound authenticator doesn't ask for TUP when creating a new credential, are we still assuming that some user was enrolled with this authenticator?  If yes: we should mention such assumption explicitly.  If not: What if user A uses the device when creating the credential and user B then enrolls to the authenticator after that?  This behavior could likely be unexpected for some relying parties.  
3. The FIDO alliance has published some privacy principles (https://fidoalliance.org/assets/images/general/FIDO_Alliance_Whitepaper_Privacy_Principles.pdf).  How would this approach meet those? For example "#1: Require explicit, informed user consent for any operation using personal data".

**Comment by nadalin** [comment]
1. It depends on the boundary as you pointed out in Sydney, so it can be simple or complicated. but the basic definition would be that the internal OS protocols are used and not CTAP
2. Agree there should be some clarification 
3. There is no violation as the FIDO conformance tests would be require user consent

@akshayku @idamlaj @christiaanbrand @rlin1  Looks like support to wrap this up as making this optional

**Comment by akshayku** [comment]
Fine with me if it is optional

**Comment by jovasco** [comment]
I'm not so sure there are no privacy considerations. Basically, you are allowing any RP to uniquely identify any system with such an authenticator.

All that is needed is a makeCredential call with a requirement for an attached authenticator without UP requirement and an exclude list. If no new credential is created, this particular credential identifies this system.  The only practical limit is the time you have to test credentials.

As for practical applications, it would be trivial to use this to validate possible correlations between users.

**Comment by idamlaj** [comment]
@jovasco you are correct. See my previous comment.

My proposal is that we make the makeCredentail call (optionally) silent if the exclude list is null.

This should be called out in the privacy considerations section.

-Ibrahim

**Comment by emlun** [comment]
"Null" as in "present with a `null` value", "not present" or both?

**Comment by selfissued** [comment]
@balfanz is creating a PR to enable this to be optional for platform authenticators. @akshayku argued that touch should still be required for external authenticators.

**Comment by equalsJeffH** [comment]
be sure to see also @nadalin's comment https://github.com/w3c/webauthn/issues/564#issuecomment-334002023
