### ISSUE TITLE
authenticatorMakeCredential has an excludeCredentialDescriptorList parameter, but doesn't do anything with it

### ISSUE THREAD

**Issue by balfanz** [w3c/webauthn#567]
`authenticatorMakeCredential` has an `excludeCredentialDescriptorList` parameter, but doesn't do anything with it. It probably should. And it should explain how the `excludeCredentialDescriptorList` is used differently between U2F and CTAP Authenticators.

**Comment by leshi** [comment]
I found the reference:

* An optional list of PublicKeyCredentialDescriptor objects provided by the Relying Party with the intention that, if any of these are known to the authenticator, it should not create a new credential.

**Comment by christiaanbrand** [comment]
We clarified the text a bit with a PR.
