### ISSUE TITLE
Where are rsaAlgName and eccAlgName defined?

### ISSUE THREAD

**Issue by emlun** [w3c/webauthn#568]
The `packed` and `tpm` attestation statement formats reference the types `rsaAlgName` and `eccAlgName`, saying "The types `rsaAlgName` and `eccAlgName` are as defined in [§5.3.1 Attestation data][attData]". Section §5.3.1 however doesn't reference these terms, and neither does the [RFC8152][rfc] cited therein to define the COSE_Key format.

Where are `rsaAlgName` and `eccAlgName` defined? Are they supposed to be the parameter `alg: COSEAlgorithmIdentifier` defined in §5.3.1 Attestation data?

[attData]: https://www.w3.org/TR/webauthn/#sec-attestation-data
[rfc]: https://tools.ietf.org/html/rfc8152

**Comment by akshayku** [comment]
This is artifact left over previous to COSE Key change. This is supposed to be alg: COSEAlgorithmIdentifier.

**Comment by selfissued** [comment]
PR #580 replaces the uses of rsaAlgName and eccAlgName with COSEAlgorithmIdentifier.

I'd like feedback on whether we should also replace uses of the strings "ED256" and "ED512", which refer to the algorithms defined at https://fidoalliance.org/specs/fido-uaf-v1.1-id-20170202/fido-ecdaa-algorithm-v1.1-id-20170202.html#ecdaa-algorithm-names, with new COSEAlgorithmIdentifier values.  If so, I would add these to the IANA registrations at http://www.w3.org/TR/2017/WD-webauthn-20170811/#sctn-cose-alg-reg.

**Comment by akshayku** [comment]
Yes, we should also replace "ED256" and "ED512" with COSE identifier.

**Comment by rlin1** [comment]
I have not seen any CODE identifier for those yet.

**Comment by selfissued** [comment]
These have been added to PR #580 .  Please review.
