### ISSUE TITLE
No description regarding representation of credential Id length

### ISSUE THREAD

**Issue by Kieun** [w3c/webauthn#570]
In section 5.3.1, there is lack of explanation regarding representation of credential Id length.
Referring to CTAP spec, the length should be 2-byte unsigned big-endian integer.
See followings
[Attestation Data](https://w3c.github.io/webauthn/#attestation-data)

**Comment by AngeloKai** [comment]
Good catch! Thank you! We should clarify this before going to CR. 

@equalsJeffH @nadalin @YubicoDemo for tracking.

**Comment by nadalin** [comment]
@selfissued Reference CTAP specification for length
