### ISSUE TITLE
Not clear what to do with cross platform authenticators during make-an-assertion step

### ISSUE THREAD

**Issue by leshi** [w3c/webauthn#574]
The current text in section 4.1.4 step 16 says:

```
16. For each authenticator currently available on this platform, perform the following steps:

  1. Let allowCredentialDescriptorList be a new list.
  2. If options.allowCredentials is not empty, execute a platform-specific procedure to determine 
      which, if any, public key credentials described by options.allowCredentials are bound to this 
      authenticator, by matching with rpId, options.allowCredentials.id, and 
       options.allowCredentials.type. Set allowCredentialDescriptorList to this filtered list.
```

If an authenticator is `xplat` (or cross platform), say an NFC token that only appears once the user taps it, how does that jive with step 16 which says "... currently available on this platform..."?

Also, "...execute a platform-specific procedure..." works for platform authenticators, but not for cross-platform authenticators.

**Comment by akshayku** [comment]
Yeah.. 
This needs to be extensible for authenticators which platform has not seen yet. This is certainly applicable for NFC, but also applicable for future USB plugins or BLE devices.

**Comment by emlun** [comment]
See also #613

**Comment by jcjones** [comment]
I will write a PR to strictly improve this for WD-07 to reflect what browsers are actually doing, and understand that it will still be under-specified, and we'll clean it up to be properly specified in #613.
