### ISSUE TITLE
RP guidelines should allow RP to not check attestation

### ISSUE THREAD

**Issue by jyasskin** [w3c/webauthn#576]
A Relying Party who merely wants to use public-key credentials without caring how well the private key is protected could get by without including code to parse the attestations, especially after #557 is fixed. However, as @emlun pointed out there, http://w3c.github.io/webauthn/#registering-a-new-credential currently says the RP MUST validate the attestation statement they receive. We should probably provide an explicit path in that algorithm to avoid parsing the attestation statement.

**Comment by emlun** [comment]
Perhaps this isn't a big issue, but one caveat of this is that if the RP does not parse the attestation statement then it also cannot verify the registration signature, so there is no cryptographic proof that the client has access to the corresponding private key.

One counterpoint is that the ritual will be performed over HTTPS anyway, and should be resistant to network MitM attacks, but this would still be vulnerable to cross-site scripting attacks that make it onto a HTTPS page. If the registration signature is not verified then a script could replace the public key and credential ID with one hard-coded into the attack payload. Verifying the signature at least requires the attacker to be able to dynamically generate the correct signature for the substituted public key.

Of course, this weakness applies only at registration time and if there's XSS you're probably screwed either way, so my point may be moot. It just feels exceptionally wrong to explicitly allow the signature to go unverified.

**Comment by emlun** [comment]
On the other hand, verifying the signature but not the attestation of the authenticator model is already explicitly allowed in step 14:

>If the attestation statement attStmt successfully verified but is not trustworthy per step 12 above, the Relying Party SHOULD fail the registration ceremony.
>NOTE: However, if permitted by policy, the Relying Party MAY register the credential ID and credential public key but treat the credential as one with self attestation (see §5.3.3 Attestation Types). If doing so, the Relying Party is asserting there is no cryptographic proof that the public key credential has been generated by a particular authenticator model. See [FIDOSecRef] and [UAFProtocol] for a more detailed discussion.

Perhaps there is some confusion in what "attestation" means?

**Comment by AngeloKai** [comment]
It's a good idea to not have the MUST keyword in the RP verification description, I don't believe we can ever impose conformance requirement to RPs. That is beyond the control of anyone. Although FIDO has certified servers, that is purely FIDO's business not W3C's. 

Overall the issue is editorial. I am assigning the issue to CR time for clarification. 

@equalsJeffH @nadalin @YubicoDemo for tracking.

**Comment by selfissued** [comment]
Closing per discussion on 28-Feb-18 call.

**Comment by emlun** [comment]
Actually, I think the RP conformance class section could be expanded a bit to cover the case where the RP doesn't care much about attestation, especially since we've agreed that that is the most likely use case. I'll write a PR for this.
