### ISSUE TITLE
CDDL for attStmtType is confusing

### ISSUE THREAD

**Issue by jcjones** [w3c/webauthn#577]
When implementing the [CBOR-encoded Attestation Object](https://w3c.github.io/webauthn/#generating-an-attestation-object), the `attStmtTemplate` defines `attStmt` to be `bytes`:

```
attObj = {
            authData: bytes,
            $$attStmtType
         }

attStmtTemplate = (
                      fmt: text,
                      attStmt: bytes
                  )

; Every attestation statement format must have the above fields
attStmtTemplate .within $$attStmtType
```

However, all of the definitions of the `attStmtType` actually override the `attStmt` to be some other type, namely a **map**. E.g.:

```
  $$attStmtType //= (
                        fmt: "fido-u2f",
                        attStmt: u2fStmtFormat
                    )
  u2fStmtFormat = {
                      x5c: [ attestnCert: bytes, * (caCert: bytes) ],
                      sig: bytes
                  }
```

Defining it at the top-level as **bytes** is confusing, then. It's probably better to define the top-level as a blank map, so that it's clear what the type repeatedly is.

**Comment by emlun** [comment]
I agree. At the interop meeting some browsers had interpreted the spec as meaning the `attStmt` should be a binary value (decoded as `attStmt := parseCbor(parseCbor(attObjBytes).attStmt)` and some had interpreted it as a map value (decoded as `attStmt := parseCbor(attObjBytes).attStmt`), both perfectly reasonable interpretations. This ambiguity should be eliminated.
