### ISSUE TITLE
No way to select an intended authenticator during authentication with attachment info

### ISSUE THREAD

**Issue by Kieun** [w3c/webauthn#583]
[Section 4.4.4](https://w3c.github.io/webauthn/#attachment) describes the way for RP to set acceptable types of authenticators for registration and authentication. 
In case of registration, there is a member for this in MakePublicKeyCredentialOptions dictionary.
But, there is no such member for authentication option defined in PublicKeyCredentialRequestOptions dictionary.
IMO, PublicKeyCredentialRequestOptions dictionary must have authenticatorSelection member to provide for RP to select platform or roaming authenticator for authentication.

**Comment by emlun** [comment]
Under what circumstances would an RP want to allow some authenticators for registration but not for authentication?

**Comment by Kieun** [comment]
Some authenticators can be platform(bound) or cross-platform(roaming) authenticators depending on their characteristics. And some of platform authenticators can be cross-platform authenticators at the same time. 
Also, the user may register multiple authenticators and the RP wants to select the specific authenticator which has user verification method in some context such as money transfer case.
In this case, the RP allows some sort of authenticators for registration but not for authentication.
Anyway, according to the current spec, there is no way to set authenticator selection criteria for the authentication. Although, the spec says authenticatorSelection member is for create() or get() operation.
Followings are described in the Section 4.4

> authenticatorSelection, of type AuthenticatorSelectionCriteria
This member is intended for use by Relying Parties that wish to select the appropriate authenticators to participate in the create() or get() operation.

At least, if we decide not to provide authenticatorSelection for get() operation, above description should be modified.

**Comment by emlun** [comment]
Ah yes, section 4.4 is indeed inconsistent as you point out. But doesn't `allowCredentials` already enable these features? Of course that assumes the RP has stored device metadata in the registration ceremony, but the RP would need that metadata anyway in order to verify that the user agent obeys the `authenticatorSelection`.

**Comment by Kieun** [comment]
AllowCredentials is similar to this feature. But I think allowCredentials is mainly used for the credential selections by setting credential Id in case of which RP knows the credential ID before sending authentication challenge. But what if the RP does not know the credential ID before sending authentication challenge in case of first factor authentication? So, authenticatorSelection is little bit different from allowCredentials.

**Comment by emlun** [comment]
Ah yes, you are right. It is technically possible for the user to select a first factor they know the RP will accept, but it would indeed make for a better user experience if the user agent can prevent the user from choosing a credential/authenticator the RP won't accept.

**Comment by emlun** [comment]
But on second thought, couldn't that also be solved with an additional authentication ceremony? The RP can first authenticate the user with any registered credential, and then when the user is identified in a session the RP can request specific credentials for specific actions. It still risks to complicate the user interaction, but at least it spares the user from retrying failed authentications.

**Comment by AngeloKai** [comment]
We discussed this issue before. When a credential is created with a list of authenticator requirement, the same set of requirement should be applied in future authentication operations. Therefore I am closing the issue with no action. 

I am setting the issue to PR to track what editorial fixes we need to make. 

@equalsJeffH @nadalin @YubicoDemo for tracking.
