### ISSUE TITLE
address needs of various webauthn spec audiences

### ISSUE THREAD

**Issue by equalsJeffH** [w3c/webauthn#585]
The webauthn spec is written for multiple audiences, including _at least_: 
* Relying Party deployers
* Web browser implementers
* OS platform implementers
* Authenticator vendors

PR #375 attempts to address this by adding a "spec roadmap" section to the introduction. this may or may not be sufficient -- we may want to consider creating "explainer" docs for one (eg RP deployers) or more audiences.

**Comment by jyasskin** [comment]
#88 also talks about specifying what RPs need to do.

**Comment by apowers313** [comment]
Server spec is here: https://fidoalliance.org/specs/fido-v2.0-rd-20180702/fido-server-v2.0-rd-20180702.html

**Comment by nadalin** [comment]
@selfissued Please re-review in light of PR #375 , If you still issues please propose update

**Comment by equalsJeffH** [comment]
given PR #375's merged, shall we close this?
