### ISSUE TITLE
Extension identifiers in examples are inconsistent with registered identifiers

### ISSUE THREAD

**Issue by manger** [w3c/webauthn#588]
§11.3 "Sample scenarios: Authentication" has an example with:
  extensions: { 'webauthn.txauth.simple': 

§11.1 "Sample scenarios: Registration" has an example with:
  extensions: {"webauthn.location": true}

But the registered extension from §10.2 "WebAuthn Extension Identifier Registrations" are:
  txAuthSimple
  loc

Fix: change the §11.3 and §11.1 examples to use the §10.2 values.

**Comment by AngeloKai** [comment]
Good catch! Move the issue to PR time. 

@equalsJeffH @nadalin @YubicoDemo for tracking.

**Comment by rlin1** [comment]
Has been addressed by PR #677 
We should close this issue IMHO.
