### ISSUE TITLE
User Verification Method (uvm) extension incorrectly mentions user verification *index*

### ISSUE THREAD

**Issue by manger** [w3c/webauthn#589]
§9.8 "User Verification Method Extension (uvm)" says (when describing authenticator extension processing) that the output is set to the
  user verification index
but it should be set to the
  user verification method

Fix: change "index" to "method"

"method" distinguished face vs finger vs iris etc; whereas "index" distinguishes, say, 2 fingers enrolled  on a device.

**Comment by AngeloKai** [comment]
Sounds good. We can do the editorial fix at PR time. 

@equalsJeffH @nadalin @YubicoDemo for tracking.

**Comment by rlin1** [comment]
This issue doesn't exist any longer (as of Dec. 6th 2017).
Might have been fixed earlier.

**Comment by rlin1** [comment]
We can close this issue (as already fixed) IMHO.

**Comment by equalsJeffH** [comment]
agreed. closing.
