### ISSUE TITLE
TAG review feedback: imageUri

### ISSUE THREAD

**Issue by vijaybh** [w3c/webauthn#59]
w3ctag/spec-reviews#97

imageUri should be renamed to imageURL, and could be aligned with manifest syntax for multiple sizes.

**Comment by leshi** [comment]
@vijaybh, what does "aligned with manifest syntax for multiple sizes" mean?

**Comment by vijaybh** [comment]
That is verbatim from the TAG feedback. I assume they are referring to http://w3c.github.io/manifest/#icons-member and how it specifies an array of images that can be used to hold multiple icons at different resolutions.
