### ISSUE TITLE
Need to remove the term "authentication key" in self attestation description

### ISSUE THREAD

**Issue by Kieun** [w3c/webauthn#590]
§5.3.3 Attestation Types depicts **Self Attestation** type and there is a term "authentication key" that is not defined elsewhere. This term is only referred in this section. 
Let us use "credential private key" instead of "authentication key". #

**Comment by AngeloKai** [comment]
Sounds good. We can do the editorial fixes at CR time.

**Comment by rlin1** [comment]
+1

**Comment by rlin1** [comment]
addressed by PR #676.
