### ISSUE TITLE
Incorrect feedback link in 20160531 WD

### ISSUE THREAD

**Issue by r12a** [w3c/webauthn#592]
fwiw, https://www.w3.org/TR/2016/WD-webauthn-20160531/ points people with comments to the wrong github repo (SOTD end of first para).

**Comment by AngeloKai** [comment]
Thank you for pointing it out! Unfortunately it is difficult to re-publish a WD. The recommended way is through errata? Plus when you open the WD, it has a big warning saying, "this is outdated." Giving this info, I am closing the issue with no action. 

If we want to do this, we can do this at any time without a milestone. So I am not assigning a milestone to this. 

@equalsJeffH @nadalin @YubicoDemo
