### ISSUE TITLE
Examples should include non-ASCII [editorial]

### ISSUE THREAD

**Issue by r12a** [w3c/webauthn#594]
[This review was done against https://www.w3.org/TR/2016/WD-webauthn-20160531/#iface-account, and the comment was raised by Addison Phillips. The i18n WG agreed to forward as a WG comment.]

Section 3.3 contains several examples of user and organizational names (`rpDisplayName`, `displayName`, etc.). The examples should include some non-English or non-Latin example.

**Comment by emlun** [comment]
It looks like §3.3 in WD1 (2016-05-31) corresponds to [`PublicKeyCredentialEntity`][dict] and its subtypes in [WD7 (2017-08-11)][wd7].

[dict]: https://w3c.github.io/webauthn/#dictdef-publickeycredentialentity
[wd7]: https://www.w3.org/TR/2017/WD-webauthn-20170811/

**Comment by AngeloKai** [comment]
Sounds good. We can do at PR time for completeness. Thank you for the review! 

@equalsJeffH @nadalin @YubicoDemo for tracking.

**Comment by samuelweiler** [comment]
adding a completely inappropriate privacy-cons label for testing purposes.  Nothing to see here; move along.  (But please leave the label here for now.)

**Comment by equalsJeffH** [comment]
fyi: we did add non-usascii chars to "name:" values in examples. can we close this?

**Comment by aphillips** [comment]
I'm satisfied with this result.
