### ISSUE TITLE
Change user.id examples to binary encoding.

### ISSUE THREAD

**Issue by christiaanbrand** [w3c/webauthn#598]
Change user.id examples to binary encoding. It can be up to 64 bytes long.

**Comment by nadalin** [comment]
@christiaanbrand can you create a PR and just merge this since this was decided in CTAP ?

**Comment by christiaanbrand** [comment]
I think this is already done?

**Comment by selfissued** [comment]
I pointed out to Christiaan that Example 2 in Section 11.1 (Registration) has an rp.name value but no required rp.id value.  His PR will fix this.
