### ISSUE TITLE
Need to fix android key attestation verification procedure

### ISSUE THREAD

**Issue by Kieun** [w3c/webauthn#599]
#546 PR fixes the android attestation generation issue.
The resolution is to change the signing procedure to handle properly android key attestation. But the verification procedure does not reflect these modification.
So, verification procedure should be fixed.
Followings are need to be fixed.
> The value of the attestationChallenge field is identical to the concatenation of authenticatorData and clientDataHash.

In stead,

> The value of the attestationChallenge field is identical to clientDataHash.

**Comment by AngeloKai** [comment]
@leshi told me to assign to christiaan.

**Comment by AngeloKai** [comment]
The issue has to do with how RP verifies android attestation and not have to do with how the platform implements the feature. Moving the issue to CR for clarification.

@christiaanbrand @equalsJeffH @nadalin @YubicoDemo for tracking.

**Comment by rlin1** [comment]
Since Christiaan isn't available for some time, who will handle that one now?

**Comment by equalsJeffH** [comment]
on 6-Dec-2017 webauthn call:  @agl will ask around at GOOG to try to get some feedback if possible.
