### ISSUE TITLE
Where should transport hints go?

### ISSUE THREAD

**Issue by equalsJeffH** [w3c/webauthn#6]
<a href="https://github.com/balfanz"><img src="https://avatars.githubusercontent.com/u/398022?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Originally submitted by: [balfanz](https://github.com/balfanz)**, on: _Wednesday Aug 19, 2015 at 22:20 GMT_

----

We currently don't have a way to hint to the platform which transports an Authenticator supports. The RP shouldn't have to be consciously aware of this (hence we don't have a parameter for this in the API). Instead, the transport hints need to be encoded somewhere else - perhaps as part of the Credential IDs. We need to figure out how we're going to do this.

**Comment by equalsJeffH** [comment]
<a href="https://github.com/arnar"><img src="https://avatars.githubusercontent.com/u/1498?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Original poster: [arnar](https://github.com/arnar)**, on: _Friday Aug 21, 2015 at 18:47 GMT_

----

I'm in favor of adding some structure to credential IDs. Client and RP must still be able to treat credential IDs as opaque binary blobs, and everything should still work. But if client (or, in rare cases, RP) knows about this structure, they can possibly optimize the flow.

An example is to have the available transports decodable from the credential ID. Clients that know how to do this can optimize their UX, and on which transports they attempt discovery.

Note: This is irrelevant for the 1st factor use case.

**Comment by equalsJeffH** [comment]
<a href="https://github.com/equalsJeffH"><img src="https://avatars.githubusercontent.com/u/226571?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Original poster: [equalsJeffH](https://github.com/equalsJeffH)**, on: _Friday Aug 28, 2015 at 19:18 GMT_

----

I don't understand why "This is irrelevant for the 1st factor use case"  ?

**Comment by equalsJeffH** [comment]
<a href="https://github.com/equalsJeffH"><img src="https://avatars.githubusercontent.com/u/226571?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Original poster: [equalsJeffH](https://github.com/equalsJeffH)**, on: _Monday Dec 07, 2015 at 19:53 GMT_

----

this remains an open issue the w3c web authn wg will need to address once it begins work. thus setting milestone to ms-fido-v2.0-w3c

**Comment by leshi** [comment]
Suggesting to add `transportHint` to: 

```
dictionary CredentialDescription {
    required CredentialType type;
    required BufferSource   id;
};
