### ISSUE TITLE
TAG review feedback: Align Credential interface with Credential Management?

### ISSUE THREAD

**Issue by vijaybh** [w3c/webauthn#60]
w3ctag/spec-reviews#97

**Comment by vijaybh** [comment]
Possible conflict with #61 - the Credential Management spec uses USVString for credential IDs. Should we push for ArrayBuffer?

**Comment by equalsJeffH** [comment]
for reference:
http://heycam.github.io/webidl/#idl-buffer-source-types
http://heycam.github.io/webidl/#idl-USVString

**Comment by vijaybh** [comment]
My understanding of the current consensus on this one is that we believe this alignment no longer makes sense. So I propose to:
- Move this interface from the global window namespace to the navigator namespace to reduce pollution of the global namespace
- Rename interface Credential to ScopedCredential to fix the name collision with Credential Management.
- Possibly rename CredentialType to version to make it clearer what this field signifies (since ScopedCredential is itself arguably a credential type and ScopedCredentialType is unwieldy)

Feedback welcome.

**Comment by jeisinger** [comment]
I'd be interested in learning about why alignment no longer makes sense?

**Comment by RByers** [comment]
Yes more details would be useful.  FWIW a feature may not pass blink's "intent to ship" process if there is a concern from TAG that hasn't been at least adequately evaluated in detail in a public forum.  So you should expect that, despite being closed, this issue is still a potential blocker for shipping in Chrome.

**Comment by vijaybh** [comment]
Reopening to track the action item in http://www.w3.org/2017/02/22-webauthn-minutes.html for moving the namespace to navigator.credentials.crypto.

**Comment by selfissued** [comment]
We should attempt to arrive at final resolutions for all the renaming issues for the Implementer's Draft.

**Comment by selfissued** [comment]
This can be closed after merging PR #384
