### ISSUE TITLE
TAG review feedback: Should we be using array types instead of base64-encoded DOMStrings?

### ISSUE THREAD

**Issue by vijaybh** [w3c/webauthn#61]
I believe Alex Russell mentioned this in person at the San Francisco F2F, elaborating on comments in w3ctag/spec-reviews#97

It may seem more natural to use BufferSource, ArrayBuffer, or ArrayBufferView in various places where we have base64-encoded DOMStrings currently. This may also make it easier for script authors to manipulate these locally if needed (e.g. WebCrypto APIs take array types) and it avoids prescribing the use of base64.

**Comment by vijaybh** [comment]
Candidates for conversion to ArrayBuffer:
- Credential ID (e.g. U2F keyHandle is binary blob)
- Attestation: signature, rawData, clientData, claimedAAGUID
- assertionChallenge (for getAssertion)
- attestationChallenge (for makeCredential)

Not sure about: extensions.

**Comment by equalsJeffH** [comment]
for reference:
http://heycam.github.io/webidl/#idl-buffer-source-types
