### ISSUE TITLE
clientExtensionResults attribute cannot be a Record type

### ISSUE THREAD

**Issue by jcjones** [w3c/webauthn#624]
The attribute clientExtensionResults is a `typedef` of  `record<DOMString, any>`:

https://github.com/w3c/webauthn/blob/e74d8c4da2813559086fa32a28bdc6c576d54c1f/index.bs#L1354

It's used in several dictionaries - where it's fine - but it's also attached to each `PublicKeyCredential` as an attribute:

https://github.com/w3c/webauthn/blob/e74d8c4da2813559086fa32a28bdc6c576d54c1f/index.bs#L471-L475

The WebIDL spec says "[Records must not be used as the type of an attribute or constant](https://www.w3.org/2017/08/webidl-fpwd-draft.html#idl-record)", so this is not legal. Not, at least, to attach directly.

Without the oppourtunity to try something right now, it seems like we might be able to convert this to an operation, something like `myNewCred.getExtensionResults()`, perhaps. What would the group think of something like this:

```
interface PublicKeyCredential : Credential {
    [SameObject] readonly attribute ArrayBuffer              rawId;
    [SameObject] readonly attribute AuthenticatorResponse    response;

    AuthenticationExtensions getExtensionResults();
};
```

**Comment by bzbarsky** [comment]
The reason records can't be attributes is that each get would return a new object, which is bizarre behavior for an attribute, btw.  An operation doing that is OK, though.

**Comment by equalsJeffH** [comment]
Presumably, then, we would need to specify the algorithm implementing `getExtensionResults()`, yes?

IIUC, given @bzbarsky's explanation, with this approach we are essentially defining an explicit "getter" (?).

**Comment by jcjones** [comment]
@bzbarsky: Makes sense, now that you've given me the context - thanks!
@equalsJeffH: That's my understanding as well, yep.

**Comment by bzbarsky** [comment]
> we would need to specify the algorithm implementing getExtensionResults(), yes?

You need to specify an algorithm no matter what, no?  The thing returns a record; you need to define how that record is constructed.  (And keep in mind that records are ordered, so you probably need to specify the ordering too, while you're here.)
