### ISSUE TITLE
Signature Counter needs to be mandatory in authenticationData

### ISSUE THREAD

**Issue by akshayku** [w3c/webauthn#625]
As discussed in WebAuthN meeting on 10/11, it is decided to make signature counter mandatory in authenticationData after merging PR #539 as that contains more clarifications.

This tracks the follow up work.

**Comment by rlin1** [comment]
Note the field signCounter is MANDATORY.
So we would need some language to say that conforming authenticators would have to increase the counter as specified in the algorithms in WebAuthn
