### ISSUE TITLE
Privacy CA not defined or linked

### ISSUE THREAD

**Issue by jovasco** [w3c/webauthn#647]
Currently, the webauthn spec mentions Privacy CA but not provide a specification or links to one.

[This](https://w3c.github.io/webauthn/#privacy-ca) is the closest the spec gets.

**Comment by equalsJeffH** [comment]
see also issue #610 **Per TCG: "privacy CA" is now "Attestation CA"**

also, over in issue https://github.com/w3c/webauthn/issues/628#issuecomment-335950203 we were liking the term "attestation proxy".  Note that, IIUC (which I may not), what the attestation proxy (nee "attestation CA" nee "privacy CA") proponents are advocating for is not actually the same as the TCG's "Attestation CA" (nee "Privacy CA"). 

In any case, agreed that we need to provide references and likely more context/explanation.

**Comment by equalsJeffH** [comment]
see issue #610, of which this is a duplicate. closing this one.
