### ISSUE TITLE
Relying Party or Server

### ISSUE THREAD

**Issue by apowers313** [w3c/webauthn#65]
Sometimes the thing receiving messages from the WebAuthn API is called a `server`:
https://github.com/w3c/webauthn/blob/master/index.src.html#L488
https://github.com/w3c/webauthn/blob/master/index.src.html#L798
https://github.com/w3c/webauthn/blob/master/index.src.html#L1280

And sometimes it is called a `relying party`:
https://github.com/w3c/webauthn/blob/master/index.src.html#L1535
https://github.com/w3c/webauthn/blob/master/index.src.html#L1585

Unless there is some subtle difference I am missing, I would suggest we settle on `server`.

**Comment by nicola** [comment]
I am going to link this to https://github.com/w3c/webauthn/issues/50

**Comment by jcjones** [comment]
I'll handle this in a follow-up to my work on #50 to keep it distinct.

**Comment by vijaybh** [comment]
We discussed this on the call, but including here so it's not forgotten:
Server = thing that serves up JS and essentially represents the other end of the HTTPS session
RP = thing that actually consumes the assertions and makes trust decisions

They don't have to be the same in general but it's certainly fair to ask if the difference matters to readers of this spec enough to justify the added complexity of having two terms.

**Comment by equalsJeffH** [comment]
lets track this in #80

**Comment by equalsJeffH** [comment]
we will track this in #80
