### ISSUE TITLE
Terminology consistency

### ISSUE THREAD

**Issue by flpm** [w3c/webauthn#66]
There are several places on the document what looks like the same concept is addressed by different names. In some cases it seems to be inherited from the generic terminology used in the FIDO version of the document. In some cases the same term is capitalized differently or abbreviated. Some examples:

- browser vs user agent
- platform vs client platform vs OS vs OS platform
- RP vs Relying Party vs relying party

There might be cases where the meaning is not exactly the same but we should be careful to explicitly notice those nuances.

**Comment by equalsJeffH** [comment]
see also #80
