### ISSUE TITLE
CollectedClientData should include a type marker

### ISSUE THREAD

**Issue by balfanz** [w3c/webauthn#674]
Since we're signing over (the serialized) `CollectedClientData`, to avoid potential signature confusion issues, we should include some sort of marker, identifying this particular JSON object as a webauthn CollectedClientData object. 

Furthermore, to avoid potential signature confusion issues between the credential-creation and credential-use cases, the marker should also identify that use case.

Proposal:

- add a field "`type`" to the `CollectedClientData`, with values "`webauthn.create`" or "`webauthn.get`"
- add a field "`level`" to the `CollectedClientData`, with value 1 (this represents the version of the spec)
- add processing rules that say that RPs should verify the values of these fields.

**Comment by akshayku** [comment]
Looks reasonable to me.

**Comment by kpaulh** [comment]
+1

**Comment by balfanz** [comment]
As per discussion at the W3C face-to-face, we don't need the `level` field.
