### ISSUE TITLE
Bug: getAssertion accidentally calls authenticatorGetAssertion in first factor mode

### ISSUE THREAD

**Issue by emlun** [w3c/webauthn#685]
Step 16 of [§5.1.4.1][get] instructs to for each `authenticator`

1. Let `allowCredentialDescriptorList` be `options.allowCredentials` filtered to contain only the credentials bound to this `authenticator`.
2. If `allowCredentialDescriptorList` is empty, call `authenticatorGetAssertion` in first factor mode (i.e. with no `allowCredentialDescriptorList` argument)
3. If `allowCredentialDescriptorList` is not empty, call `authenticatorGetAssertion` in second factor mode (i.e. with a nonempty `allowCredentialDescriptorList` argument)

This means that if the RP sends `allowList: [{ type: "public-key", id: "AAAA" }]` and there is a 1st factor capable authenticator available which the client can identify as bound to the credential `BBBB` but not `AAAA`, the client will still call `authenticatorGetAssertion` on that authenticator with no `allowCredentialDescriptorList` argument. The authenticator will (with the user's consent) happily comply and return an assertion by credential `BBBB` instead of `AAAA`, and the RP will be confused.

Some possible solutions:

 1. Remove the filtering step from `getAssertion` completely and let the similar filtering step in [`authenticatorGetAssertion`][authnr-get] do all the work. This has the drawback that unnecessarily many bytes may be sent to external authenticators.
2. Move the 1st factor mode invocation branch to before filtering, and skip the authenticator completely if `options.allowCredentials` is nonempty and is known to not intersect with the credentials available on the authenticator.

[get]: https://w3c.github.io/webauthn/#discover-from-external-source
[authnr-get]: https://w3c.github.io/webauthn/#op-get-assertion

**Comment by rlin1** [comment]
Even though the algorithm has changed quite a bit since then, the bug seems to exist today:
In step 5 the information whether the caller provided any entries in options.allowCredentials might get lost be the filtering. Proposal:
5. If options.allowCredentials is NOT empty then
    a) execute a platform-specific procedure to determine which, if any, public key credentials described by options.allowCredentials are bound to this authenticator, by matching with rpId, options.allowCredentials.id, and options.allowCredentials.type. Set allowCredentialDescriptorList to this filtered list.
     b) if options.allowCredentials is empty then fail with error code something.
step 6 etc. as they are defined today.

**Comment by emlun** [comment]
@rlin1 Did you see #672? Do you reckon it fixes the issue?

**Comment by emlun** [comment]
Er, I mean #686, and I see you have now reviewed it. Never mind!

**Comment by emlun** [comment]
Closing this since #686 is merged.
