### ISSUE TITLE
#createCredential alg: "if options.authenticatorSelection is present..." may be incorrect

### ISSUE THREAD

**Issue by equalsJeffH** [w3c/webauthn#692]
The current step 18 of [#createCredential alg](https://w3c.github.io/webauthn/#createCredential) says:
> If `options.authenticatorSelection` is present, for each authenticator...

However, if `options.authenticatorSelection` is not present, we will not invoke any authenticators, which will likely make the user sad. 

Given that we need to pass `options.authenticatorSelection.requireResidentKey` and `options.authenticatorSelection.requireUserVerification` to `authenticatorMakeCredential()`, perhaps we should make `authenticatorSelection` a `required` member of [`MakePublicKeyCredentialOptions`](MakePublicKeyCredentialOptions) ?   (unless I'm misunderstanding things...?)

**Comment by emlun** [comment]
See the first commit in #687

**Comment by emlun** [comment]
I made a separate PR with just that first commit: #696

**Comment by emlun** [comment]
I support making `options.authenticatorSelection` required and default to `{}`. Then we can also get rid of the "If `authenticatorSelection` is present" branch, and the descriptions of `requireResidentKey` and `requireUserVerification` in [authenticatorMakeCredential][make] won't describe possibly undefined behaviour. I suppose it would technically be a breaking change to how `credentials.create()` is implemented, but it wouldn't at all affect observable behaviour or the API on either end.

[make]: https://w3c.github.io/webauthn/#op-make-cred

**Comment by emlun** [comment]
The bikeshed issue appeared in bikeshed commit [aa80a167c54650c1c8f2382945f3894ee5b80bb4](https://github.com/tabatkins/bikeshed/commit/aa80a167c54650c1c8f2382945f3894ee5b80bb4).

**Comment by equalsJeffH** [comment]
thx @emlun, see https://github.com/tabatkins/bikeshed/issues/1139

**Comment by emlun** [comment]
Fixed by #696
