### ISSUE TITLE
define "blinding"

### ISSUE THREAD

**Issue by equalsJeffH** [w3c/webauthn#694]
see: https://github.com/w3c/webauthn/pull/693#discussion_r151688735

see also: issue #462

**Comment by selfissued** [comment]
Does anyone have a proposed definition of "blinding"?

**Comment by rlin1** [comment]
What about: "Blinding: Hiding authenticator details.  This is done in order to make it harder fingerprinting a user by exposing authenticator details to the relying party.  As a side effect details regarding the authenticator security are hidden as well."

**Comment by equalsJeffH** [comment]
on 20-Dec-2017 call @agl said he'd concoct text to address this.

**Comment by selfissued** [comment]
@agl plans to write actionable normative text saying *how* to accomplish the blinding.

**Comment by agl** [comment]
See #741
