### ISSUE TITLE
Rename AuthenticatorSelectionCriteria.requireUserVerification to userVerification?

### ISSUE THREAD

**Issue by ttaubert** [w3c/webauthn#698]
I'd like to propose that `AuthenticatorSelectionCriteria.requireUserVerification` should be renamed to just `userVerification`. The possible values are "preferred", "required", and "discouraged". Having "require" in the name itself seems misleading. That would also match the [change](https://github.com/w3c/webauthn/commit/b245b72221568403cb197270bfd4715ed5098869) to `PublicKeyCredentialRequestOptions`.

**Comment by emlun** [comment]
I agree. @jcjones @christiaanbrand @akshayku what do you think?

The reason for the different names between `AuthenticatorSelectionCriteria` and `PublicKeyCredentialOptions` is that the the former had the property with Boolean type until recently, while the latter got the property of type `UserVerificationRequirement` right away without it being a Boolean in between.

**Comment by jcjones** [comment]
Yep. I'm writing a PR right now.
