### ISSUE TITLE
Move extension specification out of signature format

### ISSUE THREAD

**Issue by equalsJeffH** [w3c/webauthn#7]
<a href="https://github.com/kyang1"><img src="https://avatars.githubusercontent.com/u/11166012?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Originally submitted by: [kyang1](https://github.com/kyang1)**, on: _Friday Aug 21, 2015 at 23:00 GMT_

----

Extension specification should be moved out of signature format spec for the following reasons:
1. Current description of extensions in the signature format is too specific to getAssertion method and FIDOAssertion object. It is inappropriate to refer to it for places where extensions are used in the context of makeCredential and AttestationStatement.
2. The way that extensions shall be processed by both the client and the authenticator for makeCredential and getAssertion are the same. It doesn't make much sense to describe the same thing twice in two specifications.

If WebAPI is not a good place, platform requirement may be another option.

**Comment by equalsJeffH** [comment]
<a href="https://github.com/nadalin"><img src="https://avatars.githubusercontent.com/u/7937635?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Original poster: [nadalin](https://github.com/nadalin)**, on: _Thursday Aug 27, 2015 at 19:36 GMT_

----

For now we should leave it in a single document (signature is fine for now) and other documents should just reference as needed

**Comment by equalsJeffH** [comment]
<a href="https://github.com/rlin1"><img src="https://avatars.githubusercontent.com/u/2264687?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Original poster: [rlin1](https://github.com/rlin1)**, on: _Friday Aug 28, 2015 at 16:31 GMT_

----

Extensions are already defined in two different docs: signature-format and key-attestation.
And they (mostly) apply to attestation signatures.

**Comment by equalsJeffH** [comment]
<a href="https://github.com/equalsJeffH"><img src="https://avatars.githubusercontent.com/u/226571?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Original poster: [equalsJeffH](https://github.com/equalsJeffH)**, on: _Monday Dec 07, 2015 at 19:50 GMT_

----

see also #108 #114  --  this remains an open issue the w3c web authn wg will need to address once it begins work. thus setting milestone to ms-fido-v2.0-w3c

**Comment by vijaybh** [comment]
Will be addressed as part of editorial moving-sections-around update.
