### ISSUE TITLE
remove alg argument lists in Abort Operation section

### ISSUE THREAD

**Issue by equalsJeffH** [w3c/webauthn#707]
Our convention of mostly always listing the argument list of our [\[\[Create\]\](origin, options, sameOriginWithAncestors)](https://www.w3.org/TR/2017/WD-webauthn-20171205/#createCredential) and [\[\[DiscoverFromExternalSource\]\](origin, options, sameOriginWithAncestors)](https://www.w3.org/TR/2017/WD-webauthn-20171205/#discover-from-external-source) internal methods unfortunately renders the "[Abort operations with AbortSignal](https://www.w3.org/TR/2017/WD-webauthn-20171205/#abortoperation)" section almost unreadable.

This is my overly-zealous fault.  I propose to rectify it by using the form-with-arglist for each of [\[\[Create\]\]](https://www.w3.org/TR/2017/WD-webauthn-20171205/#createCredential) and [\[\[DiscoverFromExternalSource\]\]](https://www.w3.org/TR/2017/WD-webauthn-20171205/#discover-from-external-source)'s first occurances in that section and then abbreviate them to only [\[\[Create\]\]](https://www.w3.org/TR/2017/WD-webauthn-20171205/#createCredential) and [\[\[DiscoverFromExternalSource\]\]](https://www.w3.org/TR/2017/WD-webauthn-20171205/#discover-from-external-source) in further occurances.

WDYT?

**Comment by emlun** [comment]
Sounds good to me. I wouldn't be against dropping the parameter lists from most or all references to the methods - they each have only one parameter signature, right? - but I don't know about the broader conventions on this.

**Comment by equalsJeffH** [comment]
Ok, I looked into this and given the way bikeshed links-up IDL and all it seems that absent some specialized tweaking of said linking, it's just the way it is, and not worth a bunch of time trying to figure it out. so I suggest I close this wontfix.
