### ISSUE TITLE
"5.4. Options for Credential Creation" still lists PublicKeyCredentialUserEntity.name

### ISSUE THREAD

**Issue by ttaubert** [w3c/webauthn#714]
It looks like `PublicKeyCredentialUserEntity.name` existed in the past, but has now been removed.

The second section of "5.4. Options for Credential Creation", the one talking about the `user` field, needs to be corrected and not reference the old `name` field.

**Comment by emlun** [comment]
The member is inherited from the `PublicKeyCredentialEntity` base type, which is also where "name" links to from the section you mentioned.

**Comment by ttaubert** [comment]
Yeah... I just realized that too. Sorry.

**Comment by emlun** [comment]
No worries, thanks for reviewing the spec!
