### ISSUE TITLE
Clarify that extensions are optional and may not be supported

### ISSUE THREAD

**Issue by leshi** [w3c/webauthn#74]
In the current spec, the extensions section is called "standard extensions".  This, plus the descriptions text, do not convey the intention that extensions are optional and may not be supported by certain platforms or authenticators.  We should clarify this

**Comment by gmandyam** [comment]
@leshi 

What is meant by "supported by certain platforms"? Do you mean UA's?  Do you mean the native OS's on which the UA's run?  Or do you mean both?  

Also, when you say "extensions are optional" do you mean optional for the authenticator, or optional for the UA, or both?
