### ISSUE TITLE
User consent for location extension

### ISSUE THREAD

**Issue by samuelweiler** [w3c/webauthn#744]
The location extension needs user consent.  This is mentioned briefly in section 11.2.  It should also be mentioned in both the definition section (10.7) and security considerations.

**Comment by nadalin** [comment]
@selfissued  As you look at the security considerations section can you add this

**Comment by gmandyam** [comment]
This issue has essentially been opened and closed before - see https://github.com/w3c/webauthn/issues/208.  I would recommend closing this issue, and address the fundamental topic in a PR to address https://github.com/w3c/webauthn/issues/133.
