### ISSUE TITLE
PING suggest referencing the FIDO 100k batch requirements

### ISSUE THREAD

**Issue by agl** [w3c/webauthn#749]
During the PING conference call of 2018-01-11, PING suggested that we reference the FIDO batch requirements.

**Comment by equalsJeffH** [comment]
s/batch requirements/privacy principles/ ?  if so then is this a duplicate of issue #742 ?

**Comment by agl** [comment]
We can obviously decide whether we actually want to do this, but the request that I noted down from the phone call was to reference the batch requirements for attestation certificates specifically. The FIDO Privacy Principles document doesn't seem to contain that.

**Comment by nadalin** [comment]
@agl I think there is no harm as long as this is guidance, and this is not a duplicate of #472 so I think we should just do this

**Comment by selfissued** [comment]
@agl where do you want this reference to be and what do you want it to say?  I'll create a PR to add it if I know what to write.
