### ISSUE TITLE
Packed Attestation & Certificates

### ISSUE THREAD

**Issue by apowers313** [w3c/webauthn#768]
cc: @Geoffrey-Li @rlin1

During the WebAuthn informal interop two questions came up about [packed attestation certification requirements](https://w3c.github.io/webauthn/#packed-attestation-cert-requirements):

1. Should the Organizational Unit (OU) be a string literal `"Authenticator Attestation"`?
2. What is the format of the AAGUID in `id-fido-gen-ce-aaguid`? Hex?

**Comment by agl** [comment]
I would say:

1) Yes, as a UTF8String
2) ASN.1 OCTET STRING

If nobody disagrees, I can clarify the above.
