### ISSUE TITLE
Rename MakePublicKeyCredentialOptions?

### ISSUE THREAD

**Issue by apowers313** [w3c/webauthn#773]
I realize this is late in the game, but can we rename `MakePublicKeyCredentialOptions` to `PublicKeyCredentialCreateOptions` so that it matches the naming conventions of [other APIs](https://developer.mozilla.org/en-US/docs/Web/API)? It's just a dictionary (not an interface), so hopefully it would be an easy change...

**Comment by selfissued** [comment]
I will create a PR to do this unless I hear objections.

**Comment by selfissued** [comment]
@apowers313 are there any other names that are similarly inconsistent in this way?  If so, please name them now.  It's getting pretty late to be making changes of this nature.

**Comment by nadalin** [comment]
@selfissued Please create PR and we will discuss

**Comment by emlun** [comment]
One other case of inconsistent names is the fields of [`PublicKeyCredentialEntity`][pkce] and its subclasses, as discussed in #646. It was then decided not to do that breaking change so close to CR.

[pkce]: https://w3c.github.io/webauthn/#dictionary-pkcredentialentity
