### ISSUE TITLE
s/CTAP canonical CBOR/CTAP2 canonical CBOR/g

### ISSUE THREAD

**Issue by apowers313** [w3c/webauthn#774]
The next version of the CTAP specifications will change the term `CTAP canonical CBOR` to `CTAP2 canonical CBOR`. WebAuthn specs should be updated accordingly.

**Comment by selfissued** [comment]
Can you please create a PR doing this, @apowers313 ?

**Comment by apowers313** [comment]
@selfissued see PR #783
