### ISSUE TITLE
§9.5. "Authenticator extension processing" is ambiguous

### ISSUE THREAD

**Issue by emlun** [w3c/webauthn#775]
As discussed in #724, [§9.5. Authenticator extension processing][sec] could use a revision to make it less ambiguous.

>The CBOR authenticator extension input value of each processed authenticator extension is included in the extensions data part of the authenticator request. This part is a CBOR map, with CBOR extension identifier values as keys, and the CBOR authenticator extension input value of each extension as the value.

This section can be interpreted as both of the following:

- The authenticator extension inputs as a whole is a CBOR map, where the values are not necessarily maps.
- Each value in the authenticator extension inputs is a CBOR map.

[sec]: https://w3c.github.io/webauthn/#sctn-authenticator-extension-processing

**Comment by selfissued** [comment]
The meaning is already clear - that the authenticator extension input value is the map value (with the extension identifier being the map key).  It doesn't say that the authenticator extension input value is a map - just that it's CBOR.  But if you want to make this even clearer, please create a PR and I'll review it.

**Comment by emlun** [comment]
I'd argue that the confusion in #724 is evidence the meaning is not clear enough.

PR #776 is an attempt to fix this.

**Comment by nadalin** [comment]
@selfissued Do you agree with @emlun or do you still think it if finer as is ?

**Comment by equalsJeffH** [comment]
@selfissued has approved the related PR #776
