### ISSUE TITLE
biblio.json: TPM refs 404

### ISSUE THREAD

**Issue by equalsJeffH** [w3c/webauthn#78]
The present links for the four TPM references in biblio.json 404 for me. Though, I found working links on these pages.. 
http://www.trustedcomputinggroup.org/tpm-library-specification/

http://www.trustedcomputinggroup.org/tpm-main-specification/

http://www.trustedcomputinggroup.org/tcg-ek-credential-profile-tpm-family-2-0/

http://www.trustedcomputinggroup.org/infrastructure-work-group-tcg-credential-profiles-specification/

**Comment by equalsJeffH** [comment]
well,  attempting to fetch the TPM Main Specification Level 2 Version 1.2 specs via http://www.trustedcomputinggroup.org/tpm-main-specification/ did not work for me, however the link to ISO did work and the ISO versions of these specs downloaded fine.

**Comment by vijaybh** [comment]
Merging since this was tagged OKtoDo
