### ISSUE TITLE
normalizing term(s) for authenticator-generated RP-specific public key

### ISSUE THREAD

**Issue by equalsJeffH** [w3c/webauthn#79]
The terms `public key`, `credential public key`, `attested public key`, `public key generated by the Authenticator`, and `public key associated with the credential` are all used to refer to the same thing.  

We should come up with an appropriate term/phrase for this and use it consistently throughout the spec.

**Comment by vijaybh** [comment]
Good idea. I would like to give this the [RP] treatment - define a macro for it, use that everywhere,

Would "credential public key" work?

**Comment by equalsJeffH** [comment]
due to spec changes since this issues was submitted, the two sets of terms  that are the subject of this issue now appear to be:

>public key
credential public key
public key of the credential

>private key
credential private key
private key associated with the credential
private key of the selected credential

**Comment by nadalin** [comment]
@equalsJeffH can this be closed now that we have reconciled with CredMan ?

**Comment by equalsJeffH** [comment]
this  is superseded see issue #358
