### ISSUE TITLE
reference "UTF-8 decode" directly rather than "parse JSON from bytes" 

### ISSUE THREAD

**Issue by equalsJeffH** [w3c/webauthn#792]
we recently insterted:
> Let |C|, the [=client data=] claimed as collected during the credential creation, be the result of [=parse JSON from bytes|parsing JSON from the bytes=] in <code>|response|.{{AuthenticatorResponse/clientDataJSON}}</code>.

However, this is most likely invoked RP-server-side, and is JS-specific (as we discussed).  I'm thinking we can make it implementation-non-specific by referencing https://encoding.spec.whatwg.org/#utf-8-decode, which is what [parse JSON from bytes](https://infra.spec.whatwg.org/#parse-json-from-bytes)  does in any case, and indicating that any impl is fine as long as the end results are the same as [UTF-8 decode](https://encoding.spec.whatwg.org/#utf-8-decode) provides.

See PR #793 

also fixes #712

**Comment by emlun** [comment]
I agree with making it not JS specific. Just note that this is not only UTF decoding, but also JSON parsing after that.

**Comment by equalsJeffH** [comment]
> note that this is not only UTF decoding, but also JSON parsing after that.

ah, yes, will update PR accordingly
