### ISSUE TITLE
adopt consistent terms for RP server-side and client-side components

### ISSUE THREAD

**Issue by equalsJeffH** [w3c/webauthn#80]
see also issue #358

We use the terms `script`, `a script`, `the script`, `scripts`, `browser script`, `javascript`, `WebAuthn Relying Party script`, `WebAuthn Relying Party client-side app`, `the client-side app`, `RP’s client-side app`, and `the WebAuthn Relying Party client-side application` to refer to the same **RP client-side component**.  

We use the terms `the server`, `server`, `servers`, and `WebAuthn Relying Party’s server` to refer to the same **RP server-side component**. 

We should decide on one consistent series of terms (and acronyms, as appropriate) to cover all the necessary semantic bases. 

some ideas: 

[ Note: " {....}" denotes optionality and possibly use of acronyms such as "RP", "RP's", "RPs". ]

client-side:   {  [[RP]] | [[RPS]]  }  script    // plus create glossary entry and clearly equate to "WebAuthn Relying Party's client-side webapp component" (or unambiguous equivalent).  

server-side:  {  [[RP]] | [[RPS]]  }  server   // plus create glossary entry and clearly equate to "WebAuthn Relying Party's server-side webapp component" (or unambiguous equivalent).

**Comment by nadalin** [comment]
@selfissued can you please verify that the document is consistent

**Comment by AngeloKai** [comment]
From what I am reading here, the issue shouldn't change the name of the API. I am removing the subtype:renaming tag.

**Comment by equalsJeffH** [comment]
see also #358

**Comment by nadalin** [comment]
@equalsJeffH will clean up dups

**Comment by equalsJeffH** [comment]
I checked the current editors' draft and most of the cruft I'd noted in the orig post has been cleaned up, so am closing this.
