### ISSUE TITLE
Mention FIDO transports extension in X.509 cert requirements?

### ISSUE THREAD

**Issue by emlun** [w3c/webauthn#817]
U2F attestation certificates may include the [`id-fido-u2f-ce-transports` extension][tr-ext], listing the connectivity options of the attested authenticator. Should we mention this as an optional extension in the [packed attestation statement certificate requirements][reqs]?

Is there anything else that would make sense to gather here?

[reqs]: https://w3c.github.io/webauthn/#packed-attestation-cert-requirements
[tr-ext]: https://fidoalliance.org/specs/fido-u2f-v1.1-id-20160915/fido-u2f-authenticator-transports-extension-v1.1-id-20160915.html

**Comment by selfissued** [comment]
Where is the `id-fido-u2f-ce-transports` certification extension defined?  We should probably reference the definition rather than repeating it in WebAuthn.

**Comment by emlun** [comment]
It's defined here: https://fidoalliance.org/specs/fido-u2f-v1.1-id-20160915/fido-u2f-authenticator-transports-extension-v1.1-id-20160915.html

I agree we should reference rather than repeating it, but the bigger question is whether we want it mentioned. I've received comments that it could be nice to collect all the things that are likely to appear in attestation certs in one place - and this is one such extension, as some vendors will basically be updating their existing U2F stuff to CTAP2/WebAuthn.

If people agree this makes sense to include, I can write a PR. If not we can just leave it be, it would be optional after all.

**Comment by akshayku** [comment]
This is U2F specific extension. For CTAP equivalent, one has to come up with new extension with new OID. I would just leave it be as you can have the same information with FIDO MDS if someone cares.

**Comment by nadalin** [comment]
@akshayku @selfissued @emlun Should we close this no action ?

**Comment by emlun** [comment]
Yeah, I think so. If someone wants this more than @akshayku does not, please re-open it.
