### ISSUE TITLE
Subject-C type in packed cert requirements is incorrect

### ISSUE THREAD

**Issue by emlun** [w3c/webauthn#818]
The [packed attestation statement certificate requirements][reqs] list the Subject-C field as an ASN.1 UTF8String:

>**Subject-C**
>ISO 3166 code specifying the country where the Authenticator vendor is incorporated (UTF8String)

But [RFC 5280][rfc] page 115 defines the field as an ASN.1 PrintableString:

>X520countryName ::=     PrintableString (SIZE (2))

[reqs]: https://w3c.github.io/webauthn/#packed-attestation-cert-requirements
[rfc]: https://tools.ietf.org/html/rfc5280#page-115

**Comment by selfissued** [comment]
Can you create a PR fixing this, @emlun ?

**Comment by emlun** [comment]
Will do.

**Comment by emlun** [comment]
I think this could probably be punted to PR if it would block the CR release.

**Comment by nadalin** [comment]
@emlun if we can get it done by 2/25 then we can make CR
