### ISSUE TITLE
vestigial remainders leftover from not completely removing client extension data from client data

### ISSUE THREAD

**Issue by equalsJeffH** [w3c/webauthn#828]
see https://github.com/w3c/webauthn/issues/828#issuecomment-371239195 and https://github.com/w3c/webauthn/issues/828#issuecomment-371626220 below for current actual issue.

<hr>
original post for this issue:

cloud bikeshed [1] is issuing these errors on index.bs at commit 716a169:
```
\033[1;33mLINK ERROR:\033[0m No 'idl' refs found for 'clientExtensions'.
{{CollectedClientData/clientExtensions}}
\033[1;33mLINK ERROR:\033[0m No 'idl' refs found for 'excludeCredentials' with for='MakePublicKeyCredentialOptions'.
{{MakePublicKeyCredentialOptions/excludeCredentials}}
\033[7;32m ✔ \033[0m Successfully generated, with 2 linking errors
```
[1] curl https://api.csswg.org/bikeshed/ -F file=@index.bs -F force=1 -F output=err

**Comment by selfissued** [comment]
Note that if you go to https://api.csswg.org/bikeshed/, it puts up an interactive UI (just like xml2rfc does) so you can use it without having to have curl.  Check the "Errors & Warnings" button and click "Process" to see the resulting errors.

**Comment by rlin1** [comment]
in section "9.4. Client extension processing" we state: "Supported client extensions are recorded as a dictionary in the client data with the key clientExtensions".

But when looking at client data (https://www.w3.org/TR/webauthn/#client-data), which points to the collected clientData dictionary, there is NO clientExtensions field.

**Comment by equalsJeffH** [comment]
On the 7-Mar-2018 webauthn call, @selfissued (mike jones) noted that what Rolf is noticing (https://github.com/w3c/webauthn/issues/828#issuecomment-371239195) appears to be vestigial remainders leftover from not completely removing client extension data from client data.  He said he would look into addressing it.

**Comment by equalsJeffH** [comment]
reopening because the 2nd linking error noted in the OP https://github.com/w3c/webauthn/issues/828#issue-303167961 is not as-yet resolved. 

it's a couple refs in priv-cons that are `{{MakePublicKeyCredentialOptions/excludeCredentials}}`  but should be  `{{PublicKeyCredentialCreationOptions/excludeCredentials}}`
