### ISSUE TITLE
Review of WD08

### ISSUE THREAD

**Issue by Kieun** [w3c/webauthn#831]
Since the lack of time for reviewing full documents, I added some suggestions after reading the part of the specs.

1. In Abstract section, there is a high level description of this spec. Since attestation also involves signature generation, we may use _attestation_ in stead of _signature_ from the following sentence.
   > This specification also describes the functional model for WebAuthn conformant authenticators, including their **signature** and attestation functionality.

2. Chapter 2.4 describes CBOR encoding by referring FIDO2 CTAP Spec. The link for the spec is broken. Also chapter 3 has same reference which is broken.
Here's valid link for the spec
https://fidoalliance.org/specs/fido-v2.0-ps-20170927/fido-client-to-authenticator-protocol-v2.0-ps-20170927.html#message-encoding

3. Regarding FIDO AppID definition in Chapter 3, we may add link to FIDO AppID extension (https://www.w3.org/TR/2018/WD-webauthn-20180306/#sctn-appid-extension).

4. In Chapter 4, there is a terminology regarding an Authenticator. Since some authenticator dose not have user verification features, we need to add **user presence test** to following sentence.
   > A cryptographic entity used by a WebAuthn Client to (i) generate a public key credential and register it with a Relying Party, and (ii) authenticate by potentially verifying the user, and then cryptographically signing and returning, in the form of an Authentication Assertion, a challenge and other data presented by a Relying Party (in concert with the WebAuthn Client).

5. In Chapter 4, Client-side-resident Credential Private Key is described. There is a term **roaming authenticator**. We may refer following link.
https://www.w3.org/TR/2018/WD-webauthn-20180306/#roaming-authenticators
Also we may change Authenticator to authenticator in this description.

**Comment by emlun** [comment]
Thanks for the review!

1. Do you suggest rewriting the quoted text to this?

    >This specification also describes the functional model for WebAuthn conformant authenticators, including their attestation and attestation functionality.

2. Good catch, thanks!

    For the record: What is broken is the fragment part `#ctap2-canonical-cbor-encoding-form`, which should be `#message-encoding`. The document URL is fine.

3. Good catch, thanks!

4. I don't think that's strictly necessary, because "**potentially** verifying the user" points out that authenticators do not need to perform user verification.

5. Good catch, thanks!

**Comment by emlun** [comment]
Opened PR #832 which addresses (2), (3) and (5). Leaving (1) and (4) open for discussion.

**Comment by Kieun** [comment]
@emlun regarding issue 1, I think we'd better use assertion instead of signature. Since main operations for this spec are regarding attestation and assertion.

> This specification also describes the functional model for WebAuthn conformant authenticators, including their attestation and assertion functionality.

**Comment by emlun** [comment]
Ok, I see. I think it might be better to stick to "signature" instead of "assertion" here. The abstract should get the general point across without introducing too much new terminology, and the reader is more likely to be familiar with "signature" than "assertion" which hasn't yet been introduced at that point.

**Comment by emlun** [comment]
Fixed by #832.
