### ISSUE TITLE
Unused terms

### ISSUE THREAD

**Issue by emlun** [w3c/webauthn#833]
As a complement to #462, this is a list of terms that are defined but not referenced outside of their definition.

- [Client-Side](https://www.w3.org/TR/webauthn/#client-side)
- [Rate Limiting](https://www.w3.org/TR/webauthn/#rate-limiting)

**Comment by gmandyam** [comment]
@emlun, re: Rate Limiting

I wrote the rate limiting definition to tie into user verification by including the sentence "Rate limiting is often implemented as an aspect of user verification."  The definition for user verification could be augmented to include a reference to rate limiting there if you think this would make the spec cleaner.

See https://github.com/w3c/webauthn/pull/499 and https://github.com/w3c/webauthn/pull/484.

**Comment by emlun** [comment]
@gmandyam Ok, thanks for the background. I do think it seems odd to include a terminology definition that's never referenced. I agree that adding some small mention of it, probably in the user verification steps in the authenticator ops, would be good - but judging by comments like https://github.com/w3c/webauthn/pull/484#issuecomment-308512322 it seems like the WG felt it was unnecessary to mention rate limiting at all in this spec, so I'm not sure where to go from here. @equalsJeffH You also participated in #499, any thoughts on this?

**Comment by emlun** [comment]
"Rate Limiting" is referenced in #956, and "Client-Side" has been added to #462; closing this.
