### ISSUE TITLE
Candidate recommendation exit criteria

### ISSUE THREAD

**Issue by samuelweiler** [w3c/webauthn#837]
The Director expects CR documents to explicitly state the criteria for getting to PR. We can set criteria of our choice, but the suggestion is: "In order for this specification to exit Candidate Recommendation there must be demonstrations of at least two interoperable implementations of every feature."

The general rule is that CRs "must document how adequate implementation experience will be demonstrated" and that in moving to PR we "must show adequate implementation experience except where an exception is approved by the Director."  So we need to carefully set a standard that we expect to be able to meet.

We may identify features "at risk" or with different criteria than the bulk.

**Comment by samuelweiler** [comment]
Some of this is from https://www.w3.org/2018/Process-20180201/#candidate-rec

**Comment by samuelweiler** [comment]
here's an example:  https://www.w3.org/TR/2014/CR-WebCryptoAPI-20141211/

For this specification to be advanced to Proposed Recommendation, there must be at least two independent, interoperable implementations of each feature.

Each cryptographic algorithm listed in the specification is currently an "at risk" feature. In particular, we are expecting a "browser profile" to be created of interoperable algorithms for Web browsers. To exit to Proposed Recommendation, each algorithm listed in the specification should have two interoperable implementations. Furthermore, there is an open dependency on the IRTF CFRG in terms of algorithm(s). These issues should be resolved by the interoperability testing necessary to exit CR.

**Comment by emlun** [comment]
Are the extensions included in those features? I.e., does every extension need to be implemented by at least two independent browsers and (where applicable) authenticators?

**Comment by samuelweiler** [comment]
I suggest we mark all extensions as "at risk" or at least set a lower bar for them.

**Comment by nadalin** [comment]
Since these are extensions and we are only testing input and output and all formats are same then I would say that extensions should be fine and not at risk

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by equalsJeffH** [comment]
seems to me since this is "exit (CR) criteria" I'd attach it to the PR milestone....

**Comment by samuelweiler** [comment]
JeffH: We need this in the CR draft.

Here's another example: https://www.w3.org/TR/wake-lock/

**Comment by samuelweiler** [comment]
FYI, you might need to add this include file via a PR to:
https://github.com/tabatkins/bikeshed/tree/master/bikeshed/boilerplate/webauthn

**Comment by nadalin** [comment]
"For the Web Authentication specification to move to Proposed Recommendation we must show two independent, interoperable implementations of the Web Authentication API in browsers. We have already completed a portion of this work at two informal interops with implementations from three browsers (Chrome, Firefox, and Edge). These initial compliance tests have yielded relevant datasets. We also have a suite of initial compliance tests that have been committed to the W3C Web Platform Test repo and additional improvements to the tests will be required for the move to Proposed Recommendation."

**Comment by selfissued** [comment]
Per the call, I am to add a sentence to this description about the extensions framework and having multiple interoperable implementations of at least one extension to validate the framework.

**Comment by nadalin** [comment]
yes

**Comment by selfissued** [comment]
All extensions are optional and all but AppID are at risk.

**Comment by samuelweiler** [comment]
"All extensions are optional.  All except for appid are at risk."

**Comment by samuelweiler** [comment]
Consistent with https://lists.w3.org/Archives/Public/public-webauthn/2018Mar/0143.html, I propose the following text for the CR.  Absent objection, I'll include this in the CR as published, and we'll need to backport it into the github source later:

>  For the Web Authentication specification to move to Proposed Recommendation we must show two independent, interoperable implementations of the Web Authentication API in browsers. We will also have multiple interoperable implementations of the AppID extension, validating the extensions framework. All other extensions are "at risk". If there are not multiple interoperable implementations, each may independently be removed or made informative at Proposed Recommendation.

> We have had two informal interoperability tests with implementations in three browsers.

**Comment by selfissued** [comment]
@Nadalin to talk with @AngeloKai about addressing this.

**Comment by AngeloKai** [comment]
@samuelweiler I just filed a PR for the CR include: https://github.com/tabatkins/bikeshed/pull/1285

**Comment by AngeloKai** [comment]
@samuelweiler can you please help draft the PR include? I started a PR here: https://github.com/tabatkins/bikeshed/pull/1286. But feel free to update it as you see fit. Same goes for @nadalin

**Comment by AngeloKai** [comment]
@samuelweiler The CR include was just merged. Please take a look.
