### ISSUE TITLE
Most recent Process (2018) has a different list for maturity levels

### ISSUE THREAD

**Issue by koalie** [w3c/webauthn#841]
I saw the CR milestone refers to the Process 2015 list for maturity levels; the process was updated twice since then. Most recent is 2018:
see https://www.w3.org/2018/Process-20180201/#maturity-levels

**Comment by equalsJeffH** [comment]
I edited the description of our [CR milestone](https://github.com/w3c/webauthn/milestone/15) to be: 
> Candidate spec for "Candidate Recommendation" maturity level. See https://www.w3.org/Consortium/Process/#maturity-levels
