### ISSUE TITLE
AppID / origin

### ISSUE THREAD

**Issue by apowers313** [w3c/webauthn#853]
The [AppID extension](https://w3c.github.io/webauthn/#sctn-appid-extension) says `let facetId be the origin`; should it say `let facetId be the rpId`, since rpId may be set through a parameter and may be more strict than the origin?

**Comment by equalsJeffH** [comment]
hm, are you looking at the latest spec rev? The [current text](https://w3c.github.io/webauthn/#sctn-appid-extension) says:
> 2. Let facetId be the result of passing the caller’s origin to the FIDO algorithm for determining the FacetID of a calling application.

Does that address your issue/question?

**Comment by apowers313** [comment]
[Section 5.5 PublicKeyCredentialRequestOptions](https://w3c.github.io/webauthn/#dictdef-publickeycredentialrequestoptions) allows an application to pass in a claimed `rpId` parameter to a `.get()` call. My question was whether the AppID extension should be using the claimed (and validated) `rpId` as the facet or the `origin`. Although after thinking about this more, that doesn't really make sense...
