### ISSUE TITLE
ScopedCredentialInfo attestation

### ISSUE THREAD

**Issue by apowers313** [w3c/webauthn#86]
Per conversation with @vijaybh, the attestation member of ScopedCredentialInfo should be defined as optional in the WebIDL interface definition.

**Comment by vijaybh** [comment]
Minor correction - Nullable, not optional

**Comment by equalsJeffH** [comment]
Nominally, I think optional attestation is fine -- it is up to the RP's risk tolerance whether they accept a unattested registrations. We will need to carefully examine the ramifications in the security considerations, tho.

**Comment by equalsJeffH** [comment]
Rolf argues for using at least surrogate basic attestation rather than simply nullable attstn: https://fidoalliance.org/specs/fido-uaf-v1.0-ps-20141208/fido-uaf-protocol-v1.0-ps-20141208.html#surrogate-basic-attestation
