### ISSUE TITLE
CTAP alignment: Authenticator ops UP option

### ISSUE THREAD

**Issue by emlun** [w3c/webauthn#862]
The current [CTAP][ctap] draft no longer has the `up` option in [authenticatorMakeCredential][ctap-amc], and [authenticatorGetAssertion][ctap-aga] now clearly specifies when to collect user consent and set the UP bit. We can therefore eliminate the `requireUserPresence` parameter of our [authenticatorMakeCredential][amc], and always pass `true` for the value of the `requireUserPresence` parameter of our [authenticatorGetAssertion][aga].

[amc]: https://w3c.github.io/webauthn/#op-make-cred
[aga]: https://w3c.github.io/webauthn/#op-get-assertion
[ctap]: https://drafts.fidoalliance.org/fido-2/latest/fido-client-to-authenticator-protocol-v2.0-wd-20180305.html
[ctap-aga]: https://drafts.fidoalliance.org/fido-2/latest/fido-client-to-authenticator-protocol-v2.0-wd-20180305.html#authenticatorGetAssertion
[ctap-amc]: https://drafts.fidoalliance.org/fido-2/latest/fido-client-to-authenticator-protocol-v2.0-wd-20180305.html#authenticatorMakeCredential

**Comment by emlun** [comment]
Can we perhaps also eliminate the `requireUserPresence` parameter of `authenticatorGetAssertion`, and let CTAP note in its correspondence table that WebAuthN always sends a constant `true` as the value of `options.up`?

**Comment by selfissued** [comment]
Just because an option isn't in CTAP doesn't mean that it might not be valuable in WebAuthn.  There are authenticators other than CTAP authenticators, such as platform authenticators.  There's good arguments not to delete this.
