### ISSUE TITLE
Delete per RP ID Signature counters

### ISSUE THREAD

**Issue by limpkin** [w3c/webauthn#871]
Section 6.1.1 mentions:  
  
> (The authenticator) should implement per RP-ID signature counters. This prevents the signature counter value from being shared between Relying Parties and being possibly employed as a correlation handle for the user. Authenticators may implement a global signature counter, i.e., on a per-authenticator basis, but this is less privacy-friendly for users.
  
A global signature counter may hypothetically allow several websites to identify a given user even if said user uses different IP addresses and other means of covering his tracks.  
The per RP-ID suggestion is therefore a great improvement. It however does (IMHO) only offers a "half way" compromise as it would allow a given RP to identify the different aliases of a given user for a given RP through his per RP-ID counter.  

Section 6.2.2, step 10 then mentions the possibility of a "per credential signature counter" which does offer the best solution regarding privacy-concerned users.  

The question I therefore would like to ask is : why offer the possibility to authenticators to implement per RP-ID credential counters when the privacy friendly and non-privacy friendly alternatives are available?  
I would then suggest adding a counter to the Public Key Credential Source structure, especially given the fact that "an authenticator will never contain more than one credential for a given Relying Party under the same user handle." (from 4. Terminology), which (if I'm not mistaken) also means that a given Public Key Credential Source will only be used for a single credential.

I'm still digging into the spec so I apologize if I may have missed some important info.

**Comment by emlun** [comment]
Thanks, this is a good observation.

>which (if I'm not mistaken) also means that a given Public Key Credential Source will only be used for a single credential.

Yes, this is correct.

Furthermore, [§6.1.1. Signature Counter Considerations][cons] doesn't mention per-credential counters at all, and strongly recommends per-RP ID counters. It also specifies that authenticators MUST implement a signature counter, which is not true. In previous discussion in the WG we decided to allow authenticators to opt out of implementing a signature counter by keeping the signature count at constant zero (see https://github.com/w3c/webauthn/pull/539#issuecomment-327575050 and https://github.com/w3c/webauthn/pull/539#issuecomment-326831893 for context) - and [§7.2. Verifying an authentication assertion][rp] mirrors this by instructing validate the signature counter only if it is nonzero.

[cons]: https://www.w3.org/TR/webauthn/#sign-counter
[rp]: https://www.w3.org/TR/webauthn/#verifying-assertion

**Comment by limpkin** [comment]
Oh, I didn't notice the non-zero check indeed.

On a semi-related note, as I'm mainly looking at the authenticator side of things, is there any client framework available on the computer side of things with different place holders for communications with authenticator prototypes? Assertion-related communication examples at a very low level would be welcome in the spec.

**Comment by emlun** [comment]
That sounds out of scope for this specification - WebAuthn specifies only an abstract authenticator model and leaves client-to-authenticator communications unspecified. You may be looking for the [FIDO CTAP][ctap] specification instead.

[ctap]: https://fidoalliance.org/specs/fido-v2.0-ps-20170927/fido-client-to-authenticator-protocol-v2.0-ps-20170927.html

**Comment by selfissued** [comment]
This contravenes a working group decision and removing the signature counter would be a breaking change.

**Comment by rlin1** [comment]
I would be OK with 
a) explicitly mentioning per-credential signature counters.  This is NOT a breaking change IMHO as it would not affect the browser, the server or existing authenticators.  New authenticator could implement that scheme if they want.  I would also argue that implementing that is not explicitly disallowed today.
b) recommend ("should...") implementation of per-credential signature counters.

**Comment by agl** [comment]
I think the decision to include signature counters has been settled at this point.

I think the suggestion in the spec that signature counters be per-RP (rather than per-credential) was probably just a mistake? We do not otherwise assume that an RP gets to learn information about other credentials for that RP in the same authenticator, as far as I can recall. (Indeed the term &ldquo;per-RP&rdquo; only appears in this context in the spec.)

@emlun points out that we also have an inconsistency in the spec too: [here](https://www.w3.org/TR/webauthn/#sign-counter) we say &ldquo;Authenticators MUST implement a signature counter feature&rdquo; but [here](https://www.w3.org/TR/webauthn/#verifying-assertion) (step 17) a zero signature counter is allowed.

(I obviously think that we should align with the latter of the two.)

**Comment by emlun** [comment]
Per-credential signature counters are already mentioned in step 10 of [authenticatorMakeCredential][amk], but not in [§6.1.1. Signature Counter Considerations][sig-cons].

The current recommendation ("should...") in [§6.1.1. Signature Counter Considerations][sig-cons] is to use per-RP ID counters. @limpkin is suggesting

1. changing this recommendation to per-credential counters instead, and
2. removing the mentions of per-RP ID counters.

We could opt for doing both (1) and (2), or only (1), or neither.

(1) is not a breaking change; (2) could technically make authenticators non-conforming (if any exist), depending on how strictly you read the spec, but wouldn't break any interoperability.

I support doing (1), I'm indifferent to (2), and I do not object to doing neither.

[amk]: https://w3c.github.io/webauthn/#op-make-cred
[sig-cons]: https://w3c.github.io/webauthn/#sign-counter

**Comment by akshayku** [comment]
Also, we have to fix inconsistency in the spec. "Authenticators MUST implement a signature counter" is incorrect. We have to change this to "Authenticators SHOULD implement a signature counter"

**Comment by akshayku** [comment]
@emlun , we should do both (1) and (2)

**Comment by emlun** [comment]
@akshayku Thanks for clearing that up!

There seems to be broad agreement that this is something we should do, so shall we move this to the PR milestone?

**Comment by akshayku** [comment]
I think we should.
