### ISSUE TITLE
cleanup: mark & structure biblio references consistently

### ISSUE THREAD

**Issue by equalsJeffH** [w3c/webauthn#872]
Presently, we've (myself included) become somewhat sloppy with our biblio references and auto-link entries.  There's at least two broad categories:

The first, for example, is that we are not consistent in marking citations as **(non-)normative**, e.g.:
```
[...]
        <td>
            The ...
            as defined in Section 7 of [[RFC8152]] ...
[...]
    1. Convert the COSE_KEY ... (see Section 7 of [[!RFC8152]]) to CTAP1/U2F user public key ...
[...]
```
...note the inconsistency in using the normative exclamation mark citation signal **`!`** in the above cites of RFC8152.  There are similar inconsistencies with cites of other specs.

It appears that if a referenced spec is marked normative (at least once?) then it is placed in the "Normative" biblio section, thus cleaning up is not high priority, but probably something we ought to do.

The second cleanup aspect of this is we are creating cross-spec links that are syntactically  inconsistent. E.g.:
```
<pre class="anchors">
[...]
spec: TokenBinding; urlPrefix: https://tools.ietf.org/html/draft-ietf-tokbind-protocol#
    type: dfn
        text: Token Binding
        text: Token Binding ID; url: section-3.2                   [A]
[...]
spec: FIDO-CTAP; urlPrefix: https://fidoalliance.org/specs/fido-v2.0-ps-20170927/fido-client-to-authenticator-protocol-v2.0-ps-20170927.html
    type: dfn
        text: CTAP2 canonical CBOR encoding form; 
           url: ctap2-canonical-cbor-encoding-form                [B]
[...]
</pre> <!-- class=anchors -->

[...]
[[RFC8152]] [Section 7](https://tools.ietf.org/html/rfc8152#section-7)      [C]
...
(see [[RFC8152]]
[Section 13.1](https://tools.ietf.org/html/rfc8152#section-13.1))          [D]
[...]
```
[IIUC](https://en.wiktionary.org/wiki/IIUC),  we ought to be able to craft link anchors in the same fashion as [A] and [B], for the cases of [C] and [D] such that we are using a consistent cross-spec linking approach.

**Comment by selfissued** [comment]
Alll that this is missing is an owner willing to do the work...
