### ISSUE TITLE
NULL or DOMException

### ISSUE THREAD

**Issue by AngeloKai** [w3c/webauthn#876]
The last step of both the Create and Get API specifies that we return NotAllowedError if it fails. But the credential management spec specifies that [the two APIs return a Credential if one can be returned given the options provided, null if no credential is available, or an error if discovery fails (for example, incorrect options could produce a TypeError).](https://www.w3.org/TR/credential-management-1/#credential-internal-methods). We should figure out what case would make us return null.

**Comment by AngeloKai** [comment]
@mikewest fyi

**Comment by emlun** [comment]
We'll need to consider what returning null would mean for [privacy considerations][cons] (#184, #204, #687).

[cons]: https://www.w3.org/TR/webauthn/#sec-assertion-privacy

**Comment by selfissued** [comment]
What are existing implementations doing?

**Comment by equalsJeffH** [comment]
@angelkai am not sure what various browsers are actually doing, need to look at the code....  will do this soon, will look today at Edge and chat with @cbrand

**Comment by nadalin** [comment]
@akshayku Please see what you can do here

**Comment by akshayku** [comment]
Both MakeCredential and GetAssertion has following text as last step. 
> Return a DOMException whose name is "NotAllowedError".

 IMO, this is clear enough and there is no ambiguity. @emlun / @equalsJeffH Is my understanding correct? If not, can you suggest an alternative text?

**Comment by selfissued** [comment]
It seems like we can close this with no need for a pull request because the spec already accurately describes the behavior of the implementations.  Do people agree?

**Comment by equalsJeffH** [comment]
@akshayku 
> We always do DOM exception. We also tried Chrome which always returned DOM exception in our testing.

do you mean "returned DOM exception" as a result of calling  [`navigator.credentials.create()`](https://w3c.github.io/webappsec-credential-management/#dom-credentialscontainer-create) and/or  [`navigator.credentials.get()`](https://w3c.github.io/webappsec-credential-management/#dom-credentialscontainer-get) (as opposed to directly calling the webauthn algorithms)?

@selfissued 
the original issue is pointing at an impedance mismatch between [credman](https://w3c.github.io/webappsec-credential-management)'s expectations and what the webauthn algs return.

In reviewing credman's [`[[Create]](options, sameOriginWithAncestors)`](https://w3c.github.io/webappsec-credential-management/#dom-credential-create-slot) and [S 2.5.4. Create a Credential](https://w3c.github.io/webappsec-credential-management/#algorithm-create), the former is expected by the latter to return `null` if no credential is created. 

Similarly for [`[[DiscoverFromExternalSource]](options, sameOriginWithAncestors)`](https://w3c.github.io/webappsec-credential-management/#dom-credential-discoverfromexternalsource-slot) and  [S 2.5.1. Request a Credential](https://w3c.github.io/webappsec-credential-management/#algorithm-request) where the latter expects the former to to return `null` if no credential is available. 

so I do not think we can simply close this.

**Comment by equalsJeffH** [comment]
in examining webauthn's [S 5.1.3. `[[Create]]()` method  (aka #createCredential)](https://w3c.github.io/webauthn/#createCredential) and [S 5.1.4.1. `[[DiscoverFromExternalSource]]()` method (aka #getAssertion)](https://w3c.github.io/webauthn/#discover-from-external-source), they both seem to always return a credential, or some form of error, and never return `null`.  so +1 to @AngeloKai.

So, _without_ having gone and refreshed myself wrt the privacy subtleties that @emlun notes up above in https://github.com/w3c/webauthn/issues/876#issuecomment-383946531, it sorta seems to me we ought leave webauthn as-is for now and submit an issue on credman to the effect that expecting the tri-state {credential, `null`, error} return value possibilities has privacy issues and perhaps it ought to be two-state {credential, error} (as webauthn's algs are presently).

WDYT?

**Comment by nadalin** [comment]
@equalsJeffH So I would like to leave this as-is and tag this for CredMan as you suggest as the should not change implementations of WebAuthn

**Comment by emlun** [comment]
If asking CredMan to change is an option, I think that seems more appealing. Personally I generally don't like `null` as a return value since its meaning is often quite vague, and it's easy for it to slip by as a "valid value" instead of being detected as the failure it usually represents.

**Comment by selfissued** [comment]
Could someone please file a PR against CredMan aligning it with the implemented WebAuthn behaviors and add a link to it in this issue?

**Comment by selfissued** [comment]
@equalsJeffH agreed to create the CredMan PR on the 8-Aug-18 call

**Comment by selfissued** [comment]
Where are we on getting the CredMan change merged?

**Comment by equalsJeffH** [comment]
I will try to get the credman PR initiated next week.  Getting it merged will take further coordination with webappsec folk.

**Comment by akshayku** [comment]
@equalsJeffH Can we move this out of PropRec as nothing needs to be changed from our side right?

**Comment by YubicoDemo** [comment]
Yes, let's do that. Akshay is right and Tony and I also agree there is nothing to do on Web Authn side.

**Comment by equalsJeffH** [comment]
punted to Rec -- this is essentially a tracking bug for an aspect of our mutual dependency on credman.

**Comment by equalsJeffH** [comment]
credman issue: https://github.com/w3c/webappsec-credential-management/issues/148

closing this webauthn issue.
