### ISSUE TITLE
Does it require a JavaScript library?

### ISSUE THREAD

**Issue by matthewslouismarie** [w3c/webauthn#886]
Initial FIDO U2F version required (or recommended) the use of a JavaScript library to interact with the U2F token. Is a JavaScript library still required to interact with the authenticator, or are browsers supposed to implement the WebIDL specifications natively, allowing the RP to enter WebAuthn code in JavaScript without including any JavaScipt library?

Thanks

**Comment by herrjemand** [comment]
Hey @matthewslouismarie. No it does not. Please try Chrome Canary or Firefox nightly, they have API available straight away.

**Comment by matthewslouismarie** [comment]
Thanks!
