### ISSUE TITLE
Replace [[FIDOReg]] with [[FIDO-Registry]]?

### ISSUE THREAD

**Issue by emlun** [w3c/webauthn#894]
While working on #893 and adding [`[[FIDO-Registry]]`][fido-registry] to the bibliography, I noticed there is an existing [`[[FIDOReg]]`][fidoreg] biblio entry. `[[FIDO-Registry]]` looks to me like a successor of `[[FIDOReg]]`.

Our only reference into `[[FIDOReg]]` is currently from our [§10.8. User Verification Method Extension (uvm)][uvm-ext] to their [Section 3.1 User Verification Methods][uvm], which is practically identical between the two. Shall we replace our references to `[[FIDOReg]]` with references to `[[FIDO-Registry]]`?

[fido-registry]: https://fidoalliance.org/specs/fido-v2.0-ps-20170927/fido-registry-v2.0-ps-20170927.html
[fidoreg]: https://fidoalliance.org/specs/fido-uaf-v1.0-ps-20141208/fido-uaf-reg-v1.0-ps-20141208.html
[uvm]: https://fidoalliance.org/specs/fido-uaf-v1.0-ps-20141208/fido-uaf-reg-v1.0-ps-20141208.html#user-verification-methods
[uvm-ext]: https://w3c.github.io/webauthn/#sctn-uvm-extension

**Comment by emlun** [comment]
@herrjemand @gmandyam Please correct me if my assessment here is incorrect.

**Comment by equalsJeffH** [comment]
I suspect that replacing  [`[[FIDOReg]]`][fidoreg]  with [`[[FIDO-Registry]]`][fido-registry] is fine. @rlin1 ?

[fido-registry]: https://fidoalliance.org/specs/fido-v2.0-ps-20170927/fido-registry-v2.0-ps-20170927.html
[fidoreg]: https://fidoalliance.org/specs/fido-uaf-v1.0-ps-20141208/fido-uaf-reg-v1.0-ps-20141208.html

**Comment by rlin1** [comment]
whether we call it FIDOReg or FIDO-Registry doesn't matter to me, but
today FIDOReg points to FIDO UAF Registry.  Note that there also is a FIDO Registry.
All the things related to multiple specs are in FIDO Registry, the things only used in UAF are in FIDO UAF Registry.
--> We need to check whether the relevant items really are in the registry we refer to here.

**Comment by rlin1** [comment]
Matcher Protection Types, Key Protection Typs and User Verification Methods are defined in FIDO Registry - not FIDO UAF Registry.

**Comment by rlin1** [comment]
This means that (at least for the existing references) we need to change it to reference FIDO Registry.

**Comment by equalsJeffH** [comment]
thx @rlin1 !
