### ISSUE TITLE
update FIDO spec references to link to latest revisions

### ISSUE THREAD

**Issue by equalsJeffH** [w3c/webauthn#898]
for all FIDO spec refs in the [webauthn spec](https://w3c.github.io/webauthn/), if the ref'd FIDO spec can be found amongst the specs presented in https://fidoalliance.org/specs/fido-v2.0-id-20180227/, then update the ref in webauthn spec to point to the FIDO spec in [the latter collection](https://fidoalliance.org/specs/fido-v2.0-id-20180227/).

**Comment by emlun** [comment]
1. @rlin1 [This](https://fidoalliance.org/specs/fido-v2.0-id-20180227/fido-ecdaa-algorithm-v2.0-id-20180227.html#h3_iana-considerations) seems like a newer version of [`[FIDOEcdaaAlgorithm]`](https://fidoalliance.org/specs/fido-uaf-v1.1-id-20170202/fido-ecdaa-algorithm-v1.1-id-20170202.html#h3_iana-considerations), correct?
 2. [`[FIDOMetadataService]`](https://fidoalliance.org/specs/fido-uaf-v1.0-ps-20141208/fido-uaf-metadata-service-v1.0-ps-20141208.html) is an informative reference, so there should be no problem updating that to [this](https://fidoalliance.org/specs/fido-v2.0-id-20180227/fido-metadata-service-v2.0-id-20180227.html), right? The two look like they have largely the same contents, but with some differences.
 3. [`[FIDOSecRef]`](https://fidoalliance.org/specs/fido-u2f-v1.2-ps-20170411/fido-security-ref-v1.2-ps-20170411.html) is an informative reference, so there should be no problem updating that to [this](https://fidoalliance.org/specs/fido-v2.0-id-20180227/fido-security-ref-v2.0-id-20180227.html), right? The two look like they have largely the same contents, but with some differences - the latter is much larger.

That looks to me like the only FIDO documents that have newer versions in https://fidoalliance.org/specs/fido-v2.0-id-20180227/ .

**Comment by rlin1** [comment]
regarding 1. yes, that is a newer version for FIDO ECDAA we should update the reference to that one.  
regarding 2. Should also be updated and there is even a newer version in the works for that.
regarding 3. yes, should update reference to FIDO Security Ref as well.

**Comment by emlun** [comment]
Note also that all three of the mentioned newer versions are Implementation Drafts (although the existing [`[FIDOEcdaaAlgorithm]`](https://fidoalliance.org/specs/fido-uaf-v1.1-id-20170202/fido-ecdaa-algorithm-v1.1-id-20170202.html) reference is also an Implementation Draft). Is that an issue?

**Comment by equalsJeffH** [comment]
WRT the FIDO specs being impl-drafts, I do not think is issue at this time, for CR or PropRec. They are moving targets, as is webauthn.  Once webauthn going to Rec maturity level, we nominally ought to be referring to PropStd (PS) FIDO specs.
