### ISSUE TITLE
Put all the extensions in one spot

### ISSUE THREAD

**Issue by equalsJeffH** [w3c/webauthn#9]
<a href="https://github.com/leshi"><img src="https://avatars.githubusercontent.com/u/1407369?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Originally submitted by: [leshi](https://github.com/leshi)**, on: _Friday Aug 28, 2015 at 16:33 GMT_

----

Right now, extensions are both in attestation and in web api.  Let's put them in one spot

**Comment by equalsJeffH** [comment]
<a href="https://github.com/balfanz"><img src="https://avatars.githubusercontent.com/u/398022?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Original poster: [balfanz](https://github.com/balfanz)**, on: _Friday Aug 28, 2015 at 19:35 GMT_

----

Changing the milestone to id since this would be a non-normative change.

**Comment by equalsJeffH** [comment]
<a href="https://github.com/equalsJeffH"><img src="https://avatars.githubusercontent.com/u/226571?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Original poster: [equalsJeffH](https://github.com/equalsJeffH)**, on: _Monday Dec 07, 2015 at 19:42 GMT_

----

this remains an open issue the w3c web authn wg will need to address once it begins work. thus setting milestone to ms-fido-v2.0-w3c

**Comment by vijaybh** [comment]
Will do as part of moving sections around editorially.

**Comment by jcjones** [comment]
Completed in PR#73.
