### ISSUE TITLE
Create an Explainer document

### ISSUE THREAD

**Issue by sideshowbarker** [w3c/webauthn#91]
The Web Authentication spec is complex and really would benefit from being accompanied by a high-level simple informative/non-normative Explainer document.

A good example to model it on might be [the Explainer doc for the Payment Request API spec](https://github.com/WICG/paymentrequest/blob/gh-pages/docs/explainer.md)

And another type document to consider producing is something similar to [the Rationale doc for the Payment Request API](https://github.com/WICG/paymentrequest/blob/gh-pages/docs/rationale.md)

Both of those are simple markdown documents that do not need to go through the W3C publication process in order to be published, and do not even necessarily need to be approved formally by a WG decision. Instead anybody who is interested in helping with the Web Auth work can just write up a draft and check it into this repo and then others can collaborate on it, submit PRs to refine it, etc.

**Comment by jcjones** [comment]
I'm interested in doing this, probably after my other couple issues. I won't assign this to myself yet in case someone can beat me to it.

**Comment by sideshowbarker** [comment]
Why was this closed without comment? I don’t feel strongly about keeping it open but does the fact that this was closed mean there are no plans to create some kind of explainer?

**Comment by owencm** [comment]
+1, I'm trying to learn more about webauthn right now and an explainer would be extremely helpful!

**Comment by emlun** [comment]
Related (for explaining design rationale): #764
