### ISSUE TITLE
Integrate with Feature Policy and possibly Permissions and define appropriate identifier value for WebAuthn

### ISSUE THREAD

**Issue by equalsJeffH** [w3c/webauthn#911]
[update 3-Apr-2019](https://github.com/w3c/webauthn/issues/911#issuecomment-479596069): wrt @agl's [comment](https://github.com/w3c/webauthn/issues/911#issuecomment-470718913):
Yes wrt [Permissions](https://w3c.github.io/permissions/), tho this general "how to safely orchestrate cross-origin + iframe webauthn usage" topic, along with the potentially enabling technologies ([feature policy](https://w3c.github.io/webappsec-feature-policy/), [permissions](https://w3c.github.io/permissions/), [digital asset links](https://developers.google.com/digital-asset-links/), et al), is complex (cf. the [original post](https://github.com/w3c/webauthn/issues/911#issue-323420798)). I expect that we have more investigation to do here wrt feature policy vs permissions and such before deciding on a particular solution approach.

[update 24-Jul-2018](https://github.com/w3c/webauthn/issues/911#issuecomment-407582250): Recent further investigation reveals that this is actually a technical issue if one wishes to actually integrate with [Feature Policy](https://wicg.github.io/feature-policy/), i.e., defining a [feature-identifier value](https://github.com/WICG/feature-policy/blob/master/features.md) is only one aspect. One also posibly needs to update their algorithms to check feature policy and act accordingly. See the [payment-handler integration with feature-policy](https://github.com/w3c/payment-handler/pull/282/files), see also how [picture-in-picture integrates feature policy evaluation in its algorithm](https://wicg.github.io/picture-in-picture/#request-pip), and [defines its feature name](https://wicg.github.io/picture-in-picture/#feature-policy).

----
**original post (OP):**

(framed?) webapps may request permission to use the PaymentRequest interface via the [feature-policy](https://wicg.github.io/feature-policy/) [feature-identifier value](https://github.com/WICG/feature-policy/blob/master/features.md) `payment`.  

Given the desire for webauthn to be usable in a webpayment context and its being a "powerful feature", ought we mint a `webauthn` [feature-identifier value](https://github.com/WICG/feature-policy/blob/master/features.md) ?

this may depend to some degree upon resolution of w3c/permissions#177

see also wicg/feature-policy#168, wicg/feature-policy#166,  wicg/feature-policy#75

see also discussion here:  [Relationship of Permissions, Feature Policy, Origin Policy?
](https://discourse.wicg.io/t/relationship-of-permissions-feature-policy-origin-policy/2772)

**Comment by selfissued** [comment]
This makes sense to me to do.

**Comment by selfissued** [comment]
I think it's time for a PR implementing this...

**Comment by equalsJeffH** [comment]
It's on the to-do list...

**Comment by equalsJeffH** [comment]
marking this issue as technical:

Recent further investigation reveals that this is actually a technical issue if one wishes to actually integrate with [Feature Policy](https://wicg.github.io/feature-policy/), i.e., defining a [feature-identifier value](https://github.com/WICG/feature-policy/blob/master/features.md) is only one aspect. One also posibly needs to update their algorithms to check feature policy and act accordingly. See the [payment-handler integration with feature-policy](https://github.com/w3c/payment-handler/pull/282/files), see also how [picture-in-picture integrates feature policy evaluation in its algorithm](https://wicg.github.io/picture-in-picture/#request-pip), and [defines its feature name](https://wicg.github.io/picture-in-picture/#feature-policy).

**Comment by nadalin** [comment]
@equalsJeffH My view is that this a new feature that will require breaking changes that are best done in Level 2

**Comment by equalsJeffH** [comment]
agreed.

**Comment by rlin1** [comment]
This about an RP opening an iframe for another party (e.g. a 3DS payment provider) to explicitly allow using the RP's credential.

**Comment by agl** [comment]
Webauthn group is considering implementing this using Permissions, although we would welcome guidance from webappsec on this point.

**Comment by equalsJeffH** [comment]
wrt @agl's [comment above](https://github.com/w3c/webauthn/issues/911#issuecomment-470718913)

Yes wrt [Permissions](https://w3c.github.io/permissions/), tho this general "how to safely orchestrate cross-origin + iframe webauthn usage" topic, along with the potentially enabling technologies ([feature policy](https://w3c.github.io/webappsec-feature-policy/), [permissions](https://w3c.github.io/permissions/), [digital asset links](https://developers.google.com/digital-asset-links/), et al), is complex (cf. the [original post](https://github.com/w3c/webauthn/issues/911#issue-323420798)). I expect that we have more investigation to do here wrt feature policy vs permissions and such before deciding on a particular solution approach.

**Comment by nadalin** [comment]
@equalsJeffH @agl to open PR

**Comment by equalsJeffH** [comment]
on 24-Apr-2019 call:  we are going to just alloc the feat policy string, and provide some nominal guidance say in a Note:  and see what the feedback is, and target L2-WD-01

**Comment by equalsJeffH** [comment]
see Feature Policy PR w3c/webappsec-feature-policy#306 and issue w3c/webappsec-feature-policy#168

see also CredMan issues w3c/webappsec-credential-management#135 & w3c/webappsec-credential-management#136

**Comment by cyberphone** [comment]
It might be useful knowing that the use of `WebAuthn` in payments is rather unlikely to happen in a big way since the payment industry in general have invested in _native mode_ payment applications running in mobile operating systems like Android and iOS.  The logic behind this is quite simple:
- It is doable with _existing_ technology
- Such systems may also support _non-Web scenarios_ like paying at a POS terminal or sending money to a friend (P2P payment)

These applications do usually not build on the OAuth paradigm, they rather represent variants of the age-old EMV scheme where _static_, _account specific keys_ are used to _sign locally presented/rendered payment requests_.   This is (at least) as secure as authenticating to server and getting a token back, but the main motive behind this concept actually lies in an improved UX.  Apple Pay also builds on this concept.

The W3C Payment WG have not considered the impact of native mode payment applications on their activities and work items, including how the aforementioned mobile payments systems could be used together with "desktop" Web applications, an area suffering of major interoperability and scalability issues.  To address this standards deficit, an alliance of mobile payment service providers was recently created: https://empsa.org/

A related topic can be found here:
https://lists.w3.org/Archives/Public/public-payments-wg/2019Sep/0000.html

**Comment by jcjones** [comment]
As an update, Mozilla agreed with using the `allow="webauthn"` syntax (where `webauthn` is whatever the decision is): https://groups.google.com/a/chromium.org/d/msg/blink-dev/NB6BMfcyKok/10QtWW0oDAAJ

**Comment by equalsJeffH** [comment]
thanks @jcjones :)

I assert that PR #1276 will complete the resolution of this particular issue&mdash;i.e. via integration with Feature Policy.  If anybody has some perceived need to also integrate WebAuthn with the Web Platform's "[permissions](https://w3c.github.io/permissions/)" functionality (which is distinct from Feature Policy, and is about displaying notifications to the user soliciting user "permission" to allow the webapp to access web platform functionality), they should submit a new issue.

**Comment by equalsJeffH** [comment]
closing given that we merged #1276 just now....
