### ISSUE TITLE
Location extension description is inconsistent with processing

### ISSUE THREAD

**Issue by emlun** [w3c/webauthn#923]
The description of the [`loc`][loc] extension reads (emphasis added):

>The location registration extension and authentication extension provides the ***client device’s current location*** to the WebAuthn Relying Party.

However the processing instructions read:

>**Client extension processing**
>None, except creating the authenticator extension input from the client extension input.

>**Authenticator extension processing**
>Determine the Geolocation value.

So it seems like the description should instead read:

>The location registration extension and authentication extension provides the ***authenticator's current location*** to the WebAuthn Relying Party.

[loc]: https://w3c.github.io/webauthn/#sctn-location-extension

**Comment by gmandyam** [comment]
Agreed.  Have created https://github.com/w3c/webauthn/pull/924 to address.
