### ISSUE TITLE
How can i use biometric sensor auth

### ISSUE THREAD

**Issue by GraxMonzo** [w3c/webauthn#925]
?

**Comment by emlun** [comment]
Set the `userVerification` parameter to `"required"`. For registration it's located in [`PublicKeyCredentialCreationOptions`][make-root].[`authenticatorSelection`][make-param], and for authentication it's located in [`PublicKeyCredentialRequestOptions`][get-param].

This does not guarantee that a _biometric_ will be used, but it will require some kind of user verification, which could for example be PIN or biometric. If you specifically require biometric user verification, you can inspect the attestation certificate or use the [`uvm`][uvm] extension (although the latter will only work if the authenticator supports it).

[make-root]: https://w3c.github.io/webauthn/#dictdef-publickeycredentialcreationoptions
[make-param]: https://w3c.github.io/webauthn/#dictdef-authenticatorselectioncriteria
[get-param]: https://w3c.github.io/webauthn/#dictdef-publickeycredentialrequestoptions
[uvm]: https://w3c.github.io/webauthn/#sctn-uvm-extension

**Comment by emlun** [comment]
Also, the default setting `userVerification: "preferred"` will use user verification if the authenticator supports it - so you don't need to do anything if you simply want to support biometric authentication but not require it.
