### ISSUE TITLE
TPM section is missing TPMT_PUBLIC validation steps

### ISSUE THREAD

**Issue by herrjemand** [w3c/webauthn#929]
Propose adding TPM attestation validation steps for pubArea(TPMT_PUBLIC struct) as follows:

## Validate that pubArea is valid:
* Verify that nameAlg is set to to according hashing algorithm in TPM_ALG_ID
* Verify that type is set to to according signature algorithm in  TPM_ALG_ID
* Verify that unique is set to the newly generated public key
*  If type is set to RSA, verify that parameters.exponent is set to 2048 bits for

**Comment by herrjemand** [comment]
cc @akshayku

**Comment by selfissued** [comment]
@akshayku is the proposed text above correct?

**Comment by akshayku** [comment]
I am verifying all the fields but this seems like a good clarification for TPM verification steps.

**Comment by nadalin** [comment]
@akshayku Please update

**Comment by equalsJeffH** [comment]
we closed the PR #966 -- see https://github.com/w3c/webauthn/pull/966#issuecomment-638390522

closing this issue.
