### ISSUE TITLE
#sec-authenticator-data section implies authnr enforces RP ID being eTLD+1

### ISSUE THREAD

**Issue by equalsJeffH** [w3c/webauthn#933]
in  [§6.1 Authenticator data](https://www.w3.org/TR/webauthn/#sec-authenticator-data), there's this text:
> The RP ID is originally received from the client ... it differs from other client data in some important ways. First, ... Secondly, it is validated by the authenticator during the authenticatorGetAssertion operation, by verifying that the RP ID associated with the requested credential exactly matches the RP ID supplied by the client, and that the RP ID is a registrable domain suffix of or is equal to the effective domain of the RP’s origin's effective domain.

The last portion -- "...and that the RP ID is a registrable domain suffix of or is equal to the effective domain of the RP’s origin's effective domain." -- is actually enforced by the webauthn client AFAICT -- it is step 7 in both [#createCredential](https://www.w3.org/TR/webauthn/#createCredential) and [#getAssertion](https://www.w3.org/TR/webauthn/#getAssertion).

The last portion ought to be deleted or recast to denote that the client enforces it.

**Comment by emlun** [comment]
Yes, there's no way for the authenticator to make that validation. I agree that ", and that the RP ID is a registrable domain suffix of or is equal to the effective domain of the RP’s origin's effective domain" should be removed.

**Comment by selfissued** [comment]
I agree with the proposed deletion.

**Comment by nadalin** [comment]
@equalsJeffH To create PR

**Comment by equalsJeffH** [comment]
I will do PR to remove that clause
