### ISSUE TITLE
introductory abort language missing from [[Get]]() section

### ISSUE THREAD

**Issue by equalsJeffH** [w3c/webauthn#939]
[S 5.1.3. Create a new credential](https://w3c.github.io/webauthn/#createCredential) has this language:
> This navigator.credentials.create() operation can be aborted by leveraging the AbortController; see DOM §3.3 Using AbortController and AbortSignal objects in APIs for detailed instructions. 

The intro to [S 5.1.4. Use an existing credential to make an assertion - \[\[Get\]\]()](https://w3c.github.io/webauthn/#getAssertion) is missing it.

**Comment by selfissued** [comment]
Who will create a PR to review so the working group can see what change is being proposed?

**Comment by equalsJeffH** [comment]
uh... this is assigned to moi.
