### ISSUE TITLE
use `<xmp>` uniformly for WebIDL fragments?

### ISSUE THREAD

**Issue by equalsJeffH** [w3c/webauthn#943]
presently we use a mixture of `<pre>` and  `<xmp>` blocks in our spec source for WebIDL fragments. perhaps we should use `<xmp>` uniformly ?

cf. https://tabatkins.github.io/bikeshed/#xmp

**Comment by emlun** [comment]
Sounds good to me. Looks like there are currently 17 occurrences of `<pre class="idl">`.

**Comment by nadalin** [comment]
@equalsJeffH This just seems to be preference, not a mandatory thing to do, at this point I wonder if we just close this

**Comment by emlun** [comment]
Done in #949.
