### ISSUE TITLE
appid extension: value when not acted upon?

### ISSUE THREAD

**Issue by apowers313** [w3c/webauthn#948]
The [appid extension](https://w3c.github.io/webauthn/#sctn-appid-extension) specifies the client extension output when acted upon:

> Returns the value true to indicate to the RP that the extension was acted upon.

But it's not clear what the output should be when the appid extension is supported but not acted upon. Should it be `appid: false` or `appid: undefined`?

**Comment by emlun** [comment]
This is documented, perhaps not clearly enough in [§9. WebAuthn Extensions][ext]:

>All WebAuthn extensions are OPTIONAL for both clients and authenticators. Thus, any extensions requested by a Relying Party MAY be ignored by the client browser or OS and not passed to the authenticator at all, or they MAY be ignored by the authenticator. Ignoring an extension is never considered a failure in WebAuthn API processing, so when Relying Parties include extensions with any API calls, they MUST be prepared to handle cases where some or all of those extensions are ignored.

If an extension is not acted upon, then no value will be added to the extension outputs.

[ext]: https://w3c.github.io/webauthn/#extensions

**Comment by apowers313** [comment]
If the appid extension is ignored or not supported, the result is obvious ('clientData.clientExtensions' won't have an 'appid' member).

If the extension is NOT ignored and IS supported, but not acted upon should the result look the exact same as if the extension wasn't supported? Or should it at least be clear to the server that it was considered but not acted upon by setting `clientData.clientExtensions.appid` to `false`?

**Comment by emlun** [comment]
Hm, I hadn't considered that could happen. I'm not sure the spec "allows" for not acting upon extensions that are supported: both [create()][create] and [get()][get] seem to implicitly forbid that by not specifying an algorithm branch where the extension is supported but not acted upon.

[create]: https://w3c.github.io/webauthn/#createCredential
[get]: https://w3c.github.io/webauthn/#getAssertion

**Comment by equalsJeffH** [comment]
hm, the..
> Returns the value true to indicate to the RP that the extension was acted upon.
 
..thing seems to be only in two extensions?

Is it of any value given how the spec is presently constructed?  If deemed to be of value, then perhaps it is underspecified, e.g., in terms of when it might be `false` ?

**Comment by selfissued** [comment]
Those that don't return `true` to indicate that it was acted up return actual values that indicate that it was acted upon.  I believe that the spec is already clear that if the extension was ignored, no value is to be returned.  I believe that this issue should be closed with no action.

**Comment by equalsJeffH** [comment]
>  I believe that the spec is already clear that if the extension was ignored, no value is to be returned. 

hm, might u please be able to point to where in the spec we explicitly say that?  I'm not finding it, and if it's presently only implicit (as it seems to be per @apowers313 orig post), am thinking we ought to make it explicit. Something like saying:

OLD:
> Likewise, any authenticator extension that does not otherwise require any result values MUST return a value and SHOULD return a CBOR Boolean authenticator extension output result, set to `true` to signify that the extension was understood and processed.

NEW:
> Likewise, any authenticator extension that does not otherwise require any result values MUST return a value and SHOULD return a CBOR Boolean authenticator extension output result, set to `true` to signify that the extension was understood and processed. Finally, there MUST NOT be any values returned for ignored extensions.

Also, I'm assuming that for an extension that is "[supported but not acted upon](https://github.com/w3c/webauthn/issues/948#issue-331849551)" equals "ignored", as well as "unsupported" also equaling "ignored".

WDYT?

**Comment by selfissued** [comment]
It's fine with me to add the additional sentence.

**Comment by emlun** [comment]
@equalsJeffH that sounds good to me. Will you open a PR with that change?
