### ISSUE TITLE
Clarify WebAuthn spec to allow us to return an error to RP when it makes sense

### ISSUE THREAD

**Issue by christiaanbrand** [w3c/webauthn#953]
I believe that right now, if a list of credentialIDs (with corresponding transports) gets sent to the client, and the client's isn't able to satisfy the request (let's say, all the credentialIDs referenced BLE as the only transport, but the platform doesn't support BLE), the client should be allowed to show an informative error to the user, and return an error to the RP. I think right now the spec says the client has to time the request out, but that seems subpar from a UX point of view.

Note that this is similar to the case where an RP is only looking for built-in credentials, and no credentialIDs that match is found on the platform. In this case we already said we're going to show an error to the user, and report an error back to the RP. This is just an extension of that use case.

**Comment by emlun** [comment]
I agree this requirement can be relaxed - basically, replace "MUST NOT return NotAllowedError before timeout" with "MUST NOT return NotAllowedError before timeout or user prompt".

@nadalin Would relaxing the requirement like that be a breaking normative change?

**Comment by nadalin** [comment]
@emlun yes as it's an implementation change, so we need to do this now if we are going to do it

**Comment by selfissued** [comment]
Who will volunteer to write a PR so we can review the proposed text change?

**Comment by emlun** [comment]
I will.

**Comment by equalsJeffH** [comment]
Is @christiaanbrand's [original observation](https://github.com/w3c/webauthn/issues/953#issue-332939996) in regards to [#getAssertion](https://w3c.github.io/webauthn/#discover-from-external-source), and #getAssertion only?  I.e., might it also be applicable to [#createCredential](https://w3c.github.io/webauthn/#createCredential)?

**Comment by equalsJeffH** [comment]
see also: https://github.com/w3c/webauthn/pull/962#pullrequestreview-130605914

**Comment by emlun** [comment]
I think it's also applicable to createCredential - for example, if `publicKey.authenticatorSelection.authenticatorAttachment: "platform"` and the client platform has no platform authenticator.

**Comment by emlun** [comment]
Turns out this was already handled in #906.

**Comment by equalsJeffH** [comment]
I _think_ what @emlun is saying in https://github.com/w3c/webauthn/issues/953#issuecomment-401312154 is that this entire issue is addressed by PR #906.  thus in today's call I said I'd close this, and no one objected, so here goes. if closing it is not appropriate, please re-open.

**Comment by emlun** [comment]
At least I noticed while writing #962 that what I was doing seemed awfully familiar, and sure enough #906 turned out to do almost exactly the same thing as I did in #962.
