### ISSUE TITLE
Note on "RP ID" is confusing

### ISSUE THREAD

**Issue by engedy** [w3c/webauthn#963]
Developers are confused by the note we have in section https://w3c.github.io/webauthn/#rp-id, see   https://crbug.com/854557. We should try to improve the wording so that the note no longer suggests the RP ID being an origin.

**Comment by equalsJeffH** [comment]
@engedy  thanks for submitting this. 

after perusing the bug https://crbug.com/854557 and playing with http://www.intothesymmetry.com/ mentioned therein, it seems that the bug submitter's confusion stems from the **Note**'s phrase "A public key credential's scope" (below the [RP ID definition](https://w3c.github.io/webauthn/#rp-id)), yes?

The first sentence of the Note:
> A Public key credential's scope is for a Relying Party's origin, with the following restrictions and relaxations: 

..is attempting to say that "a public key credential's scope" is based on origin, but with the following alterations. 

Perhaps changing the Note's 2nd bullet item to read something like this:
> the host, _**i.e., the RP ID**_, may be equal to the Relying Party's origin's effective domain, or it may be equal to a registrable domain suffix of the Relying Party's origin's effective domain (i.e., an available relaxation), and,

..would that address this issue?

**Comment by engedy** [comment]
Thank you for the suggestions, Jeff!

In the meantime, another developer [expressed](https://groups.google.com/a/fidoalliance.org/forum/#!topic/fido-dev/H2eXb0Gs8rI) confusion on fido-dev@, which makes me think that an example would be probably really useful? WDYT of saying that on origin https://login.example.com:1337, the following RP IDs are valid: login.example.com (default), example.com, but not "m.login.example.com" and not "com"?

**Comment by arnar** [comment]
That note confuses me as well. :)

Can we make its points more directly as follows:

Note that an RP ID is a domain string only, and does not mention a scheme or port number as an origin does. The RP ID of a PublicKeyCredential sets it scope, i.e. it determines the origins on which it may be exercised as follows:

 - The RP ID must be equal to the origin's effective domain, or a registrable suffix of the origin's effective domain.

 - The origin's scheme must be 'https'.

 - The origin's port number is unrestricted.

This is done in order ...

(+1 for adding examples as engedy@ suggests.)

wdyt?

**Comment by equalsJeffH** [comment]
thanks @arnar & @engedy for the suggestions, PR coming....
