### ISSUE TITLE
AppID extension: protocol version number?

### ISSUE THREAD

**Issue by apowers313** [w3c/webauthn#972]
According to the [AppID and Facets spec](https://fidoalliance.org/specs/fido-v2.0-id-20180227/fido-appid-and-facets-v2.0-id-20180227.html), after downloading the `TrustedFacetList` the client should:

> From among the objects in the trustedFacet array, select the one with the version matching that of the protocol message version. With "matching" we mean: the highest version that appears in the TrustedFacetList that is smaller or equal to the actual protocol version being used. 

UAF has protocol versions, but I'm not sure what to use for WebAuthn. A clarification in the appid extension would be helpful.

**Comment by agl** [comment]
(I think this is moot in practice because nobody is going to implement Trusted Facet lists.)

**Comment by apowers313** [comment]
@agl ...then we should probably note that in the spec so people know what to actually implement.

**Comment by nadalin** [comment]
@selfissued Seems like just a clarification is required in the APPID extensioni

**Comment by selfissued** [comment]
What should the proposed clarification say?  I'd be glad to write a PR but it would be helpful if someone who understands the issue could propose text.  (Or feel free to write the PR yourself!)

**Comment by selfissued** [comment]
@apowers313 agreed on the 18-Jul-18 call to create a PR for this.

**Comment by herrjemand** [comment]
@apowers313 TFC must always be of version 1.0

**Comment by selfissued** [comment]
@agl agreed on the 8-Aug-18 call to write a PR referencing the FIDO spec and saying that no one implements a particular part of it.
