### ISSUE TITLE
Clarification of valid rpIdHash value requested in section 7 when using AppID extension

### ISSUE THREAD

**Issue by sbweeden** [w3c/webauthn#980]
There are a couple of usability issues with following the RP operations guidance in section 7.2 for verifying an authentication assertion when using the AppID extension.

Even though I can validly send just the web server's hostname as the RP-ID in the call to navigator.credentials.get, if I include the AppID extension, the rpIdHash returned in aData (see step 11 of section 7.2) is the hash of the U2F APPID. 

What adds to this confusion is that verification of client extension outputs (where you can detect if "appid": true is returned) is not mentioned until step 14 of section 7.2. In fact in order to validate the rpIdHash in step 11 you must FIRST figure out if appid was used.

My suggestion is to add clarification to step 11 indicating that appid in the client extension outputs may need to be checked first to ensure the correct rpIdHash is compared.

**Comment by agl** [comment]
(I think it's worth noting here that the RP always knows whether the AppID was used. If the credential was created with the U2F API and getting an assertion didn't result in an error, then the AppID _must_ have been used. For the RP, the `appid` extension result is completely superfluous.)

**Comment by selfissued** [comment]
@agl agreed on the 8-Aug-18 call to create a PR adding clarifying text to the extension.

**Comment by sbweeden** [comment]
@agl - Is it always a fair assumption that an RP *knows* the credential was previously created with the U2F API?  Maybe... but there's absolutely nothing to require that the RP stored this vital piece of information when the server registered the key  handle and credential public key.

**Comment by emlun** [comment]
Even if the RP doesn't remember how a particular credential was created, the RP knows that it used the `appid` extension and therefore knows that if the response doesn't match the RP ID then it must instead match the AppID (or be invalid, of course). But I agree with adding a clarification of this to the `appid` extension.
