### ISSUE TITLE
Public key rules for "packed" attestation type

### ISSUE THREAD

**Issue by sbweeden** [w3c/webauthn#981]
Consider section 8.2 https://www.w3.org/TR/webauthn/#packed-attestation 

When following the steps for the verification procedure it is not clear what validation should be performed on the attested credential public key (in authData). With the fido-u2f attestation type this is explicit (strict rules on key type, algorithm and curve). With packed, I can't find any validation rules in the spec for the credential public key. 

Whilst section 6.3.5 (https://www.w3.org/TR/webauthn/#signature-attestation-types) does make mention of signature formats, there is no guidance on what is considered an acceptable key type, algorithm, etc for packed attestation credentials. Is this a gap, or simply up to the policy of the RP to decide?

**Comment by akshayku** [comment]
It's simply up-to to the RP to decide.

**Comment by emlun** [comment]
My impression is that U2F strictly specifies a single crypto suite in order to keep the spec small and implementations simple - since U2F was in some sense a pilot project with no legacy, where time to deployment held high priority. WebAuthn on the other hand wants to support existing and future authenticator hardware, so it doesn't narrow the crypto suite selection the way U2F does.

**Comment by sbweeden** [comment]
Understood. Essentially this defers acceptance criteria to RP policy, which means choices or configuration of whitelist/blacklist of key types/algorithms, leading to potential interoperability challenges. Perhaps if the spec just indicated that the acceptability of a particular key type and subsequent signature validation algorithm is at the discretion of the RP that would at least explain the intent to would-be implementors who read it later.

**Comment by equalsJeffH** [comment]
see also for how FIDO addressed aspects of this: https://fidoalliance.org/specs/fido-uaf-v1.1-id-20170202/fido-registry-v1.1-id-20170202.html#public-key-representation-formats   i.e. constraining the supported PK algs

**Comment by nadalin** [comment]
@sbweeden We should keep this flexible, discussed on call and closing
