### ISSUE TITLE
authenticatorGetAssertion has no ConstraintError step for requireUserVerification

### ISSUE THREAD

**Issue by emlun** [w3c/webauthn#983]
[authenticatorMakeCredential][mc] has the step

>5. If _requireUserVerification_ is `true` and the authenticator cannot perform user verification, return an error code equivalent to "`ConstraintError`" and terminate the operation.

[authenticatorGetAssertion][ga] also has a _requireUserVerification_ parameter, but no equivalent step returning a "`ConstraintError`" if it is not supported. Step 7 reads

>7. [...]
>
>If _requireUserVerification_ is true, the method of obtaining user consent MUST include user verification.
>
>[...]

but leaves unspecified what should happen if this MUST cannot be satisfied.

CTAP does return identical error codes from both operations if the argument value is unsupported, so adding the missing step to authenticatorGetAsserion would not affect compatibility with CTAP.

[mc]: https://w3c.github.io/webauthn/#op-make-cred
[ga]: https://w3c.github.io/webauthn/#op-get-assertion

**Comment by nadalin** [comment]
@emlun un you MUST, we don't have alternatives to MUSTS, suggest to close no action

**Comment by emlun** [comment]
Sorry, I don't understand what you mean by this:

>un you MUST, we don't have alternatives to MUSTS

**Comment by emlun** [comment]
Decided on 2018-07-11 WG call to close this.

**Comment by emlun** [comment]
This situation should not happen because the client algorithm specifies

>If `options.userVerification` is set to `required` and the authenticator is not capable of performing user verification, continue.
