### ISSUE TITLE
add abort path to createCredential alg to match that added to getAssertion alg

### ISSUE THREAD

**Issue by equalsJeffH** [w3c/webauthn#985]
in PR #906 @agl [does not disagree](https://github.com/w3c/webauthn/pull/906#discussion_r196517535) that the new switch branch in new lines 1266-1269 (in PR #906) ought to also be applied to the [#createCredential](https://w3c.github.io/webauthn/#createCredential) alg. This issue requests we make the latter change, assuming PR #906 is merged with the latter lines intact.

**Comment by nadalin** [comment]
@equalsJeffH Will open a PR

**Comment by equalsJeffH** [comment]
fixed by PR #1005
