### ISSUE TITLE
Partial dictionaries for extension outputs may be incorrect use of WebIDL

### ISSUE THREAD

**Issue by emlun** [w3c/webauthn#988]
@agl notes in https://github.com/w3c/webauthn/issues/982#issuecomment-402249758 that

> > [@emlun] made the [same interpretation](https://bugs.chromium.org/p/chromium/issues/detail?id=853770#c6) as @kpaulh: that the dictionary extension shouldn't be applied unless the extension is requested.
> 
> I agree that makes the most sense in this context, although I find scant support for the idea that partial dictionaries can be dynamically composed from reading [WebIDL](https://heycam.github.io/webidl/#dfn-partial-dictionary). [...]

So it seems like we might be using WebIDL in an incorrect way if the intent is that those partial dictionaries would only be "applied" if the respective extensions were processed.

I don't know if this is in fact a problem or how big, or if it's something we should worry about if it is, but I thought it seems important enough to warrant discussion in its own issue.

**Comment by equalsJeffH** [comment]
just to note, [from webidl wrt dictionaries](https://heycam.github.io/webidl/#idl-dictionaries): 
> On a given dictionary value, the presence of each dictionary member is optional, unless that member is specified as required. When specified in the dictionary value, a dictionary member is said to be present, otherwise it is not present.

**Comment by equalsJeffH** [comment]
CC @bzbarsky -- what are your thought here if we may ask?  thx.

**Comment by bzbarsky** [comment]
You certainly can't "dynamically compose partial dictionaries".  `partial dictionary` is just a spec feature (or misfeature; see <https://github.com/w3ctag/design-principles/issues/99>) that must lead to the same observable behavior as if the primary dictionary definition were edited.

Past that, I don't think I have enough context here.  So first question: are we talking about dictionaries as arguments, or dictionaries as return values?  And what is the actual desired behavior?

**Comment by agl** [comment]
Closing this based on discussion during the 2018-08-01 call:

I thought this was a problem because I thought that the default for a dictionary member was to be required. But it's not, it's optional. So the partial dictionaries seems like a fine way to represent this as long as we don't make any of the fields required in the future.
