### ISSUE TITLE
Section 4: Mention requirement for user to give consent for key to be used

### ISSUE THREAD

**Issue by rlin1** [w3c/webauthn#99]
This is already mentioned in section 4.1.1. but we already should mention it as well in the intro paragraphs.

**Comment by equalsJeffH** [comment]
at the time @rlin1  submitted this issue, S 4 mapped to this spot in index.src.html: `{#authenticator-model}`.   we need to note such spec source anchors in issues because section #s will change over time as we move sections around.

**Comment by equalsJeffH** [comment]
upon review of the present state of the spec (master-2b72ddf), we have "consent" and "user consent" appearing in the Abstract as well as the Introduction, plus at appropriate places in the remainder of the spec, so I'm thinking this issue can be closed.

**Comment by equalsJeffH** [comment]
Rolf to review this and close if he agrees -- see: https://www.w3.org/2016/09/07-webauthn-minutes.html

**Comment by rlin1** [comment]
Looks good to me.
