### ISSUE TITLE
add captions for tables and id attrs so we can link to them

### ISSUE THREAD

**Issue by equalsJeffH** [w3c/webauthn#990]
we are likely adding yet another table (PR #979). we have captions for figures, and id attrs so we can link to them, should do the same for tables.  the two current tables are:

https://w3c.github.io/webauthn/#authenticator-data

https://w3c.github.io/webauthn/#attested-credential-data

**Comment by emlun** [comment]
I think you mean #979. :)

**Comment by emlun** [comment]
@equalsJeffH Do you mind if I go ahead and do this?

**Comment by nadalin** [comment]
@emlun Please do so
