### ISSUE TITLE
coalesce HTML references?

### ISSUE THREAD

**Issue by equalsJeffH** [w3c/webauthn#996]
presently our editors' draft references three HTML specs:
>[HTML]
    Anne van Kesteren; et al. HTML Standard. Living Standard. URL: https://html.spec.whatwg.org/multipage/ 
[HTML52]
    Steve Faulkner; et al. HTML 5.2. 14 December 2017. REC. URL: https://www.w3.org/TR/html52/ 
[HTML53]
    HTML 5.3. 14 December 2017. WD. URL: https://www.w3.org/TR/html53/ 

Might we be able to reference just one?  Unless there's something "new" only in [HTML] that we need to specifically reference?

cc: @wseltzer @samweiler

**Comment by plehegar** [comment]
Given that W3C and WHATWG have been going back and forth on HTML, this may take a few weeks to provide an authoritative answer to this.
As a side, one of the HTML concepts used in the spec isn't in HTML52, so you can't just reference HTML52 for sure.

**Comment by equalsJeffH** [comment]
Ok, then I'm thinking that we ought to just leave the HTML references as-is for now. it's just editorial and we can fix it up later.

**Comment by equalsJeffH** [comment]
We are going to leave this as-is for L1

**Comment by equalsJeffH** [comment]
Ok, given [this announcement today from W3C & WHATWG](https://www.w3.org/blog/2019/05/w3c-and-whatwg-to-work-together-to-advance-the-open-web-platform/), we will update the HTML and DOM references to point at the WHATWG specs.
